### ISSUE TITLE
[Request] add gotify server, gotify cli

### ISSUE THREAD

**Issue by graphixillusion** [ScoopInstaller/Main#1011]
Hi there. I would like to suggest two new cool apps to add in the project:

1. gotify server (https://github.com/gotify/server/tree/v2.0.14)
2. gotify cli (https://github.com/gotify/cli)

**Comment by rashil2000** [comment]
Can you send us PRs for them?

**Comment by graphixillusion** [comment]
> Can you send us PRs for them?

I'm not involved in the project. I just was suggesting them

**Comment by rashil2000** [comment]
You don't need to be involved with them :)

**Comment by graphixillusion** [comment]
> You don't need to be involved with them :)

Oh i see. But i never did it before. Is there any guide on how to do that?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets
