### ISSUE TITLE
Download nodejs-lts failed

### ISSUE THREAD

**Issue by bpeter340** [ScoopInstaller/Main#1015]
scoop install nodejs-lts
Installing 'nodejs-lts' (12.16.2) [64bit]
node-v12.16.2-win-x64.7z (10.3 MB) [=======================================================================================================] 100%    
Checking hash of node-v12.16.2-win-x64.7z ... ok.
Extracting node-v12.16.2-win-x64.7z ... done.
Linking ~\scoop\apps\nodejs-lts\current => ~\scoop\apps\nodejs-lts\12.16.2
Persisting bin
Persisting cache
Running post-install script...
'nodejs-lts' (12.16.2) was installed successfully!

Despite the command running successfully, the bin folder remains empty and I am unable to run any node commands.

**Comment by mark05e** [comment]
have you checked if your AV is blocking? I had recently an issue where nodejs was not installing correctly and found out that my AV was blocking certain steps of the installer execution.
