### ISSUE TITLE
Add the criteria for inclusion

### ISSUE THREAD

**Issue by JanPokorny** [ScoopInstaller/Main#1017]
The criteria for inclusion in the main bucket are located elsewhere (https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket), they should be included here in README.md (or CONTRIBUTING.md). (Also may be beneficial to link https://github.com/lukesampson/scoop-extras and say that non-conforming apps go there.)

(Also, OT, but can anyone tell me why the main bucket is under ScoopInstaller and extras and scoop itself under lukesampson account? Kind of confusing.)

**Comment by mark05e** [comment]
I feel it is confusing too. It took me few days (across months) of visiting the project pages to understand and get started.

**Comment by linsui** [comment]
> (Also, OT, but can anyone tell me why the main bucket is under ScoopInstaller and extras and scoop itself under lukesampson account? Kind of confusing.)

https://github.com/ScoopInstaller/Main/pull/303#issuecomment-518575077

**Comment by JanPokorny** [comment]
Thanks for the link, looks like it's WIP. I hope resolving this issue helps with lowering the entry barrier to scoop, which I feel is higher than it should be.

**Comment by JanPokorny** [comment]
@rashil2000 The PR that closed this issue does not seem related at all to this issue, is this an error?

**Comment by rashil2000** [comment]
Oh, sorry my bad.

The criteria for new applications comes up whenever you create a Package Request in the Main bucket (I have created issue and PR templates for that). For Extras, there's no criteria.

Also, all the repos have now been moved to the ScoopInstaller org.

**Comment by JanPokorny** [comment]
@rashil2000 It would still help to have the criteria in the README since you need to know where to create the PR in the first place
