### ISSUE TITLE
latex@2.9.6942: download via aria2 failed

### ISSUE THREAD

**Issue by skysin** [ScoopInstaller/Main#102]
as the title goes。。。

maybe the reasons is：

```
The requested URL /ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6942.exe was not found on this server.
```

ps: texlive may be wanted

**Comment by xerxesb** [comment]
It appears like the upstream source for MiKTeX has changed the way they distribute the binary. 

https://ftp.fau.de/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe seems to be the new URL, but I'm new to Scoop so I'm not sure how to update the recipe.
