### ISSUE TITLE
gcc: missing gdb

### ISSUE THREAD

**Issue by ceclin** [ScoopInstaller/Main#1023]
In issue #928 and pull request #973, `gcc` is updated to 9.3.0-1 using MSYS2's build. In this latest version, it doesn't contain any gdb tool, while in previous version (8.1.0.0) there are some attached gdb tools such as `gdb.exe`.
What about adding gdb tools to `gcc` package or updating exsited `gdb` package to corresponding version?

**Comment by ret394** [comment]
> updating exsited `gdb` package

**Comment by lwintermelon** [comment]
There should be attached gdb tools in `gcc`, `gcc` and `gdb` have some duplicate dependences.

**Comment by escape0707** [comment]
The MSYS2 `gcc` lacks `gdb`. And currently provided `main/gdb` don't work well with `vscode-cpptools`. I have no choice but to revert to `main/gcc@8.1.0.0` using `git` and `scoop hold gcc`.

I don't think current situation is optimal.
