### ISSUE TITLE
openssh@7.6p1: hash check failed（can not install openssh）

### ISSUE THREAD

**Issue by panxt** [ScoopInstaller/Main#104]
C:\Users\15639>scoop install openssh
Updating Scoop...
Updating 'extras' bucket...
 * e28d30e8 lantern-client: Update to version 5.4.1                      2 hours ago
 * 44b9d724 dnscrypt-proxy: Update to version 2.0.25                     2 hours ago
 * f3cc89a8 svcat: Update to version 0.2.1                               3 hours ago
 * d9834784 tinymediamanager: Update to version 3.0 (#2235)              5 hours ago
 * 7e31d5cf ipfs-desktop: Update to version 0.8.0                        6 hours ago
 * 2b4d96fb terminus: Update to version 1.0.79                           8 hours ago
 * ddf4b628 dnscrypt-proxy: Update to version 2.0.24                     8 hours ago
Updating 'main' bucket...
 * 4aa0bb38 vim: Update to version 8.1.1461                              3 hours ago
 * 65520146 force: Update to version 0.26.9                              3 hours ago
 * 58c70ce0 aws: Update to version 1.16.170                              6 hours ago
 * 0433f74b teleport: Update to version 3.0.6                            7 hours ago
Scoop was updated successfully!
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'openssh' (7.6p1) [64bit]
Loading gcc-libs-6.4.0-1-x86_64.pkg.tar.xz from cache.
Loading heimdal-1.5.3-9-x86_64.pkg.tar.xz from cache.
Loading heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz from cache.
Loading icu-59.1-1-x86_64.pkg.tar.xz from cache.
Loading libcrypt-2.1-1-x86_64.pkg.tar.xz from cache.
Loading libdb-5.3.28-2-x86_64.pkg.tar.xz from cache.
Loading libedit-3.1-20170329-x86_64.pkg.tar.xz from cache.
Loading libopenssl-1.0.2.m-1-x86_64.pkg.tar.xz from cache.
Loading libreadline-7.0.003-1-x86_64.pkg.tar.xz from cache.
Loading libsqlite-3.19.3.0-2-x86_64.pkg.tar.xz from cache.
Loading msys2-runtime-2.9.0-2-x86_64.pkg.tar.xz from cache.
Loading ncurses-6.0.20170708-2-x86_64.pkg.tar.xz from cache.
Loading openssh-7.6p1-1-x86_64.pkg.tar.xz from cache.
Loading zlib-1.2.11-1-x86_64.pkg.tar.xz from cache.
Loading bash-4.4.012-1-x86_64.pkg.tar.xz from cache.
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz ... ok.
Checking hash of heimdal-1.5.3-9-x86_64.pkg.tar.xz ... ok.
Checking hash of heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz ... ok.
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         main/openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      29ad9ba47eec247b58d01d6bb6add8c4743006b28860720ecb06456a4c74c48b

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by panxt** [comment]
It is OK!Sorry,just try again!

**Comment by rasa** [comment]
The hash d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a in the manifest (the “expected” hash above) is correct. Please try again.
