### ISSUE TITLE
7zip@19.00: hash check failed

### ISSUE THREAD

**Issue by ben79git** [ScoopInstaller/Main#1058]
Trying to install K9s, but getting a hash error when installing 7zip:

scoop install k9s
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=================================================>                                   ]  59%
Checking hash of 7z1900-x64.msi ... ERROR Hash check failed!
App:         main/7zip
URL:         https://7-zip.org/a/7z1900-x64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    a7803233eedb6a4b59b3024ccf9292a6fffb94507dc998aa67c5b745d197a5dc
Actual:      855bb71280deb893e8932632d3bda6920a0ceea9c4ec87772fa96aee0193d394

**Comment by Ash258** [comment]
>  59%
