### ISSUE TITLE
Question (don't know where to ask?)

### ISSUE THREAD

**Issue by Zerowalker** [ScoopInstaller/Main#106]
Hi,

so this is just a question, don't know where to ask it,
if there is some forum for this please direct me to it!

I was wondering how Scoop keeps tracks of all programs,
i can see the json files, but are these actually handles manually?
Are ppl (or the creator?) actually checking daily for updates and then switching out the urls and hashes?

Thanks:)

**Comment by h404bi** [comment]
See https://github.com/lukesampson/scoop/issues/3440

**Comment by Zerowalker** [comment]
oh stupid of me not to see that one, thanks!
