### ISSUE TITLE
Update RethinkDB

### ISSUE THREAD

**Issue by PlaidDroid** [ScoopInstaller/Main#1071]
New version: **2.4.0**
Current version: **2.3.6**
https://rethinkdb.com/docs/install/windows/

**Comment by Ash258** [comment]
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

![image](https://user-images.githubusercontent.com/13260377/81466930-8f82d880-91d5-11ea-9039-2c6a39da6748.png)

**Comment by PlaidDroid** [comment]
There is an unofficial build though:
https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1
Probably should wait for the stable official release.

**Comment by rashil2000** [comment]
Tracked in #2848
