### ISSUE TITLE
innounp@0.49: download via aria2 failed

### ISSUE THREAD

**Issue by WE180** [ScoopInstaller/Main#1078]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar
    referer=https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/
    dir=C:\Users\we\scoop\cache
    out=innounp#0.49#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_innounp_innounp049.rar

ERROR & 'C:\Users\we\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\we\scoop\cache\innounp.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=5356 --continue

**Comment by l1422586361** [comment]
how to Proxy configuration for scoop ?
