### ISSUE TITLE
[Request] Add persistent "Formats" and "Codecs" folders for 7zip

### ISSUE THREAD

**Issue by DessertArbiter** [ScoopInstaller/Main#1081]
7zip supports external plugins for additional formats and codecs, in folders called "Formats" and "Codecs" (which don't exist by default) in the 7zip base directory.

Examples:
	Plugin that goes in "Formats": https://www.tc4shell.com/en/7zip/smart7z/
	Plugin that goes in "Codecs": https://www.tc4shell.com/en/7zip/modern7z/

**Comment by issaclin32** [comment]
Implemented by https://github.com/ScoopInstaller/Main/pull/1797
