### ISSUE TITLE
python@3.8.3: hash check failed

### ISSUE THREAD

**Issue by slbb** [ScoopInstaller/Main#1089]
python: 3.8.2 -> 3.8.3
Updating one outdated app:
Updating 'python' (3.8.2 -> 3.8.3)
Downloading new version
python-3.8.3-amd64.exe (26.5 MB) [====================================================================================] 100%
Checking hash of python-3.8.3-amd64.exe ... ok.
install-pep-514.reg (555 B) [=========================================================================================] 100%
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [========================================================================================] 100%
Checking hash of uninstall-pep-514.reg ... ERROR Hash check failed!
App:         main/python
URL:         https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/python/uninstall-pep-514.reg
First bytes: 57 69 6E 64 6F 77 73 20
Expected:    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Actual:      d9309423b693ed63aea6b1fbfc0c34f16842cdca22a1b3edef283b87567a53b9

**Comment by r15ch13** [comment]
Known issue, working on it. https://github.com/ScoopInstaller/Main/issues/1088
