### ISSUE TITLE
python@3.8.3: decompress error

### ISSUE THREAD

**Issue by LambdaV5** [ScoopInstaller/Main#1093]
Installing 'python' (3.8.3) [64bit]
Loading python-3.8.3-amd64.exe from cache
Checking hash of python-3.8.3-amd64.exe ... ok.
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.
Loading uninstall-pep-514.reg from cache
Checking hash of uninstall-pep-514.reg ... ok.
Running pre-install script...
Running installer script...
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\Users\lambda\scoop\apps\scoop\current\lib\decompress.ps1:281 字符: 38
+ ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\lambda\scoop\apps\python\3.8.3\setup.exe.
Log file:
  ~\scoop\apps\python\3.8.3\dark.log

**Comment by Ash258** [comment]
`scoop install dark` then reinstall python
