### ISSUE TITLE
[Request] Add winget-cli

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Main#1104]
So, hm, Microsoft finally released a package manager.

https://github.com/microsoft/winget-cli

**Comment by kostrse** [comment]
Does scoop support installation of appxbundle packages?

**Comment by kidonng** [comment]
> Does scoop support installation of appxbundle packages?

It's not Scoop's duty. Use `Add-AppxPackage <Example.AppxBundle>` in PowerShell.

**Comment by NatoBoram** [comment]
`scoop install winget` could totally download the thing and use `Add-AppxPackage` in its install script. Scoop's duty is to install stuff, and it does it very well. It's probably not a good idea to discriminate what to install.

**Comment by kidonng** [comment]
> It's probably not a good idea to discriminate what to install.

Sorry if I didn't make it clear, but AppxBundle packages needs admin permissions and won't install to Scoop's directory, which are contrary to Scoop's main aims.
One could definitely write manifests and use Scoop to manage the packages, where Scoop simply functions as a downloader and a `Add/Remove-AppxPackge` invoker, and lost its value.

**Comment by NatoBoram** [comment]
Ah, now I understand more. It would be just like `vcredist` from the "extras" bucket; to be installed temporarily by Scoop so it can run the installer, then removed so the leftovers are cleaned.

I absolutely hate "package managers" which are just installer-executors like Chocolatey and WinGet, and I also hate that we have to do that to install `vcredist` because Microsoft was too incompetent to create an free, libre and open source package format in the first place when it mattered the most; before the whole Windows ecosystem got into this mess.

But I also think it's better to use a package manager than to not use one. I'd rather use Scoop to automate the installation of shit packages like `vcredist` and `winget` rather than downloading them from random Microsoft pages and just hope I got the right package. I think it would be absolutely appropriate to have Scoop handle `winget`, and its updates, perhaps not in the main bucket, but in the `extras` one, just like it does with `vcredist` but without removing the installer+manifest so it could support auto-updates.
