### ISSUE TITLE
nodejs-lts@10.16.0: extract_dir error

### ISSUE THREAD

**Issue by xiongdahu** [ScoopInstaller/Main#111]
Extracting node-v10.16.0-win-x64.7z ... 管道元素中的“&”后面的表达式生成无效的对象。该表达式必须生成命令名称、脚本块或                    
CommandInfo 对象。                                                                                     
所在位置 C:\Users\xiongdahu\scoop\apps\scoop\current\lib\decompress.ps1:69 字符: 11                       
+         & (Get-HelperPath -Helper 7zip) x "$Path" -o"$DestinationPath ...                         
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                           
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException                             
    + FullyQualifiedErrorId : BadExpression                                                         
                                                                                                    
ERROR Could not find 'node-v10.16.0-win-x64'! (error 16)                                            
                                                                                                    
Please try again or create a new issue by using the following link and paste your console output:   
https://github.com/ScoopInstaller/Main/issues/new?title=nodejs-lts%4010.16.0%3a+extract_dir+error

**Comment by rasa** [comment]
I was able to install it without error:
````
> scoop install nodejs-lts
Installing 'nodejs-lts' (10.16.0) [64bit]
node-v10.16.0-win-x64.7z (9.7 MB) [========================================================================] 100%
Checking hash of node-v10.16.0-win-x64.7z ... ok.
Extracting node-v10.16.0-win-x64.7z ... done.
Linking C:\scoop\apps\nodejs-lts\current => C:\scoop\apps\nodejs-lts\10.16.0
Persisting bin
Persisting cache
Running post-install script...
'nodejs-lts' (10.16.0) was installed successfully!

**Comment by rasa** [comment]
Moving issue to https://github.com/lukesampson/scoop/issues/3517
