### ISSUE TITLE
git postinstall breaks git in docker container

### ISSUE THREAD

**Issue by StefanD986** [ScoopInstaller/Main#1126]
In the `git.json` recipe, there is a post install step that enables the git credential manager:

https://github.com/ScoopInstaller/Main/blob/c9de0968eb8a51fea999eaf5df0c13a03b2d28d4/bucket/git.json#L34

For me this breaks using git within a docker container when I try to git clone from a repo that uses BasicAuth. I am not exactly sure why this is a problem (maybe because there is no UI that can ask for the password?). The issue is also hard to debug out of the box because there is no error message or anything, git clone just hangs forever.

In any case doing a `git config --global --unset credential.helper` manually solved the problem for me.

If there's not a good reason to keep this, I'd propose to remove this post install step.

# Steps to reproduce:
  - Have a git repo that uses http BasicAuth at hand
  - Build a docker image that has scoop installed (I have added a example Dockerfile at the end)
  - `docker run -it NAME_OF_DOCKER_IMAGE`
  - git clone http:\\YOUR_GIT_REPO`

## Expected behaviour
git should clone the repo

## actual behaviour
git clone hangs forever. 

# Notes on debugging this
It helps to set the environment variable `GIT_CURL_VERBOSE=1`. This will show that git clone hangs at the authentication.

## Dockerfile
```Dockerfile
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

RUN powershell.exe -ExecutionPolicy RemoteSigned `
  iex (new-object net.webclient).downloadstring('https://get.scoop.sh'); `
  scoop install git 

CMD ["cmd"]
```

**Comment by rasa** [comment]
Here are all the places where we set credential.helper:
https://github.com/ScoopInstaller/Main/search?q=git+config+--global+credential.helper
and well as here:
https://github.com/rasa/scoops/search?q=credential.helper

I agree we should remove this setting. We can add this setting back in alternates in our versions bucket if we want,

**Comment by dwettstein** [comment]
Relates #1617 and #2190

**Comment by r15ch13** [comment]
Fixed
