### ISSUE TITLE
vim missing 32-bit support?

### ISSUE THREAD

**Issue by wuya666** [ScoopInstaller/Main#113]
The github project where scoop downloads the vim app from clearly has a 32-bit version available for release:

https://github.com/vim/vim-win32-installer/releases/

but the vim.json under the main bucket only contains support for 64-bit architecture, is there any reason why the 32-bit support is omitted by scoop? It seems that a simple rename of the file path from 

"url": "https://github.com/vim/vim-win32-installer/releases/download/v8.1.1471/gvim_8.1.1471_x64.zip"

to

"url": "https://github.com/vim/vim-win32-installer/releases/download/v8.1.1471/gvim_8.1.1471_x86.zip"

should do the trick? or is there some other problem related to the 32-bit file so that 32-bit support is omitted?

**Comment by rasa** [comment]
Fixed in #151
