### ISSUE TITLE
nim@0.20.0: hash check failed

### ISSUE THREAD

**Issue by kraptor** [ScoopInstaller/Main#114]
Updating 'nim' (0.19.6 -> 0.20.0)
Downloading new version
nim-0.20.0_x64.zip (18,1 MB) [================================================================================] 100%
Checking hash of nim-0.20.0_x64.zip ... ERROR Hash check failed!
App:         main/nim
URL:         https://nim-lang.org/download/nim-0.20.0_x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    c4bbd29e2a48bdd8438465c9f85f15e4bf247498d4655f31aaecb2811421e062
Actual:      47ce2a7e77c6ba65266eb35a3319cafe24e6845947bfbdcae929e57892ca1491

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=nim%400.20.0%3a+hash+check+failed

**Comment by kraptor** [comment]
I proposed updated hahes in #https://github.com/ScoopInstaller/Main/commit/526ab3ec8eeab3977a2867ede408da42d5ee7a23

**Comment by kraptor** [comment]
PR in #115

**Comment by brandon93s** [comment]
Closed in https://github.com/ScoopInstaller/Main/pull/115.
