### ISSUE TITLE
i can use scoop search 7zip ,but i fail to install it ,it said "Couldn't find manifest for '7zip'."

### ISSUE THREAD

**Issue by xcb8488** [ScoopInstaller/Main#1152]
C:\WINDOWS\system32>scoop search 7zip
'versions' bucket:
7zip-beta (18.03)
7zip-zstd (19.00-v1.4.5-R2)

C:\WINDOWS\system32>scoop install -g 7zip-zstd
Couldn't find manifest for '7zip'.

**Comment by Ash258** [comment]
7zip-zstd requires 7zip to be installed. 

Based on the output you are missing main bucket. 

`scoop bucket add main; scoop install 7zip-zstd`

**Comment by xcb8488** [comment]
Thank  you so much !
I  make it !
Thank you !

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jakub Čábera<mailto:notifications@github.com>
发送时间: 2020年6月7日 14:19
收件人: ScoopInstaller/Main<mailto:Main@noreply.github.com>
抄送: xcb8488<mailto:xcb8488@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ScoopInstaller/Main] i can use scoop search 7zip ,but i fail to install it ,it said "Couldn't find manifest for '7zip'." (#1152)


7zip-zstd requires 7zip to be installed.

Based on the output you are missing main bucket.

scoop bucket add main; scoop install 7zip-zstd
