### ISSUE TITLE
innounp@0.49: decompress error

### ISSUE THREAD

**Issue by fantasyding** [ScoopInstaller/Main#1177]
Hi,I can't install innounp,please give me some advice.

scoop install innounp
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'innounp' (0.49) [64bit]
Loading innounp049.rar from cache.
Checking hash of innounp049.rar ... ok.
Extracting innounp049.rar ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或
空。请提供一个不为 Null 或空的
参数，然后重试该命令。
所在位置 C:\Users\D\scoop\apps\scoop\current\lib\decompress.ps1:81 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationExcept
    ion
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\D\scoop\apps\innounp\0.49\innounp049.rar.
Log file:
  ~\scoop\apps\innounp\0.49\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=innounp%400.49%3a+decompress+error

**Comment by Ash258** [comment]
`scoop install 7zip` or `scoop config 7ZIPEXTRACT_USE_EXTERNAL $true` (in case you have 7zip insalled without scoop) and reinstall

**Comment by fantasyding** [comment]
When i installed 7zip,it works. Thanks for your help
