### ISSUE TITLE
imagemagick: satisfy dependency with either `ffmpeg` or `ffmpeg-nightly`?

### ISSUE THREAD

**Issue by slippycheeze** [ScoopInstaller/Main#1215]
As far as I can tell the imagemagick ffmpeg dependency isn't through a shared DLL or whatever, just through invoking the command line tools.  Given that, it'd be great if it could satisfy the dependency with either `ffmpeg` (as now) or `ffmpeg-nightly`.

Alternately, some solution that didn't involve `scoop reset ffmpeg-nightly` after `ffmpeg` overwrites the shims....

**Comment by Benjamin-Connelly** [comment]
I am here for this also @slippycheeze . The hash is failing for `ffmpeg` and I was hoping that using `ffmpeg-nightly` would satisfy the dependency. Were you able to make this work with the nightly?

**Comment by slippycheeze** [comment]
No progress; I just `scoop reset ffmpeg-nightly` after an update.

**Comment by rashil2000** [comment]
This problem was solved in #2885
