### ISSUE TITLE
Install legit without git as dependence.

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Main#1247]
I have a python, but it's installed on MSYS2 and I don't want to have another or multiple Python installed on Windows. No `pip` for me. I don't want my user `%PATH%` populated either.

When I tried to install `legit`, it install `git` automatically. **But, I already has `mingit` installed**. I solve this by uninstall `git` after the installation. I had to `scoop reset mingit` to fix the shims too.

I suggest `git` should removed from `legit`'s dependency. You can add extra note later on; just like `mingit` with its `openssh`.

This is my assumption, I haven't tried it: will scoop installs `git` if I already had Git for Windows installed (not from Scoop, but by installer and system scope; eg, it's installed on `C:\Program Files`)? Please fix.

**Comment by rasa** [comment]
@gphg Was the git executable in your path, when you installed legit? That might be a workaround for your issue.

**Comment by gphg** [comment]
@rasa It was.
