### ISSUE TITLE
python@3.8.3: hash check failed

### ISSUE THREAD

**Issue by franziskakuehn** [ScoopInstaller/Main#1249]
scoop install python
Installing 'python' (3.8.3) [64bit]
python-3.8.3-amd64.exe (26.5 MB) [================================================================================================================================] 100%
Checking hash of python-3.8.3-amd64.exe ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."
ERROR Hash check failed!
App:         main/python
URL:         https://www.python.org/ftp/python/3.8.3/python-3.8.3-amd64.exe#/setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    fd2458fa0e9ead1dd9fbc2370a42853b
Actual:

**Comment by Ash258** [comment]
> ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."

Most likely antivirus deleted file.

**Comment by franziskakuehn** [comment]
just installed scoop.

**Comment by franziskakuehn** [comment]
Fips mode was enabled on windows.
