### ISSUE TITLE
python@3.8.3: decompress error

### ISSUE THREAD

**Issue by salvadorbs** [ScoopInstaller/Main#1267]
I'm trying update Python via Scoop. I have FilePath empty or null. This is log:

> Updating 'python' (3.8.2 -> 3.8.3)
> Downloading new version
> python-3.8.3-amd64.exe (26,5 MB) [==================================================================================================================================================================================================] 100%
> Checking hash of python-3.8.3-amd64.exe ... ok.
> install-pep-514.reg (555 B) [=======================================================================================================================================================================================================] 100%
> Checking hash of install-pep-514.reg ... ok.
> 
> uninstall-pep-514.reg (86 B) [======================================================================================================================================================================================================] 100%
> Checking hash of uninstall-pep-514.reg ... ok.
> Uninstalling 'python' (3.8.2)
> Running uninstaller script...
> Removing shim for 'python'.
> Removing shim for 'pythonw'.
> Removing shim for 'python3'.
> Removing shim for 'idle'.
> Removing shim for 'idle3'.
> Unlinking D:\scoopApps\apps\python\current
> Installing 'python' (3.8.3) [64bit]
> Loading python-3.8.3-amd64.exe from cache
> Loading install-pep-514.reg from cache
> Loading uninstall-pep-514.reg from cache
> Running pre-install script...
> Running installer script...
> Invoke-ExternalCommand : Impossibile convalidare l'argomento sul parametro 'FilePath'. L'argomento è null o vuoto. Fornire un argomento che non sia null o vuoto ed eseguire di nuovo il comando.
> In D:\scoopApps\apps\scoop\current\lib\decompress.ps1:281 car:38
> + ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
> +                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand
> 
> Failed to extract files from D:\scoopApps\apps\python\3.8.3\setup.exe.
> Log file:
>   D:\scoopApps\apps\python\3.8.3\dark.log
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/ScoopInstaller/Main/issues/new?title=python%403.8.3%3a+decompress+error

**Comment by Ash258** [comment]
`scoop install dark`
