### ISSUE TITLE
install python with windows registry

### ISSUE THREAD

**Issue by Cologler** [ScoopInstaller/Main#128]
reference from [pip-514](https://www.python.org/dev/peps/pep-0514).

maybe:

``` registry
[HKEY_CURRENT_USER\Software\Python\Scoop]
(Default) = (value not set)
DisplayName = "Scoop"
SupportUrl = "https://github.com/lukesampson/scoop"

[HKEY_CURRENT_USER\Software\Python\Scoop\3.7.3]
(Default) = (value not set)
DisplayName = "Python 3.7.3"
SupportUrl = "https://github.com/lukesampson/scoop"
Version = "3.0.12345.0"
SysVersion = "3.7.3"
SysArchitecture = "64bit"

[HKEY_CURRENT_USER\Software\Python\Scoop\3.7.3\InstallPath]
(Default) = "C:\Users\<User>\scoop\apps\python\3.7.3"
ExecutablePath = "C:\Users\<User>\scoop\apps\python\3.7.3\python.exe"
WindowedExecutablePath = "C:\Users\<User>\scoop\apps\python\3.7.3\pythonw.exe"
```

**Comment by rasa** [comment]
Are you suggesting that https://github.com/ScoopInstaller/Main/blob/master/bucket/python.json be modified to add the above entries to the registry?

**Comment by Cologler** [comment]
Yes

**Comment by niheaven** [comment]
Put it in a separate `.reg` as `vscode` or wait after Registry support added into scoop-core.

Writing these keys in install script is not recommanded.

**Comment by idbrii** [comment]
I ran into this issue trying to install python for use with vim.

Looks like scoop had this issue before in lukesampson/scoop#160, the registry keys for the official python installer were added to post install, but removed in lukesampson/scoop@2ad8316764c4f61d90c6f5366f4459520f582eee.

@niheaven Are you suggesting that scoop outputs a .reg file for the user to run after installing?

**Comment by niheaven** [comment]
In general, scoop will not affect Windows Registry, so a seperate .reg file is preferred.

If someone really need it, please submit a PR.
