### ISSUE TITLE
gnuplot@5.4.0: download via aria2 failed

### ISSUE THREAD

**Issue by Dothion** [ScoopInstaller/Main#1285]
```
ERROR Download failed! (Error 3) Resource was not found
ERROR https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.4.0/gp540-win64-mingw.7z
    dir=C:\Users\thinkpad\scoop\cache
    out=gnuplot#5.4.0#https_downloads.sourceforge.net_project_gnuplot_gnuplot_5.4.0_gp540-win64-mingw.7z

ERROR & 'C:\Users\thinkpad\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\thinkpad\scoop\cache\gnuplot.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12356 --continue --all-proxy='127.0.0.1:8123'
```

The windows binary for 5.4.0 is delayed, so actually the latest version on windows is 5.2.8.

**Comment by jagd** [comment]
Maybe we should consider to switch off the automatic update for gnuplot?

**Comment by fes111-7** [comment]
Is it possible to install the 5.2.8 version using Scoop? I have just tried to install gnuplot for the first time using Scoop, but I'm stuck with nothing at the moment.

**Comment by Dothion** [comment]
`scoop install gnuplot@5.2.8`

发件人: fes111-7<mailto:notifications@github.com>
发送时间: 2020年9月2日 18:57
收件人: ScoopInstaller/Main<mailto:Main@noreply.github.com>
抄送: Dothion<mailto:Dothion@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ScoopInstaller/Main] gnuplot@5.4.0: download via aria2 failed (#1285)


Is it possible to install the 5.2.8 version using Scoop? I have just tried to install gnuplot for the first time using Scoop, but I'm stuck with nothing at the moment.

―

**Comment by fes111-7** [comment]
Thanks a lot! Found that on the internet literally at the same moment that you replied. Thanks again. @Dothion
