### ISSUE TITLE
`$?` returned from scoop installed programs is wrong.

### ISSUE THREAD

**Issue by AndrewSav** [ScoopInstaller/Main#1300]
With scoop:

![4P9au0c 1](https://user-images.githubusercontent.com/658865/89111552-1a106680-d4ab-11ea-8a4e-e1594bbf86eb.png)

Without scoop:

![2020-08-02_10-30-24](https://user-images.githubusercontent.com/658865/89111564-42986080-d4ab-11ea-88b2-ab4e31cf31b0.png)

Apparently scoop does something that changes this variable that affects scripting.

**Comment by AndrewSav** [comment]
Wrong repo, let me repost

**Comment by Ash258** [comment]
Duplicate of lukesampson/scoop#3890, lukesampson/scoop#4003
