### ISSUE TITLE
Installation of packages for cygwin are not in /usr/bin

### ISSUE THREAD

**Issue by nitrocode** [ScoopInstaller/Main#1331]
## Problem

I did notice that installing packages using cygwin-setup and apt-cyg that these packages were installed in this directory which is not in my path.

```
/cygdrive/c/Users/user/scoop/persist/cygwin/root/usr/bin/
```

I believe this is due to 

https://github.com/ScoopInstaller/Main/blob/7279133e098327d4b23ac3e2d39993456940530b/bucket/cygwin.json#L44-L51

## Proposed solution

Perhaps we can omit the `--root` argument as that seems to be why the installed packages appear there instead of in `/usr/bin`. Thoughts?

Also, perhaps we can create default packages for `apt-cyg` using the arg `--packages wget,ca-certificates,gnupg`

## Workaround

I followed these steps and were able to get it to work correctly.

1. `scoop install cygwin`
1. Manually install wget, ca-certificates, and gnupg using cygwin-setup.exe
1. Using the fork suggested by @E3V3A, install `apt-cyg`
    ```
    git clone https://github.com/kou1okada/apt-cyg.git
    ln -s "$(realpath apt-cyg/apt-cyg)" /usr/local/bin/
    ```
1. Install `vim`
    ```
    apt-cyg install vim
    ```
1. Verify that cygwin cannot find vim
    ```
    which vim
    ```
1. Add the following to your `~/.bashrc` using `vi` or whatever editor
    ```
    PATH=/cygdrive/c/Users/user/scoop/persist/cygwin/root/usr/bin/:$PATH
    ```
1. Reload your shell or `source ~/.bashrc`
1. Verify that cygwin can now find vim
    ```
    which vim
    ```

## Reference

* [Full cygwin setup command line args](https://cygwin.com/faq/faq.html#faq.setup.cli)
* Originally posted in https://github.com/lukesampson/scoop/issues/2688 but I assume that was prior to moving the scoop formula to this repo.

**Comment by dwettstein** [comment]
Hey @nitrocode. The packages are installed to `$SCOOP_HOME/persist/...` so that you don't have to reinstall everything after updating Cygwin with Scoop.
If I understand your issue correctly then this directory is not in the PATH of the Cygwin environment, which is another environment than the one you are running Scoop?

**Comment by nitrocode** [comment]
Yes, it's not in the Cygwin PATH so I have to explicitly set this or it is unable to find packages installed with apt-cyg.
