### ISSUE TITLE
puppet-bolt

### ISSUE THREAD

**Issue by dsisnero** [ScoopInstaller/Main#1364]
puppet-bolt installs but is not able to run

F:\programming\source\repos\rails\autocomplete_stimulus_example>bolt --help
Traceback (most recent call last):
        2: from F:/windows/scoop/apps/puppet-bolt/current/bin/bolt:23:in `<main>'
        1: from F:/windows/scoop/apps/puppet-bolt/2.24.1/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
F:/windows/scoop/apps/puppet-bolt/2.24.1/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem bolt (>= 0.a) with executable bolt (Gem::GemNotFoundException)

**Comment by dsisnero** [comment]
I think it is because of ruby scoop manifest setting the GEM_HOME because of versions.  need to UNSET THIS

**Comment by jfastnacht** [comment]
Related: https://github.com/puppetlabs/bolt/issues/2222

**Comment by jfastnacht** [comment]
The missing files are now within the tarball at `share\install-tarballs\ruby-2.5.8.tgz`. The `2.5.8` is a varying version number.

According to the answers within the issue in the puppet bolt repository, the bolt.cmd is not the correct way of using Bolt. There is a PowerShell module which should be installed as well.

**Comment by dsisnero** [comment]
The GEM_HOME command is still causing issues:

Updating 'puppet-bolt' (2.32.0 -> 2.33.1)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 2dba1e|OK  |   3.6MiB/s|F:/windows/scoop/cache/puppet-bolt#2.33.1#https_downloads.puppetlabs.com_windows_puppet6_puppet-bolt-2.33.1-x64.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of puppet-bolt-2.33.1-x64.msi ... ok.
Uninstalling 'puppet-bolt' (2.32.0)
Removing shim for 'bolt'.
Unlinking F:\windows\scoop\apps\puppet-bolt\current
Installing 'puppet-bolt' (2.33.1) [64bit]
Loading puppet-bolt-2.33.1-x64.msi from cache.
Extracting puppet-bolt-2.33.1-x64.msi ... done.
Linking F:\windows\scoop\apps\puppet-bolt\current => F:\windows\scoop\apps\puppet-bolt\2.33.1
Creating shim for 'bolt'.
Running post-install script...
INFO  Extract tarball of gems...
'puppet-bolt' (2.33.1) was installed successfully!

F:\programming\source\repos\git\dsisnero\faa_auth>bolt
Traceback (most recent call last):
        2: from F:/windows/scoop/apps/puppet-bolt/current/bin/bolt:23:in `<main>'
        1: from F:/windows/scoop/apps/puppet-bolt/2.33.1/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
F:/windows/scoop/apps/puppet-bolt/2.33.1/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem bolt (>= 0.a) with executable bolt (Gem::GemNotFoundException

**Comment by jfastnacht** [comment]
@dsisnero it should be fixed with the latest PR. You can wait for the PR to be accepted or try out the new manifest by using:

```
scoop install https://raw.githubusercontent.com/jfastnacht/Main/fix/puppet-bolt-gem-home/bucket/puppet-bolt.json
```

**Comment by dsisnero** [comment]
thanks-  I wonder if it would be better to not set GEM_HOME  and GEM_PATH in the ruby package and just use uru 
scoop install https://bitbucket.org/jonforums/uru/downloads/uru.json to manage the path changes for the various ruby versions
