### ISSUE TITLE
vagrant@2.2.10: decompress error

### ISSUE THREAD

**Issue by jan2ary** [ScoopInstaller/Main#1377]
PS C:\Users\username> scoop install vagrant
Installing 'vagrant' (2.2.10) [64bit]
vagrant_2.2.10_x86_64.msi (238.4 MB) [========================================================================] 100%
Checking hash of vagrant_2.2.10_x86_64.msi ... ok.
Extracting vagrant_2.2.10_x86_64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\username\scoop\apps\vagrant\2.2.10\vagrant_2.2.10_x86_64.msi.
Log file:
  ~\scoop\apps\vagrant\2.2.10\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=vagrant%402.2.10%3a+decompress+error

[msi.log](https://github.com/ScoopInstaller/Main/files/5149017/msi.log)

**Comment by Ash258** [comment]
> "Error 1618: 'Another installation is already in progress"

Lessmsi is preferred for msi extraction

`scoop config MSIEXTRACT_USE_LESSMSI true` and try again
