### ISSUE TITLE
Deprecate ffmpeg manifests until alternative builds are provided

### ISSUE THREAD

**Issue by Ash258** [ScoopInstaller/Main#1379]
Builds provided by Zeranoe will no longer be provided on 18.09.2020

![image](https://user-images.githubusercontent.com/13260377/91810748-b9518680-ec2e-11ea-9f78-b8e3b2ae4444.png)

**Comment by Witchilich** [comment]
https://jeremylee.sh/bin.html
https://github.com/AnimMouse/ffmpeg-autobuild/releases
https://github.com/AnimMouse/ffmpeg-stable-autobuild/releases
Can we also add x265 to the bucket?
