### ISSUE TITLE
gzip@1.3.12: hash check failed

### ISSUE THREAD

**Issue by zhaojin0** [ScoopInstaller/Main#1383]
Installing 'gzip' (1.3.12) [64bit]
gzip-1.3.12-2-msys-1.0.13-bin.tar.lzma (746 B) [==============================================================] 100%
Checking hash of gzip-1.3.12-2-msys-1.0.13-bin.tar.lzma ... ERROR Hash check failed!
App:         main/gzip
URL:         https://downloads.sourceforge.net/project/mingw/MSYS/Base/gzip/gzip-1.3.12-2/gzip-1.3.12-2-msys-1.0.13-bin.tar.lzma
First bytes: 3C 68 74 6D 6C 3E 3C 68
Expected:    a8954ccefa9732cd16b68e2fb50bfef281465c78
Actual:      8340847f43894bcbb48b66ef2bd7126ac823a02a
SourceForge.net is known for causing hash validation fails. Please try again before opening a ticket.

**Comment by rasa** [comment]
See #1384
