### ISSUE TITLE
latex: Use updated installer

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Main#139]
Per https://miktex.org/download#portable, it seems we'll have to do something like:
```
miktexsetup --package-set=basic download
miktexsetup install
```
See also https://miktex.org/faq/setup-cli and https://miktex.org/howto/deploy-miktex

**Comment by niheaven** [comment]
It's the same that use installer and be installed as portable, and this prevent downloading additional files that in install scripts.

**Comment by rasa** [comment]
Already being done in #123
