### ISSUE TITLE
ffmpeg@4.3.1: download via aria2 failed

### ISSUE THREAD

**Issue by lloyd18** [ScoopInstaller/Main#1406]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
    referer=https://ffmpeg.zeranoe.com/builds/win64/static/
    dir=D:\Software\Scoop\cache
    out=ffmpeg#4.3.1#https_ffmpeg.zeranoe.com_builds_win64_static_ffmpeg-4.3.1-win64-static.zip

ERROR & 'D:\Software\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Software\Scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6872 --continue

**Comment by kidonng** [comment]
#1379
Consider using `ffmpeg-nightly` instead

**Comment by lloyd18** [comment]
已经这样做了
