### ISSUE TITLE
[Proposal] Rename package 'latex' to 'miktex-basic'

### ISSUE THREAD

**Issue by mateusz-piotrowski** [ScoopInstaller/Main#1427]
Hi,

I wanted update my CV written in LaTeX. I downloaded **latex** package via **scoop** and tried build the project using **Visual Studio Code**.
During project building a few packages has been downloaded.
I checked what happen - why that packages has been downloaded.

I checked manifest file and be surprised when saw **miktex-basic** as package which has been installed.

In my opinion this package name is not intuitive for users and should be renamed.

My CV is advanced document and I need a full **LaTeX** package to build it.

I will try add new manifest which will install a full package but now I don't have enought time for it and I must do it manually.

**Comment by JanPokorny** [comment]
You may be confused about how MikTeX works. MikTeX is a LaTeX distribution for Windows that automatically installs packages on the fly: when you try to compile a document containing references to not installed packages, they will be automatically downloaded. Just install the `latex` package from scoop, then run `pdflatex cv.tex` to see that it works.

**Comment by mateusz-piotrowski** [comment]
I tried find full version for MiKTeX but I don't find.
Maybe you are right and I do not understand how it works. But even if additional packages has been downloaded something still was wrong and Visual Studio Code was not able to build my document.
I removed MiKTeX and install full package of TeX Live and everything works smoothly.
Maybe MiKTeX is not for me or my document need some fix.

**Comment by JanPokorny** [comment]
There was probably some other problem, maybe the VSCode plugin you use did not detect the installation. I do agree that `latex` is a bad name for the package, as `miktex` would be more representative. However since Scoop has no mechanism for renaming packages (users would need to re-install), I don't think renaming is worth the effort.

**Comment by mateusz-piotrowski** [comment]
Thank you for your reply.
I am glad you agree with me ; - )
Maybe, in the future someone will create function to rename package and adjust that change for everyone who using it ; - )
In my opinion we can close with conversation.

Have a nice weekend,
Regards,
Mateusz.
