### ISSUE TITLE
espanso@0.7.2: decompress error

### ISSUE THREAD

**Issue by Almo7aya** [ScoopInstaller/Main#1441]
![image](https://user-images.githubusercontent.com/17254073/94349065-6efed200-0041-11eb-8ccf-0e76fcf2d425.png)

**Comment by jdambron** [comment]
I could not reproduce the issue. Espanso 0.7.2 was installed correctly.
![Annotation 2020-10-02 141503](https://user-images.githubusercontent.com/5672954/94922085-d7263b80-04b9-11eb-884d-d53f651a4b1b.png)

**Comment by Almo7aya** [comment]
I'm still getting the error! 🤷‍♂️
