### ISSUE TITLE
a ffmpeg refresh needed

### ISSUE THREAD

**Issue by slaughtering** [ScoopInstaller/Main#1445]
Since the shutdown of zeranoe builds, scoop ffmpeg unusable now.
Note there are already solutions  #1424 #1425 , and needed to pick one.

1 https://github.com/BtbN/FFmpeg-Builds/releases	

2 https://www.gyan.dev/ffmpeg/builds/packages/

3 https://ottverse.com/ffmpeg-builds/

4 https://github.com/AnimMouse/ffmpeg-stable-autobuild/releases

1 and 2 are from official ffmpeg.org download page, 4 is stable and has win32 builds while others only 64bit, 1 is nightly by now, 3 weekly git , 2 both twice-weekly git and stable releases.

**Comment by wstein** [comment]
Does anyone need also this variants?

ffmpeg-N-99300-gb0dee629da-win64-gpl-vulkan.zip
ffmpeg-N-99300-gb0dee629da-win64-gpl.zip
ffmpeg-N-99300-gb0dee629da-win64-lgpl-vulkan.zip
ffmpeg-N-99300-gb0dee629da-win64-lgpl.zip
