### ISSUE TITLE
nmap 7.90 can't install

### ISSUE THREAD

**Issue by slaughtering** [ScoopInstaller/Main#1465]
silent installation does not work as of v7.90 
![Nmap Setup 2020_10_4 3_55_50](https://user-images.githubusercontent.com/62363507/95000915-a2b89980-05f7-11eb-8534-29ea2917afd8.png)

**Comment by slaughtering** [comment]
suggest using nmap-portable

**Comment by JanPokorny** [comment]
`nmap-portable` also broken, probably a related issue. File `npcap-oem.exe` is missing (searched for it, not located anywhere in the downloaded package).

![obrazek](https://user-images.githubusercontent.com/4580066/98601733-c13d3f00-22df-11eb-891c-e101ab69ca7b.png)

Both most likely part of a "crackdown" on "unlicenced OEM uses". Unlike what this manifest states, the licence is not actually GPL-2.0-only, but a custom modified version of it, banning the distribution on "proprietary hardware". I'm no lawyer, but I believe that this does not exclude Scoop (or other Windows package managers), it just happens to be collateral damage. I checked Ubuntu packages and it contains [the up-to-date version of nmap, 7.91](https://packages.ubuntu.com/groovy/nmap), so it doesn't seem like package managers specifically are the problem.

Possible solutions:
- Pin to an older nmap version (tested that 7.80 works, maybe a bit newer one <7.90 will work)
- Contact the author and try to arrive at a solution that re-enables inclusion in Windows package managers while not damaging his business model (ping @fyodor, or maybe [shoot him an email](https://insecure.org/fyodor/) later if he doesn't see the mention)

**Comment by PrplHaz4** [comment]
Here is a related issue for `nmap-portable`: #4168

Should the update to 7.91 not be reverted until the issue is resolved?  It seems like keeping it as is will just create a bunch of broken installs that will lead to more issues later...

**Comment by rashil2000** [comment]
Superseded by #3037
