### ISSUE TITLE
gcc@9.3.0-1: download via aria2 failed

### ISSUE THREAD

**Issue by Skips75** [ScoopInstaller/Main#1485]
![scoop-install-gcc](https://user-images.githubusercontent.com/63970801/95507380-a0688d80-09b1-11eb-8aac-d6730af28c92.png)

Hi,
trying to install gcc-9.3.0 via **sudo scoop install gcc -g** results in the error message as reported in the attached image.

**Comment by wstein** [comment]
The current versions on gcc package are pretty old! 
Why not using the msys2 package and pacman to install gcc?

like:
```
scoop install msys2
msys2
pacman -S gcc
```
