### ISSUE TITLE
Outstanding Excavator issues

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Main#150]
Here's a list of the outstanding Excavator issues found in log https://scoop.r15.ch/main/mud-20200203-010001.log at [https://scoop.r15.ch/main/](https://scoop.r15.ch/main/?sort=time&order=desc):

## Needing triage (newest to oldest):

None.

## Fixable:

None.

## Being fixed:

1. apimtemplate: 0.3-gamma (scoop version is 0.2-beta) autoupdate available. Fixed in #646. Thanks @rasa!

## Version parsing issues:

None.

## Missing binaries:

1. [pngquant](../blob/master/bucket/pngquant.json): couldn't match ` 'Binary for Windows.*?([\d.]+)'` in https://pngquant.org/ . See #299.
1. azure-functions-core-tools: 3.0.2106 (scoop version is 2.7.2100) autoupdate available. ERROR Could not update azure-functions-core-tools 32bit. Missing binaries at https://github.com/Azure/azure-functions-core-tools/releases
1. azure-ps: couldn't match `'download/v?(?<release>[\w-.]+)/Az-Cmdlets-([\d.]+)-x64\.msi'` in https://github.com/Azure/azure-powershell/releases/latest
1. ccl: 1.11.8 (scoop version is 1.11.5) autoupdate available. Missing binaries at https://github.com/Clozure/ccl/releases
1. jdupes: 1.14.0 ~~1.13.3~~ (scoop version is 1.13.2) autoupdate available. ERROR Could not update jdupes 32bit. Missing binary at https://github.com/jbruchon/jdupes/releases
1. rethinkdb: 2.4.0 (scoop version is 2.3.6) autoupdate available. https://rethinkdb.com/docs/install/windows/ lists https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip which is 404.
1. dig: 9.14.9 (scoop version is 9.14.8) autoupdate available. Missing 32bit build. See https://ftp.isc.org/isc/bind9/9.14.9/
1. pdf2djvu: 0.9.14 (scoop version is 0.9.13) autoupdate available. See https://github.com/jwilk/pdf2djvu/releases
1. [artifact](../blob/master/bucket/artifact.json): Missing windows builds, See https://github.com/vitiral/artifact/releases. Fix coming soon in vitiral/artifact#246, vitiral/artifact#271.

## Network issues:

None.

## Upstream issues:

1. llvm: couldn't match 'releases/download.html#([\d.]+)' in https://www.llvm.org/. Scoop is not decompressing the gzip'd connect. Not sure if this is an upstream server issue, or a scoop issue.
1. [less](../blob/master/bucket/less.json): 404 on https://www.guysalias.tk/misc/less/ and http://www.guysalias.tk/misc/less/.

## Fixed:
<details>
  <summary>Click to expand</summary>
1. cppcheck: 1.90 (scoop version is 1.89) autoupdate available. Missing 32bit build. See https://github.com/danmar/cppcheck/releases. Fixed in #737. Thanks @shyun3!
1. shasum: 0.2020.01.26 (scoop version is 0.2018.08.04). Fixed in #780. Thanks @rasa!
1. say: 0.2020.01.26 (scoop version is 0.2018.08.04). Fixed in #779. Thanks @rasa!
1. mercurial: couldn't match 'Mercurial-([\d.]+).exe' in https://www.mercurial-scm.org/release/windows/latest.dat. Fixed in #778. Thanks @rasa!
1. bochs: 2.6.11 (scoop version is 2.6.10) autoupdate available. ERROR Could not update bochs 32bit. Fixed in #777. Thanks @rasa!
1. redpen: 1.10.4 (scoop version is 1.10.3) autoupdate available. Fixed in #776. Thanks @rasa!
1. bind: 9.14.9 (scoop version is 9.14.8) autoupdate available.  Fixed in #711. Thanks @linsui!
1. kops: 1.15.1 (scoop version is 1.15.0) autoupdate available. ERROR Could not update kops 64bit. Fixed in #769. Thanks @Ash258!
1. broot: 0.12.0 (scoop version is 0.11.8) autoupdate available. The remote server returned an error: (404) Not Found. ERROR Could not update broot 64bit. Fixed in #771. Thanks @Ash258!
1. k9s: 0.13.2 (scoop version is 0.12.0) autoupdate available. ERROR Could not update k9s 32bit. Fixed in #743. Thanks @cristichiru!
1. gcc: couldn't match `'x86_64-([\d.]+)-release-posix-sjlj-rt_v(?<rt>\d+)-rev(\d+)\.7z'` in https://downloads.sourceforge.net/project/mingw-w64/README.rst. Fixed in #715. Thanks @linsui!
1. dotnet-sdk: You cannot call a method on a null-valued expression. Fixed in #641. Thanks @CarlosDomingues! Fixed again in #714. Thanks @niheaven!
1. ghq: 0.17.4 (scoop version is 0.17.1) autoupdate available. Fixed in #706. Thanks @Ash258!
1. nu: 0.7.0 (scoop version is 0.5.0) autoupdate available. Fixed in #661. Thanks @niheaven!
1. winpython: couldn't match '-([\d.]+)Zero\.exe' in https://github.com/winpython/winpython//releases/latest . Fixed in #520 and #523. Thanks @rasa!
1. win-acme: 2.1.2.636 (scoop version is 2.1.1.593) autoupdate available. Fixed in #663. Thanks @niheaven!
1. peco: 0.5.4 (scoop version is 0.5.3) autoupdate available. Fixed in #662. Thanks @niheaven!
1. kustomize: 3.5.1 (scoop version is 3.2.3) autoupdate available. Fixed in #659. Thanks @niheaven!
1. aws-iam-authenticator: couldn't match ` '/(?<kubernetes>[\d.]+)/(?<version>[\d-]+)/bin/windows/amd64/aws-iam-authenticator.exe'` in https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html. Fixed in #658 and #668. Thanks @niheaven and @tynril!
1. cormanlisp: couldn't match 'tree/v([\w.]+)/' in https://github.com/sharplispers/cormanlisp/releases/latest . Fixed in #647. Thanks @rasa!
1. gnuplot: 5.2.8 (scoop version is 5.2.7) autoupdate available. Fixed in #634. Thanks @rasa!
1. ie11webdriver: The remote server returned an error: (302) Found. URL http://www.seleniumhq.org/download/ is not valid. Fixed in #604. Thanks @linsui!
1. buffalo: 0.15.2 (scoop version is 0.15.1) autoupdate available. Fixed in #633. Thanks @rasa!
1. exiftool: The remote server returned an error: (301) Moved Permanently. URL https://owl.phy.queensu.ca/~phil/exiftool/ver.txt is not valid. Fixed in #632. Thanks @rasa!
1. unbound: 1.9.5 (scoop version is 1.9.4) autoupdate available. Fixed in #600. Thanks @linsui!
1. cmder: 1.3.13 (scoop version is 1.3.12) autoupdate available. Fixed in #607. Thanks @linsui!
1. sops: 3.5.0 (scoop version is 3.4.0) autoupdate available. Fixed in #598. Thanks @linsui!
1. gnirehtet: 2.4 (scoop version is 2.3) autoupdate available. Fixed in #599. Thanks @linsui!
1. gifski: 0.9.2 (scoop version is 0.9.1). Fixed in #481. Thanks @h404bi!
1. selenium: The remote server returned an error: (302) Found. URL https://www.seleniumhq.org/download/ is not valid. Fixed in #579. Thanks @linsui!
1. uncrustify: 0.70.0 (scoop version is 0.69.0) autoupdate available. Fixed in #587. Thanks @linsui!
1. [dos2unix](../blob/master/bucket/dos2unix.json): v7.4.1 is available (scoop version is 7.4.0). Fixed in #451 by @rasa.
1. win-acme: couldn't match 'win-acme\.v([\d.]+)\.zip' in https://github.com/PKISharp/win-acme/releases/latest . Fixed in #573. Thanks @linsui!
1. nu: 0 (scoop version is 0.4.0). Fixed in #549. Thanks @issaclin32!
1. kubefwd: 1.9.5 (scoop version is 1.9.4) autoupdate available. Fixed in #550. Thanks @issaclin32!
1. just: 0.4.5 (scoop version is 0.4.4) autoupdate available. Fixed in #541. Thanks @issaclin32!
1. [nikto](../blob/master/bucket/nikto.json): Expired cert. _(The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure. URL https://projects.giacomodrago.com/nikto-win/ is not valid)_. Fixed in #528. Thanks @brandon93s!
1. watchexec: 1.11.1 (scoop version is 1.10.3) autoupdate available. Fixed in #530. Thanks @brandon93s!
1. jd-cmd: 1.0.0 (scoop version is 0.9.2). Fixed in #529. Thanks @brandon93s!
1. neko: 2.3.0 (scoop version is 2.2.0) autoupdate available. Fixed in #514. Thanks @linsui!
1. [kustomize](../blob/master/bucket/kustomize.json): No Windows binaries in v2.1.0. See https://github.com/kubernetes-sigs/kustomize/releases/ . See [here](https://github.com/kubernetes-sigs/kustomize/commit/af2b101fe23927a6f9fad571eeee569ff46acbe2#diff-e64f512cda0630a85dbc662ea1e9eb21). Fixed #471. Thanks @kungfutse!
1. yara: 3.11.0 (scoop version is 3.10.0). Fixed in #476. Thanks @linsui!
1. fossil: 404 on v2.10 (scoop version is 2.9) (no bit). Fixed in https://github.com/ScoopInstaller/Main/commit/1cdbc390f9bdbfc8d3ce572d7b59768a150ac4d5. Thanks @r15ch13! See also #472.
1. freebasic: 1.07.1 (scoop version is 1.07.0) (32bit). Fixed in #474. Thanks @h404bi!
1. [traefik](../blob/master/bucket/traefik.json): 404 on v1.7.17 (32bit) (scoop version is 2.0.0). See https://github.com/ScoopInstaller/Main/pull/425#issuecomment-534367754 and https://github.com/ScoopInstaller/Versions/commit/cd317ee5fd97eda92a5b9914020f5d7dc9666fcd .
1. [buck](../blob/master/bucket/buck.json): 403 on https://chocolatey.org/packages/.
1. [nunit-extension-teamcity-event-listener](../blob/master/bucket/nunit-extension-teamcity-event-listener.json): 403 on https://chocolatey.org/packages/.
1. [nunit-extension-nunit-v2-result-writer](../blob/master/bucket/nunit-extension-nunit-v2-result-writer.json): 403 on https://chocolatey.org/packages/.
1. [nunit-extension-nunit-v2-driver](../blob/master/bucket/nunit-extension-nunit-v2-driver.json): 403 on https://chocolatey.org/packages/.
1. [nunit-extension-vs-project-loader](../blob/master/bucket/nunit-extension-vs-project-loader.json): 403 on https://chocolatey.org/packages/.
1. [nunit-console](../blob/master/bucket/nunit-console.json): 403 on https://chocolatey.org/packages/.
1. [llvm](../blob/master/bucket/llvm.json): Releases location changed (#437)
1. [bulk-rename-command](../blob/master/bucket/bulk-rename-command.json): 404. Fixed in #431. Thanks @niheaven!
1. [traefik](../blob/master/bucket/traefik.json): 404 on v2.0.0 (32bit). Fixed in #425. Thanks @rasa!
1. [links](../blob/master/bucket/links.json): 404 on v2.20.1 (32bit). Fixed in #402. Thanks @linsui!
1. [flac](../blob/master/bucket/flac.json): couldn't match '/flac-([\d.]+)-win\.zip' in https://ftp.osuosl.org/pub/xiph/releases/flac/?C=M;O=D . See #313. _(The regex appears OK, firewall/user agent issue?)_ Fixed In #398. Thanks @linsui!
1. [mongodb](../blob/master/bucket/mongodb.json): **403** on v4.2.0 (64bit). Fixed in #399. Thanks @linsui!
1. [sqlite](../blob/master/bucket/sqlite.json): couldn't match 'sqlite-tools-win32-x86-(?<number>[\d]+).zip.*?for SQLite version ([\d.]+)\.' in https://www.sqlite.org/download.html . _(The regex appears OK, firewall/user agent issue?)_ . Fixed in #400. Thanks @linsui!
1. [chromedriver](../blob/master/bucket/chromedriver.json): couldn't match 'Latest stable release:\s*<a[^>]+>ChromeDriver[^\d]*([\d.]+)<' in https://chromedriver.chromium.org/ . Fixed in #310. Thanks @niheaven!
1. [cmake](../blob/master/bucket/cmake.json): 404 on v3.15.0 (32bit) . Fixed in #237. Thanks @linsui!
1. [cuda](../blob/master/bucket/cuda.json): 404 on v10.1.243_426.00 (64bit). Fixed in #375. Thanks @linsui!
1. [doctl](../blob/master/bucket/doctl.json): 404 on v1.21.1. Fixed in #243. Thanks @niheaven!
1. [dosbox](../blob/master/bucket/dosbox.json): Fixed in #186. Thanks @hoilc!
1. [flac](../blob/master/bucket/flac.json): 404 on v1.3.3 (nobit). Fixed in #313. Thanks @rasa!
1. [gdrive](../blob/master/bucket/gdrive.json): couldn't match ` '(?sm)windows-386.*?id=(?<id32>[^&]+).*?([\d.]+).*?id=(?<id64>[^&]+)'` in https://raw.githubusercontent.com/prasmussen/gdrive/master/README.md . Fixed in #294. Thanks @niheaven!
1. [gdrive](../blob/master/bucket/gdrive.json): Fixed in #138. Thanks @rasa!
1. [go](../blob/master/bucket/go.json): couldn't match 'Build version go([\d\.]+)\.' in https://golang.org . Probably should now use https://golang.org/dl/ . Fixed in #236. Thanks @h404bi!
1. [haskell](../blob/master/bucket/haskell.json): No 32-bit binary in v8.6.5. See https://www.haskell.org/platform/windows.html . See #175 and ScoopInstaller/Versions#151. Thanks @JoshuaHall!
1. [kubefwd](../blob/master/bucket/kubefwd.json): Fixed in #178. Thanks @niheaven!
1. [latex](../blob/master/bucket/latex.json): Fixed in #123: 400: Bad Request: URL https://miktex.org/download#portable is not valid. Thanks @niheaven!
1. [llvm](../blob/master/bucket/llvm.json): 404 on v8.0.1 (32bit). Fixed in #305. Thanks @issaclin32!
1. [nano](../blob/master/bucket/nano.json): Fixed in #183. Thanks @se35710!
1. [radare2](../blob/master/bucket/radare2.json): Fixed in #190. Thanks @niheaven!
1. [win-acme](../blob/master/bucket/win-acme.json): 404 on v2.0.9.386 Double v in https://github.com/PKISharp/win-acme/releases/download/vv2.0.9/win-acme.v2.0.9.386.zip . Fixed in #292. Thanks @rasa!
1. [win-acme](../blob/master/bucket/win-acme.json): Fixed in #202. Thanks @niheaven!
1. [edgedriver](../blob/master/bucket/edgedriver.json): No autoupdate. Install requires UAC. See [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads). Fixed in #189 and https://github.com/ScoopInstaller/Versions/pull/153 . Thanks @niheaven!
</details>

## Fixed upstream:
<details>
  <summary>Click to expand</summary>
1. thrift: The operation has timed out. URL https://thrift.apache.org/ is not valid
1. zookeeper: The operation has timed out. URL https://www.apache.org/dist/zookeeper/ is not valid
1. docker-compose: 1.25.2 (scoop version is 1.25.1) autoupdate available. ERROR Could not update docker-compose 64bit.
1. flow: 0.116.1 (scoop version is 0.116.0) autoupdate available
1. shfmt: 3.0.1 (scoop version is 3.0.0) autoupdate available. ERROR Could not update shfmt 32bit
1. far: The operation has timed out. URL https://farmanager.com/download.php is not valid
1. shortcut: The remote server returned an error: (403) Forbidden. URL http://www.optimumx.com/downloads.html is not valid
1. azure-ps: couldn't match 'download/v?(?<release>[\w-.]+)/Az-Cmdlets-([\d.]+)-x64\.msi' in https://github.com/Azure/azure-powershell/releases/latest
1. [glslang](../blob/master/bucket/glslang.json): 404 on v7.12.3352 (no bit?). See https://github.com/KhronosGroup/glslang/releases.
1. coursier: 2.0.0-RC5-4 (scoop version is 2.0.0-RC5-3) autoupdate available. Missing build. See https://github.com/coursier/coursier/releases
1. syncthing: 1.3.3 (scoop version is 1.3.2) autoupdate available. ERROR Could not update syncthing 32bit
1. sampler: 1.1.0 (scoop version is 1.0.3) autoupdate available
1. haxe: 4.0.5 (scoop version is 4.0.3) autoupdate available. Missing binaries. See https://github.com/HaxeFoundation/haxe/releases
1. dvc: 0.76.0 (scoop version is 0.75.1) autoupdate available. Missing binaries. See https://github.com/iterative/dvc/releases
1. traefik: 2.1.0 (scoop version is 2.0.5) autoupdate available. See https://github.com/containous/traefik/releases
1. azure-functions-core-tools: 3.0.2009 (scoop version is 3.0.1975) autoupdate available
1. dnscrypt-proxy: 2.0.36 (scoop version is 2.0.35) autoupdate available
1. buck: The remote server returned an error: (503) Service Unavailable. URL https://chocolatey.org/packages/buck is not valid
1. traefik: **1.7.20** (scoop version is **2.0.7**)
1. vim: 8.1.2412 (scoop version is 8.1.2410) autoupdate available
1. sliksvn: The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: Connection reset by peer. URL https://sliksvn.com/download/ is not valid
1. portainer: 1.23.0 (scoop version is 1.22.2) autoupdate available
1. paket: 5.239.0 (scoop version is 5.238.2) autoupdate available
1. dnscrypt-proxy: 2.0.34 (scoop version is 2.0.33) autoupdate available
1. far: The operation has timed out. URL https://farmanager.com/download.php is not valid
1. deepstream: 5.0.4 (scoop version is 4.2.5) autoupdate available.
1. sass: 1.23.6 (scoop version is 1.23.3) autoupdate available
1. neovim: couldn't match '\/releases\/tag\/(?:v|V)?([\d.]+)' in https://github.com/neovim/neovim/releases/latest
1. flow: 0.111.3 (scoop version is 0.111.2) autoupdate available
1. vim: 8.1.2122 (scoop version is 8.1.2117) _will be fixed upstream eventually_.
1. [nssm](../blob/master/bucket/nssm.json): **504** (Gateway Time-out) on https://nssm.cc/builds.
1. xpdf-tools: The operation has timed out. URL https://www.xpdfreader.com/download.html is not valid
1. dnscrypt-proxy: 2.0.29 (scoop version is 2.0.28)
1. coq: 8.10.1 (scoop version is 8.10.0) autoupdate available
1. elm: 0.19.1 (scoop version is 0.19.0)
1. redpen: 1.10.3 (scoop version is 1.10.1)
1. azure-ps: couldn't match `'download/v?(?<release>[\w-.]+)/Az-Cmdlets-([\d.]+)-x64\.msi'` in https://github.com/Azure/azure-powershell/releases/latest.
1. vim: 8.1.2127 (scoop version is 8.1.2125),
1. time: couldn't match 'time\.ps1[\S\s]*?/(?<sha>[0-9a-f]{40})[\S\s]*?(\d+)-(\d+)-(\d+)' in https://github.com/lukesampson/psutils
1. touch: couldn't match 'touch\.ps1[\S\s]*?/(?<sha>[0-9a-f]{40})[\S\s]*?(\d+)-(\d+)-(\d+)' in https://github.com/lukesampson/psutils
1. shortcut: No route to host. URL http://www.optimumx.com/downloads.html is not valid.
1. zola: 0.9.0 (scoop version is 0.8.0). (no bit).
1. [vim](../blob/master/bucket/vim.json): 404 on v8.1.2079 (scoop version is 8.1.2072) (32bit).
1. [aliyun](../blob/master/bucket/aliyun.json): 404 on v3.0.27 (scoop version is 3.0.26) (64bit).
1. [pdftk](../blob/master/bucket/pdftk.json): The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure. URL https://www.pdflabs.com/tools/pdftk-server/ is not valid.
1. [mercurial](../blob/master/bucket/mercurial.json): URL https://www.mercurial-scm.org/release/windows/latest.dat is not valid.
1. [hub](../blob/master/bucket/hub.json): 404 on v2.12.4 (32bit). No Windows binaries. See https://github.com/github/hub/releases.
1. [mercurial](../blob/master/bucket/mercurial.json): Cannot assign requested address Cannot assign requested address.
1. [vim](../blob/master/bucket/vim.json): 404 on v8.1.2027-2047 (32bit). Missing 32bit build. See https://github.com/vim/vim-win32-installer/releases.
1. [gifski](../blob/master/bucket/gifski.json): 404 on v0.9.1 (no bit). Missing build. See https://github.com/ImageOptim/gifski/releases.
1. [openssl-mingw](../blob/master/bucket/openssl-mingw.json): couldn't match `'dl-(?<curl>[\d._]+)/openssl-(?<version>(?<major>[\da-z.]+)[_\d]*)-win64-mingw'` in https://curl.haxx.se/windows/
1. [coursier](../blob/master/bucket/coursier.json): 404 on v2.0.0-RC3-4 (no bit).
1. [vim](../blob/master/bucket/vim.json): 404 on v8.1.2021 and 8.1.2019 (32bit).
1. [vim](../blob/master/bucket/vim.json): 404 on v8.1.1996 (32bit).
1. [docker](../blob/master/bucket/docker.json): 404 on v19.03.1 (64bit).
1. [ffsend](../blob/master/bucket/ffsend.json): 404 on v0.2.50.
</details>

Let’s strive to keep this list updated, as these issues are addressed.

**Comment by se35710** [comment]
For Nano, there is a Windows port here: https://github.com/lhmouse/nano-win

**Comment by hoilc** [comment]
For traefik,  https://github.com/containous/traefik

> Please be aware that the old configurations for Traefik v1.X are NOT compatible with the v2.X config as of now. If you're testing out v2, please ensure you are using a v2 configuration.

It's not bad to keep tracking 1.x version.

**Comment by niheaven** [comment]
For pngquant, please wait to see if they will update Windows release (now Windows release is still 2.12.0).

**Comment by LoZeno** [comment]
for less: I'm still learning how scoop's manifests work, would it be possible to fix it by making scoop download the source code and compile it locally (using make as a dependency)? The source files are available, in zip and Gzip'd tar formats, and reachable.

**Comment by pratikpc** [comment]
> llvm: couldn't match 'releases/download.html#([\d.]+)' in https://www.llvm.org/. Scoop is not decompressing the gzip'd connect. Not sure if this is an upstream server issue, or a scoop issue.

[This upstream issue seems to have been fixed with LLVM now using GitHub Releases](https://github.com/ScoopInstaller/Main/pull/1741).
