### ISSUE TITLE
Poppler 20.10.0-h5d62644_0 is missing runtime dependencies

### ISSUE THREAD

**Issue by 0x326** [ScoopInstaller/Main#1508]
## Steps to reproduce

```powershell
scoop install poppler
```

Open Windows Explorer and double-click on `~/scoop/apps/poppler/current/bin/pdfunite.exe`

## Error messages

![image](https://user-images.githubusercontent.com/20781397/96346860-0e751a80-106c-11eb-8626-7ec60a907c13.png)
![image](https://user-images.githubusercontent.com/20781397/96346866-15039200-106c-11eb-9056-83763de925f9.png)
![image](https://user-images.githubusercontent.com/20781397/96346867-18971900-106c-11eb-8df9-e342b968ce17.png)
![image](https://user-images.githubusercontent.com/20781397/96346870-1b920980-106c-11eb-8077-de60e3a359eb.png)

**Comment by DavidZhang73** [comment]
A possible alternative https://github.com/oschwartz10612/poppler-windows

**Comment by tan-wei** [comment]
Same for me, and the link @DavidZhang73 give us works for me.
