### ISSUE TITLE
7zip@19.00: hash check failed

### ISSUE THREAD

**Issue by rbharathkumar** [ScoopInstaller/Main#1516]
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=========================================================>                                        ]  59%
Checking hash of 7z1900-x64.msi ... ERROR Hash check failed!
App:         main/7zip
URL:         https://7-zip.org/a/7z1900-x64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    a7803233eedb6a4b59b3024ccf9292a6fffb94507dc998aa67c5b745d197a5dc
Actual:      5c60b4c408a69ba96b962d8b580cd0e816438a0d0c07190bbc3b8d6ff5b24fc2

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4019.00%3a+hash+check+failed

Similar issue faced for dbeaver as well.

**Comment by rbharathkumar** [comment]
Hi, 
thank you for your response.
scoop is up to date.


```
scoop status
Scoop is up to date.
Everything is ok!

```
in fact I have several other apps installed.

```
scoop list
Installed apps:

  7zip 19.00 *failed*
  neovim 0.4.4
  notepadplusplus 7.9 [extras]
  ripgrep 12.1.1
  sbt 1.4.0
  vim-nightly 8.2.1869
  vimtutor 0.2018.07.25
```

As you said, maybe some firewall issues...

**Comment by Ash258** [comment]
Read the output at first before you open issue.

```
====> ] 59%
```
