### ISSUE TITLE
Youtube-dl cannot be downloaded due to legal reasons

### ISSUE THREAD

**Issue by littleli** [ScoopInstaller/Main#1528]
Maybe manifest can be adjusted to have a link to this location recommended by author http://abf-downloads.openmandriva.org/ytdl/

**Comment by equinox** [comment]
> recommende by author

Hi. Could you provide a source for this claim?

**Comment by rasa** [comment]
Proposed fix in #1533

**Comment by rasa** [comment]
Fixed in #1533
