### ISSUE TITLE
ffmpeg-shared 4.3.1-22 doesn't support 32bit architecture

### ISSUE THREAD

**Issue by ntcarver0** [ScoopInstaller/Main#1548]
The latest version of ffmpeg-shared, 4.3.1-22, does not appear to have a 32-bit version, however previous versions up to 4.3.1 did. Here's the command I ran.

`C:\Users\noahc>sudo scoop install -g -a 32bit ffmpeg-shared
`Test-7zipRequirement : Cannot bind argument to parameter 'URL' because it is null.
`At C:\Users\noahc\scoop\apps\scoop\current\lib\depends.ps1:80 char:78
`+ ... elper 7zip) -and (Test-7zipRequirement -URL (url $manifest $arch))) {
`+                                                 ~~~~~~~~~~~~~~~~~~~~~
`    + CategoryInfo          : InvalidData: (:) [Test-7zipRequirement], ParameterBindingValidationException
`    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-7zipRequirement
`
`Test-LessmsiRequirement : Cannot bind argument to parameter 'URL' because it is null.
`At C:\Users\noahc\scoop\apps\scoop\current\lib\depends.ps1:83 char:84
`+ ... Lessmsi) -and (Test-LessmsiRequirement -URL (url $manifest $arch))) {
`+                                                 ~~~~~~~~~~~~~~~~~~~~~
`    + CategoryInfo          : InvalidData: (:) [Test-LessmsiRequirement], ParameterBindingValidationException
`    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-LessmsiRequirement
`
`WARN  Scoop uses 'aria2c' for multi-connection downloads.
`WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
`'ffmpeg-shared' doesn't support 32bit architecture!

**Comment by rasa** [comment]
Sorry, 32bit support was lost October 9 in
https://github.com/ScoopInstaller/Main/commit/4a15f94b69e58a4aa1983d3aaef74d87be49562e#diff-2e84159709c1c980528c5069366163153d90e4d9856f737859fb1addb7ac98ff
Do you know if 32bit builds are being maintained anywhere?
