### ISSUE TITLE
There is no shim for pip after `scoop install python`. Only a shim for python.exe

### ISSUE THREAD

**Issue by Boscop** [ScoopInstaller/Main#1564]
There is no shim for pip after `scoop install python`. Only a shim for python.exe, python3.exe and pythonw.exe.
But pip.exe exists in `C:\Users\me\scoop\apps\python\current\Scripts`.
How can I tell scoop to also create a shim for pip?

@0x326 Re: (https://github.com/lukesampson/scoop/issues/4167#issuecomment-723468494) 
No, `Scripts` is not in my `PATH`.
The only scoop related folders in my `PATH` are:
`C:\Users\me\scoop\apps\nodejs\current\bin;C:\Users\me\scoop\apps\nodejs\current;C:\Users\me\scoop\shims`

**Comment by rasa** [comment]
Scripts is added to your PATH at https://github.com/ScoopInstaller/Main/blob/546c6075cd069bb81231a602c31f2d3b8b171463/bucket/python.json#L82-L85
Try reinstalling, and watch for errors.

**Comment by Boscop** [comment]
@rasa Only reinstalling python, not scoop, right?
Do I need to run it in a terminal with administrator rights in order to get Scripts added to PATH?
Or should that work without admin rights?

**Comment by Boscop** [comment]
Indeed I get warnings, how can I tell scoop to add Scripts to PATH?
```
Installing 'python' (3.9.0) [64bit]
Loading python-3.9.0-amd64.exe from cache
Checking hash of python-3.9.0-amd64.exe ... ok.
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.
Loading uninstall-pep-514.reg from cache
Checking hash of uninstall-pep-514.reg ... ok.
Running pre-install script...
Running installer script...
  WARNING: The scripts easy_install-3.9.exe and easy_install.exe are installed in 'C:\Users\me\scoop\apps\python\3.9.0\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'C:\Users\me\scoop\apps\python\3.9.0\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Linking ~\scoop\apps\python\current => ~\scoop\apps\python\3.9.0
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
Creating shim for 'idle'.
Creating shim for 'idle3'.
'python' (3.9.0) was installed successfully!
Notes
-----
Allow applications and third-party installers to find python by running:
"C:\Users\me\scoop\apps\python\current\install-pep-514.reg"
```

**Comment by linsui** [comment]
Looks like this issue still exist and there is no pip in Scriptat all.

**Comment by Fubuchi** [comment]
The latest version install Scripts and Lib to persist directory which cause problem, since the path added to `PATH` is `~\scoop\apps\python\current\Scripts`

**Comment by dwettstein** [comment]
Installing `Scripts` and `Lib` to `$SCOOP_HOME\persist\python` isn't a problem, since the folders in `persist` are symlinked into the corresponding `apps` folder.

**Comment by dwettstein** [comment]
> 
> 
> `pip` in not shimmed, as `Scripts` is added to your PATH at
> 
> https://github.com/ScoopInstaller/Main/blob/546c6075cd069bb81231a602c31f2d3b8b171463/bucket/python.json#L82-L85
> 
> Try reinstalling, and watch for errors.

Closing this issue as pip is added to path through `Scripts` folder.
