### ISSUE TITLE
 [Request] Add hoppscotch (postwoman)

### ISSUE THREAD

**Issue by arrebole** [ScoopInstaller/Main#1573]
postman alternative
repos: https://github.com/hoppscotch/hoppscotch

**Comment by davidxuang** [comment]
This is a GUI program. Should be transfer to [Extras](https://github.com/lukesampson/scoop-extras) bucket.

**Comment by batkiz** [comment]
Unfortunately there is no executable binary in its release, you cloud use PWA instead.

BTW if you want to use its [cli client](https://github.com/hoppscotch/hopp-cli), check this: https://github.com/batkiz/backit/blob/master/bucket/hopp-cli.json
