### ISSUE TITLE
fio@3.20: Download failed

### ISSUE THREAD

**Issue by maver1ck** [ScoopInstaller/Main#1598]
```
PS C:\Users\maverick> scoop install fio
Installing 'fio' (3.20) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://bsdio.com/fio/releases/fio-3.20-x64.zip is not valid
```

**Comment by maver1ck** [comment]
There are new addresses of those files:
https://bsdio.com/fio/

**Comment by AntonOks** [comment]
well, I have a working manifest [here](https://github.com/AntonOks/scoop-aoks/blob/master/bucket/fio-aoks.json) but without autoupdate :(

If someone knows how to implement _**autoupdate**_ based on _appveyor artifacts_, we could join forces...

@maver1ck

**Comment by rashil2000** [comment]
Fixed by now
