### ISSUE TITLE
Curl Update fails

### ISSUE THREAD

**Issue by helohe** [ScoopInstaller/Main#1608]
curl-7.73.0_3-win64-mingw.tar.xz (2.2 MB) [===================================================================] 100%
Checking hash of curl-7.73.0_3-win64-mingw.tar.xz ... ok.
Extracting curl-7.73.0_3-win64-mingw.tar.xz ... Exception: C:\Users\Nima\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'curl-7.73.0-win64-mingw'! (error 16)

I think the error might be that the _3 was left out in the extraction script.

**Comment by tan-wei** [comment]
Same for me.

**Comment by Vixb1122** [comment]
1. open `%SCOOP%\cache\curl#7.73.0_3#https_curl.haxx.se_windows_dl-7.73.0_3_curl-7.73.0_3-win64-mingw.tar.xz`
2. rename `curl-7.73.0_3-win64-mingw` to `curl-7.73.0-win64-mingw`
3. run `scoop update curl -fs` to update
