### ISSUE TITLE
[Request] Add ForceBindIP

### ISSUE THREAD

**Issue by ntcarver0** [ScoopInstaller/Main#1630]
I'd like to see ForceBindIP added to Scoop's main bucket if possible. If not, could it be added to the "extras" bucket?

Homepage: https://r1ch.net/projects/forcebindip
Download link (installer): https://r1ch.net/assets/forcebindip/ForceBindIP-1.32-Setup.exe
Download link (portable): https://r1ch.net/assets/forcebindip/ForceBindIP-1.32.zip

**Comment by batkiz** [comment]
Try this: https://github.com/batkiz/backit/blob/master/bucket/forcebindip.json

if there are no problems with this manifest, maybe we could open a PR to main bucket.

**Comment by rashil2000** [comment]
@batkiz please make a PR!
