### ISSUE TITLE
[Request] Add dotty

### ISSUE THREAD

**Issue by Ray-Eldath** [ScoopInstaller/Main#1655]
[dotty](https://dotty.epfl.ch/) is a new generation Scala compiler (pure CLI afaik), has been officially claimed as Scala 3.

**Comment by batkiz** [comment]
By now, there are only bash scripts for `scala`, `scalac` and `scalad` in the `bin` folder, we can't use it directly in cmd or PowerShell, so a scoop manifest file for dotty is impossible at this time.

```
# dotty (scala 3)
> ls ~\Downloads\scala3-3.0.0-M3\bin\

common  scala   scalac  scalad

# scala 2
> ls $env:SCOOP\apps\scala\current\bin\

fsc            fsc.bat        scala          scala.bat      scalac         scalac.bat
scaladoc       scaladoc.bat   scalap         scalap.bat
```

Consider using it in WSL, or waiting for `bat` or `ps1` files appears in the bin folder just as what scala 2 does

---

dotty 现在的 release 中只有面向 bash 的可执行脚本，没有 Windows 上能用的 bat/ps1 脚本，所以暂且还没办法写出一个 scoop manifest 来用 scoop 安装它。

在 wsl 里用吧；或者仿照 scala 2 里的 bat 脚本给 dotty 写一份，贡献回去，然后才可能在 scoop 里用到它（

**Comment by Ray-Eldath** [comment]
disappointed. 😞 dotty should support bat/ps1. maybe we should propose an issue or PR... 🤔

---

失望，不过感觉 dotty 应该支持下这个需求... 或许需要骚扰一下 dotty（
