### ISSUE TITLE
ffmpeg@4.3.1-26: download via aria2 failed

### ISSUE THREAD

**Issue by ddarfantasy** [ScoopInstaller/Main#1659]
```
Installing 'ffmpeg' (4.3.1-26) [64bit]
Starting download with aria2 ...
Download: 12/05 15:38:41 [ERROR] CUID#8 - Download aborted. URI=https://github.com/BtbN/FFmpeg-Builds/releases/download/Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/BtbN/FFmpeg-Builds/releases/download/auDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 21f016|ERR |       0B/s|C:/Users/ /scoop/cache/ffmpeg#4.3.1-26#https_github.com_BtbN_FFmpeg-Builds_releases_download_autobuild-2020-11-20-12-39_ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-11-20-12-39/ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip
    referer=https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-11-20-12-39/
    dir=C:\Users\ \scoop\cache
    out=ffmpeg#4.3.1-26#https_github.com_BtbN_FFmpeg-Builds_releases_download_autobuild-2020-11-20-12-39_ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip

ERROR & 'C:\Users\ \scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\ \scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8640 --continue --summary-interval 0 --all-proxy='127.0.0.1:1080'
```
I think the url is outdated? Since it says `https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-11-20-12-39/ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip` not found.

**Comment by ddarfantasy** [comment]
I've run autoupdate again to refresh the url:
```
{
    "version": "4.3.1-26",
    "description": "A complete, cross-platform solution to record, convert and stream audio and video.",
    "homepage": "https://ffmpeg.org",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-12-05-12-38/ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip",
            "hash": "44bd2cb6d48ac6e19c9409902a5e899a3bb570c114029581b1af9a7abe0e1bcd",
            "extract_dir": "ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3"
        }
    },
    "bin": [
        "bin\\ffmpeg.exe",
        "bin\\ffplay.exe",
        "bin\\ffprobe.exe"
    ],
    "checkver": {
        "github": "https://github.com/BtbN/FFmpeg-Builds",
        "regex": "/autobuild-(?<time>[\\d-]+)/ffmpeg-n(?<version>[\\d.]+)-(?<commit>\\d+)-g(?<hash>[a-z\\d]+)-win64-gpl-[\\d.]+\\.zip",
        "replace": "${version}-${commit}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-$matchTime/ffmpeg-n$version-g$matchHash-win64-gpl-$majorVersion.$minorVersion.zip",
                "extract_dir": "ffmpeg-n$version-g$matchHash-win64-gpl-$majorVersion.$minorVersion"
            }
        }
    }
}
```
It seems to work again, so you may merge it into the bucket. But we'd better find out why the url would become unavailable.

**Comment by mattdsteele** [comment]
I just ran into this as well.

Based on this comment, only the last build of the month is kept for a prolonged period. https://github.com/ScoopInstaller/Main/pull/1454#issuecomment-706231550

**Comment by ddarfantasy** [comment]
> 
> 
> I just ran into this as well.
> 
> Based on this comment, only the last build of the month is kept for a prolonged period. [#1454 (comment)](https://github.com/ScoopInstaller/Main/pull/1454#issuecomment-706231550)

That's frustrating... It seems that the problem won't be addressed easily.
Maybe we should switch to [https://www.gyan.dev/ffmpeg/builds/](https://www.gyan.dev/ffmpeg/builds/)?

**Comment by CrendKing** [comment]
Why can't Scoop update that URL to every day's latest URL so it's always available just like the nightly ones? If the filename and hash are unchanged, would it notify people of new version?

> switch to https://www.gyan.dev/ffmpeg/builds/

BtbN version is better in that it has the header and library files for developers.

**Comment by ddarfantasy** [comment]
> Why can't Scoop update that URL to every day's latest URL so it's always available just like the nightly ones? If the filename and hash are unchanged, would it notify people of new version?

I guess if the version number isn't changed, people won't be notified. But since the version number isn't changed, it may require extra effort to update the manifest.
So IMHO, we can still use BtbN's version for the nightly builds, and developers can still install that version to get the header and library files. And we should use gyan's builds for other versions, since their URLs aren't changed frequently. If developers don't want to use nightly builds, I think we can make another manifest to meet their need, so that we can install ffmpeg from the main repo immediately, without waiting for the problem to be solved.

**Comment by CrendKing** [comment]
> if the version number isn't changed, people won't be notified

My point is, people shouldn't be notified. But if a new user tries to install a non-nightly ffmpeg, they should be able to anytime. Right now I can't because the link is wrong. What's the "extra effort" to update that particular manifest vs. the nightly manifest? The date code is exactly the same.

> nightly builds, and developers can still install that version

Yes, you are correct. I do hope Scoop only use one build for consistency. I can imagine both developer and non-developer be surprised and frustrated when they venture to the "other" version.

**Comment by GyanD** [comment]
> 
> 
> Why can't Scoop update that URL to every day's latest URL so it's always available just like the nightly ones? If the filename and hash are unchanged, would it notify people of new version?
> 
> > switch to https://www.gyan.dev/ffmpeg/builds/
> 
> BtbN version is better in that it has the header and library files for developers.

You can get that in my release shared builds at https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
ZIP available at Github mirror.

**Comment by CrendKing** [comment]
Thanks. I checked and can confirm it is equivalent to BtbN's build. It's up to the maintainer to decide whether to switch.

**Comment by djismgaming** [comment]
thank god I checked before opening a new one, yup, same issue here
tried extracting audio from a video with youtube-dl and got the issue

**Comment by akirayamamoto** [comment]
This is fixed. Thank you!
