### ISSUE TITLE
[Request] Add LXD client

### ISSUE THREAD

**Issue by tokiedokie** [ScoopInstaller/Main#1668]
I want LXD windows client which can be found in https://ci.appveyor.com/project/lxc/lxd/branch/master/artifacts

**Comment by Erisa** [comment]
Seems they moved to GitHub Actions: https://github.com/lxc/lxd/actions
Each commit has an artifact called "Windows" which downloads `Windows.zip` containing the `lxc.exe` build.

Considering there are no tagged stable versions and that GitHub Actions artifacts expire after 90 days, I don't think this client is practical to add to scoop as it is right now.
If they included an exe with their GitHub Releases, it would be much easier.

**Comment by rashil2000** [comment]
The LXC organization maintains a Chocolatey package for LXD client - here https://github.com/lxc/lxd-pkg-chocolatey

We can use that. The version-specific link would be - https://packages.chocolatey.org/lxc.4.22.nupkg

See the manifest of sed - https://github.com/ScoopInstaller/Main/blob/master/bucket/sed.json for example.

@Erisa can you make a PR using the example?
