### ISSUE TITLE
nano@5.4-9: Download failed

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/Main#1669]
The download URL given in manifest returns 404 
https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-g7010a68f.7z

The correct one is 
https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-g8ad13081.7z

**Comment by drai8192** [comment]
While this issue is being solved, you can edit the file
C:\Users\Insert-your-user-here\scoop\buckets\main\bucket\nano.json
and use these values on lines 10 and 11
    "url": "https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-g8ad13081.7z",
    "hash": "07B0473ACC885D7AAB417F6273EAC32951339C4C71CFE027FA85CBEB8968D493",
Then
`scoop uninstall nano`
and
`scoop install nano`
should solve it.
