### ISSUE TITLE
Python should persist site-packages and scripts across minor versions

### ISSUE THREAD

**Issue by kostrse** [ScoopInstaller/Main#1680]
Currently site-packages are being stored inside of the app installation directory:
e.g. `~\scoop\apps\python\3.9.0\Lib\site-packages`

When you do minor upgrade of the package, e.g. from 3.9.0 to 3.9.1, all the installed packages and scripts remain with the previous version and you need to install everything again.

It would be great if all packages and scripts would be persisted outside of the app directory:
e.g.`~\scoop\persist\python\3.9\site-packages`

So it would be shared between 3.9.0 and 3.9.1 but not between 3.6.x and 3.9.x

**Comment by kostrse** [comment]
May be related #772

**Comment by rasa** [comment]
Was this by design, or an oversight? If an oversight, how to address?

**Comment by dwettstein** [comment]
I would also suggest to persist ("global") installed packages, similar as it is the case with [NodeJS](https://github.com/ScoopInstaller/Main/blob/master/bucket/nodejs.json). In the end, it should be the same as when installing Python from https://www.python.org/. After a bugfix upgrade, all the installed packages are still here.
