### ISSUE TITLE
imagemagick: Wrong shim for "IMDisplay.exe"

### ISSUE THREAD

**Issue by omerakgoz34** [ScoopInstaller/Main#1695]
```
Download: (OK):download completed.
Checking hash of ImageMagick-7.0.10-52-portable-Q16-x64.zip ... ok.
Uninstalling 'imagemagick' (7.0.10-51)
Removing shim for 'compare'.
Removing shim for 'composite'.
Removing shim for 'conjure'.
Removing shim for 'convert'.
Removing shim for 'imconvert'.
Removing shim for 'dcraw'.
Removing shim for 'identify'.
!--> WARN  Shim for 'IMDisplay' is missing. Skipping. <--!
Removing shim for 'magick'.
Removing shim for 'mogrify'.
Removing shim for 'montage'.
Removing shim for 'stream'.
Unlinking ~\scoop\apps\imagemagick\current
Installing 'imagemagick' (7.0.10-52) [64bit]
```
In imagemagick zip:
![Screenshot_1](https://user-images.githubusercontent.com/49201485/102710065-c15a3280-42c0-11eb-9ba1-92236dc729ba.png)
In scoop shims folder:
![Screenshot_2](https://user-images.githubusercontent.com/49201485/102710074-d6cf5c80-42c0-11eb-9577-4c569ebf8a09.png)

It's converting "I" to lowercase "ı" ?

**Comment by dwettstein** [comment]
Could you please try to uninstall and re-install to see if the issue is still there. In the manifest, the file name is written correctly.

https://github.com/ScoopInstaller/Main/blob/00e369c34109e11d4028f299c5f5dfef42ad5b1b/bucket/imagemagick.json#L28

**Comment by omerakgoz34** [comment]
![Screenshot_76](https://user-images.githubusercontent.com/49201485/135849697-a4ae0bb6-dae1-46e7-8bba-8b369f9f2c85.png)

**Comment by omerakgoz34** [comment]
![Screenshot_77](https://user-images.githubusercontent.com/49201485/135850138-08786725-fdb6-4de7-8451-45164baa8049.png)

**Comment by omerakgoz34** [comment]
Maybe it's because of Turkish lang, because has both of the uppercase "I" and lowercase "ı"
Maybe Scoop converts letters according to the system lang
