### ISSUE TITLE
clink@1.1.11: symantec endpoint protection block to install clink

### ISSUE THREAD

**Issue by zrma** [ScoopInstaller/Main#1696]
![image](https://user-images.githubusercontent.com/4281810/102728626-320c5800-4370-11eb-885e-bbd0ed1499be.png)

![image](https://user-images.githubusercontent.com/4281810/102728636-3df81a00-4370-11eb-82a0-9c5e9224d511.png)

is it ok?

thank you.

**Comment by goostleek** [comment]
It should be reported to https://github.com/chrisant996/clink rather than here. Scoop is only a package installer and is not responsible for the binaries being installed with the package.

**Comment by goostleek** [comment]
[VirusTotal](https://www.virustotal.com/gui/url/74731cecf434391f11b838b379791b51afd8c66409e5707ba007a3e616635dd7/detection) claims its clean.

**Comment by zrma** [comment]
@goostleek 
Thanks for your check

> It should be reported to https://github.com/chrisant996/clink rather than here. Scoop is only a package installer and is not responsible for the binaries being installed with the package.

I'll report it on there.
