### ISSUE TITLE
Blake2 deprecated in favor of Blake3. Can Blake2 be removed?

### ISSUE THREAD

**Issue by gbursson** [ScoopInstaller/Main#1698]
As per Blake2 website, they are recommending Blake3 instead of Blake2, can **[b2sum](https://github.com/ScoopInstaller/Main/blob/master/bucket/b2sum.json)** package be removed?

See [Blake2](https://www.blake2.net/)

**Comment by Erisa** [comment]
@rashil2000 It seems a manifest for Blake3/`b3sum` already exists: https://github.com/ScoopInstaller/Main/blob/master/bucket/b3sum.json

The Blake2 website says
> CONSIDER USING BLAKE3, faster than BLAKE2

However I don't see anything pointing to it being deprecated or unmaintained, and they appear to be separate projects, so in my opinion both manifests should stay.

**Comment by rashil2000** [comment]
> @rashil2000 It seems a manifest for Blake3/`b3sum` already exists: https://github.com/ScoopInstaller/Main/blob/master/bucket/b3sum.json

Oh, thanks for pointing that out, completely missed that.

> The Blake2 website says
> 
> > CONSIDER USING BLAKE3, faster than BLAKE2
> 
> However I don't see anything pointing to it being deprecated or unmaintained, and they appear to be separate projects, so in my opinion both manifests should stay.

Yes, that's exactly what I said :)
