### ISSUE TITLE
diffutils appears to be broken on a fresh install (msys-iconv-2.dll missing)

### ISSUE THREAD

**Issue by fgimian** [ScoopInstaller/Main#1722]
Hey guys, hope you're well.

I'm on Windows 10 20H2 and have tested the following steps on a fresh Windows instance inside Windows Sandbox with Windows PowerShell 5 (I've also replicated this on my main machine with PowerShell 7).

1. Install scoop

   ```powershell
   iwr -useb get.scoop.sh | iex
   ```

2. Install diffutils

   ```powershell
   scoop install diffutils
   ```

3. Attempt to run diff.exe

   ```powershell
   diff.exe --help
   ```

You'll notice that there's no output when you do this.

If you then open Command Prompt and attempt to run diff.exe, you'll get a popup saying that msys-iconv-2.dll is missing.

I'm not sure why PowerShell doesn't display any errors.  Of course, I can also confirm that attempting to diff two files with this command simply does nothing in PowerShell.

Any help is greatly appreciated 😄 
Fotis

**Comment by fgimian** [comment]
This issue persists today with the very latest Scoop and main bucket on a fresh Windows 10 install.  You can test this inside Windows Sandbox and reproduce it by simply installing Scoop and then installing diffutils.  It simply doesn't work anymore 😢

**Comment by jeffrson** [comment]
Still the very same bug - apparently, no single .exe inside this package is working. All are missing msys-iconv-2.dll.

**Comment by fgimian** [comment]
What I do is copy over the DLL from the Git package:

```
cp ~\scoop\apps\git\current\usr\bin\msys-iconv-2.dll ~\scoop\apps\diffutils\current\usr\bin\msys-iconv-2.dll
```

This works perfectly for me 😄 
Fotis

**Comment by rashil2000** [comment]
Support for zstd has been released now
