### ISSUE TITLE
minikube@1.1.1: hash check failed

### ISSUE THREAD

**Issue by yjakoet** [ScoopInstaller/Main#173]
Checking hash of minikube-windows-amd64.exe ... ERROR Hash check failed!
App:         main/minikube
URL:         https://storage.googleapis.com/minikube/releases/v1.1.1/minikube-windows-amd64.exe
First bytes: 3C 48 54 4D 4C 3E 3C 48
Expected:    e86e9c7c1c25cfd251f010b62e83fdf2ee2eefc3e73b4b1f7fa18971577150be
Actual:      0f7f6985321d3e8a1ef8abb56fd5fc18f33986aecee03fa56df7273426b5208a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=minikube%401.1.1%3a+hash+check+failed

**Comment by yjakoet** [comment]
This seems to be related to failed downloads.  Where does scoop write it's temp files to?

**Comment by Ash258** [comment]
Run `scoop cache rm minikube` and try to install again.

**Comment by yjakoet** [comment]
minikube-windows-amd64.exe (894 B) [==========================================================================] 100%

Yeah I doubt the exe is 894 bytes big.

**Comment by yjakoet** [comment]
> Run `scoop cache rm minikube` and try to install again.

Thanks, the same thing happens.  I wonder if this isn't .net related.  So the issue is that my download is failing but scoop is seeing it treating it as successful.

**Comment by Ash258** [comment]
Do you use proxy?

What is result of `Get-Content "$env:SCOOP\cache\minikube#1.1.1#https_storage.googleapis.com_minikube_releases_v1.1.1_minikube-windows-amd64.exe."`?

![image](https://user-images.githubusercontent.com/13260377/60002191-7ed27e00-9668-11e9-9281-a44f113a2368.png)

**Comment by yjakoet** [comment]
Okay I've found the problem.  I will close the issue.  Network security kicked in and flagged the file, causing the download the fail.  Scoop isn't at fault at all.
