### ISSUE TITLE
vagrant@2.2.14: missing shortcut

### ISSUE THREAD

**Issue by marc0l92** [ScoopInstaller/Main#1736]
After installing vagrant, I'm not able to find the command when I try to execute it from the command line.

I'm new to this tool but I suppose it is related to the missing shortcut section in the manifest file.

Is it possible to add the section or fix this issue in a different way?

Thanks,
Marco

**Comment by HUMORCE** [comment]
nope, it's work well.

`"bin": "bin\\vagrant.exe",`

the manifest has specified bin field.

make sure scoop\shims in your PATH.

`$env:Path -split ';'`

**Comment by marc0l92** [comment]
Apparently, there was an issue the first time I installed it. After uninstalling and cleaning the cache I now have the shortcuts in the scoop/shims.

Thanks for the support.
