### ISSUE TITLE
[Request] Add Multipass

### ISSUE THREAD

**Issue by fsdrw08** [ScoopInstaller/Main#1745]
Moved from https://github.com/lukesampson/scoop/issues/3956

Canonical has created Multipass, a cross-platform tool that enables individuals to easily deploy Ubuntu virtual machines using the native hypervisor capabilities of the operating system (ie. xhyve, Hyper-V, or KVM). I use this tool on Windows with Hyper-V to spin up development systems whenever I need to test something out.

Please consider adding this tool to Scoop. Thank you!

https://multipass.run/
https://www.youtube.com/watch?v=Ap_bAW8i2zY

**Comment by tech189** [comment]
I tried to create a manifest but it doesn't work after extracting because it expects a service to be installed. The installer also requires admin privileges so maybe the non-portable bucket would be a good fit for it.

<details>
<summary>Manifest</summary>
<p>

```
{
    "version": "1.8.0",
    "description": "Multipass orchestrates virtual Ubuntu instances",
    "homepage": "https://multipass.run/",
    "license": "GPL-3.0",
    "url": "https://github.com/canonical/multipass/releases/download/v1.8.0/multipass-1.8.0+win-win64.exe#dl.7z",
    "hash": "SHA256:60b01ed14d63c9759680abc5d706a53cca9875c9e2ff9daab635481fad90a879",
    "bin": [
        [
            "bin\\multipass.exe",
            "multipass"
        ]
    ],
    "shortcuts": [
        [
            "bin\\multipass.gui.exe",
            "Multipass"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/canonical/multipass/releases/download/v$version/multipass-$version+win-win64.exe#dl.7z" 
    }
}
```
</p>

</details>

**Comment by rashil2000** [comment]
Okay, please shift this request to nonportable bucket.

**Comment by rashil2000** [comment]
Multipass has been added
