### ISSUE TITLE
ffmpeg@4.3.1-29: Download failed

### ISSUE THREAD

**Issue by nathanielcwm** [ScoopInstaller/Main#1760]
```scoop install ffmpeg                                                                                                                         Installing 'ffmpeg' (4.3.1-29) [64bit]                                                                                                                                              The remote server returned an error: (404) Not Found.                                                                                                                               URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-01-01-12-35/ffmpeg-n4.3.1-29-g89daac5fe2-win64-gpl-4.3.zip is not valid```

https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-01-17-12-46/ffmpeg-n4.3.1-29-g89daac5fe2-win64-gpl-4.3.zip

This link should work...

**Comment by rufanov** [comment]
Seems to be fixed in 851b538
