### ISSUE TITLE
openssh@8.2p1-1: download failed

### ISSUE THREAD

**Issue by jaan-git** [ScoopInstaller/Main#1769]
(py3x64) E:\Document\code-git>scoop install openssh
Installing 'openssh' (8.2p1-1) [64bit]
bash-4.4.023-2-x86_64.pkg.tar.xz (1.9 MB) [=============================================================================================================] 100%
Checking hash of bash-4.4.023-2-x86_64.pkg.tar.xz ... ok.
gcc-libs-9.3.0-1-x86_64.pkg.tar.xz (1.2 MB) [===========================================================================================================] 100%
Checking hash of gcc-libs-9.3.0-1-x86_64.pkg.tar.xz ... ok.
远程服务器返回错误: (404) 未找到。
URL http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-1-x86_64.pkg.tar.xz is not valid

**Comment by Kreijstal** [comment]
So just provide another mirror?

**Comment by kratos9394** [comment]
openssl is invaild
