### ISSUE TITLE
imagemagick@7.0.10-59: Download via aria2 failed

### ISSUE THREAD

**Issue by davidhaymond** [ScoopInstaller/Main#1780]
Download failed! (Error 3) Resource was not found

imagemagick: 7.0.10-58 -> 7.0.10-59
Updating 1 outdated app:
Updating 'imagemagick' (7.0.10-58 -> 7.0.10-59)
Downloading new version
Starting download with aria2 ...
Download: 01/25 09:33:52 [ERROR] CUID#8 - Download aborted. URI=https://www.imagemagick.org/download/binaries/ImageMagicDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://download.imagemagick.org/ImageMagick/download/binaDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 9269c6|ERR |       0B/s|C:/Users/David/scoop/cache/imagemagick#7.0.10-59#https_www.imagemagick.org_download_binaries_ImageMagick-7.0.10-59-portable-Q16-x64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://www.imagemagick.org/download/binaries/ImageMagick-7.0.10-59-portable-Q16-x64.zip
    referer=https://www.imagemagick.org/download/binaries/
    dir=C:\Users\David\scoop\cache
    out=imagemagick#7.0.10-59#https_www.imagemagick.org_download_binaries_ImageMagick-7.0.10-59-portable-Q16-x64.zip

ERROR & 'C:\Users\David\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\David\scoop\cache\imagemagick.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=20736 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

**Comment by NatoBoram** [comment]
It also fails without aria2

> Installing 'imagemagick' (7.0.10-58) [64bit]
> The remote server returned an error: (404) Not Found.
> URL https://www.imagemagick.org/download/binaries/ImageMagick-7.0.10-58-portable-Q16-x64.zip is not valid

**Comment by davidhaymond** [comment]
As of 3866fe1 imagemagick now uses `7.0.11` so this issue can be closed.
