### ISSUE TITLE
[Request] Add vale

### ISSUE THREAD

**Issue by louie-github** [ScoopInstaller/Main#1796]
"📝 A syntax-aware linter for prose built with speed and extensibility in mind." - from their [Github repo](https://github.com/errata-ai/vale)

I read about this program while looking for alternatives to Grammarly. It seems to be a command line grammar checker that "brings code-like linting to prose." The download to the Windows zip release, however, does seem to be rarely downloaded because it brought up a warning in the Chrome browser and VirusTotal did not have any copy of it.

The project is moderately well-known with about 800+ stars. If this application is better suited to the [extras](https://github.com/lukesampson/scoop-extras) bucket, please tell me. Thank you!

**Comment by issaclin32** [comment]
`vale` is moved to the main bucket now. (https://github.com/ScoopInstaller/Main/commit/7389ecd84c99bedde9048516d34f2f8508c7b9f3)
