### ISSUE TITLE
Impossible to update to msys2 20210105

### ISSUE THREAD

**Issue by yme44** [ScoopInstaller/Main#1809]
Hi,

After upgrading scoop (scoop update), it seems that the package msys2 still only available for the version 20190524.
The strange thing concerns the other packages where updates are indicated as available (none for msys2).

I tried to force the update (scoop update msys2) without success.

When I look at the repo, the msys2.json indicates 2021-01-05.

I am not an expert so I surely miss something but I don't know what !

Thanks for your help !

**Comment by HUMORCE** [comment]
try uninstall then reinstall.
