### ISSUE TITLE
yq@4.5.1: hOperation did not complete successfully because the file contains a virus or potentially unwanted software.

### ISSUE THREAD

**Issue by shaqo88** [ScoopInstaller/Main#1818]
yq: 4.5.0 -> 4.5.1
Updating one outdated app:
Updating 'yq' (4.5.0 -> 4.5.1)
Downloading new version
yq_windows_amd64.exe (6.9 MB) [=====================================================================================================================================================================================================] 100%
Move-Item : Operation did not complete successfully because the file contains a virus or potentially unwanted software.
At C:\Users\shaul.royzen\scoop\apps\scoop\current\lib\install.ps1:112 char:9
+         Move-Item "$cached.download" $cached -force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\shaul....yq.exe.download:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

**Comment by Felix480** [comment]
df.,khgltdsuighdtruigdsyigwsrigwrs

**Comment by Felix480** [comment]
fuck you
