### ISSUE TITLE
openssl-mingw@1.1.1j_3: Decompress error

### ISSUE THREAD

**Issue by PhotonNite** [ScoopInstaller/Main#1834]
Installing 'openssl-mingw' (1.1.1j_3) [64bit]
Loading openssl-1.1.1j_3-win64-mingw.tar.xz from cache.
Checking hash of openssl-1.1.1j_3-win64-mingw.tar.xz ... ok.
Extracting openssl-1.1.1j_3-win64-mingw.tar.xz ... Exception: C:\scoop\apps\scoop\current\lib\core.ps1:510
```
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'openssl-1.1.1j_3-win64-mingw'! (error 16)
```

**Comment by silverqx** [comment]
I have the same problem, this is full output:
```
❯❯❯ scoop update openssl-mingw -f
openssl-mingw: 1.1.1j_3 -> 1.1.1j_3
Updating one outdated app:
Updating 'openssl-mingw' (1.1.1j_3 -> 1.1.1j_3)
Downloading new version
Loading openssl-1.1.1j_3-win64-mingw.tar.xz from cache
Checking hash of openssl-1.1.1j_3-win64-mingw.tar.xz ... ok.
Uninstalling 'openssl-mingw' (1.1.1j_3)
Installing 'openssl-mingw' (1.1.1j_3) [64bit]
Loading openssl-1.1.1j_3-win64-mingw.tar.xz from cache
Extracting openssl-1.1.1j_3-win64-mingw.tar.xz ... Could not find 'openssl-1.1.1j_3-win64-mingw'! (error 16)
At C:\users\silver zachara\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...gw'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'openssl-1.1.1j_3-win64-mingw'! (error 16)
```

**Comment by silverqx** [comment]
Problem still exists with openssl-1.1.1j_4

**Comment by silverqx** [comment]
The problem is that it is `openssl-1.1.1j_4-win64-mingw.tar.xz` _tar_ and _xz_ archive, so scoop extracts `xz` archive with `Expand-7zipArchive` function and the result of this decompression is `openssl-1.1.1j_4-win64-mingw.tar` file, but scoop's `movedir` function expects to have extracted directory at `.\openssl-1.1.1j_4-win64-mingw` which he can not find and because of that it throws an exception.

If I look at the `openssl-mingw` package history, it was `.tar.xz` archive before too, so something was changed in the scoop core what is causing this issue.

**Comment by silverqx** [comment]
If somebody is searching workaround then you are in, add this line `read-host “Press ENTER to continue...”` to the `"C:\Users\Your_UserName\scoop\apps\scoop\current\lib\core.ps1"` at line 496, it is exactly an empty line in following snippet:
```
function movedir($from, $to) {
    $from = $from.trimend('\')
    $to = $to.trimend('\')

    $proc = New-Object System.Diagnostics.Process
    $proc.StartInfo.FileName = 'robocopy.exe'
```

Then when the script will wait for the keypress, extract `openssl-1.1.1j_4-win64-mingw.tar` into the **subfolder** `openssl-1.1.1j_4-win64-mingw` and press some key afterward, so the script can continue and it will be installed properly. 😁

**Comment by jeffrson** [comment]
I think the reason is, that the .tar.xz file contains a folder without the revision number (_4 in your example).

Problem still exists: https://github.com/ScoopInstaller/Main/issues/2593

**Comment by silverqx** [comment]
Ok, this problem was fixed, now I have upgraded openssl-mingw without problems.
