### ISSUE TITLE
git-filter-repo.ps1 installed by Scoop breaks --filename-callback

### ISSUE THREAD

**Issue by nyanpasu64** [ScoopInstaller/Main#1869]
The `git-filter-repo.exe` installed by Scoop actually shells out to a `git-filter-repo.ps1` created by Scoop and not found in upstream. The script is created by this line in the Scoop JSON:

https://github.com/ScoopInstaller/Main/blob/4659e9b3a14eb192b7690604ec73556e93d8244c/bucket/git-filter-repo.json#L13

The PowerShell script has the bug that `git filter-repo --filename-callback 'return filename'` ends up splitting single arguments with spaces, resulting in `--filename-callback return filename` and a runtime error.

I traced out the call tree from root to leaf:

- `git filter-repo --filename-callback 'return filename'` calls
- `sh "C:\\Users\\nyanpasu64\\scoop\\shims\\git-filter-repo" --filename-callback "return filename" ` calls the the same command (weirdly), which calls
- `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -ex unrestricted C:\Users\nyanpasu64\scoop\apps\git-filter-repo\current\git-filter-repo.ps1 --filename-callback "return filename"` calls
- `"C:\Users\nyanpasu64\scoop\apps\python\current\python.exe" C:\Users\nyanpasu64\scoop\apps\git-filter-repo\2.29.0\git-filter-repo --filename-callback return filename` which erroneously splits the multi-word string argument.

The defective script is `git-filter-repo.ps1`, whose contents are `python3 'C:\Users\nyanpasu64\scoop\apps\git-filter-repo\2.29.0\git-filter-repo' @args` on my machine. I don't know how to fix the script:

- `@args` splits strings
- `$args` splits strings
- `"@args"` is not expanded
- `"$args"` turns all arguments into a single string.

One hack-fix is to copy the `git-filter-repo` python script with shebang, directly to the shims folder. Another alternative is to use pip or pipx or a global path folder, bypassing Scoop.

**Comment by rashil2000** [comment]
The ps1 file is no longer created - https://github.com/ScoopInstaller/Main/commit/8b8da663ffc7d7c893ad728d9ff5bd751e36aa44
