### ISSUE TITLE
How to add language support for xpdf-tools?

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Main#1896]
It's very important that adding language support packages for Xpdf. You can get the download link from this page http://www.xpdfreader.com/download.html
But I don't know how to add them for xpdf-tools If I install xpdf-tools via scoop.

Is it able to add these languages packages via scoop? Any one can help?

**Comment by HUMORCE** [comment]
example for schinese language pack:

`xpdf-tools-language-pack-schinese.json`
```
{
    "homepage": "http://www.xpdfreader.com/",
    "description": "Chinese-simplified language pack for xpdf-tools.",
    "version": "nightly",
    "license": {
        "identifier": "GPL-2.0-only|GPL-3.0-only",
        "url": "https://www.xpdfreader.com/opensource.html"
    },
    "depends": "main/xpdf-tools",
    "url": "https://dl.xpdfreader.com/xpdf-chinese-simplified.tar.gz",
    "hash": "99a848c3e2b17d6e862aa0d904bac7df3177efe093f07bb2c76b17e09cf6eb1a",
    "installer": {
        "script": "Copy-Item \"$dir\\xpdf-chinese-simplified\\\" \"$(appdir xpdf-tools $global)\\current\\chinese-simplified\" -Recurse"
    },
    "uninstaller": {
        "script": "Remove-Item \"$(appdir xpdf-tools $global)\\current\\chinese-simplified\" -Recurse"
    }
}

```

**Comment by ssfjhh** [comment]
That's not enough. we have to copy "chinese-simplified\add-to-xpdfrc" to xpdfrc. and correct the path in it. I know how to write the installer script now.

How about adding it directly to xpdf-tools.json? I mean add all the language packages to xpdf-tools so that users don't need to add install another language package.

**Comment by HUMORCE** [comment]
i don't think the app need to include all language packs unless they are built-in part.
you can make/modify the xpdf-tools.json to include that for self-use.

**Comment by ssfjhh** [comment]
But it's not so easy for users to add language packages. In fact, I only learned today that I can add language packages to xpdf-tools.

**Comment by ssfjhh** [comment]
Furthermore, If we don't add language packages to xpdf-tools, every time scoop updates xpdf-tools, I have to move language files to the new folder.

**Comment by HUMORCE** [comment]
i have not used this app.
after some understanding that, the packs doesn't need to be copied/moved to the xpdf-tools directory, then just download and store it.

**xpdf-tools-LSP-schinese.json**
```
{
    "homepage": "http://www.xpdfreader.com/",
    "description": "Chinese-simplified language support packages for xpdf-tools",
    "version": "nightly",
    "license": {
        "identifier": "GPL-2.0-only|GPL-3.0-only",
        "url": "https://www.xpdfreader.com/opensource.html"
    },
    "suggest": {
        "Xpdf": "main/xpdf-tools"
    },
    "url": "https://dl.xpdfreader.com/xpdf-chinese-simplified.tar.gz",
    "extract_dir": "xpdf-chinese-simplified"
}
```

you just need to point the path to `scoop\apps\xpdf-tools-LSP-schinese\current\` in the configuration file (xpdfrc).

i did not check how to do the configuration, the actual path needs to be modified manually.
```
#----- begin Chinese Simplified support package (2011-sep-02)
cidToUnicode	Adobe-GB1	scoop\apps\xpdf-tools-LSP-schinese\current\Adobe-GB1.cidToUnicode
unicodeMap	ISO-2022-CN	scoop\apps\xpdf-tools-LSP-schinese\current\ISO-2022-CN.unicodeMap
unicodeMap	EUC-CN		scoop\apps\xpdf-tools-LSP-schinese\current\EUC-CN.unicodeMap
unicodeMap	GBK		scoop\apps\xpdf-tools-LSP-schinese\current\GBK.unicodeMap
cMapDir		Adobe-GB1	scoop\apps\xpdf-tools-LSP-schinese\current\CMap
toUnicodeDir			scoop\apps\xpdf-tools-LSP-schinese\current\CMap
#fontFileCC	Adobe-GB1	path\to\font\NotoSansCJKsc-Regular.otf
#----- end Chinese Simplified support package
```

eq.
`-s languagedir scoop\apps\xpdf-tools-LSP-schinese\current`

**Comment by ssfjhh** [comment]
You are right. I don't really need to move/copy xpdf-tools-LSP to xpdf-tools/current，but I have to copy/move xpdfrc every time.
Thank you very much.

**Comment by HUMORCE** [comment]
move your config file `.xpdfrc` to %userprofile%.

or persist xpdfrc with manifest self-use

**Comment by ssfjhh** [comment]
I have tried this method. It doesn't work.

> Place all of these files in a directory, typically:

    Unix - /usr/local/share/xpdf/chinese-simplified
    Win32 - C:\Program Files\xpdf\chinese-simplified

> Add the contents of the "add-to-xpdfrc" file to your system-wide
xpdfrc config file, which is typically:

    Unix - /usr/local/etc/xpdfrc
    Win32 - C:\Program Files\xpdf\xpdfrc

> **Alternatively, on _Unix_ systems you can add these lines to your
personal xpdfrc file in $HOME/.xpdfrc.**

**Comment by HUMORCE** [comment]
check this:
https://github.com/lukesampson/scoop/wiki/Persistent-data

**Comment by HUMORCE** [comment]
no more need to manually copy/move config file, when PR https://github.com/ScoopInstaller/Main/pull/1902 is approved.

**Comment by rashil2000** [comment]
Is this still an issue?

**Comment by NamelessUzer** [comment]
> Is this still an issue?

yes. I believe Scoop should add language support directly so that users don't need to add language support by themselves.

**Comment by rashil2000** [comment]
Is it required for the core functionality though? I believe it works for English out-of-the-box. 

We can't have packages related to all languages, for a specific tool, in the official bucket. For that you'll have to make your own manifest.

/cc @humorce

**Comment by HUMORCE** [comment]
i created manifests of xpdf-tools LSPs in personal bucket.

```
# https://github.com/HUMORCE/nuke/tree/master/bucket
xpdf-tools-LSP-arabic.json
xpdf-tools-LSP-cyrillic.json
xpdf-tools-LSP-greek.json
xpdf-tools-LSP-hebrew.json
xpdf-tools-LSP-japanese.json
xpdf-tools-LSP-korean.json
xpdf-tools-LSP-latin2.json
xpdf-tools-LSP-schinese.json
xpdf-tools-LSP-tchinese.json
xpdf-tools-LSP-thai.json
xpdf-tools-LSP-turkish.json
```

these packages are used for language support, not translation.

a precedent here:
`main/tesseract` and `main/tesseract-languages`

**Comment by rashil2000** [comment]
Would it be possible to create a combined manifest for all of them? (something called xpdf-tools-languages)..

Having different manifests for each language would result in lot of clutter.
