### ISSUE TITLE
vim@8.2: hash check failed

### ISSUE THREAD

**Issue by oscaritoro** [ScoopInstaller/Main#1946]
$ scoop install vim
Installing 'vim' (8.2) [64bit]
gvim82.exe (8.8 MB) [=========================================================================================] 100%
Checking hash of gvim82.exe ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."
ERROR Hash check failed!
App:         main/vim
URL:         https://ftp.nluug.nl/pub/vim/pc/gvim82.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    aa84543492cd8260f44a5acf1ec35641
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=vim%408.2%3a+hash+check+failed

**Comment by oscaritoro** [comment]
Scoop is up to date.  File actually downloads fine and when I manually run an "md5sum.exe .\scoop\apps\vim\8.2\dl.7z" I get back the expected hash: \aa84543492cd8260f44a5acf1ec35641 *.\\scoop\\apps\\vim\\8.2\\dl.7z
Other apps are installing fine so just going with vim-nightly for now.

**Comment by PipeItToDevNull** [comment]
This is a FIPS issue as far as the error goes. Are you using FIPS on your machine. I have this same error and I am trying to ensure my FIPS stays off long enough to get the install done.

**Comment by PipeItToDevNull** [comment]
So Vim uses an md5 field in the json file while vim-nightly does not.

I would recommend this mf5 field be removed or updated to prevent needless issues on FIPS compliant systems.
