### ISSUE TITLE
mediainfo@20.09: download via aria2 failed

### ISSUE THREAD

**Issue by Navirl** [ScoopInstaller/Main#1947]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'mediainfo' (20.09) [64bit]
Starting download with aria2 ...
Download: 03/19 17:41:27 [ERROR] CUID#8 - Download aborted. URI=https://mediaarea.net/download/binary/mediainfo/20.09/MeDownload: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 5bb6f1|ERR |       0B/s|D:/Scoop/cache/mediainfo#20.09#https_mediaarea.net_download_binary_mediainfo_20.09_MediaInfo_CLI_20.09_Windows_x64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://mediaarea.net/download/binary/mediainfo/20.09/MediaInfo_CLI_20.09_Windows_x64.zip
    referer=https://mediaarea.net/download/binary/mediainfo/20.09/
    dir=D:\Scoop\cache
    out=mediainfo#20.09#https_mediaarea.net_download_binary_mediainfo_20.09_MediaInfo_CLI_20.09_Windows_x64.zip

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\mediainfo.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=5152 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=mediainfo%4020.09%3a+download+via+aria2+failed

**Comment by gordlord** [comment]
I have sometimes problems too downloading with aria2. Uninstalling it made everything work again.
To uninstall: scoop uninstall aria2

**Comment by HUMORCE** [comment]
@gordlord 

`scoop config aria2-enabled $false`

**Comment by Navirl** [comment]
> `scoop config aria2-enabled $false`

This solution is worked.
I've had same error in Mediainfo-gui, but solved it with.
Thanks everyone :)
