### ISSUE TITLE
ack doesn't work without restart of console

### ISSUE THREAD

**Issue by street-grease-coder** [ScoopInstaller/Main#1951]
installed ack, but didn't recognize perl immediately, not until I had restarted cmd. I guess it's extremely minor, but it took me a couple of minutes to realize, a note or fix would be great (unless this is standard behavior I'm unaware of)

**Comment by HUMORCE** [comment]
the reason:
https://github.com/ScoopInstaller/Main/blob/f5b363499560048cf269fbfa8ceda831fc838852/bucket/perl.json#L22-L26

**Comment by street-grease-coder** [comment]
I'm guessing this adds perl to the path variable, which may or may not be updated in the local cmd console? If I remember correctly, scoop usually allows to access the apps immediately/in the same console without manually updating the path. In any case, I do not know enough to contribute anything sensible here - I guess you're saying this is in the range of expected behavior. If that's right, please close, and thanks for the work and this great tool

**Comment by HUMORCE** [comment]
if perl is not properly configured (installed and env is ok) before installing ack, that's expected behavior.

https://github.com/ScoopInstaller/Main/blob/f5b363499560048cf269fbfa8ceda831fc838852/bucket/ack.json#L6
