### ISSUE TITLE
heroku-cli install is failing

### ISSUE THREAD

**Issue by BrazucaCredAdmin** [ScoopInstaller/Main#1971]
It seems that heroku pack is empty or, at the very least, doesn't contain the necessary files.

```bash
scoop install  heroku-cli
Installing 'heroku-cli' (7.51.0) [64bit]
Loading heroku-win32-x64.tar.xz from cache
Checking hash of heroku-win32-x64.tar.xz ... ok.
Extracting dl.xz ... done.
Running pre-install script...
WARN  Can not create symlink while running from un-elevated prompt. Installation is not affected.
Move-Item : Cannot find path 'C:\Users\Bruno Brant\scoop\apps\heroku-cli\7.51.0\dlo\heroku' because it does not exist.
At line:9 char:1
+ Move-Item "$dir\dlo\heroku\*" "$dir"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Bruno ...51.0\dlo\heroku:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
```

Those errors occurs even on a elevated prompt.

**Comment by stevehipwell** [comment]
@BrazucaCredAdmin I'm going to close this as stale, please re-open with up to date details if this is still an issue for you.

**Comment by SonaliBendre** [comment]
lmao there are many same issue of failed heroku installation. I got the same error

**Comment by rashil2000** [comment]
Unable to reproduce. 

Check whether your issue is same as this - https://github.com/ScoopInstaller/Main/issues/3003#issuecomment-977859335

**Comment by SonaliBendre** [comment]
Heroku-cli archive contains:

--
Path = C:\scoop\cache\heroku-cli#7.59.2#https_cli-assets.heroku.com_heroku-win32-x64.tar.xz_dl.xz
Type = xz
Physical Size = 16177060
Method = LZMA2:23 CRC64
Streams = 1
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
                    .....    125081600     16177060  heroku-cli#7.59.2#https_cli-assets.heroku.com_heroku-win32-x64.tar.xz_dl
------------------- ----- ------------ ------------  ------------------------
                             125081600     16177060  1 files

**Comment by SonaliBendre** [comment]
C:\scoop\apps\heroku-cli\7.59.2 is empty

**Comment by SonaliBendre** [comment]
I gave my whole day today just to install heroku using scoop

**Comment by SonaliBendre** [comment]
well wth
![image](https://user-images.githubusercontent.com/73757361/143585291-d8292f60-89e6-426a-a2b8-03020b3ba38a.png)
`dl` was supposed to be a folder and BTW there is `dlo` folder in `C:\scoop\apps\heroku-cli\7.59.2`
and BTW we can't see actual error logs in scoop right?

**Comment by SonaliBendre** [comment]
It installed without any issues in my Windows server 
![image](https://user-images.githubusercontent.com/73757361/143586359-cb2a7a4a-4073-48fe-9bb4-428b4b60bfc1.png)

**Comment by rashil2000** [comment]
> and BTW we can't see actual error logs in scoop right?

The log file is written in ~\Scoop\apps\heroku-cli\\<version\>, but it seems to be empty. 

What is the SHA256 hash of the C:\scoop\cache\heroku-cli#7.59.2#https_cli-assets.heroku.com_heroku-win32-x64.tar.xz_dl.xz file?

**Comment by rashil2000** [comment]
Also, 7-zip was recently updated, can you try with latest 7zip version?

**Comment by SonaliBendre** [comment]
I updated 7-zip but same error.
Can you tell me the step to install it manually according to the manifest? I didn't find good guide in documentation and I don't know powershell script

**Comment by rashil2000** [comment]
Since scoop install is not working for you, I would recommend you use their official installer for the time being. Manually installing a scoop package is not recommended, and is not very straightforward as the manifest contains a pre-install script. 

Here's the link to installer: https://cli-assets.heroku.com/heroku-x64.exe
