### ISSUE TITLE
pwsh: Ctrl+C no longer works as before in Windows Terminal / VS Code 

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Main#1980]
After installing PowerShell Core, using Ctrl+C to terminate a process causes the terminal to end with `[process exited with code 3221225786]` every time, thus a new terminal be launched to issue any new commands. Quite annoying. An explanation can be read [here](https://www.teppos.com/posts/windows_terminal_and_powershell_troubles/).

As the linked article explains, the fix is to make sure applications that use the shell, e.g. Windows Terminal and VS Code, point to scoop's ...\apps\pwsh\current\pwsh.exe, as by default, the pwsh.exe shim is being used, which is the source of the problem.

Could a warning or tip be printed after the installation of pwsh to make users aware that they should update their config files?

For Windows Terminal's \<profile\>.ps1:
```
"list":
[
    {
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "name": "PowerShell",
        // ...
        "commandline": "%USERPROFILE%\\scoop\\apps\\pwsh\\current\\pwsh.exe"
    },
```
For VS Code's settings.json:
```
{
    "terminal.integrated.shell.windows": "c:\\users\\<username>\\scoop\\apps\\pwsh\\current\\pwsh.exe"
}
```

Thanks.

**Comment by HUMORCE** [comment]
related:
https://github.com/lukesampson/scoop/pull/3998
https://github.com/lukesampson/scoop/issues/3634

**Comment by Vechro** [comment]
Yeah this is a shim problem but there's a less painful fix by changing the shim (as described in the issue links above) if you execute the following commands
```
scoop config shim kiennq
scoop reset *
```
