### ISSUE TITLE
reference to versions/rtools35 in rtools.json is broken

### ISSUE THREAD

**Issue by joseffrank** [ScoopInstaller/Main#1981]
in  [rtools.json](https://github.com/ScoopInstaller/Main/blob/71ab239f6465085ad838f84c20b4cb722efd3cd1/bucket/rtools.json#L6) versions/rtools35 is suggested for use with older R version. Its manifest file however is missing from the versions bucket:

```
c:\> scoop install versions/rtools35
Couldn't find manifest for 'rtools35' from 'versions' bucket.
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Versions/pull/203
