### ISSUE TITLE
nssm site is 503 Service Unavailable

### ISSUE THREAD

**Issue by everyx** [ScoopInstaller/Main#199]
Anyway to fix that? I can't install nssm via scoop.

https://nssm.cc/ show 503 Service Unavailable

**Comment by niheaven** [comment]
If it keeps unavailable, I'll upload downloaded zip file to `ScoopInstaller/Binary`.

**Comment by everyx** [comment]
website is get back now.

**Comment by rasa** [comment]
Noted on https://github.com/ScoopInstaller/Main/issues/150

**Comment by ClarenceL** [comment]
It's gone again, can we add that back to `ScoopInstaller/Binary`?
