### ISSUE TITLE
wget@1.21.1: Download via aria2 failed

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ScoopInstaller/Main#1993]
Download failed! (Error 3) Resource was not found

RROR Download failed! (Error 3) Resource was not found
ERROR https://eternallybored.org/misc/wget/releases/wget-1.21.1-win64.zip
    referer=https://eternallybored.org/misc/wget/releases/
    dir=C:\Scoop\cache
    out=wget#1.21.1#https_eternallybored.org_misc_wget_releases_wget-1.21.1-win64.zip

ERROR & 'C:\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Scoop\cache\wget.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=10 --max-connection-per-server=10 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12032 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

**Comment by rasa** [comment]
https://eternallybored.org/misc/wget/releases/wget-1.21.1-1-win32.zip is available

**Comment by rasa** [comment]
Fixed in https://github.com/ScoopInstaller/Main/commit/bb85b930df1bfff1b5d187e001e5f7a2f225ddc3
