### ISSUE TITLE
[Request] add sdcc - small device c compiler

### ISSUE THREAD

**Issue by phgmacedo** [ScoopInstaller/Main#1994]
SDCC is a retargettable, optimizing Standard C (ANSI C89, ISO C99, ISO C11) compiler suite that targets the Intel MCS51 based microprocessors (8031, 8032, 8051, 8052, etc.), Maxim (formerly Dallas) DS80C390 variants, Freescale (formerly Motorola) HC08 based (hc08, s08), Zilog Z80 based MCUs (z80, z180, gbz80, Rabbit 2000/3000, Rabbit 3000A, TLCS-90), Padauk (pdk14, pdk15) and STMicroelectronics STM8.

Project link: http://sdcc.sourceforge.net/
Releases binaries: http://sdcc.sourceforge.net/snap.php#Windows

**Comment by phgmacedo** [comment]
I created a manifest, but I'm not sure how to auto-update if a new version comes out: 
https://gist.githubusercontent.com/phgmacedo/1e3e8db1aa18df82b61f1671a8de7f69/raw/c27522821ac1be638ed16f0c1a3646569d487212/sdcc.json

**Comment by HUMORCE** [comment]
i opened a [PR for the released version](https://github.com/ScoopInstaller/Main/pull/2000).

to install snapshot builds, check in my bucket repo:
https://github.com/HUMORCE/scoop-nuke/blob/master/bucket/sdcc-snapshot-x86.json
https://github.com/HUMORCE/scoop-nuke/blob/master/bucket/sdcc-snapshot-x86_64.json
