### ISSUE TITLE
yasm requires Visual C++ Redistributable 2010 to run

### ISSUE THREAD

**Issue by Calinou** [ScoopInstaller/Main#200]
If the Visual C++ Redistributable 2010 isn't installed, `yasm.exe` will throw an error message due to MSVCR100.dll not being found.

Installing `extras/vcredist2010` solves this, but it must be installed from an elevated command prompt (or PowerShell window), so I'm not sure if putting it in the manifest's `suggest` field is a good idea (as the user is probably not running an elevated prompt most of the time). We may have to write `notes` manually instead.

Otherwise, this happens if `extras/vcredist2010` is installed from a standard Command Prompt (or PowerShell window):

```
> scoop install extras/vcredist2010
Installing 'vcredist2010' (10.0.40219) [64bit]
vcredist_x64.exe (9.8 MB) [========================================================================================================================] 100%
Checking hash of vcredist_x64.exe ... ok.
vcredist_x86.exe (8.6 MB) [========================================================================================================================] 100%
Checking hash of vcredist_x86.exe ... ok.
Linking ~\scoop\apps\vcredist2010\current => ~\scoop\apps\vcredist2010\10.0.40219
Running post-install script...
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
```

**Comment by niheaven** [comment]
I'll check vcredist's manifest, maybe we need `-RunAs`

**Comment by madmiraal** [comment]
I think this issue needs to be reopened. yasm depends on Visual C++ Redistributable 2010 to run, and it's still not being installed with yasm.

https://github.com/lukesampson/scoop-extras/pull/2464 allows Visual C++ Redistributable 2010 to be installed, but it still needs to be installed separately.
