### ISSUE TITLE
R@4.0.5: decompress error

### ISSUE THREAD

**Issue by ati-ozgur** [ScoopInstaller/Main#2077]
I get following error:

> scoop install R
Installing 'R' (4.0.5) [64bit]
R-4.0.5-win.exe (84.5 MB) [========================================================] 100%
Checking hash of R-4.0.5-win.exe ... ok.
Extracting R-4.0.5-win.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\USER\scoop\apps\R\4.0.5\R-4.0.5-win.exe.
Log file:
  ~\scoop\apps\R\4.0.5\innounp.log

innounp.log: 

Signature detected: Inno Setup Setup Data (6.0.0) (u). This is not a supported version.

**Comment by HUMORCE** [comment]
cannot reproduce, maybe you should update innounp first: `scoop update innounp`

innounp changelog:

> 0.50 (2020.12.18)
> Added support for IS 6.1.
> Fixed broken paths that originally were in UNC format.
> 
> 0.49 (2019.05.09)
> Added support for IS 6.0.
