### ISSUE TITLE
Python Install - Missing py.exe

### ISSUE THREAD

**Issue by rbharathkumar** [ScoopInstaller/Main#2181]
Hi Team,
Probably a duplicate of https://github.com/ScoopInstaller/Main/issues/377

I just installed python using scoop - python command works as expected but py.exe is nowhere to be found.
I did search through many links and issues and only found the one mentioned above relevant and close to my issue.
**Error message:**

`py.exe : The term 'py.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.

At line:1 char:1
 py.exe -0p
     CategoryInfo          : ObjectNotFound: (py.exe:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException`

Would be nice if we can include the launcher also as part of the install and the relevant environmental variable to go with it ?

**Comment by Valinor** [comment]
Hello,

This is why, when you are installing python, the last lines on cmd are :

> Notes
> -----
> Allow applications and third-party installers to find python by running: "[yourdirectory with python]\install-pep-514.reg"`

If you run this .reg, the command py.exe will works.
