### ISSUE TITLE
[Request] Add miller

### ISSUE THREAD

**Issue by Kreijstal** [ScoopInstaller/Main#2245]
Could miller be added to this repo?
https://github.com/johnkerl/miller
It's good for handling tabular data

**Comment by pratikpc** [comment]
@Kreijstal where could we find the Windows binaries?

Could you create a PR for the same?

**Comment by issaclin32** [comment]
There are Windows binaries in ver 6.0.0, but it is still in beta. Let's wait for the stable release.
https://github.com/johnkerl/miller/releases
