### ISSUE TITLE
nu@0.32.0: Nushell plugins should be installed beside executable

### ISSUE THREAD

**Issue by jntrnr** [ScoopInstaller/Main#2254]
Package: https://github.com/ScoopInstaller/Main/blob/master/bucket/nu.json

Recent versions of Nushell will look for plugins in the same directory as nu.exe. We changed this as startup performance on Windows to crawl the path looking for plugins contributed to slow startup times. Would it be possible for the scoop package to install the plugins from the release binaries into the same directory as nu.exe?

cc @Ash258

**Comment by tiffany352** [comment]
It looks like deleting the `pre_install` directive from the app manifest is enough to fix the issue.

https://gist.github.com/tiffany352/d8ae066d0f12eb5869da9ac523d6e54c
