### ISSUE TITLE
innounp@0.50: download via aria2 failed

### ISSUE THREAD

**Issue by vitoi** [ScoopInstaller/Main#2259]
Updating Scoop...
Updating 'main' bucket...
fatal: unable to access 'https://github.com/ScoopInstaller/Main/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
Updating 'nonportable' bucket...
fatal: unable to access 'https://github.com/TheRandomLabs/scoop-nonportable/': Failed to connect to github.com port 443: Timed out
Scoop was updated successfully!
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'innounp' (0.50) [64bit]
Starting download with aria2 ...
Download: 06/05 08:13:24 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/ScoopInstaller/Binary/maDownload: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is notDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 579ad0|ERR |       0B/s|C:/Users/vito/scoop/cache/innounp#0.50#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_innounp_innounp050.rar
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp050.rar
    referer=https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/
    dir=C:\Users\vito\scoop\cache
    out=innounp#0.50#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_innounp_innounp050.rar

ERROR & 'C:\Users\vito\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\vito\scoop\cache\innounp.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=20384 --continue --summary-interval 0

**Comment by dwettstein** [comment]
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run '**scoop config aria2-enabled false**' to disable it.
