### ISSUE TITLE
innounp@0.50: download via aria2 failed

### ISSUE THREAD

**Issue by quant-tam** [ScoopInstaller/Main#2276]
scoop install innounp
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'innounp' (0.50) [64bit]
Starting download with aria2 ...
Download: 06/10 16:24:51 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/ScoopInstaller/BinaryDownload: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d2a85e|ERR |       0B/s|D:/Scoop/cache/innounp#0.50#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_innounp_innounp050.rar
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp050.rar
    referer=https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/
    dir=D:\Scoop\cache
    out=innounp#0.50#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_innounp_innounp050.rar

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\innounp.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8148 --continue --summary-interval 0

**Comment by dwettstein** [comment]
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run '**scoop config aria2-enabled false**' to disable it.
