### ISSUE TITLE
ffmpeg 4.4-19 - download failed

### ISSUE THREAD

**Issue by Kore-Development** [ScoopInstaller/Main#2284]
https://i.imgur.com/itOPuhy.png

**Comment by pd-kcarrasco** [comment]
Same here. Here is the text:
```
Installing 'ffmpeg' (4.4-19) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-05-30-13-01/ffmpeg-n4.4-19-g8d172d9409-win64-gpl-4.4.zip is not valid
```

If this ffmpeg build existed before, looks like the repo owner might be doing some culling of old builds.

**Comment by pd-kcarrasco** [comment]
Looks like they do prune releases:
https://github.com/BtbN/FFmpeg-Builds/blob/master/.github/workflows/build.yml#L149

The script keeps the latest 14 releases plus the latest release of each of the last 12 months. Other tags/releases get pruned.

**Comment by akirayamamoto** [comment]
This is fixed. Thank you!
