### ISSUE TITLE
dark@3.11.2: download via aria2 failed

### ISSUE THREAD

**Issue by BoneSun** [ScoopInstaller/Main#2298]
ERROR  Bone-PC@ZengYu-PC ~ ❯❯❯ sudo scoop install -G emscripten
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'lessmsi' (1.8.1) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d6c7e3|OK  |   375KiB/s|C:/Users/Bone-PC/scoop/cache/lessmsi#1.8.1#https_github.com_activescott_lessmsi_releases_download_v1.8.1_lessmsi-v1.8.1.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of lessmsi-v1.8.1.zip ... ok.
Extracting lessmsi-v1.8.1.zip ... done.
Linking C:\ProgramData\scoop\apps\lessmsi\current => C:\ProgramData\scoop\apps\lessmsi\1.8.1
Creating shim for 'lessmsi'.
Creating shortcut for Less MSIérables (lessmsi-gui.exe)
'lessmsi' (1.8.1) was installed successfully!
Installing 'dark' (3.11.2) [64bit]
Starting download with aria2 ...
Download: 06/18 18:40:27 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/ScoopInstalDownload: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested aDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 614cfe|ERR |       0B/s|C:/Users/Bone-PC/scoop/cache/dark#3.11.2#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_dark_dark-3.11.2.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/ScoopInstaller/Binary/master/dark/dark-3.11.2.zip
    referer=https://raw.githubusercontent.com/ScoopInstaller/Binary/master/dark/
    dir=C:\Users\Bone-PC\scoop\cache
    out=dark#3.11.2#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_dark_dark-3.11.2.zip

ERROR & 'C:\Users\Bone-PC\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Bone-PC\scoop\cache\dark.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6760 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=dark%403.11.2%3a+download+via+aria2+failed

**Comment by BoneSun** [comment]
> Cannot reproduce.
> 
> All files could be downloaded without any issue.
> Problems with download could be caused by:
> 
> * Network error
> * Site is blocked (Great Firewall of China, Corporate restrictions, ...)
> * Antivirus settings could block URL or block downloaded file
> * Proxy configuration

Try
`- scoop config aria2-enabled false`

**Comment by dwettstein** [comment]
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run '**scoop config aria2-enabled false**' to disable it.
