### ISSUE TITLE
Why go@1.16 was rolled back to 1.15?

### ISSUE THREAD

**Issue by Bpazy** [ScoopInstaller/Main#2328]
Why `go@1.16` was rolled back to `1.15` in this commit: 5764396ba88010da6af9546c370272b24570e08d

I want to know why roll back, because I want to use this version (1.16).

**Comment by HUMORCE** [comment]
checkver(regex) is not updated caused this issue.

**Comment by Bpazy** [comment]
Thank you for your answer and PR
