### ISSUE TITLE
openssl@1.1.1c: decompress error

### ISSUE THREAD

**Issue by frankggyy** [ScoopInstaller/Main#233]
```
Installing 'openssl' (1.1.1c) [64bit]
Loading Win64OpenSSL-1_1_1c.exe from cache.
Checking hash of Win64OpenSSL-1_1_1c.exe ... ok.
Extracting Win64OpenSSL-1_1_1c.exe ...
Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'.
The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\user\scoop\apps\scoop\current\lib\decompress.ps1:192 char:38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand
Failed to extract files from C:\Users\user\scoop\apps\openssl\1.1.1c\Win64OpenSSL-1_1_1c.exe.
Log file:
~\scoop\apps\openssl\1.1.1c\innounp.log
```

**Comment by issaclin32** [comment]
Try running `scoop update innounp -f`

Looks like it's a problem with `innounp` package. Probably something went wrong when updating `innounp`, or the update process was interrupted.

**Comment by myty** [comment]
The same thing happened to me with `scoop update python`.  It was failing on `dark`.  Ran `scoop update dark -f` and then ran `scoop update python -f` and all is good.

**Comment by frankggyy** [comment]
My problem resolved, thanks!


--
Best Regards !
------------------------------------

Tiger Wang（王虎）

Mobile: 008618971219133
------------------------------------

在 2019-07-11 21:30:22，"issaclin32" <notifications@github.com> 写道：


Try running scoop update innounp -f

Looks like it's a problem with innounp package. Probably something went wrong when updating innounp, or the update process was interrupted.
