### ISSUE TITLE
sudo@0.2020.01.26： 通过 aria2 下载失败

### ISSUE THREAD

**Issue by caozehang1992** [ScoopInstaller/Main#2337]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'sudo' (0.2020.01.26) [64bit]
Starting download with aria2 ...
Download: 07/02 17:13:51 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/psutils/c7Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is nDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 4afec5|ERR |       0B/s|C:/Users/caoze/scoop/cache/sudo#0.2020.01.26#https_raw.githubusercontent.com_lukesampson_psutils_c7116ac143ca81f223e6091d0974f45ac241eb1d_sudo.ps1
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/sudo.ps1
    referer=https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/
    dir=C:\Users\caoze\scoop\cache
    out=sudo#0.2020.01.26#https_raw.githubusercontent.com_lukesampson_psutils_c7116ac143ca81f223e6091d0974f45ac241eb1d_sudo.ps1

ERROR & 'C:\Users\caoze\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\caoze\scoop\cache\sudo.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=7480 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=sudo%400.2020.01.26%3a+download+via+aria2+failed

**Comment by dwettstein** [comment]
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run '**scoop config aria2-enabled false**' to disable it.
