### ISSUE TITLE
xmake@2.5.5: hash check failed

### ISSUE THREAD

**Issue by ruitard** [ScoopInstaller/Main#2346]
App:         main/xmake
URL:         https://github.com/xmake-io/xmake/releases/download/v2.5.5/xmake-v2.5.5.win64.zip
First bytes: 50 4B 03 04 14 00 00 08
Expected:    824d7652ab06cc0e27e7edce9226bd07ff1a465df65bce8fb95cebeae02a6991
Actual:      c8deccd2fbd5d38f7ee828e907639090aa6dae25fd15c4a7bb6b7d23bd9d206b

**Comment by akirayamamoto** [comment]
Fixed on https://github.com/ScoopInstaller/Main/commit/117101ef9a101ef1d107a2275b7c169a3dbb4535
