### ISSUE TITLE
Help/assist maintaining the repository

### ISSUE THREAD

**Issue by dwettstein** [ScoopInstaller/Main#2403]
Hey maintainers and everyone

Recently I observed that more and more duplicated issues and even pull requests are created. Sometimes, a PR (e.g. hash fix) would exist, but cannot be merged, since an additional review by someone with write access is required.

Examples:
- https://github.com/ScoopInstaller/Main/pull/2116 (https://github.com/ScoopInstaller/Main/pull/2219, #2435 respectively): 31 issues
- https://github.com/ScoopInstaller/Main/pull/2195 (https://github.com/ScoopInstaller/Main/pull/2263, #2423 respectively): 25 issues
- https://github.com/ScoopInstaller/Main/pull/2278: 15 issues

Merging these pull requests would solve in total 71 issues!

To me, it looks like no one (with write access) is interested (anymore?) in merging PRs. I can totally understand, that maintaining such a community repository is a huge effort.

**So the questions is, how can we help or assist maintaining the repository?**

BTW, thank you very much @Ash258, @r15ch13 and @rasa for putting that much time and effort into Scoop. That's awesome!

**Comment by wjrogers** [comment]
At the risk of asking an unpopular question, is there a reason the maintainers are losing interest in scoop? For example, is there a viable alternative?

**Comment by rasa** [comment]
https://en.m.wikipedia.org/wiki/List_of_software_package_management_systems#Windows has a rather complete list of Windows package managers. Missing is 
[Baulk](https://github.com/baulk/baulk), which looks very interesting. It's C-based and allows one to install multiple versions of the same app in virtual environments. It also claims to solve the symlink issues that plague chocolatey scoop.

**Comment by dwettstein** [comment]
In the end, all alternatives will have the same weakness, having enough maintainers to keep things going.

Eventually the [Windows Package Manager Client (aka winget.exe)](https://github.com/microsoft/winget-cli) won't have this problem, but let's see. Currently it doesn't support installing portable applications yet, so it's basically doing the opposite of Scoop (see https://github.com/microsoft/winget-cli/issues/140 and https://github.com/microsoft/winget-cli/issues/182).

**Comment by stevehipwell** [comment]
@rasa as one of the listed maintainers, is there an official statement or direction on this? Is there the possibility to add maintainers or automation to clear the backlog as IMHO Scoop is still the best solution to this specific problem.

**Comment by rasa** [comment]
@stevehipwell Thank you for your interest. I added you to the Main repo, but can't figure out how to add you as a Maintainer to the ScoopInstaller organization. Perhaps one of the owners of that group can: @lukesampson, @r15ch13 or @deevus. I am just a member, not an owner.

**Comment by stevehipwell** [comment]
Thanks @rasa, being able to help here would be a good start. Are there any docs on the process for PRs?

**Comment by stevehipwell** [comment]
@rasa I think I've figured out the process and merged https://github.com/ScoopInstaller/Main/pull/2620. I've assigned you to my two outstanding PRs as I obviously can't approve my own but I'll try and pick up some more of the outstanding ones I'm familiar with.

**Comment by dwettstein** [comment]
@rasa, thanks for inviting us to help. I will take the time to clean up old issues and PRs that are not relevant anymore (e. g. due to e newer version). What is the usual process for these ones, just closing them?

Additionally, what do you think of pinning this issue so that other people, who want to help as well, can add a comment? I suggest to close the issue then.

**Comment by akirayamamoto** [comment]
I am willing to help as well.

**Comment by rasa** [comment]
@akirayamamoto You've been added. Thanks for your help.

**Comment by rasa** [comment]
> Additionally, what do you think of pinning this issue so that other people, who want to help as well, can add a comment? I suggest to close the issue then.

Pinned.

**Comment by stevehipwell** [comment]
@rashil2000 you've been very active on here, were you also keen to be a maintainer?

**Comment by rashil2000** [comment]
I haven't thought about maintaining, actually. I'll ping you up whenever I feel I'm ready for it 😅

**Comment by issaclin32** [comment]
@stevehipwell I would like to help as well.

**Comment by stevehipwell** [comment]
@issaclin32 I'm only helping here myself so can't add anyone else. This thread is the right place but I'd suggest asking @rasa.

**Comment by rasa** [comment]
@issaclin32 Thank you for your past efforts, and your current support. You should have received an invite to become a maintainer.

**Comment by Valinor** [comment]
I am willing to help as well. Scoop is a great tools. It deserves more attention.

**Comment by dwettstein** [comment]
![image](https://user-images.githubusercontent.com/412133/135839408-a6f9fb8d-84f9-4ee7-8d8e-a97f48fc3e9e.png)

🎉 Thank you all and keep it up! 😃

**Comment by rasa** [comment]
> I am willing to help as well. Scoop is a great tools. It deserves more attention.

@Valinor You should have received an invite to become a maintainer. Thank you for your support.

**Comment by issaclin32** [comment]
@linsui Are you interested in help maintaining the project? I see you did a lot of work previously.

**Comment by Valinor** [comment]
> > I am willing to help as well. Scoop is a great tools. It deserves more attention.
> 
> @Valinor You should have received an invite to become a maintainer. Thank you for your support.

Thanks @rasa .

**Comment by deevus** [comment]
> At the risk of asking an unpopular question, is there a reason the maintainers are losing interest in scoop? For example, is there a viable alternative?

For me personally I don't work in a Windows environment anymore and haven't for years. I still use scoop when I'm dabbling on my home PC but I was operating on the assumption that scoop was in good hands.

**Comment by issaclin32** [comment]
@HUMORCE Are you willing to help maintain the project?
I see you did some work and code suggestions in previous months.

**Comment by rasa** [comment]
@pratikpc You should be receiving an invite to be a maintainer. Thank you for your interest and support.

**Comment by issaclin32** [comment]
> Hi everyone. I'm sorry to be late for the party. I'm the author of the[ comment mentioned](https://github.com/ScoopInstaller/Main/issues/2403#issuecomment-950869162). I already committed to the manifests repos several times and it will be a pleasure to help as well. I hope the train has not left yet :)

@rasa Should we invite @goostleek to become a maintainer?
Or, do we have other concerns?

**Comment by rasa** [comment]
> > Hi everyone. I'm sorry to be late for the party. I'm the author of the[ comment mentioned](https://github.com/ScoopInstaller/Main/issues/2403#issuecomment-950869162). I already committed to the manifests repos several times and it will be a pleasure to help as well. I hope the train has not left yet :)
> 
> @rasa Should we invite @goostleek to become a maintainer? Or, do we have other concerns?

@issaclin32 Thanks for the heads up, somehow I missed this. @goostleek has been invited to join in the fun!

**Comment by rasa** [comment]
I just invited @wiredmind too, another request I missed. And what are the odds that @goostleek and @wiredmind are both named Marcin?

**Comment by sitiom** [comment]
Hello. If this is still available, I am interested in becoming a maintainer.

**Comment by rashil2000** [comment]
We do need lots of bucket maintainers - I'll be happy to add you in the Extras repo :)

Pinging @rasa and @niheaven for their vote...

**Comment by niheaven** [comment]
Vote for @sitiom, we need maintainers that have been doing good creating or maintaining jobs.

**Comment by rasa** [comment]
+1 for @sitiom @Zliced13 has been very active as well. @Zliced13 would you want to become a scoop maintainer as well?

**Comment by Zliced13** [comment]
@rasa Thanks for the offer but I'm going to have to decline. I think that position should go to @sitiom, they are more experienced in PowerShell than I am.

**Comment by rashil2000** [comment]
@sitiom I have sent you an invite.

**Comment by sitiom** [comment]
Thanks!

**Comment by rasa** [comment]
@Zliced13 Not a problem, and I get you, PowerShell is an acquired taste, that I'm still reaching for.
