### ISSUE TITLE
[Request] Add OfflineInsiderEnroll

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Main#2417]
https://github.com/whatever127/offlineinsiderenroll

> OfflineInsiderEnroll is a simple Windows Command Prompt script to enable access to the Windows Insider Program on machines not signed in with Microsoft Account.

It's just a `.bat` file. Uses [GitHub Releases](https://github.com/whatever127/offlineinsiderenroll/releases).

**Comment by pratikpc** [comment]
@NatoBoram works for 11?

**Comment by NatoBoram** [comment]
Yep

**Comment by pratikpc** [comment]
@NatoBoram does Scoop already have a tool which is similar to this?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/pull/3002
