### ISSUE TITLE
Error: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by Mine-MuYan** [ScoopInstaller/Main#2446]
```
scoop install git
Installing 'git' (2.32.0.windows.2) [64bit]
根据验证过程，远程证书无效。
URL https://gh.haval.gq/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-64-bit.7z.exe#/dl.7z is not valid
```

**Comment by dwettstein** [comment]
Hey @Mine-MuYan 
Please check your buckets. It seems that the URL you are using is different than as defined in the main bucket (see https://github.com/ScoopInstaller/Main/blob/master/bucket/git.json).
Best regards.

**Comment by rashil2000** [comment]
@issaclin32 this can be closed (because of the `wontfix` label)

**Comment by issaclin32** [comment]
@rashil2000 This ca be closed.
