### ISSUE TITLE
tor@0.4.5.9: download via aria2 failed

### ISSUE THREAD

**Issue by zeruel11** [ScoopInstaller/Main#2463]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'tor' (0.4.5.9) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 53c540|ERR |       0B/s|C:/Users/--/.scoopy/cache/tor#0.4.5.9#https_dist.torproject.org_torbrowser_10.0.18_tor-win64-0.4.5.9.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://dist.torproject.org/torbrowser/10.0.18/tor-win64-0.4.5.9.zip
    referer=https://dist.torproject.org/torbrowser/10.0.18/
    dir=C:\Users\--\.scoopy\cache
    out=tor#0.4.5.9#https_dist.torproject.org_torbrowser_10.0.18_tor-win64-0.4.5.9.zip

ERROR & 'C:\Users\--\.scoopy\apps\aria2\current\aria2c.exe' --input-file='C:\Users\--\.scoopy\cache\tor.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.0 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=21724 --continue --summary-interval 0

**Comment by zeruel11** [comment]
tried going to the link and apparently moved to either torbrowser/10.5 or torbrowser/10.5.2
will try changing the url

**Comment by akirayamamoto** [comment]
This is fixed. Thank you!
