### ISSUE TITLE
julia@1.6.2: decompress error

### ISSUE THREAD

**Issue by anwarsky** [ScoopInstaller/Main#2471]
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.

**Comment by Valinor** [comment]
@anwarsky : You reported version `1.6.2`, but the latest available version is `1.6.3`.

Run `scoop update; scoop uninstall julia; scoop install julia`

If the problem persist, reopen a new issue with the correct julia version please. Thanks (can't reproduce with the last version)
