### ISSUE TITLE
gitlab-runner@14.1.0: hash check failed

### ISSUE THREAD

**Issue by xukecheng** [ScoopInstaller/Main#2491]
App:         main/gitlab-runner
URL:         https://gitlab-runner-downloads.s3.amazonaws.com/v14.1.0/binaries/gitlab-runner-windows-amd64.exe#/gitlab-runner.exe
First bytes: 4D 5A 90 00 03 00 04 00
Expected:    0c44b1232bd45363a090d482c06715faaf9ca2890e183b87f895495d6dfeffbf
Actual:      13b08d06cf90b7e8e7411bcca72cc3ac397c8a3a71ef30e0452d076d37ad35d0

**Comment by akirayamamoto** [comment]
Fixed on https://github.com/ScoopInstaller/Main/commit/df20b73f4e0804caf80b1db30f3cea0bcbdd5dcd
