### ISSUE TITLE
vagrant@2.2.18: hash check failed

### ISSUE THREAD

**Issue by lwintermelon** [ScoopInstaller/Main#2518]
Installing 'vagrant' (2.2.18) [64bit]
vagrant_2.2.18_x86_64.msi (253.1 MB) [========================================================================] 100%
Checking hash of vagrant_2.2.18_x86_64.msi ... ERROR Hash check failed!
App:         main/vagrant
URL:         https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    aed44d72e72d2183354c7e2e0f6118e289becba0491a67eb2e5551701b70d359
Actual:      8ce913bee9debcbf39f313f4255e56f37dac5281cd62458c0c0040e5c76ee93e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=vagrant%402.2.18%3a+hash+check+failed

**Comment by ksophocleous** [comment]
This problem is open since beginning of August?! And it's still not fixed. What is happening here?
