### ISSUE TITLE
lynx@2.9.0dev.8: download via aria2 failed

### ISSUE THREAD

**Issue by markfelt** [ScoopInstaller/Main#2534]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://invisible-island.net/datafiles/current/lynx-newssl-setup.exe
    referer=https://invisible-island.net/datafiles/current/
    dir=C:\Users\rustd\scoop\cache
    out=lynx#2.9.0dev.8#https_invisible-island.net_datafiles_current_lynx-newssl-setup.exe
https://slproweb.com/download/Win32OpenSSL_Light-1_1_1j.exe
    referer=https://slproweb.com/download/
    dir=C:\Users\rustd\scoop\cache
    out=lynx#2.9.0dev.8#https_slproweb.com_download_Win32OpenSSL_Light-1_1_1j.exe

ERROR & 'C:\Users\rustd\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\rustd\scoop\cache\lynx.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=21748 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=lynx%402.9.0dev.8%3a+download+via+aria2+failed

**Comment by markfelt** [comment]
The latest version of Lynx is currently not available?

**Comment by igitur** [comment]
Fixed by https://github.com/ScoopInstaller/Main/pull/2155
