### ISSUE TITLE
gitlab-runner@14.1.0: hash check failed

### ISSUE THREAD

**Issue by shakahl** [ScoopInstaller/Main#2540]
Updating 'gitlab-runner' (14.0.1 -> 14.1.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: a7ed8d|OK  |   1.8MiB/s|C:/Users/***/scoop/cache/gitlab-runner#14.1.0#https_gitlab-runner-downloads.s3.amazonaws.com_v14.1.0_binaries_gitlab-runner-windows-amd64.exe_gitlab-runner.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of gitlab-runner-windows-amd64.exe ... ERROR Hash check failed!
App:         main/gitlab-runner
URL:         https://gitlab-runner-downloads.s3.amazonaws.com/v14.1.0/binaries/gitlab-runner-windows-amd64.exe#/gitlab-runner.exe
First bytes: 4D 5A 90 00 03 00 04 00
Expected:    0c44b1232bd45363a090d482c06715faaf9ca2890e183b87f895495d6dfeffbf
Actual:      13b08d06cf90b7e8e7411bcca72cc3ac397c8a3a71ef30e0452d076d37ad35d0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gitlab-runner%4014.1.0%3a+hash+check+failed

**Comment by akirayamamoto** [comment]
gitlab-runner@14.2.0 on https://github.com/ScoopInstaller/Main/commit/df20b73f4e0804caf80b1db30f3cea0bcbdd5dcd
