### ISSUE TITLE
trid@2.24-21.08.05: hash check failed

### ISSUE THREAD

**Issue by natesilva** [ScoopInstaller/Main#2544]
scoop install trid
Installing 'trid' (2.24-21.08.05) [64bit]
triddefs.zip (1.6 MB) [===========================================================================================================] 100%
Checking hash of triddefs.zip ... ERROR Hash check failed!
App:         main/trid
URL:         https://mark0.net/download/triddefs.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d538bdc8b438e36bae72851a53de3afbff09a910870d6e9b50348209b6ddf9ac
Actual:      27c759c9c143a101c5fbb11872a714bfe95dd465ad21edd9852c52ea17c29647

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=trid%402.24-21.08.05%3a+hash+check+failed

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Main/pull/2545/commits/0c0480f017a21b7609b8b9ddb3709d3202424a63
