### ISSUE TITLE
gitlab-runner@14.1.0: hash check faile

### ISSUE THREAD

**Issue by yagodkin** [ScoopInstaller/Main#2554]
Installing 'gitlab-runner' (14.1.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: affaf5|OK  |   3.8MiB/s|C:/Users/yagodkin/scoop/cache/gitlab-runner#14.1.0#https_gitlab-runner-downloads.s3.amazonaws.com_v14.1.0_binaries_gitlab-runner-windows-amd64.exe_gitlab-runner.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of gitlab-runner-windows-amd64.exe ... ERROR Hash check failed!
App:         main/gitlab-runner
URL:         https://gitlab-runner-downloads.s3.amazonaws.com/v14.1.0/binaries/gitlab-runner-windows-amd64.exe#/gitlab-runner.exe
First bytes: 4D 5A 90 00 03 00 04 00
Expected:    0c44b1232bd45363a090d482c06715faaf9ca2890e183b87f895495d6dfeffbf
Actual:      13b08d06cf90b7e8e7411bcca72cc3ac397c8a3a71ef30e0452d076d37ad35d0

**Comment by akirayamamoto** [comment]
gitlab-runner@14.2.0 on https://github.com/ScoopInstaller/Main/commit/df20b73f4e0804caf80b1db30f3cea0bcbdd5dcd
