### ISSUE TITLE
xnconvert Request

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Main#2577]
PackageIdentifier: xnconvert
PackageVersion: 1.92
PackageLocale: en-US
Publisher: xnconvert
PackageName: xnconvert
License: proprietary
ShortDescription: Image converter for Windows
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://download.xnview.com/XnConvert-win-x64.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Valinor** [comment]
**Criteria :** 
https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket 
- a non-GUI tool :x:

Try to post for inclusion in extra bucket (https://github.com/lukesampson/scoop-extras)
