### ISSUE TITLE
Auto-updating Sass

### ISSUE THREAD

**Issue by nex3** [ScoopInstaller/Main#258]
I noticed recently you have [a bucket for Dart Sass](https://github.com/ScoopInstaller/Main/blob/master/bucket/sass.json), which seems to be maintained by hand. Dart Sass has a deploy process that automatically deploys it to all its other target locations—would you be interested in looping Scoop into that process? You'd need to give @SassBot commit access to this repository.

**Comment by Ash258** [comment]
All autoupdates are handled automatically on hour basis by https://github.com/ScoopInstaller/Excavator

**Comment by nex3** [comment]
Okay, sounds like this is taken care of then!
