### ISSUE TITLE
tup@0.7.11: hash check failed

### ISSUE THREAD

**Issue by korrat** [ScoopInstaller/Main#2591]
```
Checking hash of tup-latest.zip ... ERROR Hash check failed!
App:         main/tup
URL:         http://gittup.org/tup/win32/tup-latest.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    933dafd45f7e630f3b1d7ebac791a1497db9c38729995f29c14478eb9cfbb2c6
Actual:      6a4e8ac4eeff50eb9bc0b7030c9b50e74f2ef49315b7757f8a200e3e35985235
```

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Main/pull/2592/commits/e5fd24c9858bca7ec14fe6152a4a0c13748dd143

**Comment by metakosmo** [comment]
Tup provides bundles for specific versions.  You could tie the manifest to the specific version for the hash; `tup-lastest.zip` is always the latest version, and will change when a new bundle is uploaded, invalidating your hash.  The link for the version with the current hash is `http://gittup.org/tup/win32/tup-v0.7.11-34-g069a8fc5.zip`.

**Comment by issaclin32** [comment]
> Tup provides bundles for specific versions. You could tie the manifest to the specific version for the hash; `tup-lastest.zip` is always the latest version, and will change when a new bundle is uploaded, invalidating your hash. The link for the version with the current hash is `http://gittup.org/tup/win32/tup-v0.7.11-34-g069a8fc5.zip`.

Thanks for the information. The problem will be fixed in https://github.com/ScoopInstaller/Main/pull/2732.
