### ISSUE TITLE
k9s@0.24.15: download via aria2 failed

### ISSUE THREAD

**Issue by jiang-wen** [ScoopInstaller/Main#2609]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'k9s' (0.24.15) [64bit]
Starting download with aria2 ...
Download: 08/29 18:19:49 [ERROR] CUID#8 - Download aborted. URI=https://github.com/derailed/k9s/releases/download/v0.24.15/kDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: f34bd1|ERR |       0B/s|D:/Scoop/cache/k9s#0.24.15#https_github.com_derailed_k9s_releases_download_v0.24.15_k9s_Windows_x86_64.tar.gz
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 2) Timeout
ERROR https://github.com/derailed/k9s/releases/download/v0.24.15/k9s_Windows_x86_64.tar.gz
    referer=https://github.com/derailed/k9s/releases/download/v0.24.15/
    dir=D:\Scoop\cache
    out=k9s#0.24.15#https_github.com_derailed_k9s_releases_download_v0.24.15_k9s_Windows_x86_64.tar.gz

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\k9s.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=22740 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=k9s%400.24.15%3a+download+via+aria2+failed

**Comment by dwettstein** [comment]
> WARN Scoop uses 'aria2c' for multi-connection downloads.
> WARN Should it cause issues, run '**scoop config aria2-enabled false**' to disable it.
