### ISSUE TITLE
ffmpeg.ps1 causes issues

### ISSUE THREAD

**Issue by arnabanimesh** [ScoopInstaller/Main#2611]
Calling `ffmpeg.exe` shim doesn't cause any issue, but calling `ffmpeg.ps1` (default behaviour when calling from PowerShell 7) causes issues.

Running the following in PowerShell: `ffmpeg -i i.avi -bsf:v mpeg4_unpack_bframes -codec copy o.avi` causes this error:
```
[NULL @ 00000235ef2ebd00] Unable to find a suitable output format for 'mpeg4_unpack_bframes'
mpeg4_unpack_bframes: Invalid argument
```

I need to explicitly call `ffmpeg.exe` from PowerShell to avoid issues.

Check this link for more detailed discussion: https://trac.ffmpeg.org/ticket/9398

**Comment by ValZapod** [comment]
you should explicitly call ffmpeg.exe. Not ending in exe is just a hack of cmd and powershell interpreters, it should not be relied upon. Please print versions of key ffmpeg components libraries in both cases. That looks like 
libavutil 57. 4.101 ... 

it recogniseses mpeg4_unpack_bftames as an output instead of -bsf:v. But that is not a bug in ffmpeg, it is a bug in the shall interface.

**Comment by arnabanimesh** [comment]
If `ffmpeg.ps1` is not intended for use, then it shouldn't exist in the first place.

An end user won't know.

**Comment by HUMORCE** [comment]
https://github.com/HUMORCE/scoop-nuke/blob/master/bucket/ffmpeg.json

Add the bin directory to PATH can solve this problem, but you cannot switch between different versions. (`scoop reset ffmpeg/ffmpeg-shared/...`)

**Comment by arnabanimesh** [comment]
Deleting ps1 file is a temporary issue as it will reappear after update.

I'll add the bin directory in the path, but it may cause issues in some other apps also using incompatible characters, and hence it needs to be addressed in order to make it robust.

**Comment by akirayamamoto** [comment]
I can reproduce the issue. I am not sure when this `ffmpeg.ps1` is created though.

**Comment by arnabanimesh** [comment]
> I can reproduce the issue. I am not sure when this `ffmpeg.ps1` is created though.

ffmpeg.ps1 is created using this: https://raw.githubusercontent.com/lukesampson/psutils/3290c04d7653ea8183a5e11d3d5a4e46716035d1/shim.ps1
You can find it in this code: https://github.com/ScoopInstaller/Main/blob/3d8c2e1c5eb8adc8fc9627165d0e796cad846876/bucket/shim.json
