### ISSUE TITLE
rtools@4.0.0: hash check failed

### ISSUE THREAD

**Issue by wheineman** [ScoopInstaller/Main#2615]
PS C:\Users\Willy> scoop install rtools
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'rtools' (4.0.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b982c3|OK  |   3.7MiB/s|C:/Users/Willy/scoop/cache/rtools#4.0.0#https_cloud.r-project.org_bin_windows_Rtools_rtools40-x86_64.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of rtools40-x86_64.exe ... ERROR Hash check failed!
App:         main/rtools
URL:         https://cloud.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    46cde0914de2fe8f122edd1f2910f204631abdb4c7271bd98b4a605c5c144c26
Actual:      3a41212b16523473e6343680d665c5dcc23d068d63c28f0d4ce91c5ce50960dd

Please try again or create a new issue by using the following link and paste your

**Comment by dwettstein** [comment]
Closed by #2149
