### ISSUE TITLE
dotnet-sdk - Download/Updates are always so slow and fails a lot

### ISSUE THREAD

**Issue by damienbutt** [ScoopInstaller/Main#2635]
Hi all,

Not sure if this is a scoop issue as such but the dotnet-sdk is always so slow to download/update. Has anyone else noticed this? It can't be just me.

Is there a way to improve this? I don't have an issue with any other application downloading. 80% of the time the download is so slow it fails halfway through.

Any ideas?

D

**Comment by pratikpc** [comment]
@damienbutt could be a Windows CDN issue?

**Comment by Valinor** [comment]
![image](https://user-images.githubusercontent.com/2079654/139808871-cda8c6b9-6e57-4333-8b77-c671779e2019.png)
Not fast, not slow. It's seem ok for me. Maybe your network. Not a scoop issue except if someone else can repeat this.
