### ISSUE TITLE
rtools@4.0.0: hash check failed

### ISSUE THREAD

**Issue by mintpancake** [ScoopInstaller/Main#2639]
Checking hash of rtools40-x86_64.exe ... ERROR Hash check failed!
App:         main/rtools
URL:         https://cloud.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    46cde0914de2fe8f122edd1f2910f204631abdb4c7271bd98b4a605c5c144c26
Actual:      3a41212b16523473e6343680d665c5dcc23d068d63c28f0d4ce91c5ce50960dd

**Comment by dwettstein** [comment]
Closed by #2149
