### ISSUE TITLE
[Request] Add libavif

### ISSUE THREAD

**Issue by TamamoNoMae13** [ScoopInstaller/Main#2640]
https://github.com/AOMediaCodec/libavif
I think it would be webp successor in the future.
Moved from https://github.com/lukesampson/scoop/issues/4443

**Comment by pratikpc** [comment]
@TamamoNoMae13 not yet released?
Everything is in pre-release

**Comment by issaclin32** [comment]
This package has been in pre-release for years. Should we just add it to the bucket?

**Comment by rashil2000** [comment]
I think we can add it:

> ![image](https://user-images.githubusercontent.com/46838874/150627337-b633dac7-09ce-4d11-a73b-f4d296dce587.png)
