### ISSUE TITLE
nssm triggers windows defender

### ISSUE THREAD

**Issue by mauskillsgiants** [ScoopInstaller/Main#2642]
Installed Jellyfin which recommends to install nssm. Tried to install that and windows defender immediately was triggered.
![nssm](https://user-images.githubusercontent.com/7538121/132141262-40f73f92-3a7b-4489-860c-d82d9bdc3641.jpg)

**Comment by HUMORCE** [comment]
scoop prompts added some directories as exceptions for defender, when you execute `scoop checkup`.
