### ISSUE TITLE
imagemagick 404

### ISSUE THREAD

**Issue by eastlovsky** [ScoopInstaller/Main#2646]
Installing 'ImageMagick' (7.1.0-5) [64bit]
远程服务器返回错误: (404) 未找到。
URL https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-5-portable-Q16-x64.zip is not valid

**Comment by HUMORCE** [comment]
`7.1.0-5` is out of date, just wait for the main bucket to update the manifest to `7.1.0-6`.

https://imagemagick.org/script/download.php#windows

**Comment by issaclin32** [comment]
Closing this issue because the problem has been solved (with version update)
