### ISSUE TITLE
gnuplot@5.4.2: hash check failed

### ISSUE THREAD

**Issue by basheewang** [ScoopInstaller/Main#2647]
>scoop install gnuplot
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'gnuplot' (5.4.2) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8ccc23|OK  |   1.2MiB/s|C:/Users/wanchen/scoop/cache/gnuplot#5.4.2#https_downloads.sourceforge.net_project_gnuplot_gnuplot_5.4.2_gp542-win64-mingw.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of gp542-win64-mingw.7z ... ERROR Hash check failed!
App:         main/gnuplot
URL:         https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.4.2/gp542-win64-mingw.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed
Actual:      4512c76d5846929459527686a8e5f4634652ddd366bb0013a153137fa897e155
SourceForge.net is known for causing hash validation fails. Please try again before opening a ticket.

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gnuplot%405.4.2%3a+hash+check+failed

**Comment by akirayamamoto** [comment]
Thank you for your contribution. This is fixed on #2450
