### ISSUE TITLE
imagemagick@7.1.0-6: hash check failed

### ISSUE THREAD

**Issue by shanmuha** [ScoopInstaller/Main#2673]
Updating 'imagemagick' (7.1.0-5 -> 7.1.0-6)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 82f2d7|OK  |   0.9MiB/s|C:/Users/sthia/scoop/cache/imagemagick#7.1.0-6#https_www.imagemagick.org_download_binaries_ImageMagick-7.1.0-portable-Q16-x64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ImageMagick-7.1.0-portable-Q16-x64.zip ... ERROR Hash check failed!
App:         main/imagemagick
URL:         https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    8c52c289de93894688281027f8f84eaffff8188f7b2f6a83223a08ba5e1b6750
Actual:      2090859ec45d48e59e8e4d2a381b7479abbb95e385d19a8a2da4b0c6fee98d44

**Comment by dwettstein** [comment]
Resolved by https://github.com/ScoopInstaller/Main/commit/87ca8ae5bcef2b95d60e29e58e68cb9ccb974300
