### ISSUE TITLE
Request for irssi

### ISSUE THREAD

**Issue by bharatvaj** [ScoopInstaller/Main#2713]
There is a [prebuilt](http://cygwin.osuosl.org/x86_64/release/irssi/) cygwin package for irssi

Can this be added to scoop?

**Comment by pratikpc** [comment]
@bharatvaj could you create a PR for the same?

**Comment by bharatvaj** [comment]
I thought the cygwin package would work but unfortunately it requires cygwin environment. I'll try to build a version that works on windows standalone(I may fail in this) as I currently require it. Can we submit custom builds?

**Comment by rashil2000** [comment]
The source repo should meet the Main [criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

**Comment by bharatvaj** [comment]
It seems that irssi does require a cygwin environment and I can't find any easy solutions to get a single static binary. I'll close this issue for now.
