### ISSUE TITLE
imagemagick@7.1.0-8: hash check failed

### ISSUE THREAD

**Issue by philklc** [ScoopInstaller/Main#2724]
`Installing 'imagemagick' (7.1.0-8) [64bit]`
`Loading ImageMagick-7.1.0-portable-Q16-x64.zip from cache.`
`Checking hash of ImageMagick-7.1.0-portable-Q16-x64.zip ... ERROR Hash check failed!`
`App:         main/imagemagick`
`URL:         https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip`
`First bytes: 50 4B 03 04 14 00 08 00`
`Expected:    444bb252eb171007353c3dca16f79fb6efd129d1ae31b777b4c8c3e296832e3c`
`Actual:      53b954907b2a19e64e908e097fa669499a373e359d1e398ca9356c98656949de`

**Comment by dwettstein** [comment]
Resolved by https://github.com/ScoopInstaller/Main/commit/87ca8ae5bcef2b95d60e29e58e68cb9ccb974300
