### ISSUE TITLE
ffmpeg file not found

### ISSUE THREAD

**Issue by chrismccoy** [ScoopInstaller/Main#2734]
ffmpeg update fails, because of file not found for the latest version, 404 error.

The remote server returned an error: (404) Not Found.
URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-09-22-12-21/ffmpeg-n4.4-154-g79c114e1b2-win64-gpl-4.4.zip is not valid

**Comment by Valinor** [comment]
Thanks for reporting. 
**About BtbN :**

> _Release Retention Policy_
> The last build of each month is kept for two years.
> The last 14 daily builds are kept.
