### ISSUE TITLE
[Request] rqlite

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Main#2769]
Repo: https://github.com/rqlite/rqlite

Build downloads: https://ci.appveyor.com/api/projects/otoolep/rqlite/artifacts/rqlite-latest-win64.zip?branch=master (as mentioned on `README.md`)

The zip contains 3 executable binaries.

**Comment by rashil2000** [comment]
@gphg Here's the versioned download link - https://ci.appveyor.com/api/projects/otoolep/rqlite/artifacts/rqlite-latest-win64.zip?tag=v6.7.0

But AppVeyor artifacts expire after one month. So the manifest will be invalid after that. Please ask the rqlite maintainers to persist these artifacts (or better yet, release them on GitHub itself). Until then, I'm afraid we can't add it to Scoop.

**Comment by gphg** [comment]
I did a look up. Some one issued this years ago:
https://github.com/rqlite/rqlite/issues/259

I might open an issue regarding persistence of build release.
