### ISSUE TITLE
tor@0.4.5.10: Download failed

### ISSUE THREAD

**Issue by roythearsonist** [ScoopInstaller/Main#2770]
The remote server returned an error: 
Is the webpage dead for this too?

**Comment by theblobscp** [comment]
It's also quite out of date

**Comment by issaclin32** [comment]
> The url has been changed to https://www.torproject.org/dist/torbrowser/10.5.8/tor-win32-0.4.5.10.zip https://www.torproject.org/dist/torbrowser/10.5.8/tor-win64-0.4.5.10.zip

The URL is actually re-directed to https://dist.torproject.org/torbrowser/10.5.8/tor-win32-0.4.5.10.zip
