### ISSUE TITLE
How to add a new manifest for `fselect` cli tool

### ISSUE THREAD

**Issue by OdinTech3** [ScoopInstaller/Main#282]
Hey I am new user of scoop. I came across the awesome cli tool called [`fselect`](https://github.com/jhspetersson/fselect) that unfortunately wasn't available via scoop. I am wiling to add it to the main bucket but i need guidance on how to go about that.

**Comment by Ash258** [comment]
https://scoop.netlify.com/concepts/#app-manifests

**Comment by OdinTech3** [comment]
Thanks!!
