### ISSUE TITLE
checkversion problem for some package

### ISSUE THREAD

**Issue by Valinor** [ScoopInstaller/Main#2843]
## Bug Report

Theses packages have problem with checkversion : 
- ffmpeg-shared
- forego
- ~~invoke-build~~ (https://github.com/ScoopInstaller/Main/pull/2890)
- mariadb
- ~~megacmd~~ (https://github.com/ScoopInstaller/Main/pull/2892)
- ~~neovim~~ (https://github.com/ScoopInstaller/Main/pull/2960)
- opus-tools
- redis
- teleport

**Comment by pratikpc** [comment]
Forego is hosted on Equinox

Equinox is gone

https://equinox.io/blog/shutting-down

**Comment by pratikpc** [comment]
@Valinor Redis looks like it is broken

**Comment by BasixKOR** [comment]
Could we add a `contribution welcome` tag to this issue? I'm willing to work on fixing `ffmpeg`.

**Comment by rashil2000** [comment]
Done. Thank you @BasixKOR :)
