### ISSUE TITLE
[Request] Add Jenkins

### ISSUE THREAD

**Issue by onacit** [ScoopInstaller/Main#2851]
I'm not sure what could be harsh with Windows but hombrew already has a formula for the Jenkins.

See,
* [macOS Installers for Jenkins LTS](https://www.jenkins.io/download/lts/macos/)
* [jenkins](https://formulae.brew.sh/formula/jenkins)(Homebrew Formulae)

Can anybody please add Jenkins to scoop?

**Comment by pratikpc** [comment]
For hash you can use $url.sha256 as well

**Comment by pratikpc** [comment]
Why openjdk11?

It would not work with openjdk17 for example or latest OpenJDK?

**Comment by PeeZu** [comment]
> Why openjdk11?
> 
> It would not work with openjdk17 for example or latest OpenJDK?

https://www.jenkins.io/doc/administration/requirements/java/
