### ISSUE TITLE
imagemagick@7.1.0-13: hash check failed

### ISSUE THREAD

**Issue by jadeker** [ScoopInstaller/Main#2854]
imagemagick: 7.1.0-12 -> 7.1.0-13
Updating one outdated app:
Updating 'imagemagick' (7.1.0-12 -> 7.1.0-13)
Downloading new version
ImageMagick-7.1.0-portable-Q16-x64.zip (110.7 MB) [===============================================================================================] 100%
Checking hash of ImageMagick-7.1.0-portable-Q16-x64.zip ... ERROR Hash check failed!
App:         main/imagemagick
URL:         https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    2630cd01858f445312146eb09e8b5f925017e6ecae952ef31db15f876c7bea9c
Actual:      946f3ff4a3a25621820cedf020796c897a987830bf0e471ec97611f25bd24215

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/2852
