### ISSUE TITLE
trid@2.24-19.07.28: hash check failed

### ISSUE THREAD

**Issue by nazikus** [ScoopInstaller/Main#286]
App:         main/trid
URL:         http://mark0.net/download/triddefs.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    12331a67714911b8350afedd056a018c735697232ef269efeb2e568019f55c7a
Actual:      52f23161b68b320acd4019461b02905af0ae9a31e1efa7fc228582b6ad7491a9

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=trid%402.24-19.07.28%3a+hash+check+failed

**Comment by issaclin32** [comment]
**trid** has just updated its definition file, while the URL remains the same. This causes the hash-check to fail.

`scoop install trid@2.24-19.08.01` works fine.

The manifest to be automatically updated in a few hours.
(see: https://github.com/ScoopInstaller/Excavator)

**Comment by r15ch13** [comment]
Should be fixed now
https://github.com/ScoopInstaller/Main/commit/43ba6cdbd6b5a44a4fd2d11942c6f8c89cb3322a
