### ISSUE TITLE
dotnet-sdk package download link very slow

### ISSUE THREAD

**Issue by nicolaic** [ScoopInstaller/Main#2884]
## Bug Report

**Package Name:**  dotnet-sdk

### Current Behaviour

The current download link used download the dotnet SDK is extremely slow to me for some reason.

Current download link speed:
![Current download link speed](https://cdn.discordapp.com/attachments/315953498946666496/905727632904167475/unknown.png)

### Expected Behaviour

I'd expect the download speed to be close to my usual download speeds.

Alternative download link speed:
![Alternative download link speed](https://cdn.discordapp.com/attachments/315953498946666496/905728046915543120/unknown.png)

### Possible Solution

Current: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.402/dotnet-sdk-5.0.402-win-x64.zip
Alternative: https://download.visualstudio.microsoft.com/download/pr/8a504918-9508-464d-80c6-4da7f9cc9ac6/f9d6ad00bbd798bafb549101b5b4a4c0/dotnet-sdk-5.0.402-win-x64.exe

I got the alternative link directly from the official download page for the dotnet SDK. As far as I'm aware there's not really any significant difference between the two besides the delivery format (zip vs exe), and the download speeds.

### System details

**Windows version:** 20H2
**OS arch (32 or 64 bit):** 64
**PowerShell version:** 5.1.19041.1237

**Comment by rashil2000** [comment]
The zip vs exe is an important difference. Zip is a portable application.

**Comment by pratikpc** [comment]
@nicolaic can the '8a504918-9508-464d-80c6-4da7f9cc9ac6/f9d6ad00bbd798bafb549101b5b4a4c0' part in : https://download.visualstudio.microsoft.com/download/pr/8a504918-9508-464d-80c6-4da7f9cc9ac6/f9d6ad00bbd798bafb549101b5b4a4c0/dotnet-sdk-5.0.402-win-x64.exe be expected to remain the same with every new release?

If not can you extract it using checkver?

Is the exe portable with the same expected behaviour as the zip?

Could you on this basis create a PR for the same?

**Comment by rashil2000** [comment]
Older issue #2635

**Comment by nicolaic** [comment]
Hey, sorry for the long delay, I haven't logged in to my GitHub account is quite a while.


> The zip vs exe is an important difference. Zip is a portable application.

I've found this link that downloads the exact same zip as the current download, but this one downloads a lot faster for me.
Link: https://download.visualstudio.microsoft.com/download/pr/c826dbd3-e72f-46f7-a60a-8edde0e086de/aced282e985e941bfdd222781c722fe2/dotnet-sdk-5.0.402-win-x64.zip



> @nicolaic can the '8a504918-9508-464d-80c6-4da7f9cc9ac6/f9d6ad00bbd798bafb549101b5b4a4c0' part in : https://download.visualstudio.microsoft.com/download/pr/8a504918-9508-464d-80c6-4da7f9cc9ac6/f9d6ad00bbd798bafb549101b5b4a4c0/dotnet-sdk-5.0.402-win-x64.exe be expected to remain the same with every new release?
> 
> If not can you extract it using checkver?
> 
> Is the exe portable with the same expected behaviour as the zip?
> 
> Could you on this basis create a PR for the same?

I presume the part before the slash is an UUID and the second part is a hash of the download. They do not remain the same between releases, I can confirm that much.

I'm not familiar with `checkver` but it seems pretty simple. If you take the current URL used in `checkver` for the `dotnet-sdk` config, and look at the JSON for the releases, each version has a link to another JSON file which has a lot more information, including the link I posted above.

I can't easily tell what the `checkver` regex does, but if you can explain what it's supposed to do, I can craft a new regex for you if needed. As for the auto-update functionality, I'm not entirely sure if that's easy or even possible at with with how scoop currently works.

Currnet link: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
Release link: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json

**Comment by rashil2000** [comment]
Are you familiar with PowerShell? The checkver supports a `script` field that can be used to run arbitrary commands. You can fetch the 2 JSON files from there, and then output the version and links.

**Comment by nicolaic** [comment]
No, sorry. I've never worked with writing PowerShell scripts before, but I reckon it should be quite simple to learn enough to write a script for extracting the information. What information does the script need to return, and does it have to be in a specific format?

**Comment by rashil2000** [comment]
The script needs to return the current version, and URLs for 32 and 64bit zip files. This output will be captured by regex. @tech189 recently wrote one for Inkscape, see https://github.com/ScoopInstaller/Extras/pull/7586/files.

**Comment by tech189** [comment]
Being able to run a script is very useful but I recommend writing it first in a separate `.ps1` file for debugging, then once you have the output you need, dump that into [regex101](regex101.com) to compose the regex with variables so then you can `$match` them in the autoupdate section. Make sure the first letter of the `$match` is a capital letter (e.g. “W” in`$matchWin32bit`)!

**Comment by rashil2000** [comment]
Closing this as stale
