### ISSUE TITLE
NMAP 7.92 won't install due to requiring OEM license

### ISSUE THREAD

**Issue by JustinGrote** [ScoopInstaller/Main#2886]
## Bug Report

**Package Name:** nmap

### Current Behaviour

![image](https://user-images.githubusercontent.com/15258962/140374858-1052a5bb-bbd1-4e0c-a64c-e0728bd4675a.png)

### Expected Behaviour

Installs

### Additional context/output

Started requiring OEM license for silent installs

### Possible Solution

Pin to version prior to OEM license being required, otherwise warn that it must be installed manually.

### System details

**Windows version:** [PLACEHOLDER]
**OS arch (32 or 64 bit):** [PLACEHOLDER]
**PowerShell version:** [PLACEHOLDER]
**Additional software:** [PLACEHOLDER]

**Comment by rashil2000** [comment]
This is a dup of #1465
