### ISSUE TITLE
URL for libopenssl is not valid

### ISSUE THREAD

**Issue by pasuder** [ScoopInstaller/Main#2887]
For command `scoop install openssh` it fails on downloading `libopenssl` with information `URL ... is not valid`:

![scoop install openssh url is not valid](https://user-images.githubusercontent.com/3436085/140476860-8e8b3f21-e837-4025-a672-99d639a5cca9.png)

https://github.com/ScoopInstaller/Main/blob/30dde179f8a7407fc35c3e5a338eb01f19001fbf/bucket/openssh.json#L21

`scoop update` was run in prior to `scoop install openssh`

It was mentioned by @github-actions[bot] in https://github.com/ScoopInstaller/Main/issues/2883#issuecomment-960163437

**Comment by rashil2000** [comment]
Dup #1769
