### ISSUE TITLE
Suggest change git from portable to setup

### ISSUE THREAD

**Issue by wentong-wow** [ScoopInstaller/Main#2894]
## Package Request
- git

### Why
I have install git to gitlab ci runner with main bucket. However, gitlab ci runner execute job will be stucked and timeout at:

> created fresh repository.

It was because portable has default config will cause git always popup to ask for user credentials when fetch. After I try to install by setup, everything is OK. So I suggest to change git from portable to setup. Thanks.

P.S. this issue take me a lots of time to debug. QQ

### Suggested App Manifest
``` json
{
    "version": "2.33.1.windows.1",
    "description": "Distributed version control system",
    "homepage": "https://gitforwindows.org",
    "license": "GPL-2.0-only",
    "architecture": {
        "64bit": {
            "url": "https://github.com/git-for-windows/git/releases/download/v2.33.1.windows.1/Git-2.33.1-64-bit.exe",
            "hash": "b1b69fcf56d50199536f7e6fc79b75ab16734d4d9a4b85c8e931596f02dd0688"
        },
        "32bit": {
            "url": "https://github.com/git-for-windows/git/releases/download/v2.33.1.windows.1/Git-2.33.1-32-bit.exe",
            "hash": "bc2ca8f6ffcc6914ed04cfb13b2d0b6b994bd2437283cb3b43188b969bd5ef8b"
        }
    },
    "bin": [
        "cmd\\git.exe",
        "cmd\\gitk.exe",
        "cmd\\git-gui.exe",
        "usr\\bin\\tig.exe",
        "git-bash.exe"
    ],
    "installer": {
        "args": [
            "/DIR=$dir",
            "/SILENT"
        ]
    },
    "shortcuts": [
        [
            "git-bash.exe",
            "Git Bash",
            "--cd-to-home"
        ],
        [
            "cmd\\git-gui.exe",
            "Git GUI"
        ]
    ],
    "env_set": {
        "GIT_INSTALL_ROOT": "$dir"
    },
    "checkver": {
        "github": "https://github.com/git-for-windows/git",
        "regex": "v([\\w.]+)/Git-(?<full>[\\w.]+)-64-bit"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/git-for-windows/git/releases/download/v$version/Git-$matchFull-64-bit.exe"
            },
            "32bit": {
                "url": "https://github.com/git-for-windows/git/releases/download/v$version/Git-$matchFull-32-bit.exe"
            }
        },
        "hash": {
            "url": "https://github.com/git-for-windows/git/releases/tag/v$version",
            "regex": "<td>$basename</td>\\s*<td>$sha256</td>"
        }
    }
}
```

**Comment by rashil2000** [comment]
How about creating a different manifest called git-full or something.

What are the differences between the Setup and Portable version? (sorry I don't use Git installed via scoop).

**Comment by rasa** [comment]
Instead of replacing git, we could add this as `git-installer.json`. Submit a PR?

**Comment by rasa** [comment]
> How about creating a different manifest called git-full or something.

Both the portable and setup versions install the full git. So I would suggest not using `git-full`.

 I would prefer `git-installer`, `git-setup`, `git-alt`, or something similar.

**Comment by rashil2000** [comment]
git-setup would be good then.

But what's the difference between them then 🤔

**Comment by rasa** [comment]
The setup/installer asks the user about 10 questions (unless `/SILENT` is used), and then writes to the registry.

**Comment by pratikpc** [comment]
Maybe non-portable bucket would be useful?

git-np would work well.

Should the setup be here on Main or there?

**Comment by rashil2000** [comment]
> Maybe non-portable bucket would be useful?
> 
> git-np would work well.
> 
> Should the setup be here on Main or there?

I like this idea of putting in np bucket - since the setup will be modifying registry - will it remain portable?

**Comment by wentong-wow** [comment]
> git-setup would be good then.
> 
> But what's the difference between them then 🤔

Hi @rasa ,

Key different is `credential.helper` in system config `etc/gitconfig` between them. Portable is `helper-selector`. Setup is `manager-core`.

Refer to gitlab runner source code, the repository url will be init by `http` so that runner execute git fetch/pull/push need `credential.helper`. The `helper-selector` means always popup for asking credential so that gitlab runner will be stuck in `created fresh repository`.

Maybe we can add post script to change portable's `credential.helper` to `manager-core` for solving this issue.

### Reference
- [manager-core](https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/configuration.md) is suggested credential.helper for Windows

**Comment by rashil2000** [comment]
> Maybe we can add post script to change portable's credential.helper to manager-core for solving this issue.

This was actually the case previously, but it was removed in https://github.com/ScoopInstaller/Main/pull/2200


Since this uses a Setup installer and modifies registry, I would suggest making a manifest called git-np.json and sending a PR to https://github.com/TheRandomLabs/scoop-nonportable

**Comment by wentong-wow** [comment]
> Since this uses a Setup installer and modifies registry

Could you give me more information what's impact if registry was modified?  I'm just curious. Thanks.

**Comment by pratikpc** [comment]
When it comes to portable apps @wentong-wow we usually prefer that the app should work even if you copy paste it from 1 PC to another

For example if you install Git on a pen drive, if Git was a portable app the expectation is that it would work on every machine you take it to without requiring installations.

But if registry values are modified, it becomes a difficult right?

So we usually prefer to err on the side of caution.

**Comment by rashil2000** [comment]
Perfect explanation @pratikpc!

**Comment by rasa** [comment]
Please see
https://github.com/ScoopInstaller/Main/search?q=git+credential&type=issues
for related discussions.
Also see 
https://github.com/ScoopInstaller/Main/commit/6cb380afd011e0c7396381963e80ad75143e33c0#diff-ee5c7dea359dcb2d038cbeb23fb76e2b3f227926b6c0548a167bd6d63fd6f61c

While I don't support changing [git.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/git.json) to run a setup/installer, I would support fixing it, so it doesn't annoy users with unnecessary prompts.

Or at the very least, providing a `git-manager-core.json` package, or a modified git package (say `git-with-credential-manager-core.json`?) that sets `credential.helper` to `manager-core`.

**Comment by dwettstein** [comment]
The issue back then was that the `post_install` task has overwritten an existing user config. Thus it has been removed.

So actually, this prompt only occurs if the user doesn't have a `.gitconfig` file containing the `credential.helper` setting. If this is the case, one can easily get rid of the prompt by selecting _Always use this from now on_, which will write the selected option to the config file.

**Comment by wentong-wow** [comment]
I prefer @rasa suggeustion to add option `git-manager-core.json` because git setup default set manager core as credential.helper.

**Comment by rashil2000** [comment]
Yes, but anything that involves an installer modifying registry keys shouldn't be in the main bucket (there are exceptions where users can manually run .reg files, but that's not the case here)

**Comment by dwettstein** [comment]
What if we just add a note that will be shown:

```
"notes": "Set Git Credential Manager Core by running: \"git config --global credential.helper manager-core\"",
```

See PR https://github.com/ScoopInstaller/Main/pull/2902

**Comment by chawyehsu** [comment]
I'm trying to find a good way to avoid the annoying CredentialHelperSelector pop-up every time getting git updated. Then I read your (@dwettstein ) comment:

> So actually, this prompt only occurs if the user doesn't have a .gitconfig file containing the credential.helper setting. If this is the case, one can easily get rid of the prompt by selecting Always use this from now on, which will write the selected option to the config file.

In fact, the gitcredentials loading strategy is not the way you said. From the [git-scm doc](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-helper):

> **helper**
> The name of an external credential helper, and any associated options. If the helper name is not an absolute path, then the string `git credential-` is prepended. The resulting string is executed by the shell (so, for example, setting this to `foo --option=bar` will execute `git credential-foo --option=bar` via the shell. See the manual of specific helpers for examples of their use.
> If there are multiple instances of the `credential.helper` configuration variable, each helper will be tried in turn, and may provide a username, password, or nothing. Once Git has acquired both a username and a password, no more helpers will be tried.
> If `credential.helper` is configured to the empty string, this resets the helper list to empty (so you may override a helper set by a lower-priority config file by configuring the empty-string helper, followed by whatever set of helpers you would like).

**If there are multiple instances of the `credential.helper` configuration variable, each helper will be tried in turn.** 

This is how git actually find the `credential.helper`. It will do a top-down try of all `credential.helper`, first the system-wide one (`/etc/gitconfig`), then the global one (`~/.gitconfig`),  and last the local one.

My global config `~/.gitconfig` did have a `credential.helper` setting, which is set by the note `git config --global credential.helper manager-core`. Although I've selected the `Always use this from now on`, the CredentialHelperSelector still shows up, since every time the git package updates the system-wide config `/etc/gitconfig` gets reset with the `helper-selector` `credential.helper`.

The notes does not help.

There are two different ways to fix.

- persist the system-wide config file `/etc/gitconfig`, so it will not be reset when updating.
- unset the system-wide `credential.helper` by doing a `git config --system --unset credential.helper` post_install, which makes git always try the global config first.
