### ISSUE TITLE
imagemagick@7.1.0-13: decompress error

### ISSUE THREAD

**Issue by pdcxs** [ScoopInstaller/Main#2900]

**Comment by rashil2000** [comment]
Not reproducible

**Comment by rashil2000** [comment]
What is the output of `scoop config SCOOP_REPO`?

**Comment by pdcxs** [comment]
> What is the output of `scoop config SCOOP_REPO`?

The output is: `https://github.com/lukesampson/scoop`

**Comment by pdcxs** [comment]
It should be a network problem. I clear the cache and re-install it, all works fine. Thanks.
