### ISSUE TITLE
[Request] mpg123

### ISSUE THREAD

**Issue by bottle2** [ScoopInstaller/Main#2909]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [X] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool
- [X] the latest stable version of the program
- [X] the full version i.e. not a trial version
- [ ] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

I don't know how the installation works and afaik it's not a developer tool. But I'd appreciate a lot if I could install it from scoop.

### Information

**Name:** mpg123

**Description:** Fast console MPEG Audio Player and decoder library

**Homepage:** https://mpg123.de/

**Download link(s):** Check the section "Win32 and Win64 binaries" at https://mpg123.de/download.shtml

**Some indication of popularity/repute:** Check the section "Misc. programs and modules based on mpg123" at https://mpg123.de/links.shtml, and it was rated 5 stars in 26 of 27 reviews at its [SourceForge page](https://sourceforge.net/projects/mpg123/)

**Comment by bottle2** [comment]
Sorry, I was anxious to use it, but turns out its console interface is broken. I'll see what's the problem and reopen if it is fixed.

**Comment by rashil2000** [comment]
#3207
