### ISSUE TITLE
[Request] ryzenadj

### ISSUE THREAD

**Issue by diklios5768** [ScoopInstaller/Main#2916]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information
**Name:**: ryzenadj

**Description:**: Adjust power management settings for Ryzen Mobile Processors.

**Homepage:**: https://github.com/FlyGoat/RyzenAdj

**Download link(s):**: https://github.com/FlyGoat/RyzenAdj/releases
https://github.com/FlyGoat/RyzenAdj/releases/tag/v0.8.2

**Some indication of popularity/repute:**: 649 stars on Github

**Comment by rashil2000** [comment]
Why did you remove checkboxes? Please edit your post to fill out the complete issue form. Incomplete forms will be closed.

**Comment by diklios5768** [comment]
> Why did you remove checkboxes? Please edit your post to fill out the complete issue form. Incomplete forms will be closed.

Okay, first time to use it. What about use a robot to remind? There are many requests also incomplete.

**Comment by rashil2000** [comment]
There's already a bot present, it reminds after 14 days
