### ISSUE TITLE
Personal gVim configuration can get stomped by install settings

### ISSUE THREAD

**Issue by ludovicchabant** [ScoopInstaller/Main#2920]
## Bug Report

**Package Name:** vim-nightly  (and I assume vim also has the same problem)

### Current Behaviour

On install, Scoop copies example configuration files (see https://github.com/ScoopInstaller/Main/blob/master/bucket/vim-nightly.json#L29)

This means that if you don't have a file named `$HOME/_gvimrc`, gVim will find the one from the install directory. This file is a copy of `gvimrc_example.vim`, and among other things it sets some "nice colors".

The problem is that I set my color scheme in `$HOME/_vimrc` (note the lack of "g"). Some of these colors were getting messed up on startup, resulting in a gVim UI that looked all wrong. This was caused by the above "nice colors" set by the installation's `$VIMRUNTIME/_gvimrc`.

### Expected Behaviour

The `gvimrc_example.vim` is just an example file. It's not meant to be loaded, and it's not loaded in Linux/Unix. Scoop copying it to `_gvimrc` on Windows means it gets loaded by gVim on startup if no other similarly-named file is found in a higher priority directory. This shouldn't happen, since this file can mess up settings defined in one's personal configuration files, and since it's only meant to be an example.

### Additional context/output

None.

### Possible Solution

Scoop should copy the example file to, say, `_gvimrc_example`. Or maybe not even copy it at all since the original example file is perfectly easy to find. I'm not sure why these files are copied and renamed.

My work around (after I figured out the problem), was to simply create an empty `$HOME/_gvimrc` (note the "g") so that gVim wouldn't load the one from the install directory.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1237

**Additional software:** n/a

**Comment by rashil2000** [comment]
Hey @ludovicchabant, thanks for the detailed report!

Would you like to contribute a fix?

**Comment by ludovicchabant** [comment]
I could contribute a fix, assuming the fix is indeed to remove the two lines that copy the example config files?

**Comment by rashil2000** [comment]
Yes

**Comment by rashil2000** [comment]
@ludovicchabant any update?

**Comment by tech189** [comment]
`vim-nightly` has been moved to the Versions bucket and the lines that copy the example files are here: https://github.com/ScoopInstaller/Versions/blob/70ee2a6059609290fa81b984161cbc310eb7aec8/bucket/vim-nightly.json#L40

`vim` is in the Main bucket (this repo) and the lines to be removed are here: https://github.com/ScoopInstaller/Main/blob/701f3226b70f5f60ccd7d8baa92a40369599e9b6/bucket/vim.json#L28
