### ISSUE TITLE
Remove all references to oraclejdk from main

### ISSUE THREAD

**Issue by pratikpc** [ScoopInstaller/Main#2927]
There are a lot of packages where suggests references java/oraclejdk but java/oraclejdk has been removed due to issues.

It would be nice if someone could create a PR with all references removed.

**Comment by pratikpc** [comment]
We would prefer if we could get new contributors for example.

All you have to do is remove oraclejdk references.

**Comment by amreus** [comment]
Remove or suggest some alternative?

If alternative, which?

**Comment by rashil2000** [comment]
Remove, for now
