### ISSUE TITLE
[Request] Help us to update all MSYS packages to their latest ZSTD versions

### ISSUE THREAD

**Issue by pratikpc** [ScoopInstaller/Main#2933]
We are working on ZSTD support currently and it might get released in a while and by then, we hope all packages will be ready for release.

We need your help to update them all to their latest ZSTD versions

**Comment by niheaven** [comment]
Emm, zstd support is only in `develop`, so this should wait for a while.

**Comment by pratikpc** [comment]
@niheaven yeah

I think we can get the PRs ready by then so we can help release ZSTD supported packages while we can work on and fix the PRs.

Might make the release easier

Thoughts?

**Comment by niheaven** [comment]
And what's your experience with `develop`'s new commits? Any problem or error?

**Comment by pratikpc** [comment]
ZSTD support works for me

**Comment by rashil2000** [comment]
ZSTD works for me too (tried with the PR for openssh).

Is there a way to test the multiple-URLs in autoupdate functionality?

**Comment by niheaven** [comment]
Use lua in main bucket，or some manifests that I attached in that PR.

**Comment by rashil2000** [comment]
I'll past my reply from #2967 here:

> I agree that this might be a breaking change - for that we can redirect users to the Versions bucket as @niheaven said.
> 
> However, I strongly believe Scoop should not be used to download MSYS2 packages - from a maintenance perspective, it's impossible to keep track of individual versions of the 15-20 different download URLs there. Pacman (widely touted as the most respected package manager out there) in MSYS2 handles dependency trees beautifully; if people need MSYS2 tools they should use it.
> 
> It's a similar argument to why Scoop isn't (and shouldn't be) used to download/manage NPM packages, or PIP packages - these are far better managed by their respective package managers.
> 
> If applications provide standalone builds (like this WinLibs does), we can use it freely and the manifest will even get autoupdated.
> 
> One more problem - currently we have around 10 different manifests in Main which individually download the MSYS2 Runtime - this leads to unnecessary bloat. It might also cause inter-compatibility if someone uses tools from different runtime versions - for example openssh and diffutils.

**Comment by rashil2000** [comment]
List of packages using MSYS2 repos:
- diffutils
- openssh
- gdb

List of packages using MSYS repos (these should ideally be deprecated or updated to use other sources - it's a security risk to keep 8-10 year old packages in Main):
- telnet (who still uses this in 2021???)
- tar
- findutils
- coreutils
- gzip
- patch

**Comment by rashil2000** [comment]
For GDB and related and Binutils, we can use http://win-builds.org - standalone, clean packages with version numbers so that manifests can be autoupdated. 

I'm a bit busy this week, but I'll try updating/finding the sources for others from next week.

**Comment by rashil2000** [comment]
> > * telnet (who still uses this in 2021???)
> 
> Is there any other way to test network protocols by hand? 😄

I was merely concerned with the security implications of using a very old technology - if you can point us to regularly maintained telnet sources, we'll update the manifest :)

**Comment by issaclin32** [comment]
>  * telnet (who still uses this in 2021???)

By the way, actually a few big bulletin board websites in Japan and Taiwan are still using **telnet**. Most use third-party tools like *Pietty*(`extras/pietty`), *MobaXTerm*(`extras/mobaxterm`) or *JPTT*(an Android app) to access these sites.

**Comment by rashil2000** [comment]
Okay, I apologize, I have edited my comment. Is there an up-to-date source for telnet we can use?

**Comment by issaclin32** [comment]
> Okay, I apologize, I have edited my comment. Is there an up-to-date source for telnet we can use?

No need to apologize. It's just some discussion IMO. But we should definitely avoid [something like this](https://github.com/ScoopInstaller/Main/pull/624#discussion_r353181860).:sweat_smile:

I think the best way to support **telnet** is to use the official binary from Microsoft.

It can be installed from the Control Panel, or by: `dism /online /Enable-Feature /FeatureName:TelnetClient`
However this requires **admin rights**, so we might better add a non-portable package for this.

**Comment by rashil2000** [comment]
The problem is, telnet binary provided by Microsoft is extremely outdated. Then there's [puttytel](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html), but it's a GUI app.

**Comment by issaclin32** [comment]
If we are providing `telnet`, I think the priority is to give users what they expect to have. (rather than an implementation that acts differently)

Microsoft's binary is outdated, and it has problems supporting newer UTF-8 standards (a big issue for Chinese/Japanese users who uses ASCII art), but I still think it's the implementation we should provide. If the user need a newer implementation, they can just go ahead and use **MobaXTerm** or something else.

On the other hand, I don't think MSYS's version will have a better support. It will not be "actually updated" for obvious reasons.

In terms of security, I think it's fine to use an old telnet **client**, as long as it has no inbound connections.

**Comment by rashil2000** [comment]
> Microsoft's binary is outdated, and it has problems supporting newer UTF-8 standards (a big issue for Chinese/Japanese users who uses ASCII art). 

Yes, you summarized it perfectly!

> , but I still think it's the implementation we should provide

If it's already present in Windows (and we just need to enable it), then I don't think we need a manifest for it, right? Other than that, the current manifest for telnet is still a newer version than Microsoft's, so I think we can let it remain as it is.
