### ISSUE TITLE
[Request] Add BaiduPCS-Go

### ISSUE THREAD

**Issue by AlexaraWu** [ScoopInstaller/Main#2939]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** baidupcs-go

**Description:** Terminal utility for Baidu Network Disk

**Homepage:** https://github.com/qjfoidnh/BaiduPCS-Go

**Download link(s):** https://github.com/qjfoidnh/BaiduPCS-Go/releases/latest

**Some indication of popularity/repute:** GitHub 880 stars

**Comment by issaclin32** [comment]
This package cannot be accepted in official buckets. See https://github.com/ScoopInstaller/Main/pull/2938#issuecomment-966830432 for reasons.
