### ISSUE TITLE
curl@7.80.0: download via aria2 failed

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Main#2940]
Updating 'curl' (7.79.1_4 -> 7.80.0)
Downloading new version
Starting download with aria2 ...
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://curl.haxx.se/windows/dl-7.80.0/curl-7.80.0-win64-mingw.tar.xz
    referer=https://curl.haxx.se/windows/dl-7.80.0/
    dir=C:\Users\<user>\scoop\cache
    out=curl#7.80.0#https_curl.haxx.se_windows_dl-7.80.0_curl-7.80.0-win64-mingw.tar.xz

ERROR & 'C:\Users\<user>\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\<user>\scoop\cache\curl.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9196 --continue --summary-interval 0 --show-console-readout=false --download-result=hide --max-overall-download-limit=3M

**Comment by AntonOks** [comment]
grrr....

works after
```
λ  scoop config aria2-enabled false
'aria2-enabled' has been set to 'false'
```

**Comment by rashil2000** [comment]
The links are accessible through browser and Scoop (without aria). So this is resolved now?

**Comment by AntonOks** [comment]
> The links are accessible through browser and Scoop (without aria). So this is resolved now?

As I wrote, works once you disable Aria2... no idea if others have the same problem and if so, whats special with the curl download site so that Aria2 stumbles here :|

**Comment by rashil2000** [comment]
Honestly, no idea, but there's a giant-ass warning when using aria 😂, so I presume unknown problems are to be expected
