### ISSUE TITLE
[Request] Nekofetch

### ISSUE THREAD

**Issue by justanobody2107** [ScoopInstaller/Main#2975]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool (somewhat)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** nekofetch

**Description:** This is winfetch, but it uses catgirls as distro icon instead of the regular Windows 10/11 icon.

**Homepage:** https://github.com/justanobody2107/public-projects/tree/main/nekofetch

**Download link(s):** https://github.com/justanobody2107/public-projects/blob/main/nekofetch/v1.0.0/nekofetch.ps1

**Some indication of popularity/repute:** 1 star on GitHub repo, very popular package from a developer named [Boba](https://github.com/BBaoVanC), which has since been deleted for personal reasons. This is simply the Windows port of it.

**Comment by amreus** [comment]
This is a wrapper script for `winfetch` that downloads and displays an alternate image. It does not meet the criteria for the Main repo.

This is the entire script:

```
$url = ((iwr https://nekos.life/api/v2/img/neko).Content | ConvertFrom-Json).url
iwr $url -OutFile neko.jpg
winfetch -image neko.jpg
Remove-Item neko.jpg
```

**Comment by rashil2000** [comment]
@amreus is right. 

@justanobody2107 if people want this, they can simply create a function for it in their $Profile.

I'm going to close this and the PR.
