### ISSUE TITLE
[Request] nuwen gcc

### ISSUE THREAD

**Issue by pratikpc** [ScoopInstaller/Main#2977]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** Nuwen's MinGW Distro

**Description:** MinGW distro with Boost, GCC etc.

**Homepage:** https://nuwen.net/mingw.html

**Download link(s):** https://nuwen.net/files/mingw/mingw-18.0-without-git.exe

**Some indication of popularity/repute:** It's pretty well known when it comes to C++ development on Windows.

**Comment by rashil2000** [comment]
Nice!

In a similar fashion, we can rename the current gcc.json manifest to winlibs-mingw.json. As discussed, we'll add standalone isolated tools for gcc, gdb, make, binutils etc. separately.

**Comment by pratikpc** [comment]
@rashil2000 that could be a bit of a headache for most users.

People usually expect to install GCC and get access to GDB, make etc.

**Comment by rashil2000** [comment]
The current gcc.json manifest is much more than though (as we discussed in that thread) 😅

> People usually expect to install GCC and get access to GDB, make etc.

That's technically a false expectation though. On Linux too, you get this collection of tools when you install packages like `base-devel` (and not just `gcc`).

We are making a breaking change anyway (well, not really), why not do it correctly and set a standard?

**Comment by pratikpc** [comment]
@rashil2000 I mean we are on Windows and given the primary source of GCC is MinGW-w64 who always ship with these utilities present so it could be a bit of a headache for users to transition to the new way is a worry for me.

I think it works for Debian and Fedora family thanks to the devel like packages which allow you to install a lot of dependencies at once. The uninstalls would be a headache though

**Comment by rashil2000** [comment]
In that case we don't need to do anything extra then.

My main nit was that currently the gdb.json, make.json etc. all are pulling from different (and incompatible) sources (and the `make` in make.json doesn't even work). I was hoping to streamline and update all the sources (along with gcc.json itself) to get rid of the frustration.

**Comment by pratikpc** [comment]
I think its a great idea and can be done for packages other than GCC.

For example, a user might need standalone GDB in their path but at the same time not want to install GCC.

Same goes for make etc.

**Comment by pratikpc** [comment]
If we add it for GCC, then the manifest will be full of depends though.

GCC sort of needs to be a devel like package for Scoop

**Comment by rashil2000** [comment]
> If we add it for GCC, then the manifest will be full of depends though.

I don't think so. I'll see what can be done.

> GCC sort of needs to be a devel like package for Scoop

Sadly, yes. But the nuwen-gcc and winlibs-gcc are exactly that :) So it's a step in the right direction.

BTW, the sources with which I was planning to update gcc, gdb, make, binutils is win-builds.org, which is one of the official sources of MinGW-w64 according to their website - https://www.mingw-w64.org/downloads/#win-builds

**Comment by pratikpc** [comment]
> So it's a step in the right direction.

Yeah but like I am worried about broken workflows to be honest.

Personally I am of the opinion that Scoop should be sort of server grade so as to make it easier for IT companies to use Scoop to install and update all portable packages that Scoop can support.
