### ISSUE TITLE
scoop install kafka failed.

### ISSUE THREAD

**Issue by lijian12345** [ScoopInstaller/Main#2987]
Log as following:
Installing 'kafka' (3.0.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 836bc3|OK  |   2.1MiB/s|C:/Users/lijian/scoop/cache/kafka#3.0.0#https_www.apache.org_dist_kafka_3.0.0_kafka_2.12-3.0.0.tgz
Download: Status Legend:
Download: (OK):download completed.
Checking hash of kafka_2.12-3.0.0.tgz ... ok.
Extracting kafka_2.12-3.0.0.tgz ... done.
Linking ~\scoop\apps\kafka\current => ~\scoop\apps\kafka\3.0.0
Creating shim for 'connect-distributed'.
Creating shim for 'connect-standalone'.
Creating shim for 'kafka-acls'.
Creating shim for 'kafka-broker-api-versions'.
Creating shim for 'kafka-configs'.
Creating shim for 'kafka-console-consumer'.
Creating shim for 'kafka-console-producer'.
Creating shim for 'kafka-consumer-groups'.
Creating shim for 'kafka-consumer-perf-test'.
Creating shim for 'kafka-delegation-tokens'.
Creating shim for 'kafka-dump-log'.
Creating shim for 'kafka-mirror-maker'.
Creating shim for 'kafka-preferred-replica-election'.
Can't shim 'bin\windows\kafka-preferred-replica-election.bat': File doesn't exist.

So where is kafka-preferred-replica-election.bat?

**Comment by pratikpc** [comment]
It was deprecated

https://issues.apache.org/jira/browse/KAFKA-8405
