### ISSUE TITLE
aws-sam-cli@1.35.0: decompress error

### ISSUE THREAD

**Issue by rahulchaudharyofficial** [ScoopInstaller/Main#2997]

**Comment by rahulchaudharyofficial** [comment]
![image](https://user-images.githubusercontent.com/1083982/142929759-01daf336-d1fc-4229-a455-c3ec8339b152.png)

**Comment by rahulchaudharyofficial** [comment]
[msi.log](https://github.com/ScoopInstaller/Main/files/7584115/msi.log)

**Comment by tech189** [comment]
Can confirm, I think it's to do with the fact that the length of that file path exceeds Windows' limit of 260 characters. You could install scoop at the root directory of a disk drive to gain some characters. Or maybe you could give [this](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) a go?

**Comment by mastazi** [comment]
On my system, LongPathsEnabled was already `1` but I have experienced the same error as @rahulchaudharyofficial - so unfortunately the workaround suggested by @tech189 did not work for me. 

Windows 11 Pro 22000.318
PowerShell 7.2.0
Windows Terminal 1.11.2921.0

**Comment by rashil2000** [comment]
See #2775
