### ISSUE TITLE
[Request] Update 7-Zip package to latest stable version 21.05

### ISSUE THREAD

**Issue by kborowinski** [ScoopInstaller/Main#3005]
## Package Request

Update 7zip package to latest stable version **21.05**:
https://www.7-zip.org/download.html

### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** [name of new package]
7-Zip

**Description:** [clear and concise details of what it is]
7-Zip is a file archiver with a high compression ratio

**Homepage:** [a URL/link]
https://www.7-zip.org/

**Download link(s):** [URL(s)/link(s)]
https://www.7-zip.org/download.html

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by HUMORCE** [comment]
no msi installer released yet.

**Comment by rashil2000** [comment]
Looks like the exe is an archive, we can use that itself? Or will it cause problems for new Scoop users?

**Comment by HUMORCE** [comment]
@rashil2000 
https://sourceforge.net/p/sevenzip/discussion/45797/thread/edcb38bbab/

**Comment by Valinor** [comment]
did you talk about 7zip.json. The version in main is 21.06.

![image](https://user-images.githubusercontent.com/2079654/143546854-086abd9b-98b4-464a-8e02-82c6675c18b3.png)
