### ISSUE TITLE
7zip@21.06: download via aria2 failed

### ISSUE THREAD

**Issue by teddue** [ScoopInstaller/Main#3022]
Installing '7zip' (21.06) [64bit]
Starting download with aria2 ...
Download:   -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error: Die Sperrfunktion konnte die Sperrung Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: beddce|ERR |       0B/s|C:/Users/username/scoop/cache/7zip#21.06#https_7-zip.org_a_7z2106-x64.msi
Download: 7e49cf|OK  |       0B/s|C:/Users/username/scoop/cache/7zip#21.06#https_raw.githubusercontent.com_ScoopInstaller_Main_master_scripts_7-zip_uninstall-context.reg
Download: 1c8a02|OK  |       0B/s|C:/Users/username/scoop/cache/7zip#21.06#https_raw.githubusercontent.com_ScoopInstaller_Main_master_scripts_7-zip_install-context.reg
Download: Status Legend:
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://7-zip.org/a/7z2106-x64.msi
    referer=https://7-zip.org/a/
    dir=C:\Users\username\scoop\cache
    out=7zip#21.06#https_7-zip.org_a_7z2106-x64.msi
https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/7-zip/install-context.reg
    referer=https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/7-zip/
    dir=C:\Users\username\scoop\cache
    out=7zip#21.06#https_raw.githubusercontent.com_ScoopInstaller_Main_master_scripts_7-zip_install-context.reg
https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/7-zip/uninstall-context.reg
    referer=https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/7-zip/
    dir=C:\Users\username\scoop\cache
    out=7zip#21.06#https_raw.githubusercontent.com_ScoopInstaller_Main_master_scripts_7-zip_uninstall-context.reg

ERROR & 'C:\Users\username\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\username\scoop\cache\7zip.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8172 --continue --summary-interval=0 --auto-save-interval=1

**Comment by rashil2000** [comment]
Have you tried with aria2 disabled?

**Comment by xyl23333** [comment]
> Have you tried with aria2 disabled?

I've tried. But the issue still remains even if Aria2 is disabled.

**Comment by niheaven** [comment]
7-zip.org is blocked in some country (e.g., Russia), Please download `7z2106-x64.msi` from other website and rename to `7zip#21.06#https_7-zip.org_a_7z2106-x64.msi` (for 32bit, rename it accordingly) and put it in scoop's cache folder, then `scoop install 7zip`.
