### ISSUE TITLE
[Request] libvips

### ISSUE THREAD

**Issue by BasixKOR** [ScoopInstaller/Main#3030]
### Criteria

For a package to be acceptable in the Main bucket, it should be

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** libvips

**Description:** An image manipulation library and command-line tool.

**Homepage:** https://www.libvips.org/

**Download link(s):** https://github.com/libvips/build-win64-mxe/

**Some indication of popularity/repute:** It is used by a popular NPM package `sharp`.

## Note

I have a working package ready on my fork: https://github.com/BasixKOR/Main/blob/libvips/bucket/libvips.json

Since there are `libwebp` available on the main, I think this deserves its place in the main too.

**Comment by BasixKOR** [comment]
The real blocker here is that for now libvips omits their minor version in its zip file folder, which makes setting `extract_dir` hard.

**Comment by rashil2000** [comment]
You can use majorVersion and minorVersion, see here - https://github.com/ScoopInstaller/Main/blob/master/bucket/julia.json

**Comment by BasixKOR** [comment]
That's very nice of you, thanks!

**Comment by BasixKOR** [comment]
It seems like `$majorVersion` is not interpolated properly:

``
Extracting vips-dev-w64-all-8.12.1.zip ... Could not find 'vips-dev-$majorVersion.$minorVersion'! (error 16)
At C:\Users\basix\scoop\apps\scoop\current\lib\core.ps1:515 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...on'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'vips-dev-$majorVersion.$minorVersion'! (error 16)
```

**Comment by rashil2000** [comment]
Can you show me the manifest?

**Comment by BasixKOR** [comment]
```
"extract_dir": "vips-dev-$majorVersion.$minorVersion",
```

I changed the manifest to change `extract_dir` like this with no other changes from the git URL above.

**Comment by rashil2000** [comment]
> ```
> "extract_dir": "vips-dev-$majorVersion.$minorVersion",
> ```
> 
> I changed the manifest to change `extract_dir` like this with no other changes from the git URL above.

This statement needs to be put inside the autoupdate section, not outside. Outside will have the `8.12` itself.
