### ISSUE TITLE
Cannot install erlang

### ISSUE THREAD

**Issue by sinni800** [ScoopInstaller/Main#3035]
When I try, this is the result:

```
C:\Users\sinni>scoop install erlang
Installing 'erlang' (23.0) [64bit]
Loading otp_win64_23.0.exe from cache
Checking hash of otp_win64_23.0.exe ... ok.
Extracting dl.7z ... done.
Running installer... error.
ERROR Exit code was -1073741515!
Installation aborted. You might need to run 'scoop uninstall erlang' before trying again.
```

Retrying by uninstalling and deleting the cache does not help.

EDIT

Running install.exe manually told me the MSVCR120.DLL is missing. The solution is to install "Microsoft Visual C++ 2013" redist. 

Can this be reported if it's missing somehow?

EDIT2: 

It does suggest that, `'erlang' suggests installing 'extras/vcredist2013'.` but this is _after_ the installation is successful, this message doesn't pop up when the install fails due to vcredist2013 missing.

So in this case, could vcredist2013 just be a dependency of erlang?

**Comment by tech189** [comment]
I can't reproduce, maybe it was fixed since. Installation succeeds without installing vcredist2013, although it looks like I have the 2010 and 2015-2019 redistributables installed already. Does it work for anyone else?

**Comment by rashil2000** [comment]
> I can't reproduce, maybe it was fixed since. Installation succeeds without installing vcredist2013, although it looks like I have the 2010 and 2015-2019 redistributables installed already. Does it work for anyone else?

Exactly the same for me

**Comment by HUMORCE** [comment]
cannot reproduce @24.2

reopen the issue if this problem still occurs.

**Comment by gp-pereira** [comment]
to anyone with this issue, try executing the .exe file downloaded by scoop directly. This will show which executable is missing as in my case it was not the one reported above

**Comment by sinni800** [comment]
I think this issue is most likely to occur if you have a *fresh* windows installation with as little stuff as possible.

I used Windows 11 LTSC here, which is super minimal for Windows installations
