### ISSUE TITLE
Can't install nmap: requires elevation + "Silent installation is only supported in Nmap OEM"

### ISSUE THREAD

**Issue by pmorch** [ScoopInstaller/Main#3037]
If I try to install nmap *without* elevation, I get:

```
Scoop was updated successfully!
Installing 'nmap' (7.91) [64bit]
Loading nmap-7.91-setup.exe from cache
Checking hash of nmap-7.91-setup.exe ... ok.
Running installer... error.
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.
```

If I then try to install it with *with* elevation, cmd run as Administrator, I get:

![image](https://user-images.githubusercontent.com/159292/110331202-19324b00-801f-11eb-8cd9-96761593b63f.png)

When I hit enter, I see this in the cmd console:

```
Running installer... error.
ERROR Exit code was 2!
Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.
```

Installing https://nmap.org/dist/nmap-7.91-setup.exe from https://nmap.org/download.html worked fine.

**Comment by rashil2000** [comment]
Closed in 3504b0cd59dcad3055d932d537e314414011e694
