### ISSUE TITLE
[Request] Sonatype - Nancy

### ISSUE THREAD

**Issue by falco467** [ScoopInstaller/Main#3041]
### Criteria
- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** nancy

**Description:** check for vulnerabilities in your Golang dependencies

**Homepage:** https://github.com/sonatype-nexus-community/nancy

**Download link(s):** https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.29/nancy-v1.0.29-windows-amd64.zip

**Some indication of popularity/repute:** 300+ GitHub Stars, Software by Sonatype to check dependencies for vulnerabilities

```
{
    "version": "1.0.29",
    "description": "check for vulnerabilities in your Golang dependencies",
    "homepage": "https://github.com/sonatype-nexus-community/nancy",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.29/nancy-v1.0.29-windows-amd64.zip"
        },
        "32bit": {
            "url": "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.29/nancy-v1.0.29-windows-386.zip"
        }
    },
    "bin": "nancy.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/sonatype-nexus-community/nancy/releases/download/v$version/nancy-v$version-windows-amd64.zip"
            },
            "32bit": {
                "url": "https://github.com/sonatype-nexus-community/nancy/releases/download/v$version/nancy-v$version-windows-386.zip"
            }
        }
    }
}
```

**Comment by rashil2000** [comment]
Can you make a PR for the same?

**Comment by falco467** [comment]
> Can you make a PR for the same?

Pull Request is open :-)
