### ISSUE TITLE
[Request] gleam

### ISSUE THREAD

**Issue by BasixKOR** [ScoopInstaller/Main#3050]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** gleam

**Description:** A Erlang-based language for building type-safe, scalable systems

**Homepage:** https://gleam.run/

**Download link(s):** https://github.com/gleam-lang/gleam/releases

**Some indication of popularity/repute:** 
* 3.4k stars on GitHub
* Active development

**Comment by BasixKOR** [comment]
The packaging would be trivial with GitHub auto-update and stuff, so I'm pretty willing to take this issue.

**Comment by rashil2000** [comment]
Go right ahead :)
