### ISSUE TITLE
Discussion: Installing Docker (CLI & engine)

### ISSUE THREAD

**Issue by JanPokorny** [ScoopInstaller/Main#3058]
# Docker on Windows

In the last years, the tooling around Docker on Windows has evolved a lot. It appears that all the current packages in Scoop for installing Docker ([`docker`](https://github.com/ScoopInstaller/Main/blob/master/bucket/docker.json) and [`docker-nightly`](https://github.com/ScoopInstaller/Versions/blob/master/bucket/docker-nightly.json)) are obsolete. The [`docker-toolbox`](https://github.com/docker-archive/toolbox) project, as well as [`docker-machine`](https://github.com/docker/machine) and [`lcow`](https://github.com/linuxkit/lcow) are deprecated and archived. I wasn't able to make either work, even though it might be a problem on my side.

The current "go-to" official way of installing Docker on Windows is [Docker Desktop](https://www.docker.com/products/docker-desktop) -- a huge monolithic GUI app with a proprietary licence forbidding its free use in companies with >250 employees. Definitely not the "Scoop way" of doing things.

## Components of Docker

Now, when I talk about Docker on Windows, there are actually three components I have in mind -- Docker CLI (`docker.exe` that can connect to any backend, local or remote), Docker Engine for Windows Containers, and Docker Engine for Linux Containers. You might think that a developer tool like Docker would extensively document installation of all the parts, quite the opposite is true -- the official documentation focuses on "just use Docker Desktop".

### Docker CLI

There is a project https://github.com/StefanScherer/docker-cli-builder, which builds `docker.exe` CLI from the latest sources. Should be easy to add into scoop.

### Docker Engine for Windows Containers

[The official documentation actually shows a way of installing this engine](https://docs.docker.com/engine/install/binaries/#install-server-and-client-binaries-on-windows) -- and it appears it consists only of unzipping it in a folder and registering and exe as a service -- also should be easy to add into scoop.

### Docker Engine for Linux Containers

The most interesting and the hardest part. Docker on Windows used to use VirtualBox in the past, but it gradually switched to Hyper-V and later WSL2 as it became available. (You might be aware that WSL2 uses Hyper-V internally. However, the WSL2 Docker backend has better performance and furthermore it runs even on Home editions of Windows where Hyper-V is not available.) WSL2 support in Docker Desktop is proprietary, even though it is known how it works -- it creates its own WSL2 distro where it runs the Linux version of Docker Engine.

There are two main possibilities (I can think of) of avoiding Docker Desktop here:

1. Install Docker Egine inside WSL and use some painful networking shenanigans to use it from the Docker CLI on Windows, [as described by Nicolas Luis on DEV.TO](https://dev.to/_nicolas_louis_/how-to-run-docker-on-windows-without-docker-desktop-hik).
2. Install [`minikube`](https://github.com/ScoopInstaller/Main/blob/master/bucket/minikube.json) which already exists as a Scoop manifest. Why Kubernetes, you might ask? As Kubernetes uses Docker Engine internally, Minikube packs one too. Minikube also supports [pretty much anything _except WSL2_](https://minikube.sigs.k8s.io/docs/drivers/) as a backend and allows exposing its internal Docker daemon using `minikube docker-env`. But as you might already guess, mounting FS and networking is complicated using this setup -- more in [this article from ITNEXT](https://itnext.io/goodbye-docker-desktop-hello-minikube-3649f2a1c469).

## What I propose

_(And by "propose" I mean "let's discuss", I don't expect anyone to do this for me.)_

- Remove current obsolete `docker` and `docker-nightly`
- Add `docker-cli`: https://github.com/StefanScherer/docker-cli-builder
- Add `docker-engine-windows`: https://download.docker.com/win/static/stable/x86_64/ (instructions: https://docs.docker.com/engine/install/binaries/#install-server-and-client-binaries-on-windows)
- Create a convenience CLI installer that goes through the process in the [DEV.TO article](https://dev.to/_nicolas_louis_/how-to-run-docker-on-windows-without-docker-desktop-hik) and basically mimics Docker Desktop -- creates a new WSL2 distro, configures it for Docker, and configures the local Docker CLI to work with it. (Make it available as `wsl-docker-installer` or something like that.)
- Finally, create a meta-manifest `docker` that installs all of the above in a seamless way. Basically the "Docker Desktop experience", but The Scoop Way™ (Yeah I know automatically creating stuff in WSL2 is not very scoopy but what can you do...)

I am interested in hearing what the community thinks of this approach. It's a shame that Scoop doesn't pack a working Docker installer, since Docker is one of the most important developer tools nowadays -- and there are ways to fix this.

**Comment by rashil2000** [comment]
Wow, thanks for writing this insanely detailed piece. Really appreciated. I'll do my best to absorb and help here.

> Remove current obsolete `docker` and `docker-nightly`

Sounds good. Add `lcow` to this too. 

> Add `docker-cli`

The archive https://download.docker.com/win/static/stable/x86_64/docker-20.10.11.zip contains a `docker.exe` too. How different is it from https://github.com/StefanScherer/docker-cli-builder? Can it not connect to remote containers and linux containers?

> Add `docker-engine-windows`

Sounds good. The '-windows' part can be dropped. All scoop apps are by default meant for Windows only :) For others, we can add a '-linux' suffix.

> Create a convenience CLI installer that goes through the process in the DEV.TO article and basically mimics Docker Desktop -- creates a new WSL2 distro, configures it for Docker, and configures the local Docker CLI to work with it.

I don't think this should be done. This is way more involved than just running a script (even if we're able to write one robust enough). Just too many variables here. And, as you said, definitely not the 'Scoop way' of doing things :p 

> Finally, create a meta-manifest docker that installs all of the above in a seamless way.

Metapackages are not supported by Scoop yet. It is something that has been requested some times in the past, and I'd personally like to see too, but as of now, it's not here.

**Comment by JanPokorny** [comment]
Yeah, you can probably tell that I'm not happy with the current state of Docker on Windows -- in general, not related to Scoop -- since due to the licence change there is no simple and free way to actually install Docker with Linux containers support. I hope Scoop can be used to solve this problem.

Oh, I have missed that they apparently now include the Docker CLI together with the Windows daemon. I tested it and it connected to a Linux container backend just fine. Perhaps it could be just one package then, `docker`, that would contain both `docker` and `dockerd` executables? Seems easier to do.

By the installer I meant basically creating a utility separate from Scoop that could be installable with Scoop. Something like `nvm` but for Docker. This part is no concern of Scoop until someone (me?) actually makes it. I suppose it will pop up around January 31 when big companies realize they have to pay for Docker Desktop now and hack something together. (And I am pretty certain I saw a meta-package -- [`vcredist`](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist.json) surely acts like one!)

Anyways, it looks like this long write-up boils down to "remove old packages and replace with a new one from https://download.docker.com/win/static/stable/x86_64/ that sadly doesn't have a Linux engine included". At least in the meantime while there is no "Scoopy" way of installing the Linux backend.

**Comment by rasa** [comment]
> Metapackages are not supported by Scoop yet. It is something that has been requested some times in the past, and I'd personally like to see too, but as of now, it's not here.

@rashil2000 If the buckets are already added, then we do support metapackages. See https://github.com/ScoopInstaller/Scoop/issues/2289#issuecomment-393768207

**Comment by rashil2000** [comment]
> Perhaps it could be just one package then, docker, that would contain both `docker` and `dockerd` executables?

Yes.

> By the installer I meant basically creating a utility separate from Scoop that could be installable with Scoop. Something like nvm but for Docker. This part is no concern of Scoop until someone (me?) actually makes it.

If a convenient installer exists for this (outside of Scoop), then yes, it can definitely be added.

> If the buckets are already added, then we do support metapackages. See ScoopInstaller/Scoop#2289 (comment)

Oh yes, I seem to have forgotten that exists. Seems reasonable to me.

**Comment by Luckz** [comment]
I tried to get a docker-cli by itself, but https://github.com/iquiw/docker-cli-binary/releases/ (scoop repo -> https://github.com/iquiw/scoop-bucket/blob/master/bucket/docker-cli.json ) didn't go so well:

![image](https://user-images.githubusercontent.com/224748/154818553-edbc458c-cfb2-4ad2-9237-3fda995bcb16.png)

**Comment by JanPokorny** [comment]
@Luckz That's an unofficial build and an unofficial bucket. If you want to install docker CLI using Scoop, use `scoop install docker` to install it from the Main bucket.

**Comment by Luckz** [comment]
> If you want to install docker CLI using Scoop, use `scoop install docker` to install it from the Main bucket.

While at it, `scoop install main/docker` for Shovel users, to avoid the nasty surprise of suddenly getting [Docker Desktop](https://github.com/Ash258/Shovel-Ash258/blob/main/bucket/docker.yml), UAC prompt and all. 🛩️

**Comment by JanPokorny** [comment]
@Luckz Shovel is also unofficial 😁

**Comment by cloud-66** [comment]
Hello, Could you please explain a little how to install and connect to docker daemon on linux. I have ubuntu 20.04  on wsl and isntalled docker in it
```
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
but there is no docker daemon in linux, Do i need to enable systemd in wsl ? this is error in wsl
![image](https://user-images.githubusercontent.com/41143306/230969725-0923e78c-1154-4d57-9e77-c952e4c31cb1.png)

installed docker by scoop and this is error in windows
![image](https://user-images.githubusercontent.com/41143306/230970083-5070fefe-b7ba-4087-9e94-cc9152362956.png)
![image](https://user-images.githubusercontent.com/41143306/230970221-9442133a-79e4-4a3d-a5a8-2c70ddcaf1b1.png)

**Comment by rashil2000** [comment]
> Do i need to enable systemd in wsl

Yes. Or just start the docker service manually.

**Comment by ROBERT-MCDOWELL** [comment]
still no chance to have access to linux container via scoop docker?

**Comment by JanPokorny** [comment]
Nowadays I recommend installing `extras/rancher-desktop` which gives you a fully functioning docker CLI, optionally even kubernetes.

**Comment by ROBERT-MCDOWELL** [comment]
docker buildx = commnand not found. does it come from its version or else?
I found this on their repo
https://github.com/rancher-sandbox/rancher-desktop/issues/3532
but it's from 2022. don't know if it's still the issue.

**Comment by JanPokorny** [comment]
Isn't buildx the default now anyways? In any case, you can try the default Docker CLI (instead of the one bundled with Rancher) with the buildx plugin, both are in main bucket and should work with Rancher.

**Comment by ROBERT-MCDOWELL** [comment]
yes it is, but apparently the scoop pkg rancher-desktop does not contain buildx. its version is 1.22, today they are 1.70 right?
how to install buildx from main? I tried scoop install buildx but not found.

**Comment by JanPokorny** [comment]
You can use the website scoop.sh to search for packages more easily 😁

**Comment by ROBERT-MCDOWELL** [comment]
completely forgot scoop website for search... :-\.

**Comment by ROBERT-MCDOWELL** [comment]
ok docker and docker-buildx installed but not possible to build linux containers?!? 
reason why rancher-desktop was ok for that. or am missing something?

**Comment by JanPokorny** [comment]
You are definitely missing something. Rancher Desktop uses WSL for Linux containers. I suggest trying Claude/Gemini/ChatGPT to debug it out.

**Comment by JanPokorny** [comment]
Try 5 maybe? Just kidding, I'll leave the discussion now, best of luck!

pá 13. 2. 2026 v 13:25 odesílatel ROBERT MCDOWELL ***@***.***>
napsal:

**Comment by ROBERT-MCDOWELL** [comment]
ok will try 5 A.i., thanks for your help... (just kidding.)
