### ISSUE TITLE
Install latex 21.12 result can't shim error

### ISSUE THREAD

**Issue by kele14x** [ScoopInstaller/Main#3066]
Hi,

I'm trying to install package `latex` using scoop, the downloading and the installer works. But after the installer finish copying the files, scoop report error **can't shim**. Here is the console log:

```text
PS C:\Users\xxx> scoop install latex
Installing 'latex' (21.12) [64bit]
Loading basic-miktex-21.12-x64.exe from cache
Checking hash of basic-miktex-21.12-x64.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\latex\current => ~\scoop\apps\latex\21.12
Creating shim for 'miktex'.
Can't shim 'texmfs\install\miktex\bin\x64\miktex-console.exe': File doesn't exist.
```
Both `scoop list` and `scoop status` report the installation is fail.

I'm using scoop on Windows 10 21H2.

**Comment by rashil2000** [comment]
Fixed in 7ad1831e849ae897552e13583a90865811dc114d

**Comment by kele14x** [comment]
I see github-action changed version back to 21.8 in https://github.com/ScoopInstaller/Main/commit/7ed7682b6bc7ca64174b519b8f8b50235c190dbe

**Comment by rashil2000** [comment]
It is possible that the devs reverted a release. We should wait for them to release 21.12 again.

**Comment by magneticflux-** [comment]
@rashil2000 21.12 was re-released, and it uses the `scoop\apps\latex\current\texmfs\install\miktex\bin\x64\miktex-console.exe` path.

@issaclin32 https://github.com/ScoopInstaller/Main/commit/7ad1831e849ae897552e13583a90865811dc114d should be reverted

**Comment by issaclin32** [comment]
> @issaclin32 [7ad1831](https://github.com/ScoopInstaller/Main/commit/7ad1831e849ae897552e13583a90865811dc114d) should be reverted

Done. Thanks for the info.

**Comment by magneticflux-** [comment]
Confirmed working again!
```
Installing 'latex' (21.12) [64bit]
Loading basic-miktex-21.12-x64.exe from cache.
Checking hash of basic-miktex-21.12-x64.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\latex\current => ~\scoop\apps\latex\21.12
Creating shim for 'miktex'.
Creating shortcut for MiKTeX Console (miktex-console.exe)
Persisting texmfs\config
'latex' (21.12) was installed successfully!
```
