### ISSUE TITLE
[Request] Add htmlq

### ISSUE THREAD

**Issue by BasixKOR** [ScoopInstaller/Main#3073]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** htmlq

**Description:** Like jq, but for HTML.

**Homepage:** https://github.com/mgdm/htmlq

**Download link(s):** https://github.com/mgdm/htmlq/releases/tag/v0.3.0

**Some indication of popularity/repute:** I think 5.2k stars are more than enough.

**Comment by BasixKOR** [comment]
I think I'll likely take this issue, but please feel free to take this issue if you're willing to do this!

**Comment by rashil2000** [comment]
@BasixKOR Can you make a PR to add Scoop install instructions (similar to cargo and brew) to htmlq's Readme?

**Comment by BasixKOR** [comment]
I've just submitted a PR to htmlq.
