### ISSUE TITLE
gcc@11.2.0: hash check failed

### ISSUE THREAD

**Issue by xxthunder** [ScoopInstaller/Main#3088]
#### Scoop Configuration

```json
{
    "lastupdate":  "2021-12-14T10:39:51.3767274+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master",
    "MSIEXTRACT_USE_LESSMSI":  true
}
```

**Comment by xxthunder** [comment]
Hi there, seems that the hash in bucket is wrong?!? gcc 11.2.0 is failing and I cannot go back to 8.1.0 because it seems missing.

**Comment by rashil2000** [comment]
The hash is correct, maybe your download didn't complete fully:

![image](https://user-images.githubusercontent.com/46838874/145981422-da264ca3-f127-419e-a21e-baa84a6ecbf4.png)

**Comment by xxthunder** [comment]
Hi @rashil2000 , yes you are right. My company's internet connection is really bad, at least to nuwen.net. I am not able to download the components 7z. Thanks for your fast reply and sorry for that issue.

**Comment by rashil2000** [comment]
No worries :)
