### ISSUE TITLE
ffmpeg@4.4.1-2: download via aria2 failed

### ISSUE THREAD

**Issue by mister-glass** [ScoopInstaller/Main#3113]
#### Scoop Configuration

```json
{
  "lastupdate": "2021-12-21T09:24:09.9248929+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": true
}
```

scoop update output

```powershell
Updating 'ffmpeg' (4.4-80 -> 4.4.1-2)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 83f708|ERR |       0B/s|C:/Users/bogda/scoop/cache/ffmpeg#4.4.1-2#https_github.com_BtbN_FFmpeg-Builds_releases_download_autobuild-2021-12-07-12-23_ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-12-07-12-23/ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip
    referer=https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-12-07-12-23/
    dir=C:\Users\bogda\scoop\cache
    out=ffmpeg#4.4.1-2#https_github.com_BtbN_FFmpeg-Builds_releases_download_autobuild-2021-12-07-12-23_ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip

ERROR & 'C:\Users\bogda\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\bogda\scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9352 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ffmpeg%404.4.1-2%3a+download+via+aria2+failed
```

**Comment by LazyGeniusMan** [comment]
Looks like this URL not found problem happen quite often when I searched for "ffmpeg" in issue, are they often delete older build or something? Should we switch to other mirror listed in FFmpeg official website? [this](https://www.gyan.dev/ffmpeg/builds/) or [this](https://github.com/GyanD/codexffmpeg). I looked into Chocolatey's ffmpeg manifest and see that they are using that releases for their manifest.

Also is there any reason for using auto build releases for this manifest? this manifest should be stable version right? since the one that using auto build/nightly build has been covered by `ffmpeg-nightly` manifest in ScoopInstaller/Versions bucket

**Comment by rashil2000** [comment]
We can switch to @GyanD's builds - there have been previous discussions on this #1459, #1659.

Can you make a PR for the same?

**Comment by rashil2000** [comment]
> I could, but looks like it's fixed ? [b7b9051](https://github.com/ScoopInstaller/Main/commit/b7b905144e25dd0aed9ad0b273d7bf5bd5967600) 

Temporarily, yes

> But it's using 21 Dec releases from current repo, which will expire again in 14 days. So scoop will still use current repo or move to another mirror?

We will face the same problem again, so it's best to switch mirrors

**Comment by LazyGeniusMan** [comment]
> We will face the same problem again, so it's best to switch mirrors

We can still use current repo if we use last build of the month, the owner said it will removed in the next 2 years.

Why current repo build stable version everyday? Does it only rebuild using the same exact source? I can't find the info about that anywhere

If we're switching to mirrors, which version should we use? essentials? or full?

**Comment by GyanD** [comment]
@BtbN builds from the latest release branch. There may be new commits between builds. The numbered releases, however, correspond to tags. I only update the release build when a new tag has been created. This is infrequent.

Essentials works for 90% of users. You can offer full as a separate target if you like.

**Comment by rashil2000** [comment]
We can use ffmpeg-release-full.7z for `ffmpeg.json` and ffmpeg-release-full-shared.7z for `ffmpeg-shared.json`.
