### ISSUE TITLE
upgrade yarn to version 1.22.17

### ISSUE THREAD

**Issue by devhawk** [ScoopInstaller/Main#3125]
As per https://classic.yarnpkg.com/, Classic Stable: v1.22.17

**Comment by tech189** [comment]
Judging by https://github.com/yarnpkg/yarn/releases, 1.22.15 was the last release with an msi installer. Looks like the recommended way to install is with `npm`:
```
scoop install nodejs
npm install --global yarn
```

**Comment by tech189** [comment]
Thanks for fixing it @HUMORCE I thought because their installer link (https://classic.yarnpkg.com/latest.msi) was a 404, they had stopped providing an installation for windows!

**Comment by HUMORCE** [comment]
@tech189 the msi package will not be redistributed when fixes that do not affect windows platfrom.

https://classic.yarnpkg.com/en/docs/install#windows-stable would not contain these **PATCH** versions, previously.
