### ISSUE TITLE
[Request] Add clib

### ISSUE THREAD

**Issue by rishavs** [ScoopInstaller/Main#3140]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [*] a non-GUI tool
- [*] a reasonably well-known and widely used developer tool
- [*] the latest stable version of the program
- [*] the full version i.e. not a trial version
- [*] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** [name of new package]
clib

**Description:** [clear and concise details of what it is]
Package manager for the C programming language.

*What does clib(1) do?*
Basically the lazy-man’s copy/paste promoting smaller C utilities, also serving as a nice way to discover these sort of libraries. From my experience C libraries are scattered all over the web and discovery is relatively poor. The footprint of these libraries is usually quite large and unfocused. The goal of clibs is to provide stand-alone “micro” C libraries for developers to quickly install without coupling to large frameworks.

You should use clib(1) to fetch these files for you and check them into your repository, the end-user and contributors should not require having clib(1) installed. This allows clib(1) to fit into any new or existing C workflow without friction.

**Homepage:** [a URL/link]
https://www.clibs.org/

**Download link(s):** [URL(s)/link(s)]
https://github.com/clibs/clib/releases

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
3.9k stars on Github. See https://github.com/clibs/clib

**Comment by rishavs** [comment]
I would love to contribute on this but want to make sure that it meets the criteria for the main bucket. IMO it is one of the more important tools in the c programmer's toolbox and it should definitely be here.

**Comment by rashil2000** [comment]
It fits the criteria perfectly. Please make a PR!

**Comment by rishavs** [comment]
Actually, I just realized that clib has its own upgrade utility that can be invoked from cli.
As such, I am wary of adding it to scoop where the upgrades from both instances can conflict (have had similar issues with dotnet previously).

I am closing his issue. Thanks for your patience.
