### ISSUE TITLE
[Enhancement] python from bucket/main

### ISSUE THREAD

**Issue by KumaYYC** [ScoopInstaller/Main#3143]
#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-01T10:15:41.1145195-07:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

#### Purpose

This request is to make the python manifest from bucket/main comply with the usage of shims.

#### Issue

When multiple versions of python is installed, the version from the bucket/main takes priority because it adds the `current` directory into the path. This should not be the case and it should respect the usage of shims.

#### Solution (I will attach PR to issue)

In the package manifest, remove the `"."` entry from the `"env_add_path"` key.

```json
{
    "version": "3.10.1",
    "description": "A programming language that lets you work quickly and integrate systems more effectively.",
    "homepage": "https://www.python.org/",
    "license": "Python-2.0",
    "notes": "Allow applications and third-party installers to find python by running: \"$dir\\install-pep-514.reg\"",

    ...
    "env_add_path": [
        "Scripts",
        "."   # remove this line
    ],
    ...

}
```

**Comment by rashil2000** [comment]
The `.` added to PATH is the only way to access `python` and `pythonw`. There are no shims for them.

**Comment by KumaYYC** [comment]
Sorry, I didn't confirm the differences in the bin argument.

Can we possibly add the bin configuration to create that shim?
I'll push another commit to my fork.

**Comment by KumaYYC** [comment]
![image](https://user-images.githubusercontent.com/47726396/147858315-402e882d-6c4e-4218-8adb-e6cea9ad3f8b.png)

The new configuration allows me to switch between python versions like resetting java with scoop.

**Comment by rashil2000** [comment]
> Can we possibly add the bin configuration to create that shim?

I don't think you should. They were removed for a reason. See https://github.com/ScoopInstaller/Main/pull/2144 and https://github.com/ScoopInstaller/Main/pull/316

**Comment by KumaYYC** [comment]
I see. I guess the added complexity of the python version updating is the issue.
Thank you. Closing issue.
