### ISSUE TITLE
App "gcc" does not contain gdb anymore. On purpose? 

### ISSUE THREAD

**Issue by basejumpa** [ScoopInstaller/Main#3150]
## Bug Report

**Package Name:** gcc ...

... used to contain `gdb.exe`  with former version 8.1.0: Since 12.2.0 is does not contain `gdb.exe` anymore. On purpose?

<details>

```
PS C:\> scoop list
Installed apps:

  ...
  gcc 8.1.0 [main]
  ...

PS C:\> (gcm gdb).Path
C:\Users\manna\scoop\apps\gcc\current\bin\gdb.exe

PS C:\> gdb --version
GNU gdb (GDB) 8.1
...
```
</details>

There is also an other app with name "gdb".  It contains (only) `gdb.exe`

So my QUESTION: Is the removal of `gdb.exe` in app "gcc" on purpose? It also could be a design decision. 

Both apps where updated recently; see
* https://github.com/ScoopInstaller/Main/commits/master/bucket/gdb.json
* https://github.com/ScoopInstaller/Main/commits/master/bucket/gcc.json

### Current Behaviour

Since Version 11.2.0 (head as of this writing) it does not contain `gdb.exe` anymore

The change (removal of gdb.exe in gcc) *breaks* at least the automatic creation of `launch.json` inside Visual Studio Code (created by C++ extension) because the extension expects `gdb.exe` in the directory where `gcc.exe` resides.

I came along that issue while fiddling on https://github.com/basejumpa/GettingStarted-unittest-with-cmake

<details>

```
PS C:\> scoop list
Installed apps:

  ...
  gcc 11.2.0 [main]
  gdb 11.1 [main]
  ...

PS C:\> (gcm gdb).Path
C:\Users\basejumpa\scoop\shims\gdb.exe

PS C:\> gdb -version
GNU gdb (GDB) 11.1
...
```

File `launch.json` generated automaticaly by vs code extension:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}\\a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Users\\basejumpa\\scoop\\apps\\gcc\\current\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe build active file"
        }
    ]
}
```

</details>

### Expected Behaviour

App gcc and visual studio extension creating the `launch.json` with paths to both `gcc.exe` and `gdb.exe` work seamlessly together.

### Possible Solution

My suggestion is to add gdb.exe to app "gcc" again. Rationale: Using debugger suitable to compile/link toolchain is very common.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**Additional software:** Visual Studio code (from bucket extras the app vscode)

**Comment by rashil2000** [comment]
The GCC manifest you're familiar with has been renamed to mingw.json.

It was done because gcc.json name was slightly misleading, it contained make, binutils, gdb and some other stuff too.

So you can just do `scoop install mingw` to get back everything. Only the manifest name has changed.
