### ISSUE TITLE
Duplicate package: Main/bulk-rename-command & Extras/bulk-rename-utility

### ISSUE THREAD

**Issue by amreus** [ScoopInstaller/Main#3168]
Although not exact duplicates, they are the same packge and download.

Are duplicate packages considered a bug?

* [Main] https://github.com/ScoopInstaller/Main/blob/master/bucket/bulk-rename-command.json
* [Extras] https://github.com/ScoopInstaller/Extras/blob/master/bucket/bulk-rename-utility.json

**Comment by rashil2000** [comment]
They're allowed. One is GUI, one is CLI.

See another example: 

https://github.com/ScoopInstaller/Extras/blob/master/bucket/everything.json

https://github.com/ScoopInstaller/Main/blob/master/bucket/everything-cli.json
