### ISSUE TITLE
[Request] PNPM

### ISSUE THREAD

**Issue by T145** [ScoopInstaller/Main#3177]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** `pnpm`

**Description:** A fast and disk space efficient Node package manager.

**Homepage:** https://pnpm.io/

**Download link(s):** https://pnpm.io/installation#using-a-standalone-script

**Some indication of popularity/repute:** https://github.com/pnpm/pnpm

**Comment by HUMORCE** [comment]
please make/create a PR/issue to https://github.com/pnpm/pnpm.github.io, if possible.

let people know that it can be installed via Scoop.

(when the PR https://github.com/ScoopInstaller/Main/pull/3193 is merged)
