### ISSUE TITLE
[Request] Danser

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/Main#3186]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [X] a non-GUI tool
- [X] a reasonably well-known and widely used developer tool
- [X] the latest stable version of the program
- [X] the full version i.e. not a trial version
- [X] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** danser-go

**Description:** Dancing visualizer of osu! standard maps and custom osu! client written in Go. Also a generator for osu! videos. 

**Homepage:** https://github.com/Wieku/danser-go

**Download link(s):** https://github.com/Wieku/danser-go/releases

**Some indication of popularity/repute:** 
* 421 stars on GitHub
* Multiple tutorials with tens of thousand of views, and satisfying videos using it that have millions ([1](https://www.youtube.com/c/Wieku/videos?view=0&sort=p&flow=grid), [2](https://www.youtube.com/watch?v=0l7Bt8Vo7dc), [3](https://www.youtube.com/watch?v=7gUaxpeQG5g))
* [Discord with 3K members](https://discord.com/invite/UTPvbe8)

I have a manifest ready for it, let me know if this fits in Main or if I should move to Extras

**Comment by rashil2000** [comment]
If it has a GUI, then Extras. If it's only a CLI app, then Main is okay.

**Comment by couleurm** [comment]
![image](https://user-images.githubusercontent.com/82747632/149557683-d0cd33bc-9701-4acd-849f-7c57fd55218b.png)
of course, CLI :)
