### ISSUE TITLE
aws-sam-cli@1.37.0: decompress error

### ISSUE THREAD

**Issue by saeednm** [ScoopInstaller/Main#3212]
#### Scoop Configuration

```json
{
    "lastupdate":  "2022-01-19T16:39:38.2157596+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```
Installing 'aws-sam-cli' (1.37.0) [64bit]
Loading AWS_SAM_CLI_64_PY3.msi from cache
Checking hash of AWS_SAM_CLI_64_PY3.msi ... ok.
Extracting AWS_SAM_CLI_64_PY3.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\saeed.n\scoop\apps\aws-sam-cli\1.37.0\AWS_SAM_CLI_64_PY3.msi.
Log file:
  ~\scoop\apps\aws-sam-cli\1.37.0\msi.log

here is the log file content: 
=== Logging started: 19/01/2022  16:40:26 ===
Error 1320. The specified path is too long: C:\Users\saeed.n\scoop\apps\aws-sam-cli\1.37.0\_tmp\SourceDir\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\init\templates\cookiecutter-aws-sam-hello-java-gradle\{{cookiecutter.project_name}}\HelloWorldFunction\src\main\java\helloworld
=== Logging stopped: 19/01/2022  16:40:47 ===

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/2775
