### ISSUE TITLE
[Request] Add P4

### ISSUE THREAD

**Issue by miarodri** [ScoopInstaller/Main#3218]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** p4

**Description:** Helix Core Command-Line (P4) provides access to versioned files in Helix Core through a command-line interface.

**Homepage:** https://www.perforce.com/products/helix-core-apps/command-line-client

**Download link(s):** https://cdist2.perforce.com/perforce/r21.2/bin.ntx64/helix-p4-x64.exe

**Some indication of popularity/repute:** Perforce (also known as Helix) is pretty popular in the games industry as a version control software. See [Wikipedia](https://en.wikipedia.org/wiki/List_of_version-control_software) for reference to it in source control listings.

**Comment by rashil2000** [comment]
The P4V package in Extras bucket contains both GUI and TUI - https://github.com/ScoopInstaller/Extras/blob/master/bucket/p4v.json

So this request can be closed.

**Comment by miarodri** [comment]
Yes, but is there any value to avoiding installing 3 binaries that won't be used on CLI-only systems?

**Comment by rashil2000** [comment]
No, but they won't cause any problems, right

**Comment by miarodri** [comment]
No, they'll work fine. Just thought it would be useful. I'll go ahead and close.

**Comment by rashil2000** [comment]
Is there a size/network bandwidth limitation on your system? Just trying to know more.

**Comment by miarodri** [comment]
Not at all. I just dislike installing things I don't need, especially if I'm creating an image that I intend to distribute.

**Comment by rashil2000** [comment]
Hmm, I think this is reasonable.

Can you do a PR?

**Comment by miarodri** [comment]
Sure, I'm messing around with it now. I'll try to put up a PR in the next day or so.

**Comment by rashil2000** [comment]
The manifest for p4v in _Extras_ was added by @MathewBlock.

@MathewBlock would you like to have a go at this?

**Comment by MathewBlock** [comment]
It sounds like @miarodri is working on it, but I can take over if need be.
@miarodri let me know how you'd like to proceed.

**Comment by rashil2000** [comment]
@MathewBlock could you work on this now?

**Comment by miarodri** [comment]
Ack, sorry, completely dropped this. If I don't have a PR up today, @MathewBlock feel free to take over.
