### ISSUE TITLE
[Request] chezmoi

### ISSUE THREAD

**Issue by twpayne** [ScoopInstaller/Main#3220]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** chezmoi

**Description:** Manage your dotfiles across multiple machines, securely. With first-class Windows support.

**Homepage:** https://www.chezmoi.io/

**Download link(s):** https://github.com/twpayne/chezmoi/releases

**Some indication of popularity/repute:** 5.8K stars on GitHub, the [most popular dotfile manager](https://dotfiles.github.io/utilities/)

chezmoi has been available as a Scoop bucket for two years: https://github.com/twpayne/scoop-bucket

Follow a request from @LazyGeniusMan in https://github.com/twpayne/scoop-bucket/issues/2, would you consider including this package in Main? I (the creator of chezmoi) would be happy to maintain chezmoi as a Scoop Main bucket.

**Comment by rashil2000** [comment]
Yes! Please make a PR!
