### ISSUE TITLE
[Request] Add Terraformer (not to be confused with Terraform)

### ISSUE THREAD

**Issue by Megasware128** [ScoopInstaller/Main#3227]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** Terraformer

**Description:** CLI tool to generate terraform files from existing infrastructure (reverse Terraform). Infrastructure to Code

**Homepage:** [Terraformer GitHub](https://github.com/GoogleCloudPlatform/terraformer)

**Download link(s):** [Extension-less exe](https://github.com/GoogleCloudPlatform/terraformer/releases/download/0.8.18/terraformer-all-windows-amd64) but can be worked around with #/terraformer.exe

**Some indication of popularity/repute:** 6.6k stars

**Comment by Megasware128** [comment]
I can open a PR if you like

**Comment by rashil2000** [comment]
Is that a _363 MB_ executable I see? 😲

Yes, please make a PR

**Comment by Megasware128** [comment]
Yeah, the size has to do with that it includes all the different providers
