### ISSUE TITLE
[Request] add influxdb2-cli

### ISSUE THREAD

**Issue by kubiani** [ScoopInstaller/Main#3235]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [X] a non-GUI tool
- [X] a reasonably well-known and widely used developer tool
- [X] the latest stable version of the program
- [X] the full version i.e. not a trial version
- [X] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** InfluxDB 2 CLI

**Description:** Use the influx CLI to interact with and manage your InfluxDB instance. Write and query data, generate InfluxDB templates, export data, and more.

**Homepage:** 
> both Cloud and OSS versions point to same CLI
- https://docs.influxdata.com/influxdb/v2.1/tools/influx-cli/?t=Windows
- https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/?t=Windows

**Download link(s):**
- https://portal.influxdata.com/downloads/
- https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.2.1-windows-amd64.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
- https://db-engines.com/en/ranking_trend/system/InfluxDB

**Comment by rashil2000** [comment]
Are these the same as your request?

https://github.com/ScoopInstaller/Main/blob/master/bucket/influxdb2.json

https://github.com/ScoopInstaller/Main/blob/master/bucket/influxdb.json

**Comment by kubiani** [comment]
No. See https://github.com/ScoopInstaller/Main/issues/3236. The CLI is not packaged with the DB daemon.
