### ISSUE TITLE
[Request] Ninja, Kitware fork/build

### ISSUE THREAD

**Issue by segevfiner** [ScoopInstaller/Main#3243]
## Package Request
Kitware (CMake devs among other libs) makes available a fork/build of Ninja that integrates the long languishing job server PR/feature.

This feature is practically a necessity when integrating Ninja with other build systems, but sadly hasn't been merged for years, leading to this fork.

This fork is also what is installed by `pip install ninja` (Which is maintained by Kitware).

P.S. The binary in the PyPI repo might be newer than the one in GitHub. The maintainer might need to be contacted about this.

* https://github.com/Kitware/ninja
* https://pypi.org/project/ninja/
* https://github.com/ninja-build/ninja/issues/1139

### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** ninja-kitware (Kitware fork/build)

**Description:** A fork/build of ninja by Kitware with the job server PR/feature merged in.

**Homepage:**
https://github.com/Kitware/ninja https://pypi.org/project/ninja/

**Download link(s):**
ninja-1.10.0.gfb670.kitware.jobserver-1_i686-pc-windows-msvc.zip
ninja-1.10.2.3-py2.py3-none-win_amd64.whl 

**Some indication of popularity/repute:** https://github.com/Kitware/ninja

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by segevfiner** [comment]
Just need to know whether to package the PyPI or GitHub release as the PyPI one is more up-to-date, yet I'm not exactly sure on how to setup autoupdate for a PyPI package or if scoop will handle a whl file (It's a zip, and will require `extract_dir`).

@bradking @jcfr @henryiii, which seem to be maintaining this might be able to shed some light if the lack of updated package on GitHub is intentional or an accidental omission.

**Comment by jcfr** [comment]
Version of ninja packaged in the python ninja wheel corresponds to the latest commit of the branch in the [Kitware/ninja@kitware-staged-features](https://github.com/Kitware/ninja/commits/kitware-staged-features)

```
set(unix_source_url       "https://github.com/Kitware/ninja/archive/v1.10.2.g51db2.kitware.jobserver-1.tar.gz")
set(unix_source_sha256    "549c31ee596566b952c600e23eb9b8d39a4112cd5fdeb2e5a83370669176da40")

set(windows_source_url    "https://github.com/Kitware/ninja/archive/v1.10.2.g51db2.kitware.jobserver-1.zip")
set(windows_source_sha256 "2dfd74ac583340869d5e236892d782f96bf70533706c1a2d7c968c43ded474bc")
```

Source: https://github.com/scikit-build/ninja-python-distributions/blob/f7ee4a9981b2f942e32581be74fd808f875b0b0c/NinjaUrls.cmake


The latest `Kitware/ninja` release available at https://github.com/Kitware/ninja/releases is based of [Kitware/ninja@fb6705334](https://github.com/Kitware/ninja/commit/fb6705334a7ec7d9f4cd64a7bd146180f2e973c4) 

I will reach out to the CMake team so that we update the Kitware ninja fork and create a new release

**Comment by jcfr** [comment]
@segevfiner  I believe this issue can now be closed.
