### ISSUE TITLE
Link for less is Dead

### ISSUE THREAD

**Issue by matthewjberger** [ScoopInstaller/Main#327]
The [manifest for less](https://github.com/ScoopInstaller/Main/blob/master/bucket/less.json) uses a [download link which is currently out of service](https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z) (hopefully temporarily). Just letting you know for now!

**Comment by rasa** [comment]
It seems it’s an expired cert. see https://github.com/ScoopInstaller/Main/issues/150

**Comment by matthewjberger** [comment]
Thanks for letting me know about #150. I'll close this issue.
