### ISSUE TITLE
imagemagick@7.1.0-21: Requested URL not found

### ISSUE THREAD

**Issue by trallnag** [ScoopInstaller/Main#3270]
## Bug Report

**Package Name:** imagemagick

Updating to the latest version of the package returns an error because the URL where the exe should be located cannot be found.

### Current Behaviour

I ran `scoop update imagemagick` to upgrade to the newest available version.

```txt
Updating 'imagemagick' (7.1.0-20 -> 7.1.0-21)
Downloading new version
OperationStopped: C:\Users\GHXCA\scoop\apps\scoop\current\lib\install.ps1:138
Line |
 138 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

The installation failed, because the URL defined in the manifest could not be found.

The installation script tries to fetch a file from the following URL, which is currently not available.

<https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-21-Q16-HDRI-x64-dll.exe>

```txt
> curl -i https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-21-Q16-HDRI-x64-dll.exe
HTTP/1.1 404 Not Found
```

### Expected Behaviour

The URL should be valid.

### Additional context/output

I assume that there is some lag between the release of a new imagemagick version and the executable being available.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-29T23:22:15.6705469+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": true,
  "aria2-enabled": false
}
```

**Comment by trallnag** [comment]
Seems like this already occurred in the past: https://github.com/ScoopInstaller/Scoop/issues/4450

**Comment by HUMORCE** [comment]
wait for Excavator to update its version, urls, hashes ... https://github.com/ScoopInstaller/Main/actions/workflows/excavator.yml

if you cannot wait to install:
```
cd <MAIN BUCKET>
bin\checkver.ps1 -app imagemagick -u
scoop install imagemagick
```

after install:
```
git restore .\bucket\imagemagick.json
```
if you do not restore the manifest, this bucket may not be updated (in the future)

**Comment by trallnag** [comment]
Okay, interesting to know. Thanks for the info. Then this is not a bug and I shall close this issue
