### ISSUE TITLE
[Request] aws-nuke

### ISSUE THREAD

**Issue by Console32** [ScoopInstaller/Main#3271]
## Package Request
AWS Nuke

### Information

**Name:** aws-nuke

**Description:** nukes a aws account (deletes all resources)

**Homepage:** https://github.com/rebuy-de/aws-nuke

**Download link(s):** https://github.com/rebuy-de/aws-nuke/releases/download/v2.17.0/aws-nuke-v2.17.0-windows-amd64.zip

**Some indication of popularity/repute:** 2.5k Github Stars

There was a Issue some time ago, it was closed due to no windows version [here](https://github.com/ScoopInstaller/Main/issues/1349). There is a Windows Version available now.

I can provide a MR

**Comment by rashil2000** [comment]
Sure
