### ISSUE TITLE
[Bug] mongodb-database-tools cannot be installed if 7zip is already installed

### ISSUE THREAD

**Issue by jeffrson** [ScoopInstaller/Main#3279]
#### Current Behavior
(Not only) In a clean installation, if 7zip is installed, mongodb-database-tools cannot be installed:
"ERROR Could not find 'mongodb-database-tools-windows-x86_64-100.5.2" (error 16)
apparently, robocopy in core.ps1 fails, but this may not be the origin of the bug

#### Expected Behavior
mongodb-database-tools should be installable as before (100.5.1 could be installed - but this may be with an older version of 7zip)

### System details

**Windows version:** [e.g. 7, 8, 10] Windows 10

**OS architecture:** [e.g. 32bit, 64bit] 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`] 7.2.1 (as well as 5)

## Repro
scoop install 7zip
scoop install mongodb-database-tools

after
scoop uninstall 7zip
scoop uninstall mongodb-database-tools
the installation
scoop install mongodb-database-tools
will be successful

**Comment by HUMORCE** [comment]
caused by upstream with special compression method
