### ISSUE TITLE
Installing python use scoop broke vim

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Main#3281]
#### Current Behavior
Vim raises error but when remove python which is installed by scoop, it runs normal. Trying install python 3.10.2 with .exe file, vim runs normal.
#### Expected Behavior
Vim run like normal.

#### Possible Solution
I have a question in Vim repo [here](https://github.com/vim/vim-win32-installer/issues/71)

### System details

**Windows version:**: 10

**OS architecture:**: 64bit

**PowerShell version:**: 
```

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1

```
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-30T09:54:08.0971711+07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "alias.reinstall": "scoop uninstall {0}; scoop install {0}",
  "alias": {}
}

```

**Comment by HUMORCE** [comment]
cannot reproduce

please provide more information, e.g. screenshots, environment variables, etc.

```
> scoop list python
Installed apps matching 'python':
python 3.10.2 [main]
> scoop list vim
Installed apps matching 'vim':
vim 8.2.2824 [main]
```

![screenshot_20220204114458](https://user-images.githubusercontent.com/4353480/152523701-ae939af1-478d-403d-a1b1-ea263728f051.png)

**Comment by tech189** [comment]
I don't have any issue with pyenv and Python 3.10 either. If [this comment](https://github.com/vim/vim-win32-installer/issues/71#issuecomment-1029691279) is correct and you might need Python 3.6 then you can install that with `python36` in the versions bucket. But I suspect something else is wrong, check your PATH/env variables

**Comment by giggio** [comment]
Please see my comment here for a work around: https://github.com/neoclide/coc.nvim/issues/3623#issuecomment-1033401869
I hope it helps.

**Comment by sqliuchang** [comment]
Vim 9.0 can't load python36.dll, but I'm sure python has been configured rightly.
I also tried to set pythonthreehome and pythonthreedll, but no improvement.
Besides the vim package from chocolatey works well with the python installed by scoop.
I just replace the vim folder with the chocolatey one to solve this problem.
