### ISSUE TITLE
[Request] add support for nerdctl

### ISSUE THREAD

**Issue by Console32** [ScoopInstaller/Main#3282]
## Package Request
https://github.com/containerd/nerdctl
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x ] a non-GUI tool
- [x ] a reasonably well-known and widely used developer tool
- [x ] the latest stable version of the program
- [x ] the full version i.e. not a trial version
- [x ] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** nerdctl

**Description:** replacement for docker cli

**Homepage:** https://github.com/containerd/nerdctl

**Download link(s):** https://github.com/containerd/nerdctl/releases

**Some indication of popularity/repute:** 3100 Github Stars

**Comment by Console32** [comment]
I can provide the manifest if needed :)

**Comment by rashil2000** [comment]
Sure
