### ISSUE TITLE
pip not working

### ISSUE THREAD

**Issue by criticic** [ScoopInstaller/Main#3283]
## Bug Report

**Package Name:** [name of package which has bug(s)]
Python
### Current Behaviour
running pip throws an error, as for some reason it is opened by previous version of python

```
❯ pip
Fatal error in launcher: Unable to create process using '"C:\Users\user\scoop\apps\python\3.10.1\python.exe"  "C:\Users\user\scoop\apps\python\current\Scripts\pip.exe" ': The system cannot find the file specified.
```
### Expected Behaviour
pip uses the latest python & runs wothout errors.

### Additional context/output

`C:\Users\user\scoop\apps\python\3.10.1\python.exe` does not exist as it was cleaned after an update, it should instead use `C:\Users\user\scoop\apps\python\current\python.exe`

`python -m pip` & `python C:\Users\user\scoop\apps\python\current\Scripts\pip.exe` works as expected.
### Possible Solution
not sure, link pip to /current/

### System details

**Windows version:** [e.g. 7, 8, 10]
10
**OS architecture:** [e.g. 32bit, 64bit]
64
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.1

**Comment by rashil2000** [comment]
Please search for existing issues before opening a new one. 

![image](https://user-images.githubusercontent.com/46838874/152554795-dd398469-8c87-49d0-8f06-40c015a4884e.png)
