### ISSUE TITLE
GCC compilation issues inside Neovim

### ISSUE THREAD

**Issue by ffuszthaler** [ScoopInstaller/Main#3286]
## Bug Report

**Package Name:** gcc

### Current Behaviour

I installed neovim and gcc through scoop and some neovim plugins require gcc to compile some stuff, everything worked fine on Win10 and gcc version 8.1.0, but after I updated to 11.2.0 issues like these started to show up:
![image](https://user-images.githubusercontent.com/25418250/152685197-859e5469-e9fb-40ef-8626-4cc336a7e3aa.png)

Same thing is happening on my Win11 notebook. I know this might seem like a neovim issue, but as it had worked previously I think othervise.

### Expected Behaviour

Plugins should be compiled without any issues.

### Additional context/output

I tried adding gcc and g++ directly to the PATH but to no avail.

### System details

**Windows version:** 10, 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-02-06T15:17:45.7829198+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
What is the output of these two?

```pwsh
$Env:Path.Split(';')
dir ~\scoop\apps\gcc\current\bin\
```

**Comment by ffuszthaler** [comment]
![image](https://user-images.githubusercontent.com/25418250/152686140-c3aa65ac-2ee4-4235-9cc8-66613d105db7.png)

![image](https://user-images.githubusercontent.com/25418250/152686152-8a7fd136-6288-4a62-83d4-38b0ba3d8798.png)

**Comment by rashil2000** [comment]
As you can see, GCC has been installed correctly, and `as.exe` is available in your PATH. (You can also run `as --help` to check this directly).

**Comment by ffuszthaler** [comment]
I mean it did work previously so...

**Comment by rashil2000** [comment]
Try running Neovim in Windows PowerShell

**Comment by ffuszthaler** [comment]
I already do so the entire time, but there is no difference regardless of the terminal

**Comment by ffuszthaler** [comment]
Nevermind, what I just said, I did use powershell, but through the new Windows Terminal, but when I tried it through 'Windows Powershell', it worked

**Comment by rashil2000** [comment]
In the screenshot you are using PowerShell Core (installed through Store), which has some limitations compared to when it's installed through the MSI installer. I'd advice you to not use the Store version.

**Comment by ffuszthaler** [comment]
Alright, thanks
