### ISSUE TITLE
Vim stable ver 8.2.2824 break colorscheme in GUI Vim using scoop 

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Main#3290]
#### Current Behavior
Colorscheme is displayed wrong. It just happens with vim installed by scoop. I tried to use this version in .exe file and it worked. It seems a problem with vim stable in scoop.

#### Expected Behavior
colorscheme is displayed normal.

#### Possible Solution
I don't know exactly the reason but after testing a lot of times, this problem affects not only this version but also vim-nightly. It just happens when using scoop, `.exe file` still normal, especially in GUI Vim. You can check [here](https://github.com/vim/vim/issues/9678)

### System details

**Windows version:*: 11

**OS architecture:**: 64 bit

**PowerShell version:**:

```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1
```

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-30T09:54:08.0971711+07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "alias.reinstall": "scoop uninstall {0}; scoop install {0}",
  "alias": {}
}

```

**Comment by rashil2000** [comment]
Can you remove/rename the _vimrc and _gvimrc files from the scoop vim folder to see if the issue is solved?

**Comment by hungpham3112** [comment]
> Can you remove/rename the _vimrc and _gvimrc files from the scoop vim folder to see if the issue is solved?

yeah, It works, I think it should be remove from `scoop vim `because when learning vim, people can figure out where and how to put their vimrc, _gvimrc and _vimrc could be raise many unexpected errors in the future. In my case, I put my vimrc in ~/vimfiles/.

**Comment by hungpham3112** [comment]
> Can you confirm if this also solves #3281?

yes, remove _vimrc, _gvimrc solve my problems. Thanks, I don't know why scoop add _vimrc and _gvimrc by default but if scoop does, please remove it. Thanks a lot

**Comment by rashil2000** [comment]
Done #3291
