### ISSUE TITLE
Can't install yt-dlp

### ISSUE THREAD

**Issue by Goooler** [ScoopInstaller/Main#3298]
## Bug Report

**Package Name:** yt-dlp

### Current Behaviour
```bash
❯ scoop info main/yt-dlp
Could not find manifest for 'yt-dlp'.
```

```bash
❯ scoop install yt-dlp
Couldn't find manifest for 'yt-dlp'.
```

### Expected Behaviour

Should install it.
### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** Windows Terminal

#### Scoop Configuration
```json
{
  "lastupdate": "2022-02-12T14:39:04.4486855+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by HUMORCE** [comment]
make sure that the main bucket is updated: `scoop -v`

```
'main' bucket:
c3a4046 (HEAD -> master, origin/master, origin/HEAD) lxc: Update to version 4.23
```

in case of the update fails: `scoop bucket rm main; scoop bucket add main`

**Comment by Goooler** [comment]
```bash
❯ git pull
error: Your local changes to the following files would be overwritten by merge:
        bucket/hexyl.json
Please commit your changes or stash them before you merge.
Aborting
Updating 1b0505839..c3a404670
```

**Comment by Goooler** [comment]
You are right, seems something wrong with commits.
