### ISSUE TITLE
ImageMagick does not find its build config

### ISSUE THREAD

**Issue by xworld21** [ScoopInstaller/Main#3299]
## Bug Report

**Package Name:** ImageMagick 7.1.0-24

### Current Behaviour

Running `magick identify -list Configure` shows
```
identify: UnableToOpenConfigureFile `configure.xml' @ warning/configure.c/GetConfigureOptions/705.
```
This prevents `Image::Magick` from building, for example.

### Expected Behaviour

The command should print something like
```
Name                  Value
-------------------------------------------------------------------------------
CC                    VS2022
COPYRIGHT             Copyright (C) 1999-2021 ImageMagick Studio LLC
CXX                   VS2022
DOCUMENTATION_PATH    unavailable
LIB_VERSION           0x710
LIB_VERSION_NUMBER    7,1,0,24
```

### Possible Solution
Setting `MAGICK_CONFIGURE_PATH` to `$dir` resolves the issue on my system.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-02-12T21:48:15.6411388+00:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Please make a PR for the fix
