### ISSUE TITLE
maven: install failed

### ISSUE THREAD

**Issue by vegchic** [ScoopInstaller/Main#3308]
## Bug Report

**Package Name:** maven

### Current Behaviour

When I try to install maven, scoop print output likes this
```
Installing 'maven' (3.8.4) [64bit]
apache-maven-3.8.4-bin.zip (8.7 MB) [=========================================================================] 100%
Checking hash of apache-maven-3.8.4-bin.zip ... ok.
Extracting apache-maven-3.8.4-bin.zip ... done.
Linking D:\Scoop\apps\maven\current => D:\Scoop\apps\maven\3.8.4
Persisting conf
The filename, directory name, or volume label syntax is incorrect.
File not found - D:\Scoop\apps\maven\current\conf
Persisting lib\ext
The filename, directory name, or volume label syntax is incorrect.
File not found - D:\Scoop\apps\maven\current\lib\ext
'maven' (3.8.4) was installed successfully!
```
seems like persist files are wrong 

### Expected Behaviour

install successfully without error

### Possible Solution

I have fixed it by copying files in `persist/maven` into `apps/maven/current`

### System details

**Windows version:**  10

**OS architecture:** 64bit

**PowerShell version:** 7.2.0-preview.5

**Additional software:** 

#### Scoop Configuration

```json
{
  "lastupdate": "2022-02-17T23:44:50.1659701+08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/154753010-0bcf4a9e-0c62-400c-bd53-6a93ac548753.png)

Do you have an antivirus?

**Comment by vegchic** [comment]
I only have the windows defender, and i have added scoop's path into the exclusive path by `sudo Add-MpPreference -ExclusionPath 'D:\Scoop'`

**Comment by rashil2000** [comment]
Where have you installed PowerShell from?

**Comment by vegchic** [comment]
sorry for replying late, i install it from MS offcial and run in windows terminal

**Comment by rashil2000** [comment]
Using Microsoft Store or running the MSI installer?

**Comment by vegchic** [comment]
MSI installer

**Comment by rashil2000** [comment]
Can you try using develop branch?

```
scoop config SCOOP_BRANCH develop
scoop update
scoop install maven
```

**Comment by vegchic** [comment]
sorry, but i can't even update 😂
```
Updating Scoop...
fatal: couldn't find remote ref refs/heads/"develop"
fatal: 'origin/develop' is not a commit and a branch 'develop' cannot be created from it
fatal: ambiguous argument 'origin/develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Update failed.
```
