### ISSUE TITLE
cygwin@2.918: hash check failed

### ISSUE THREAD

**Issue by Roseleaves** [ScoopInstaller/Main#3313]
#### Scoop Configuration
ERROR Hash check failed!
App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    98fac3ee56a183f8c45abc1e80395c48f075e338708d27a64eee8c942fd2baa9
Actual:      18b445dc16259bb772aaf0d32d64f9ed3166045fdc07eb9154651840d8a27752

```json
//# Your configuration here
```

**Comment by everettttt** [comment]
I just got this error today. If I opened an issue it'd have the same exact title.

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-08-26T08:28:21.4155300-04:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

#### Scoop version

```
Current Scoop version:
v0.2.4 - Released at 2022-08-08

'extras' bucket:
93e0ec06b (HEAD -> master) mockoon: Update to version 1.16.0

'java' bucket:
e434579f (HEAD -> master, origin/master, origin/HEAD) semeru11-jdk: Update to version 11.0.16-8-0.33.0

'main' bucket:
d31c7ee93 (HEAD -> master) units: Add version 2.21 (#3683)
```

**Comment by rashil2000** [comment]
Try creating an issue with the same title to run the hash verifier

**Comment by everettttt** [comment]
#3859
