### ISSUE TITLE
git-filter-repo@2.34.0: Decompress error

### ISSUE THREAD

**Issue by mike-geiger** [ScoopInstaller/Main#3329]
Failed to extract files from D:\Users\geiger\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip.
Log file:
  ~\scoop\apps\git-filter-repo\2.34.0\7zip.log

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4647

**Comment by mike-geiger** [comment]
> [ScoopInstaller/Scoop#4647](https://github.com/ScoopInstaller/Scoop/issues/4647)

Thanks this resolve my issue.
