### ISSUE TITLE
podman: static binaries name changed

### ISSUE THREAD

**Issue by JadynWong** [ScoopInstaller/Main#3348]
## Bug Report

**Package Name:** podman

### Current Behaviour

https://github.com/ScoopInstaller/Main/blob/1206d0301c335d1c82def00cef40f93da28d1471/bucket/podman.json#L8

### Expected Behaviour

https://github.com/containers/podman/releases/tag/v4.0.2

Binary name changed from `podman-remote-release-windows.zip` to `podman-remote-release-windows_amd64.zip`

### Additional context/output

![image](https://user-images.githubusercontent.com/13699353/156682693-01ee0038-e347-43ae-8849-2cf3f9c1a5af.png)

### Possible Solution

Change the binary name in url to `podman-remote-release-windows_amd64.zip`

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Comment by rashil2000** [comment]
Can you make a PR for the fix?

**Comment by JadynWong** [comment]
I have a problem. `podman.exe` is located under the `podman-x.x.x` directory in the old version, but under `podman-x.x.x\user\bin` in the new version. I can change `extract_dir` to `podman-x.x.x\usr\bin`, but this will cause other files such as `containers.conf`, docs, etc. to not be copied.

![image](https://user-images.githubusercontent.com/13699353/156702775-bf995b7d-f19c-489a-b888-4c5b7070c6fe.png)


![image](https://user-images.githubusercontent.com/13699353/156703148-ef2dbf72-ad53-4d78-aa57-0574551c4af1.png)

**Comment by rashil2000** [comment]
You need to modify the `bin` field for that. `extract_dir` does not need to be changed.
