### ISSUE TITLE
nvs post install throws an error

### ISSUE THREAD

**Issue by segevfiner** [ScoopInstaller/Main#3350]
## Bug Report

**Package Name:** nvs

### Current Behaviour

The post install script throws an error:
```pwsh
❯ scoop install nvs
Installing 'nvs' (1.6.0) [64bit]
Loading nvs-1.6.0.msi from cache
Checking hash of nvs-1.6.0.msi ... ok.
Extracting nvs-1.6.0.msi ... done.
Linking ~\scoop\apps\nvs\current => ~\scoop\apps\nvs\1.6.0
Persisting nodejs
Running post-install script...
Get-Content:
Line |
   2 |  $CONF = (Get-Content "$persist_dir\nodejs\settings.json") | ConvertFr …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\Segev\scoop\persist\nvs\nodejs\settings.json' because it does not exist.
Add-Member:
Line |
   3 |  … Name linkToSystem -NotePropertyValue $false -Force -InputObject $CONF
     |                                                                    ~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
'nvs' (1.6.0) was installed successfully!
```

### Expected Behaviour

It shouldn't throw an error.

### Possible Solution

Perhaps adding`-ea SilentlyContinue` to `Get-Content` and `if (-not $?) { $CONF = New-Object -TypeName PSObject }

Why is setting `linkToSystem` required, and is it desired to do so or an issue with nvs? (I guess it detects the scoop installation directory thinking that it's a system wide installation of nvs?)

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** Git, starship prompt

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-04T16:28:15.9629229+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
I think there's something else going on. The last time I used (and contributed to NVS), there was no problem.


> Perhaps adding`-ea SilentlyContinue` to `Get-Content` and `if (-not $?) { $CONF = New-Object -TypeName PSObject }

The file is created during `nvs remote` command. It should exist, at that point. Can you manually run and verify?

> I guess it detects the scoop installation directory thinking that it's a system wide installation of nvs?

Most probably yes. I think it might also have something to do with symlink creation (which require admin privileges by default).

**Comment by segevfiner** [comment]
```
❯ powershell -NoProfile -File "C:\Users\Segev\scoop\apps\nvs\1.6.0\nvs.ps1" remote
File C:\Users\Segev\scoop\apps\nvs\1.6.0\nvs.ps1 cannot be loaded because running scripts is disabled on this system.
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

So this boils down to needing to use `pwsh` instead of `powershell` on powershell core.

**Comment by rashil2000** [comment]
Hmm, I'm thinking why the `powershell` part is needed at all. We can just do `& "dir\nvs.ps1"`. We're inside powershell already, after all.

**Comment by segevfiner** [comment]
Indeed we are. There is a `-NoProfile` stuck in there, but is that really needed? As far as I know, isn't nvs is going to get imported into the PowerShell session with the profile active anyhow later on.

**Comment by rashil2000** [comment]
Right. Can you make a PR for removing that part?

**Comment by segevfiner** [comment]
Yep. Let's see if that works.
