### ISSUE TITLE
smartmontools@7.3: failing to install

### ISSUE THREAD

**Issue by Pyker** [ScoopInstaller/Main#3352]
## Bug Report

**Package Name:** smartmontools

### Current Behaviour

`Can't shim 'bin\update-smart-drivedb.exe': File doesn't exist.`

### Expected Behaviour

I expect the upgrade/installation to work.

### Additional context/output

<details>
<summary>Details</summary>

```
Checking hash of smartmontools-7.3-1.win32-setup.exe ... ok.
Uninstalling 'smartmontools' (7.2-1)
Removing shim 'runcmdu.shim'.
Removing shim 'runcmdu.exe'.
Removing shim 'smartctl.shim'.
Removing shim 'smartctl.exe'.
Removing shim 'smartctl-nc.shim'.
Removing shim 'smartctl-nc.exe'.
Removing shim 'smartd.shim'.
Removing shim 'smartd.exe'.
Removing shim 'smartd_warning'.
Removing shim 'smartd_warning.cmd'.
Unlinking ~\scoop\apps\smartmontools\current
Installing 'smartmontools' (7.3-1) [64bit]
Loading smartmontools-7.3-1.win32-setup.exe from cache
Extracting dl.7z ... done.
Linking ~\scoop\apps\smartmontools\current => ~\scoop\apps\smartmontools\7.3-1
Creating shim for 'runcmdu'.
Creating shim for 'smartctl'.
Creating shim for 'smartctl-nc'.
Creating shim for 'smartd'.
Creating shim for 'smartd_warning'.
Creating shim for 'update-smart-drivedb'.
Can't shim 'bin\update-smart-drivedb.exe': File doesn't exist.
```
</details>

### Possible Solution

From the changelog:

> - Windows: New script 'update-smartd-drivedb.ps1' provides gpg verification and replaces 'update-smartd-drivedb.exe'.
<https://www.smartmontools.org/browser/tags/RELEASE_7_3/smartmontools/NEWS#L76>

We could either provide a shim for that (somehow) or just remove this shim outright.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** irrelevant

#### Scoop Configuration

Irrelevant

**Comment by rashil2000** [comment]
Can you make a PR for the fix?

**Comment by Pyker** [comment]
I'm not familiar with how to fix it, so I don't know what changes are required.

**Comment by rashil2000** [comment]
Check the manifest: https://github.com/ScoopInstaller/Main/blob/master/bucket/smartmontools.json 

It should be pretty self-explanatory - just change the file extension of the binary
