### ISSUE TITLE
[Request] par2cmdline

### ISSUE THREAD

**Issue by pessoalzy** [ScoopInstaller/Main#3412]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** par2cmdline

**Description:** par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.

**Homepage:** https://github.com/Parchive/par2cmdline

**Download link(s):** https://github.com/Parchive/par2cmdline/releases/download/v0.8.1/par2cmdline-0.8.1-win-x64.zip

**Some indication of popularity/repute:** GitHub stars 479

**Comment by rashil2000** [comment]
Nice! Can you make a PR for this?

**Comment by pessoalzy** [comment]
OK, I'll try.
