### ISSUE TITLE
px: autoupdate not working

### ISSUE THREAD

**Issue by daniel-liuzzi** [ScoopInstaller/Main#3418]
## Bug Report

**Package Name:** [`px`](https://github.com/ScoopInstaller/Main/blob/master/bucket/px.json)

### Current Behaviour

`scoop update` won't find anything newer than `v0.4.0`, which [came out on Sep 04, 2018](https://github.com/genotrance/px/releases/tag/v0.4.0)

### Expected Behaviour

`scoop update` should find the latest version ([`v0.5.1`](https://github.com/genotrance/px/releases/tag/v0.5.1) as of this writing)

### Additional context/output

n/a

### Possible Solution

n/a

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-22T16:48:54.9652358+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by daniel-liuzzi** [comment]
@rashil2000 done, let me know if it's OK (first time I se checkver)
