### ISSUE TITLE
Can not update pwsh to v7.2.2

### ISSUE THREAD

**Issue by test210820** [ScoopInstaller/Main#3420]
### The update script starts a pwsh process, but the update requires that the pwsh process does not exist 

`scoop -v`
```
7d5a47cc (HEAD -> master, tag: v0.1.0, origin/master, origin/HEAD) fix(install): Use 'Get-Command' to test scoop install status (#4785)
```

![屏幕截图 2022-03-22 210325](https://user-images.githubusercontent.com/65008815/159555499-05ada407-0fb6-43d4-802e-7806d94d1680.png)

**Comment by rashil2000** [comment]
Use Windows PowerShell
