### ISSUE TITLE
miller@6.2.0: Shim creation fail

### ISSUE THREAD

**Issue by forwardcompatible** [ScoopInstaller/Main#3429]
Cannot shim 'mlr.exe': File does not exist

PS C:\Users\tryan> scoop install miller
Installing 'miller' (6.2.0) [64bit] [main]
WARN  By installing you accept following license: BSD-2-Clause (https://spdx.org/licenses/BSD-2-Clause.html)
Loading miller-6.2.0-windows-amd64.zip from cache
Checking hash of miller-6.2.0-windows-amd64.zip ... ok.
Extracting miller-6.2.0-windows-amd64.zip ... done.
Linking ~\scoop\apps\miller\current => ~\scoop\apps\miller\6.2.0
Creating shim for 'mlr'.
ERROR Cannot shim 'mlr.exe': File does not exist

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=miller%406.2.0%3a+Shim+creation+fail&body=Cannot+shim+%27mlr.exe%27%3a+File+does+not+exist
ERROR This application failed to install: main/miller

**Comment by rashil2000** [comment]
The manifest needs a `extract_dir`. 

/cc @tech189
