### ISSUE TITLE
clojure stuck -- can't upgrade or uninstall

### ISSUE THREAD

**Issue by forwardcompatible** [ScoopInstaller/Main#3430]
PS C:\Users\tryan> scoop status
Scoop is up to date
Update is available for:
    clojure: 1.10.3.1040 -> 1.10.3.1087

PS C:\Users\tryan> scoop update clojure
clojure: 1.10.3.1040 -> 1.10.3.1087
Updating 1 outdated app:
Updating 'clojure' (1.10.3.1040 -> 1.10.3.1087) [64bit]
Downloading new version
Loading clojure-tools-1.10.3.1087.zip from cache
Checking hash of clojure-tools-1.10.3.1087.zip ... ok.
Uninstalling 'clojure' (1.10.3.1040)
WARN  Shim for 'cmd-clojure' is missing. Skipping.
WARN  Shim for 'cmd-clj' is missing. Skipping.
Uninstalling PowerShell module 'ClojureTools'.
Removing ~\scoop\modules\ClojureTools
ERROR Cannot bind argument to parameter 'LinkName' because it is an empty string.
ERROR This application failed to update: clojure

PS C:\Users\tryan> scoop uninstall clojure
Uninstalling 'clojure' (1.10.3.1040)
WARN  Shim for 'cmd-clojure' is missing. Skipping.
WARN  Shim for 'cmd-clj' is missing. Skipping.
Uninstalling PowerShell module 'ClojureTools'.
Removing ~\scoop\modules\ClojureTools
ERROR Cannot bind argument to parameter 'LinkName' because it is an empty string.

PS C:\Users\tryan> scoop checkup
No problems identified!
PS C:\Users\tryan> scoop status
Scoop is up to date
Update is available for:
    clojure: 1.10.3.1040 -> 1.10.3.1087

**Comment by rashil2000** [comment]
There's no app called clojure in Main bucket
