### ISSUE TITLE
Use extern openssh with git

### ISSUE THREAD

**Issue by PigeonF** [ScoopInstaller/Main#3438]
## Bug Report

**Package Name:** git

### Current Behaviour

When signing commits with SSH keys, the `git` package uses the bundled `ssh-keygen`, instead of the system one.

### Expected Behaviour

Git should use the system version of openssh.

### Additional context/output

I assume that this is an actual bug, since there are two versions of git in scoop: `git` and `git-with-openssh`. Note that although the `git` version does not copy `ssh-keygen` or `ssh-agent` to the bin folder, they are still present in `<git install>/usr/bin`.

### Possible Solution

Delete the corresponding files in the usr/bin folder. See also https://github.com/git-for-windows/git/discussions/3451 for a discussion about this issue.

### System details

**Windows version:** 10

**OS architecture:** 64

**Comment by rashil2000** [comment]
Deleting those binaries in the default git manifest is not a good idea, it will be a breaking change.
You can create a custom manifest to do it and submit it to Versions bucket
