### ISSUE TITLE
rust@1.59.0: decompress error

### ISSUE THREAD

**Issue by Tyler887** [ScoopInstaller/Main#3450]
```
=== Logging started: 27/03/2022  12:33:20 ===
=== Logging stopped: 27/03/2022  12:33:22 ===
```
*note: scoop came up with **nothing** in the logs*
#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-27T11:22:46.8962601+01:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}

```

**Comment by Tyler887** [comment]
Since it's most likely that MSI install was removed from Scoop after depreciation of MSI install, because most MSIs require running as admin, which should be avoided in Scoop manifests.

**Comment by rashil2000** [comment]
> MSI install was removed from Scoop after depreciation of MSI

When did this happen?

**Comment by Tyler887** [comment]
> > MSI install was removed from Scoop after depreciation of MSI
> 
> When did this happen?

Eh, I'm wrong. Code line for reference:
https://github.com/ScoopInstaller/Scoop/blob/04b30de9dde613acec8bb0014b42f381f83e2ec9/lib/install.ps1#L620

**Comment by Tyler887** [comment]
I found executable setup scripts: https://www.rust-lang.org/tools/install

This may require Visual C/C++ Build Tools, which requires UAC, so this may not be fully portable.

**Comment by rashil2000** [comment]
The links you've shared are for rustup and not rust. Rustup already exists in Main bucket.

https://github.com/ScoopInstaller/Main/blob/master/bucket/rustup.json
https://github.com/ScoopInstaller/Main/blob/master/bucket/rustup-msvc.json
