### ISSUE TITLE
[Request] Remove Python note for VapourSynth

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/Main#3506]
[This note](https://github.com/ScoopInstaller/Main/blob/eba45f2fa62243281848f267c14b76f387a4225c/bucket/vapoursynth.json#L5) is not necessary anymore as it got support for Python 3.10 in it's [latest release](https://github.com/vapoursynth/vapoursynth/releases/tag/R58)

**Comment by rashil2000** [comment]
Can you remove it?
