### ISSUE TITLE
Lua 5.4.4 is published. however, the Lua in the main bucket is still 5.4.2 out of date[Request] 

### ISSUE THREAD

**Issue by Roseleaves** [ScoopInstaller/Main#3511]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [ ] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool
- [ ] the latest stable version of the program
- [ ] the full version i.e. not a trial version
- [ ] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** [name of new package]

**Description:** [clear and concise details of what it is]

**Homepage:** [a URL/link]

**Download link(s):** [URL(s)/link(s)]

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by issaclin32** [comment]
The reason why it stays at **version 5.4.2** is that *Scoop* relies on [LuaBinaries](http://luabinaries.sourceforge.net/download.html) for pre-compiled binaries. I think it will be updated to version 5.4.4 in a short time.

**Comment by Valinor** [comment]
Maybe we can close this one ?

**Comment by rashil2000** [comment]
Hmm yeah
