### ISSUE TITLE
[Request] Azure Terrafy

### ISSUE THREAD

**Issue by Megasware128** [ScoopInstaller/Main#3523]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** Azure Terrafy (aztfy)

**Description:** A tool to bring existing Azure resources under Terraform's management

**Homepage:** https://github.com/Azure/aztfy

**Download link(s):** https://github.com/Azure/aztfy/releases/tag/v0.2.0

**Some indication of popularity/repute:** 400 stars

I have a manifest ready to open in a PR if you like.

**Comment by rashil2000** [comment]
Sure, go ahead!
