### ISSUE TITLE
cacert@2022-04-26: download via aria2 failed

### ISSUE THREAD

**Issue by krystofkrticka** [ScoopInstaller/Main#3528]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://curl.haxx.se/ca/cacert-2022-04-26.pem#/cacert.pem
    referer=https://curl.haxx.se/ca/cacert-2022-04-26.pem#/
    dir=C:\Users\Admin\scoop\cache
    out=cacert#2022-04-26#https_curl.haxx.se_ca_cacert-2022-04-26.pem_cacert.pem

ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Admin\scoop\cache\cacert.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=25056 --continue --summary-interval=0 --auto-save-interval=1

#### Scoop Configuration
{
  "lastupdate": "2022-04-26T10:42:39.4178639+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/165261571-e17bb8de-2e5d-46ac-bbc2-87792d950f32.png)

**Comment by krystofkrticka** [comment]
![image](https://user-images.githubusercontent.com/37749100/165262029-2a6e63bf-655d-4f1e-8ee6-053bad01d3fe.png)
I tried it again and it still shows this.

**Comment by rashil2000** [comment]
Try with aria2 disabled

**Comment by krystofkrticka** [comment]
![image](https://user-images.githubusercontent.com/37749100/165263087-572a11a3-5f81-45ac-bcb1-5ff9f1f6f484.png)
It looks like aria problem because when I try to download using aria manually it errors out.

**Comment by krystofkrticka** [comment]
Yes, after disabling aria2 it works just fine.
