### ISSUE TITLE
nano doesn't work

### ISSUE THREAD

**Issue by kaboddy** [ScoopInstaller/Main#3541]
I've installed / reinstalled nano and it won't launch.  Used to work - Not sure if it was because of the recent update or not.

## Bug Report

**Package Name:** nano

### Current Behaviour

Using in powershell, nothing is displayed / opened.  I can't even get the version info.

### Expected Behaviour

I would expect nano to run and open.

### System details

**Windows version:** Win 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

**Additional software:** 
Installed apps:

Name       Version          Source Updated             Info
----       -------          ------ -------             ----
7zip       21.07            main   2022-04-13 15:04:07
dark       3.11.2           main   2022-04-28 20:04:41
git        2.36.0.windows.1 main   2022-04-28 16:04:36
innounp    0.50             main   2022-04-28 20:04:35
nano       6.3-7            main   2022-04-28 21:04:05
neofetch   7.1.0            main   2022-04-13 15:04:14
shellcheck 0.8.0            main   2022-04-18 22:04:41
sudo       0.2020.01.26     main   2022-04-28 20:04:15

```json
{
  "lastUpdate": "2022-04-30T17:28:47.8814072-04:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by issaclin32** [comment]
When I run *nano* under cmd, it says libmcfgthread-1.dll is missing. Are you having the same problem?

**Comment by issaclin32** [comment]
It should be fixed now.
Re-install *nano* and see if it works.

**Comment by kaboddy** [comment]
Yeah!  Looks good!
