### ISSUE TITLE
r@4.1.3: download via aria2 failed

### ISSUE THREAD

**Issue by epieczko** [ScoopInstaller/Main#3544]
Looks like r no longer has this binary available for download.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://cloud.r-project.org/bin/windows/base/R-4.1.3-win.exe
    referer=https://cloud.r-project.org/bin/windows/base/
    dir=C:\SDE\Scoop\cache
    out=r#4.1.3#https_cloud.r-project.org_bin_windows_base_R-4.1.3-win.exe

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by tech189** [comment]
You can install it with the `r41` package in the Versions bucket. You'll be able to install the latest version of R once #3530 is merged.
