### ISSUE TITLE
curl@7.83.0_1: download via aria2 failed

### ISSUE THREAD

**Issue by Vedabahu** [ScoopInstaller/Main#3559]
- [X] By opening this issue you confirm that you have searched for similar issues/PRs here already.

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-05-08T18:52:54.8924617+05:30",
    "rootPath":  "D:\\Vedabahu\\Scoop\\Scoop",
    "globalPath":  "D:\\Vedabahu\\Scoop\\ScoopGlobal",
    "cachePath":  "D:\\Vedabahu\\Scoop\\ScoopCache",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-split":  16,
    "aria2-max-connection-per-server":  16,
    "aria2-warning-enabled":  false,
    "MSIEXTRACT_USE_LESSMSI":  true
}
```

The error with accessing the links for curl by aria2 is this:
```powershell
05/08 19:15:28 [ERROR] CUID#7 - Download aborted. URI=https://curl.haxx.se/windows/dl-7.83.0_1/curl-7.83.0_1-win64-mingw.tar.xz
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://curl.se/windows/dl-7.83.0_1/curl-7.83.0_1-win64-mingw.tar.xz
  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error: The message received was unexpected or badly formatted.
(80090326)
```
Using aria2 to download other files gives no error.
Directly downloading the `curl-7.83.0_1-win64-mingw.tar.xz` file from the browser works fine.

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/167310873-a547cb79-f4df-4965-9f65-56ecc3590c08.png)

**Comment by helohe** [comment]
Same issue here:

Updating 'curl' (7.83.0 -> 7.83.1_1)
Downloading new version
Starting download with aria2 ...
Download: 05/23 09:35:40 [ERROR] CUID#8 - Download aborted. URI=https://curl.haxx.se/windows/dl-7.83.1_1/curl-7.83.1_1-w
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://curl.se/windows/dl-7.83.1_1/curl-7.83.1_1-win64-mi
Download:   -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error: The message received was unexpected or
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b1c382|ERR |       0B/s|C:/Users/Admin/scoop/cache/curl#7.83.1_1#https_curl.haxx.se_windows_dl-7.83.1_1_curl-7.
83.1_1-win64-mingw.tar.xz
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://curl.haxx.se/windows/dl-7.83.1_1/curl-7.83.1_1-win64-mingw.tar.xz
    referer=https://curl.haxx.se/windows/dl-7.83.1_1/
    dir=C:\Users\Admin\scoop\cache
    out=curl#7.83.1_1#https_curl.haxx.se_windows_dl-7.83.1_1_curl-7.83.1_1-win64-mingw.tar.xz

ERROR & 'C:\Users\Admin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Admin\scoop\cache\curl.txt' --user-age
nt='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 6.1; Win64; x64; Core)' --allow-overwrite=true --auto-file-
renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --ena
ble-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --st
op-with-process=2072 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=curl%407.83.1_1%3a+download+via+aria2+failed

**Comment by rashil2000** [comment]
If you're able to download from the link in a browser, rename it to `curl#7.83.1_1#https_curl.haxx.se_windows_dl-7.83.1_1_curl-7.83.1_1-win64-mingw.tar.xz` and put it in ~\scoop\cache folder. Then install curl normally, it will read from the cache.

**Comment by helohe** [comment]
Perfect, this worked.
