### ISSUE TITLE
Neofetch doesn't run after installation (broken shim)

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Main#3562]
## Bug Report

**Package Name:** neofetch

### Current Behaviour

After installing neofetch, it does not run. Windows says "The system cannot find the path specified."

### Expected Behaviour

Neofetch runs as normal

### Additional context/output

Others are having the same issue here: https://github.com/dylanaraps/neofetch/issues/2100

```
Installing 'neofetch' (7.1.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 21dd0e|OK  |   1.2MiB/s|C:/Users/me/scoop/cache/neofetch#7.1.0#https_raw.githubusercontent.com_dylanaraps_neofetch_7.1.0_neofetch
Download: Status Legend:
Download: (OK):download completed.
Checking hash of neofetch ... ok.
Linking ~\scoop\apps\neofetch\current => ~\scoop\apps\neofetch\7.1.0
Creating shim for 'neofetch'.
'neofetch' (7.1.0) was installed successfully!

~ took 26s
❯ neofetch
The system cannot find the path specified.
```

### Possible Solution

Looks like the [previous manifest](https://github.com/ScoopInstaller/Main/blob/351ab03c49ddf2655c627b96761b49a72a3a8a0c/bucket/neofetch.json) worked - `scoop install https://github.com/ScoopInstaller/Main/raw/351ab03c49ddf2655c627b96761b49a72a3a8a0c/bucket/neofetch.json` works for me.

At the moment Scoop creates a shim pointing to non existent file: `~\scoop\bin\bash.exe` (found here: https://github.com/dylanaraps/neofetch/issues/2100#issuecomment-1106656322)

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

#### Scoop Configuration

```json
{
  "SCOOP_BRANCH": "master",
  "lastupdate": "2022-05-09T10:02:10.2311408+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "debug": false,
  "aria2-enabled": true,
  "aria2-retry-wait": 4,
  "aria2-split": 16,
  "aria2-max-connection-per-server": 16,
  "aria2-min-split-size": "4M",
  "alias": {
    "reinstall": "scoop-reinstall"
  },
  "aria2-warning-enabled": false,
  "enable-aria2": true
}

```

**Comment by rashil2000** [comment]
Hi, thanks for the report. This is an upstream issue and I have raised a PR here - https://github.com/ScoopInstaller/Scoop/pull/4913
