### ISSUE TITLE
graphicsmagick: leave q8 here (and drop `-q8`) and move q16 to `versions`

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Main#357]
> Note that the QuantumDepth=8 version (Q8) which provides industry standard 24/32 bit pixels consumes half the memory and about 30% less CPU than the QuantumDepth=16 version (Q16) which provides 48/64 bit pixels for high-resolution color. A Q8 version is fine for processing typical photos intended for viewing on a computer screen. If you are dealing with film, scientific, or medical images, use ICC color profiles, or deal with images that have limited contrast, then the Q16 version is recommended.

I think keep q8 here (and drop `-q8`) and move q16 to `versions` should be better.

_Originally posted by @niheaven in https://github.com/ScoopInstaller/Main/pull/331#issuecomment-521565764_

**Comment by niheaven** [comment]
@r15ch13 There're many such *alternative* apps (i.e. `graphicsmagick-q8`/`graphicsmagick-q16` here, or `atom`/`atom-portable`, or `omnisharp`/`omnisharp-http`, etc.), should they stay in the same bucket or move one of them to `versions` or maybe a brand new bucket likes `alt`?

**Comment by rasa** [comment]
IMO, moving dup apps makes sense. Portable apps should remain, and non-portables should move to the [nonportable](https://github.com/oltolm/scoop-nonportable) or versions bucket
