### ISSUE TITLE
azcopy

### ISSUE THREAD

**Issue by nikolasd** [ScoopInstaller/Main#3575]
#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-16T13:28:41.9517686+03:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}

```

azcopy: 10.14.1 -> 10.15.0
Updating one outdated app:
Updating 'azcopy' (10.14.1 -> 10.15.0)
Downloading new version
dl.zip (12,2 MB) [============================================================================================] 100%
Checking hash of dl.zip ... ERROR Hash check failed!
App:         main/azcopy
URL:         https://aka.ms/downloadazcopy-v10-windows/#dl.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    dab9d075b078da04b381f45459ebce87f147b8134fb86cb896463290cd87afa4
Actual:      65d6699618e7e7d13525a5e9b9c2598a6051b7710e722345f54339faf690efa0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=azcopy%4010.15.0%3a+hash+check+failed

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/3576#issuecomment-1127526834
