### ISSUE TITLE
[Bug] Erlang OTP 25.0 breaks Elixir 1.13.4

### ISSUE THREAD

**Issue by tensor-programming** [ScoopInstaller/Main#3592]
## Bug Report

**Package Name:** 
Erlang@25.0 
Elixir@1.13.4

### Current Behaviour

When you use scoop to install Elixir it goes and fetches a precompiled set of binaries from the elixir github along with the latest version of Erlang in the bucket.  The problem is that the current windows release of elixir wasn't precompiled with OTP 25.0 and so when you try to run anything with the current elixir setup it fails with something like this: 
```
13:31:52.121 [error] beam\beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
  lambda already defined for label 749. To fix this, please recompile this module with an OTP 25 compiler.
```  

### Expected Behaviour

The expected behavior is that the elixir package grabs the appropriate OTP package that it is compatible with. 

### Additional context/output

According to some of the devs over on Elixir, they seem to lag with releasing precompiled versions of Elixir with the latest OTP version.   

Should also note, trying to run `scoop install erlang@24.0 -a 64bit` doesn't fetch the 64bit release of `24.0` either.   

### Possible Solution

Allow the bucket to specify a version and architecture inline with the precompiled version of elixir so that it won't fetch the latest erlang if it breaks the install. 

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PowerShell 7.2.3
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2022-05-20T13:21:49.8348183-04:00",
  "aria2-enabled": true,
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
A much simpler solution is to change the `depends` in the Elixir manifest to `suggest`, so that Scoop won't install incompatible packages automatically, and will notify users instead.

**Comment by tensor-programming** [comment]
Sure but the issue is that Erlang is a strict dependency for Elixir.  You can't run one without the other.  Does suggest allow the user to pick the version or is it just a simple yes or no prompt?

**Comment by rashil2000** [comment]
The `suggest` doesn't do anything except suggest the user about the application. User still has to install Erlang himself. The upside is that they can now Erlang however they want, even outside of Scoop, and whatever version they want.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/commit/83e8acaf9a9c1cdd24777a5d59360da8cf81b740
