### ISSUE TITLE
`scoop update curl` fails updating curl to recent version (7.83.1_1 atm)

### ISSUE THREAD

**Issue by przemoc** [ScoopInstaller/Main#3593]
## Bug Report

**Package Name:** curl

### Current Behaviour

`scoop update curl` fails updating curl to recent version (7.83.1_1 atm)

### Expected Behaviour

Successfully updating curl to recent version (7.83.1_1 atm)

### Additional context/output

```
PS C:\Users\przemoc> scoop update curl
curl: 7.83.0 -> 7.83.1_1
Updating one outdated app:
Updating 'curl' (7.83.0 -> 7.83.1_1)
Downloading new version
OperationStopped: C:\Users\przemoc\scoop\apps\scoop\current\lib\install.ps1:107
Line |
 107 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

- `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` doesn't help.
- Running `scoop update curl` from `cmd` doesn't help.
- Before upgrading PowerShell from version 7.2.3, the issue was also there.

### System details

**Windows version:** 7
Microsoft Windows 7 Professional 6.1.7601 Service Pack 1 Build 7601

**OS architecture:** 64-bit

**PowerShell version:** 7.2.4

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-21T12:34:50.2158203+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/169650494-c61c93b7-5da0-4b07-972c-fc7639b878d5.png)

**Comment by sharma** [comment]
```
PS C:\> scoop install curl
Installing 'curl' (7.83.1_2) [64bit]
Loading curl-7.83.1_2-win64-mingw.tar.xz from cache
Checking hash of curl-7.83.1_2-win64-mingw.tar.xz ... ok.
Extracting curl-7.83.1_2-win64-mingw.tar.xz ... Exception: C:\Users\me\scoop\apps\scoop\current\lib\core.ps1:572
Line |
 572 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'curl-7.83.1-win64-mingw'! (error 16)
```

**Comment by bradenhilton** [comment]
Is there any particular reason `$matchHead` is used in `autoupdate`? It installs fine for me when I change `$matchHead` to `$version`.

**Comment by przemoc** [comment]
The original error I reported appearing when attempting to update curl (`The SSL connection could not be established, see inner exception`) has not been fixed. Others joined discussion here with _different issues_ (different error messages), and it has been mistakenly closed.

```
PS C:\Users\przemoc> scoop update
Updating Scoop...
[...]
Scoop was updated successfully!
PS C:\Users\przemoc> scoop update curl
curl: 7.83.0 -> 7.83.1_3
Updating one outdated app:
Updating 'curl' (7.83.0 -> 7.83.1_3)
Downloading new version
OperationStopped: C:\Users\przemoc\scoop\apps\scoop\current\lib\install.ps1:107
Line |
 107 |          throw $e
     |          ~~~~~~~~
     | The SSL connection could not be established, see inner exception.
```

I'm not sure what changed between curl 7.83.0 and more recent versions of the package or how scoop itself handles it. In the past I did not have any issues when updating curl. Error started showing up around 7.83.1 availability, but I wasn't reporting it immediately, as I was thinking it was a temporary thing that would be fixed in a few days. In the meantime I upgraded PowerShell, but issue did not go away, so I reported it.

As I already wrote:
- `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` doesn't help.
- Running `scoop update curl` from `cmd` doesn't help.
- Before upgrading PowerShell from version 7.2.3, the issue was also there.

Does anyone who commented here uses scoop on Windows 7?

I'm not familiar with PS, so if there are any suggestions how to root cause the issue, I could try to dig into it a bit more.

**Comment by rashil2000** [comment]
Does the download link work in a web browser?

**Comment by przemoc** [comment]
> Does the download link work in a web browser?

I tested:
https://curl.haxx.se/windows/dl-7.83.1_3/curl-7.83.1_3-win64-mingw.tar.xz
on:
- Edge 101.0.1210.53 (Official build) (64-bit) - works
- LibreWolf 100.0.2 (64-bit) - works
- Internet Explorer 11.0.9600.19596 (64-bit) - FAILS with message:
  > This page can’t be displayed
  > 
  > •Make sure the web address https://curl.se is correct.
  > •Look for the page with your search engine.
  > •Refresh the page in a few minutes.
  
  and after clicking Fix connection problems button, I get:
  
  > This page can’t be displayed

  >
  >Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in Advanced settings and try connecting to https://curl.se  again. If this error persists, it is possible that this site uses an unsupported protocol or cipher suite such as RC4 [(link for the details)](http://go.microsoft.com/fwlink/?LinkId=735074), which is not considered secure. Please contact your site administrator.
  
  but I already have "Use TLS 1.0", "Use TLS 1.1", "Use TLS 1.2" turned on.

BTW I already have installed MicrosoftEasyFix51044.msi from https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392.

**Comment by neheb** [comment]
Relevant: https://github.com/curl/curl-www/issues/182
