### ISSUE TITLE
ngrok autoupdate not working for v3

### ISSUE THREAD

**Issue by jordanbtucker** [ScoopInstaller/Main#3603]
## Bug Report

**Package Name:** ngrok

### Current Behaviour

ngrok v3 is not in the bucket because the autoupdate script does not check the new v3 page.

### Expected Behaviour

The autoupdate script should check for v3 and update the manifest.

### Additional context/output

ngrok seems to have put its v3 releases at https://dl.equinox.io/ngrok/ngrok-v3/stable/archive instead of https://dl.equinox.io/ngrok/ngrok/stable/archive

### Possible Solution

Changing the autoupdate script to look at the new v3 archive will work, but I don't know if ngrok is planning on updating the original archive.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

**Additional software:**

#### Scoop Configuration
```json
{
  "lastupdate": "2022-05-24T09:00:43.8725175-05:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by tech189** [comment]
I've got a manifest working for v3. Before I make a PR, do you think it would be good to keep a package for v2 in the Versions bucket?

**Comment by jordanbtucker** [comment]
I think that would be prudent considering v3 has breaking changes.
