### ISSUE TITLE
[LLVM] clang 14 do not include <stdlib.h> 

### ISSUE THREAD

**Issue by g-berthiaume** [ScoopInstaller/Main#3606]
## Bug Report

The `llvm` package doesn't seems to include the <stdlib.h> header file.

![image](https://user-images.githubusercontent.com/19377511/170102262-70135715-f64a-4f37-a547-986d41e013c5.png)

Is this possible that scoop `llvm` doesn't include [clang libc++](https://libcxx.llvm.org/#) ?  
I'm new to the LLVM toolchain, so my apology if it's not a scoop problem.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 
```powershell
$  $($PSVersionTable.PSVersion)

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      4
```

**Additional software:** 
llvm package info
![image](https://user-images.githubusercontent.com/19377511/170102574-ea526404-9f98-46f7-b2f9-8d88eb9f6707.png)

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-24T08:17:48.8589265-04:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
This is a quirk of LLVM itself. It doesn't include header files for the system, it's supposed to find standard header files in your system and use them.
You can Google your missing header statement and you'll find a lot of results.

**Comment by g-berthiaume** [comment]
My apology for the confusion.
Thanks for your support.
