### ISSUE TITLE
vim@8.1.1866: hash check failed

### ISSUE THREAD

**Issue by dongyanming** [ScoopInstaller/Main#361]
PS C:\WINDOWS\system32> scoop install vim
Updating Scoop...
Updating 'extras' bucket...
 * 440bec8a ios-webkit-debug-proxy: Update to version 1.8.5              78 minutes ago
 * 0606d659 googlechrome-canary: Update to version 78.0.3885.0           78 minutes ago
 * c2358697 netron: Update to version 3.3.2                              5 hours ago
Updating 'main' bucket...
 * 41111ff3 busybox: Update to version 3244-g48128b9aa                   80 minutes ago
Scoop was updated successfully!
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'vim' (8.1.1866) [64bit]
Loading gvim_8.1.1866_x64.zip from cache.
Checking hash of gvim_8.1.1866_x64.zip ... ERROR Hash check failed!
App:         main/vim
URL:         https://github.com/vim/vim-win32-installer/releases/download/v8.1.1866/gvim_8.1.1866_x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ad5e8bcad72fdb569781c3408f3cf4cca3e83425fc7974907dd13b1388e2d8cd
Actual:      8459688457d42df11d6c596579bd7c68ba221489273eedc0dc73c8a2e8d3a67f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=vim%408.1.1866%3a+hash+check+failed

**Comment by issaclin32** [comment]
It works fine on my PC. Probably just a connection issue?

![hash](https://user-images.githubusercontent.com/27724471/63262749-6625c380-c2b9-11e9-9d28-7a018efa957d.png)

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
