### ISSUE TITLE
[Update] GNU Diffutils is five years out of date

### ISSUE THREAD

**Issue by Diablo-D3** [ScoopInstaller/Main#3616]
Currently in the package list is 3.6, which was released 2017-05-21, while the current version is 3.8, released 2021-08-01.

**Comment by rashil2000** [comment]
Nobody makes diffutils for Windows anymore 😬

**Comment by rasa** [comment]
> Nobody makes diffutils for Windows anymore 😬

https://github.com/rasa/scoops/blob/8e1504b5abcfddefe39f66d7e08e79df3e64a185/bucket/git-all.json#L57

**Comment by rashil2000** [comment]
Haha yeah Cygwin and MSYS2 are always there. I was talking about native Win32 binaries.

**Comment by Diablo-D3** [comment]
This ticket probably shouldn't be closed then until the package is updated.

Any reason why it isn't just converted to pulling out of git or msys2's build? If there are no plans on upgrading or replacing with a better binary source, then the package should be removed.

**Comment by rashil2000** [comment]
Why should the package be removed? It's useful and works perfectly fine. There are plenty of popular tools in the bucket which are abandoned and do not receive updates.

**Comment by Diablo-D3** [comment]
I'm not sure why this there is pushback here. Diffutils is one of the core GNU packages that everyone depends on, and there are clearly multiple acceptable upstream binaries to choose from.

This also might be a possible x/y problem for me, as it is my use of git that requires diff. I would find it acceptable if the git package also adds a shim for diff.exe, since I imagine a lot of people who are going to use git will also be using diff.

**Comment by rasa** [comment]
Git already comes with diffutils, but scoop does not shim them by default.

@Diablo-D3 To get the latest diff in scoop, you could do one of the following:
1. `scoop bucket add rasa https://github.com/rasa/scoops & scoop install git-all`
2. Hack the existing git package to expose just the diffutil binaries.
2. Create a manifest that packages up the contents of https://packages.msys2.org/package/diffutils
3. Push a change to https://github.com/pfmoore/builder-diffutils/blob/master/build.sh to bump to 3.8.3

**Comment by Diablo-D3** [comment]
Since I'm already installing the `git` package which pulls in GFW, I'm just going to take the other step and do `scoop shim add diff "c:\users\username\scoop\apps\git\current\usr\bin\diff.exe"`instead, which is effectively using `git-all` with less steps.
