### ISSUE TITLE
espanso: outdated version

### ISSUE THREAD

**Issue by ldunkum** [ScoopInstaller/Main#3620]
## Bug Report

**Package Name:** [espanso](https://github.com/federico-terzi/espanso)

### Current Behaviour

Last version in bucket is "v0.7.3". Auto update probably didn't work as the name of the installer file changed at some point.

### Expected Behaviour

The current version of espanso (v2.1.5-beta) should be able to be installed.

### Possible Solution

Already wrote a new manifest, mainly opening this issue to follow contribution guidelines

### System details

**Windows version:** 10

**OS architecture:** 64bit

**Comment by rashil2000** [comment]
Main bucket contains the latest stable version. For alpha and beta versions, use the Versions bucket
