### ISSUE TITLE
rustup-msvc notes is outdated and incomplete

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [ScoopInstaller/Main#3645]
## Bug Report

**Package Name:** rustup-msvc

### Current Behaviour

https://github.com/ScoopInstaller/Main/blob/106af52652c8d776a391008c2aeab06e0a1b1d24/bucket/rustup-msvc.json#L6

Link in notes is outdated and instruction is incomplete.

### Expected Behaviour

Improved notes.

### Possible Solution

According to https://doc.rust-lang.org/book/ch01-01-installation.html#installing-rustup-on-windows

Microsoft C++ Build Tools can be downloaded here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

While installing, those two components should be installed:

- MSVC vXXX - VS XXXX C++ x64/x86 build tools
- Windows XX SDK

![](https://i.imgur.com/e7H9WVU.png)

### System details

**Windows version:** Windows 11 (Windows Sandbox)

**OS architecture:**

**PowerShell version:**

**Additional software:**

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by issaclin32** [comment]
Would you like to make a PR for this?

We can use multi-line notes like:
```
"notes": [
    "According to https://doc.rust-lang.org/book/ch01-01-installation.html#installing-rustup-on-windows",
    "Microsoft C++ Build Tools can be downloaded at: https://visualstudio.microsoft.com/visual-cpp-build-tools/",
    ".....",
]
```
