### ISSUE TITLE
rust/rust-msvc: Add support for including rust-src,to make package rust/rust-msvc more useful

### ISSUE THREAD

**Issue by ArchGuyWu** [ScoopInstaller/Main#3646]
The one who installed rust/rust-msvc may also want to use rust-analyzer,to make rust-analyzer work,the rust-src is needed.

The rust-src is provided in:  https://forge.rust-lang.org/infra/other-installation-methods.html

**Comment by issaclin32** [comment]
I am not familiar with *rust*'s workflow, but it looks **rust-analyzer** can download rust sources by itself.

Is there any specific reason, or any advantage to install the sources via *Scoop*?


https://rust-analyzer.github.io/manual.html#installation
> In theory, one should be able to just install the rust-analyzer binary and have it automatically work with any editor. We are not there yet, so some editor specific setup is required.
...
Additionally, rust-analyzer needs the sources of the standard library. If the source code is not present, rust-analyzer will attempt to install it automatically.
...
To add the sources manually, run the following command:
...
rustup component add rust-src

**Comment by ArchGuyWu** [comment]
rust-analyzer can only download itself,not the rust source,and it's **unavaliable** when using the rust-analyzer installed by scoop(In this case,I only installed **no-server** version of rust-analyzer in vscode).
If rust-src can be included in package rust/rust-msvc,we can get rust-src updated once the package rust/rust-msvc updates.
I'm also an arch user,I installed rust-analyzer by using **pacman** and it makes rust-src as the **dependency** of rust-analyzer,so we may create a **standalone** package called rust-src,or include it in the package rust/rust-msvc.

**Comment by ArchGuyWu** [comment]
Creating a standalone package may be a better choice,as it may be the **garbage** for those who don't use rust-analyzer,and being included in the package rust-analyzer can make user **have to** use the one provided by scoop since it doesn't included in the package rust/rust-msvc.

**Comment by ArchGuyWu** [comment]
I tried to create a standalone rust-src package,but it requires to be linked to the directory (stable-x86_64-pc-windows-msvc/stable-x86_64-pc-windows-gnu)\lib\rustlib\src\rust\,and it may cause issue when updating the package rust/rust-msvc.
