### ISSUE TITLE
Ant: Import user persisted libs in $persist_dir/lib

### ISSUE THREAD

**Issue by dstcruz** [ScoopInstaller/Main#3662]
## Bug Report

**Package Name:** ant

### Current Behaviour

No way to add user defined libs into `$dir/lib` that persist across updates.

### Expected Behaviour

Allow user persisted libs not included in the default ant install to be copied into the `$dir/lib` folder.

### Additional context/output

Some libs, such as `ant-contrib` are extras that don't come with the default `ant` install.

### Possible Solution

As suggested in https://github.com/ScoopInstaller/Scoop/discussions/4973#discussion-4128671, this can be done via a `pre_install` script that copies the user libs from `$persist_dir/lib`.

I have a PR ready for this, but as instructed by the PR template I'm opening this issue first.  For reference, here is my suggested change: https://github.com/dstcruz/Scoop-Main/commit/441fca7193edbe8dadabfb14848504eb106d4fbe

**Comment by dstcruz** [comment]
Do I need to wait for some kind of approval here before I open a PR for this?

**Comment by rashil2000** [comment]
You can open a PR
