### ISSUE TITLE
[Request] Topgrade

### ISSUE THREAD

**Issue by BasixKOR** [ScoopInstaller/Main#3665]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool - I guess 2.8k stars would be enough
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** topgrade

**Description:** Upgrades packages from various package managers in a single command.

**Homepage:** https://github.com/r-darwish/topgrade

**Download link(s):** https://github.com/r-darwish/topgrade/releases/tag/latest

**Some indication of popularity/repute:** 2.8k stars?

## Note
- It seems like this tool supports upgrading Scoop packages as well!
- I'm willing to implement this, this issue is primarily for introduction and confirmation

**Comment by rashil2000** [comment]
Sure, go ahead!

**Comment by BasixKOR** [comment]
lol it was already in the main. closing issue as invalid.
