### ISSUE TITLE
aws@1.16.220: decompress error

### ISSUE THREAD

**Issue by codescrawl** [ScoopInstaller/Main#368]
The new aws installer seems to have some issues - no problems with previous versions but this one (1.16.220) fails.

scoop install aws
Installing 'aws' (1.16.220) [64bit]
Loading AWSCLI64PY3-1.16.220.msi from cache
Checking hash of AWSCLI64PY3-1.16.220.msi ... ok.
Extracting AWSCLI64PY3-1.16.220.msi ... ERROR Exit code was 1603!
Failed to extract files from <snip>\scoop\apps\aws\1.16.220\AWSCLI64PY3-1.16.220.msi.
Log file:
  ~\scoop\apps\aws\1.16.220\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=aws%401.16.220%3a+decompress+error

=== Logging started: 18/08/2019  17:27:39 ===
Error 1310. Error writing to file: <snip>\scoop\apps\aws\1.16.220\_tmp\SourceDir\Amazon\AWSCLI\runtime\Lib\site-packages\awscli\examples\s3api\get-object-torrent.rst.  System error 0.  Verify that you have access to that directory.
=== Logging stopped: 18/08/2019  17:27:50 ===

**Comment by brandon93s** [comment]
Unable to reproduce:

![image](https://user-images.githubusercontent.com/4730164/63227585-f4188600-c1b5-11e9-98ff-9bf4e8c5bf72.png)

**Comment by codescrawl** [comment]
Looks like it's due to Mcafee Enterprise - uninstalling and reinstalling scoop didn't help.

This link gives some more information if anyone else is suffering the same issue.

https://github.com/aws/aws-cli/issues/2654
