### ISSUE TITLE
[git-with-openssh] Should expose bundled gpg in `$PATH`

### ISSUE THREAD

**Issue by CarterLi** [ScoopInstaller/Main#3685]
## Bug Report

**Package Name:** git-with-openssh

### Current Behaviour

1. `git-with-openssh` ( and maybe `git-for-windows` too ) includes a old version gpg. However it's not exposed ( not in $PATH ). For users come from *nix world ( like me ) doesn't know that.
2. Install gpg manually with `scoop install gpg`; set up gpg keys; and configure git to use that key.
3. `git commit -S` errors with  
```
gpg: skipped "MYKEY": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```

It turns out that despite a new gpg being installed, git-with-openssh still uses the gpg program that included internally. The error is hard to find and if you ask google they tell you to use gpg2

### Expected Behaviour

* Expose the path of the internal gpg in `$PATH` so users won't install new gpg

OR

* Metion `git-with-openssh` includes their gpg

OR

* Configure `git-with-openssh` uses user installed gpg by default 

### Additional context/output

N/A

### Possible Solution

N/A

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

**Additional software:** git version 2.36.1.windows.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-06-17T10:26:22.9532420+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Why not just create a shim for gpg itself? Exposing /usr/bin is a bad idea because it contains hundreds of binaries which can be problematic

**Comment by rasa** [comment]
Including many that conflict with Windows internal and external commands. See
https://github.com/ScoopInstaller/Scoop/issues/1290#issuecomment-284896316

**Comment by rasa** [comment]
To add the commands in `\usr\bin` to your PATH, you could install [git-all[(https://github.com/rasa/scoops/blob/master/bucket/git-all.json) instead.

Also note the above conflict list is far from complete: at least `hostname`, `ssh*`, `tar`, and `timeout` are missing. There may be more.
