### ISSUE TITLE
msys2 cannot be upgraded actually

### ISSUE THREAD

**Issue by ArchGuyWu** [ScoopInstaller/Main#3689]
## Bug Report

**Package Name:** msys2

### Current Behaviour

All the packages installed will lost after upgrading.
### Expected Behaviour

msys2 can be upgraded with all the packages installed preserved.
### Possible Solution

As msys2 can upgrade itself using its own package manager,so we can just modify the manifest.json file to pretend that it has been upgraded,so that user won't be confused by the output of 'scoop list msys2'.
### System details

**Windows version:** [e.g. 7, 8, 10]
10
**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.4
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
I'm actually surprised it took so long for someone to create an issue about this. 

The MSYS2 package cannot be managed by Scoop - you would have to put `persist` all top-level folders for that. I realized this the moment I installed it, but I did not remove it because people seemed to be okay with it.

Frankly I would just suggest using their installer.

**Comment by ArchGuyWu** [comment]
Yes,only persisting the home directory is okay,as people only use scoop to **uninstall** or **reinstall** it.
msys2 itself can handle the upgrade,thus we just need to **tell** scoop that msys2 has been upgraded.

According to the scripts of scoop,scoop gets app's current version from the file **manifest.json**,so if we only update manifest.json when a newer version is avaliable,scoop will think that the app has been upgraded.
And we should also do that for directory name.(Let scoop think that there's only the latest version left)

**Comment by ArchGuyWu** [comment]
I'll hold msys2 until this has been solved.

**Comment by ArchGuyWu** [comment]
But scoop will complain that msys2 is held when a newer version is avaliable.

**Comment by rashil2000** [comment]
Are you talking about the output of `scoop status`? I'm working on improving it 😉
