### ISSUE TITLE
Problem with aspell in main bucket

### ISSUE THREAD

**Issue by nmichalo** [ScoopInstaller/Main#3709]
## Bug Report

**Package Name:** aspell

### Current Behaviour

Libraries necessary for execution are not included.  Attempting to run "aspell --version" from cmd pops up System Error dialog windows with the messages: 
The code execution cannot proceed because libintl-8.dll was not found. Reinstalling the program may fix this issue.
The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this issue.
The code execution cannot proceed because libstdc++6.dll was not found. Reinstalling the program may fix this issue.

### Expected Behaviour
"aspell --version" should return (something like) :

@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)

### Possible Solution
Looking at the json file it seems to install:
"https://mirror.msys2.org/mingw/mingw32/mingw-w64-i686-aspell-0.60.8-2-any.pkg.tar.zst" and 
"https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-aspell-en-2020.12.07-1-any.pkg.tar.zst"

but the msys package has 4 dependencies that are not listed.

[mingw-w64-x86_64-gcc-libs] (https://packages.msys2.org/package/mingw-w64-x86_64-gcc-libs)
[mingw-w64-x86_64-gettext] (https://packages.msys2.org/package/mingw-w64-x86_64-gettext)
[mingw-w64-x86_64-libiconv] (https://packages.msys2.org/package/mingw-w64-x86_64-libiconv)
[mingw-w64-x86_64-libwinpthread-git] (https://packages.msys2.org/package/mingw-w64-x86_64-libwinpthread-git)

Adding these to the install may fix the issue.

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** 5.1.19041.1682

**Additional software:** 

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-06-24T14:42:35.0466421-04:00"
}

```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/pull/3517#pullrequestreview-948670019 

/cc @issaclin32

**Comment by issaclin32** [comment]
Thank you for reporting. The problem has been fixed in https://github.com/ScoopInstaller/Main/commit/788b647fc598ab3dc57673118b6b60a82676d0f6

It turns out that I misunderstood that *aspell* does not require extras libs because I have [mingw-winlibs](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw-winlibs.json) installed, which has `libiconv`, `libwinpthread`, etc. in it.

**Comment by rashil2000** [comment]
All the dependencies will now have to be updated manually. This was the exact reason why MSYS2 packages were removed from this bucket in https://github.com/ScoopInstaller/Main/issues/2933 😢

**Comment by issaclin32** [comment]
> All the dependencies will now have to be updated manually. This was the exact reason why MSYS2 packages were removed from this bucket in #2933 😢

Yeah. Sadly it is the case for now.

I think I should use `checkver.script` for this package, and make sure that when *ASpell* updates, all the dependencies are updated to the latest version, so that we can avoid potential problems due to mismatched version of the libs.

**Comment by rashil2000** [comment]
> I think I should use `checkver.script` for this package, and make sure that when _ASpell_ updates, all the dependencies are updated to the latest version, so that we can avoid potential problems due to mismatched version of the libs.

Hmm, or there's an alternative way described here: https://github.com/ScoopInstaller/Scoop/pull/4533#issuecomment-981154273

**Comment by issaclin32** [comment]
I removed `autoupdate` (only kept `checkver`) due to stability concerns.

**Comment by sitiom** [comment]
> I think I should use `checkver.script` for this package, and make sure that when _ASpell_ updates, all the dependencies are updated to the latest version, so that we can avoid potential problems due to mismatched version of the libs.

I have done this for [`qrencode`](https://github.com/ScoopInstaller/Main/blob/master/bucket/qrencode.json)
