### ISSUE TITLE
Windows 10 May 2019 Update break python

### ISSUE THREAD

**Issue by linsui** [ScoopInstaller/Main#372]
See https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor

What can we do? Show a note or remove python installer from `%LocalAppdata%\Microsoft\WindowsApps` ?

**Comment by issaclin32** [comment]
How about describing the problem in `notes`, and let user remove the *Microsoft store's Python installer* **by running a batch file or registry file**?
(similar to the case of [R Language](https://github.com/ScoopInstaller/Main/blob/master/bucket/r.json))

We can use `remove-windows-store-python-installer.ps1` and `restore-windows-store-python-installer.ps1` to block/unblock *Microsoft store's Python installer*. Put these 2 ps1 scripts in `bin`, and put `restore-windows-store-python-installer.ps1` in `uninstaller.script`.

The notes may look like this:
```
Notes
---
Windows 10 now includes Microsoft Store's Python in the PATH variable, 
which causes Microsoft store to be called while user runs 'python' in command line.

You can run 'remove-windows-store-python-installer' to block Microsoft store's Python installer, 
and run 'restore-windows-store-python-installer.reg' to restore the change.
```

Also, I don't think blocking *Microsoft store's Python installer* without telling the user is a good idea. To my understanding, a general rule of `Scoop` is to do **least harm** to your system. `Scoop` tends not to change any system configurations, unless it is (1) unavoidable, or (2) the user knows what he/she is doing, and explicitly does it.

**Comment by linsui** [comment]
It seems that we can't remove the file manually at all... So maybe we'd better add such a note

```
Please go to Settings -> Apps & Features -> App execution aliases and ensure that 'python.exe' and 'python3.exe' is disabled.
```
