### ISSUE TITLE
[Request] Add omnisharp-net6, omnisharp-http-net6

### ISSUE THREAD

**Issue by Ill1** [ScoopInstaller/Main#3728]
### Criteria

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:**  
omnisharp-net6, omnisharp-http-net6

**Description:**  
[OmniSharp servers that run on .NET 6 SDK](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#1380---2021-12-15)  
Packages already exist for [omnisharp](https://github.com/ScoopInstaller/Main/blob/master/bucket/omnisharp.json) and [omnisharp-http](https://github.com/ScoopInstaller/Main/blob/master/bucket/omnisharp-http.json).

**Homepage:**  
[Omnisharp-Roslyn](https://github.com/OmniSharp/omnisharp-roslyn)

**Download link(s):**  
[omnisharp-win-x64-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.0/omnisharp-win-x64-net6.0.zip)
[omnisharp-win-x86-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.0/omnisharp-win-x86-net6.0.zip)
[omnisharp.http-win-x64-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.0/omnisharp.http-win-x64-net6.0.zip)  
[omnisharp.http-win-x86-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.0/omnisharp.http-win-x86-net6.0.zip)

**Some indication of popularity/repute:**  385 forks, around 1300 stars

**Comment by Ill1** [comment]
Open to feedback if there's a better way than having 4 seperate installs for Omnisharp i.e.  
omnisharp, omnisharp-net6  
omnisharp-http and omnisharp-http-net6.

Per [https://www.strathweb.com/2022/01/hello-omnisharp-on-net-6-0/](https://www.strathweb.com/2022/01/hello-omnisharp-on-net-6-0/)
> Note that OmniSharp supports older .NET/.NET Core versions as well, as long as you have the necessary SDK installed, it's just for its own startup it requires you to have .NET 6.0 SDK available.

Will mean that users without dotnet6.0sdk will still want to keep using the older version.

**Comment by Ill1** [comment]
Okay - the net6 version goes to the versions bucket instead.

For the Main bucket, what about having a notes-section in both that says:
> For omnisharp-net6, please install 'versions/omnisharp-net6'

**Comment by rashil2000** [comment]
> For the Main bucket, what about having a notes-section in both 

Yes, that'd be good
