### ISSUE TITLE
7zip@22.00: decompress error

### ISSUE THREAD

**Issue by JingYu-Kylin** [ScoopInstaller/Main#3733]
#### Scoop Configuration

```json
//# Your configuration here
```

Updating '7zip' (21.07 -> 22.00)
Downloading new version
Loading 7z2200-x64.msi from cache
Checking hash of 7z2200-x64.msi ... ok.
Loading 7z2200-x64.msi from cache
Extracting 7z2200-x64.msi ... ERROR Exit code was 1618!
Log file:
  D:\Applications\Scoop\apps\7zip\22.00\msi.log

Please try again or create a new issue by using the following link and paste your console output:

**Comment by issaclin32** [comment]
Code `1618` for msi means: Another installation is already in progress.

Could you **(1)** restart your PC, and **(2)** install again, to see if the problem still exists?
