### ISSUE TITLE
Autocompletion for commands of scoop

### ISSUE THREAD

**Issue by GarciaPL** [ScoopInstaller/Main#374]
Hi, 

I am not sure if it's feasible to add this feature, but maybe it's a way to enrich scoop that all the commands might be autocompleted by hitting Tab ? Maybe it's not a matter of scoop itself, but terminal software running on Windows ? Thank you for an explanation in advance.

**Comment by Ash258** [comment]
`scoop install https://github.com/Ash258/scoop-Ash258/raw/master/bucket/scoop-completion.json`

https://github.com/liuzijing97/scoop-completion/

**Comment by r15ch13** [comment]
It's not supported by Scoop itself but there is an implemention created by @liuzijing97
See: https://github.com/liuzijing97/scoop-completion

Related: https://github.com/lukesampson/scoop/issues/1439 and https://github.com/lukesampson/scoop/issues/2597

@Ash258 was faster ... :grin:

**Comment by Ash258** [comment]
This could be added to core in future, but I do not have time right now to implement it into core with more optimizations.
