### ISSUE TITLE
gitlab-runner needs Git accessible by the SYSTEM user if the install command has no option

### ISSUE THREAD

**Issue by Slug-V** [ScoopInstaller/Main#3757]
## Bug Report

**Package Name: gitlab-runner**

### Current Behaviour

- confirm it's fine with Chocolatey, and uninstall it
    - note: Chocolatey's uninstall script for gitlab-runner didn't remove simlink. so I removed it manually from C:\ProgramData\Chocolatey\bin
- don't forget to run `git config --global credential.helper manager-core`
1. run `scoop install gitlab-runner`
2. run `New-Item -ItemType Directory C:\GitLab-Runner`
3. Set-Location there and elevate (using gsudo)
4. run `gitlab-runner register` , `gitlab-runner install`, and `gitlab-runner start` 
    - command `gitlab-runner install` makes a Windows Service, which uses the SYSTEM account
    - I chose `shell` executor, but any executor is affected because this is an issue about checking out the source.
5. start CI from GitLab
6. **get fail with the message which means the runner cannot access any git binary**
```
Line |
 227 |  & "git" "config" "-f" "C:\GitLab-Runner\builds\[runner id]\0\[username]\winfo **
     |    ~~~~~
     | The term 'git' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR: Job failed: exit status 1
```

7. open gitlab-runner in services.msc
8. change logon accout from local system account to my personal account
9. restart CI job
10. in the first time run, the runner makes a dialog to choose credential helper but gracefully runs if it's chosen
    - I don't know why this prompt appeared even if I run `git config --global credential.helper manager-core`
    - this behaviour which won't occur with Chocolatey will be another issue, but I couldn't find what to correct about this
-  (note: I still have an issue about using a proxy in `dotnet` command, but it obviously unrelated to this)

### Expected Behaviour

run without any issue with `gitlab-runner register`, `gitlab-runner install`, and `gitlab-runner start`.

### Possible Solution

`gitlab-runner install` have an option to specify a service-run user.
adding note `gitlab-runner install --user <your username> --password <your password>` instead of `gitlab-runner install` for using git which is installed by Scoop.

Or, ~~set the installing user's Scoop PATH into the SYSTEM account or machine-wide.~~ **edit: suggest [global install of git](https://github.com/ScoopInstaller/Main/issues/3757#issuecomment-1186845648) for user**.

### System details

**Windows version: 10 Pro 21H2**, build 19044.1806

**OS architecture: 64bit**

**PowerShell version: 7.2.5**

<details><summary>raw output of `"$($PSVersionTable.PSVersion)"` </summary>

```
> $($PSVersionTable.PSVersion)

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      5
```
</details>

**Additional software: Git 2.37.1.windows.1**

<details>
<summary>other Scoop apps</summary>

```
> scoop list
Installed apps:

Name              Version          Source Updated             Info
----              -------          ------ -------             ----
7zip              22.01            main   2022-07-18 08:37:03
aria2             1.36.0-1         main   2022-07-05 16:17:16
git               2.37.1.windows.1 main   2022-07-13 08:34:14
gitlab-runner     15.1.0           main   2022-07-18 09:08:38
gsudo             1.3.0            main   2022-07-05 16:18:30
keepassxc         2.7.1            extras 2022-07-05 15:24:38
nextcloud         3.5.2            extras 2022-07-11 16:59:43
peazip            8.7.0            extras 2022-07-12 13:31:58
rocketchat-client 3.8.7            extras 2022-07-05 16:18:55
vcredist2022      14.32.31332.0    extras 2022-07-06 13:27:49
winmerge          2.16.20          extras 2022-07-05 16:19:00
wsl-ssh-agent     1.6.1            extras 2022-07-06 11:57:14
```
</details>

from MS Store: Windows Terminal 1.13.11431.0, CrystalDiskInfo 8.17.3

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-07-18T08:32:19.2318840+09:00",
  "proxy": "[server ip]:[portnum]",
  "aria2-warning-enabled": false,
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
> Or, set the installing user's Scoop PATH into the SYSTEM account or machine-wide.

You can do this by installing git as a global app, i.e. `scoop install git --global`. This command needs to be run as admin.

**Comment by Slug-V** [comment]
@rashil2000 Thank you. I updated.

**Comment by rashil2000** [comment]
So is your issue resolved?

**Comment by Slug-V** [comment]
Nope.
Any gitlab-runner user will face this issue unless change [the note](https://github.com/ScoopInstaller/Main/blob/14fadfeb822c56ed04be523f781ffe6fa25cc4eb/bucket/gitlab-runner.json#L6).

**Comment by rashil2000** [comment]
Okay, can you make a PR to update note?

**Comment by Slug-V** [comment]
@rashil2000 Thank you.

**Comment by rashil2000** [comment]
Welcome :)
