### ISSUE TITLE
less@551: hash check failed

### ISSUE THREAD

**Issue by m410** [ScoopInstaller/Main#376]
```
scoop install less
Installing 'less' (551) [64bit]
less-551-win32-static-x86.7z (3.7 KB) [==============================================================================================================================================================] 100%
Checking hash of less-551-win32-static-x86.7z ... ERROR Hash check failed!
App:         main/less
URL:         https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    8ec4eb52b6f8cedf48d18491fd161ea9039ba40fdbd8fb466aa978c55cf5a372
Actual:      1cdb710e9f30742a340f5d598153e5b28dd2a10f857cf2257ba265ef5c1eff74

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=less%40551%3a+hash+check+failed

**Comment by JTBrinkmann** [comment]
The website now gives SSL errors and appears to not host the files anymore.

**Comment by rasa** [comment]
It seems it’s an expired cert. see #150

**Comment by jkrehm** [comment]
I don't think that's the only issue. I don't think the file is present at all. I get a 404 when I tell my browser that it's ok to ignore the invalid cert. I think the file is gone entirely.

**Comment by jeffrson** [comment]
Currently they have the files, but only provide a self-signed certificate.

Is there any way to disable certificate check temporarily? With and/or without aria2c?

**Comment by jkrehm** [comment]
I contacted the email address listed on the site and asked that the maintainer consider switching to LetsEncrypt (vs self-signed). With some luck s/he will be willing to and we'll be able to connect without having to reduce security.
