### ISSUE TITLE
nim@1.6.6 nimsuggest.exe crashes with missing .dll error

### ISSUE THREAD

**Issue by vincentmathis** [ScoopInstaller/Main#3762]
### Current Behaviour

Running `nimsuggest` in a terminal does nothing, no output at all. Trying to open the .exe file manually spawns an error dialog:

```
---------------------------
nimsuggest.exe - System Error
---------------------------
The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

Installing the `nim` package also installs `gcc` which contains the dll:  `~\scoop\apps\gcc\current\x86_64-w64-mingw32\lib\libwinpthread.dll`, just without the `-1` at the end of the filename. Copying the dll and adding `-1` into the filename didn't fix the problem though.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**Comment by rashil2000** [comment]
Hi, can you try again after running these commands:
```
scoop uninstall gcc
scoop install mingw-winlibs
```

**Comment by vincentmathis** [comment]
> Hi, can you try again after running these commands:
> 
> ```
> scoop uninstall gcc
> scoop install mingw-winlibs
> ```

This fixed the problem, thank you very much.
