### ISSUE TITLE
mvndaemon@0.8.0: download via aria2 failed

### ISSUE THREAD

**Issue by xiangagou** [ScoopInstaller/Main#3777]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://dist.apache.org/repos/dist/release/maven/mvnd/0.8.0/maven-mvnd-0.8.0-windows-amd64.zip
    referer=https://dist.apache.org/repos/dist/release/maven/mvnd/0.8.0/
    dir=C:\Users\SYLINCOM\scoop\cache
    out=mvndaemon#0.8.0#https_dist.apache.org_repos_dist_release_maven_mvnd_0.8.0_maven-mvnd-0.8.0-windows-amd64.zip

ERROR & 'C:\Users\SYLINCOM\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\SYLINCOM\scoop\cache\mvndaemon.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19168 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7890'

**Comment by rashil2000** [comment]
Please disable aria2 and try again
