### ISSUE TITLE
WAPM is not installed with wasmer

### ISSUE THREAD

**Issue by wmstack** [ScoopInstaller/Main#3785]
https://github.com/ScoopInstaller/Main/blob/aa2eee1b1e4ca4008165ead195d29e85faf25543/bucket/wasmer.json#L16-L19

Hello, I would've liked WAPM to be installed with WASMER but I see that it is not added by default. Can you please add it to the WASMER version?

Edit: Wax can't even run because it requires WAPM, which is not installed by default.

@syrusakbary
@Ash258
@r15ch13 
@HUMORCE

**Comment by HUMORCE** [comment]
https://github.com/HUMORCE/nuke/blob/master/bucket/wapm-cli.json

I do this in my own bucket earlier but forgot to make PR to the main bucket.
