### ISSUE TITLE
[Request] Bitwarden CLI Repo Has Changed

### ISSUE THREAD

**Issue by BinaryWizard904** [ScoopInstaller/Main#3793]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [X] a non-GUI tool
- [X] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [X] the latest stable version of the program
- [X] the full version i.e. not a trial version
- [X] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** bitwarden-cli

**Description:** The powerful command-line tool (CLI) to write and execute scripts on your Bitwarden vault.

**Homepage:** https://bitwarden.com/

**Download link(s):** https://github.com/bitwarden/clients/releases/download/cli-v2022.6.2/bw-windows-2022.6.2.zip

**Updates an existing manifest**
Bitwarden consolidated all of their clients (except the mobile application) into a single repository: https://github.com/bitwarden/clients.  All current and future releases of bitwarden-cli will be released there.  Unfortunately, not all releases relate to bitwarden-cli, so the default scoop GitHub behavior of querying https://github.com/bitwarden/clients/releases/latest does not work in this case.  Moreover the default version parsing RegEx no longer works either as we must prefix the version with 'cli-v' instead of 'v'.

I have created and tested an [alternative version](https://github.com/BinaryWizard904/Main/blob/cf157f990c58ad30e686117c77b7363ccb37d459/bucket/bitwarden-cli.json) of the manifest that parses the releases.atom feed of that repository for the latest version of the cli. I would be happy to issue a PR to update the main repo if you'd like.

**Comment by niheaven** [comment]
Submit a PR, thx
