### ISSUE TITLE
[Request] lf: add lfcd to shims

### ISSUE THREAD

**Issue by Markov99** [ScoopInstaller/Main#3796]
[lf](https://github.com/gokcehan/lf) [manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/lf.json) should add [lfcd.ps1](https://github.com/gokcehan/lf/blob/master/etc/lfcd.ps1) and/or [lfcd.cmd](https://github.com/gokcehan/lf/blob/master/etc/lfcd.cmd) (there are also versions for other shells) to shims. `lfcd` provides a way to change working directory to the last directory in `lf` on exit. Which is a common [use case](https://github.com/gokcehan/lf/issues/631).

**Comment by rashil2000** [comment]
The lfcd scripts are not included in the release archive. You would need to download them separately, and then:
- copy them in the shims folder during pre_install
- delete them from shims folder during pre_uninstall
