### ISSUE TITLE
[Request] Add ripgrep-all

### ISSUE THREAD

**Issue by Kreijstal** [ScoopInstaller/Main#3808]
## Package Request
This packages is a plugin for ripgrep, but can search much more than plain text.
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** ripgrep-all

**Description:** supercharges ripgrep by allowing it text in pdf files, it can ocr images, etc.. 

**Homepage:** [a URL/link]

**Download link(s):** https://github.com/phiresky/ripgrep-all

**Some indication of popularity/repute:** 4.8k Stars and 108 Forks

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/rga.json
