### ISSUE TITLE
qemu 7.1.0-rc1 from Aug 5th has missing DLLs

### ISSUE THREAD

**Issue by ciarancourtney** [ScoopInstaller/Main#3813]
## Bug Report

qemu

### Current Behaviour

fails with `error while loading shared libraries: api-ms-win-core-path-l1-1-0.dll: cannot open shared object file: No such file or directory`

### Possible Solution

Update manifest to fixed installer `qemu-w64-setup-20220809.exe` from https://qemu.weilnetz.de/w64/

P.s. this makes me think the autoupdate attempt is failing if it works by date matching.

**Comment by rashil2000** [comment]
Looks like a one-off problem. Can you make a PR to update the URL to 20220809?

**Comment by ciarancourtney** [comment]
Looks like weilnetz just released rc2, so maybe that'll be picked up automatically by GH soon?

**Comment by rashil2000** [comment]
Updated https://github.com/ScoopInstaller/Main/commit/3cd53242c0aad01af6e3f2cb8045953232e1c122
