### ISSUE TITLE
Can't get Sudo installed.

### ISSUE THREAD

**Issue by spookymyo** [ScoopInstaller/Main#3818]
I'm trying to get sudo installed via scoop but it won't work. 

Any help would be much appreciated.

Here's the console info:

PS C:\Users\spook\Downloads\PC Programs\EXE> scoop update
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
 * 8639c9fce stoplight-prism: Update to version 4.10.2                   9 minutes ago
 * cad2f7420 monero-cli: Update to version 0.18.1.0                      9 minutes ago
 * a4588009d marp: Update to version 2.1.1                               9 minutes ago
 * 54d8fda3c jfrog: Update to version 2.24.1                             9 minutes ago
 * b8c927acd jdtls: Update to version 1.15.0-202208111822                9 minutes ago
 * 5e5765988 fnproject: Update to version 0.6.22                         9 minutes ago
 * f2de1b7bb flyctl: Update to version 0.0.370                           10 minutes ago
 * 9ee382dc0 deno: Update to version 1.24.3                              10 minutes ago
 * dc8ad0a53 dapr-cli: Update to version 1.8.1                           10 minutes ago
 * d33369c86 conan: Update to version 1.50.2                             10 minutes ago
 * 384513e6b cloudflared: Update to version 2022.8.0                     10 minutes ago
 * 6eaf2e6dc circleci-cli: Update to version 0.1.20500                   10 minutes ago
 * 52c9d31a9 azure-functions-core-tools: Update to version 4.0.4704      10 minutes ago
 * 1b41c89e8 argocd: Update to version 2.4.9                             10 minutes ago
Scoop was updated successfully!

PS C:\Users\spook\Downloads\PC Programs\EXE> scoop install sudo
WARN  Purging previous failed installation of sudo.
ERROR 'sudo' isn't installed correctly.
Removing older version (0.2020.01.26).
'sudo' was uninstalled.
Installing 'sudo' (0.2020.01.26) [64bit] from main bucket
Starting download with aria2 ...
Download: 08/11 16:41:05 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/psutils/c7Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b6fbaf|ERR |       0B/s|C:/Users/spook/scoop/cache/sudo#0.2020.01.26#https_raw.githubusercontent.com_lukesampson_psutils_c7116ac143ca81f223e6091d0974f45ac241eb1d_sudo.ps1
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/sudo.ps1
    referer=https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/
    dir=C:\Users\spook\scoop\cache
    out=sudo#0.2020.01.26#https_raw.githubusercontent.com_lukesampson_psutils_c7116ac143ca81f223e6091d0974f45ac241eb1d_sudo.ps1

ERROR & 'C:\Users\spook\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\spook\scoop\cache\sudo.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3060 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=sudo%400.2020.01.26%3a+download+via+aria2+failed
PS C:\Users\spook\Downloads\PC Programs\EXE> PP

**Comment by rashil2000** [comment]
Please disable aria2 and try again
