### ISSUE TITLE
ERROR Application "git" is still running. Close all instances and try again.

### ISSUE THREAD

**Issue by onthebusiness** [ScoopInstaller/Main#3820]
Scoop update git

**Comment by rashil2000** [comment]
Please close all possible applications on your PC and try again.

**Comment by onthebusiness** [comment]
It's doesn't help me

**Comment by rashil2000** [comment]
Have you tried restarting?

**Comment by onthebusiness** [comment]
Yes, i try to restart pc and also killing all git.exe processes, but when I run `scoop update git` I gets the same error

**Comment by onthebusiness** [comment]
I resolve problem with killing gpg-agent.exe
