### ISSUE TITLE
cacert@2019-08-28: hash check failed

### ISSUE THREAD

**Issue by mikepruett3** [ScoopInstaller/Main#383]
Checking hash of cacert-2019-08-28.pem ... ERROR Hash check failed!
App:         main/cacert
URL:         https://curl.haxx.se/ca/cacert-2019-08-28.pem#/cacert.pem
First bytes: 23 23 0A 23 23 20 42 75
Expected:    cb2eca3fbfa232c9e3874e3852d43b33589f27face98eef10242a853d83a437a
Actual:      38b6230aa4bee062cd34ee0ff6da173250899642b1937fc130896290b6bd91e3

**Comment by heikopanjas** [comment]
Checking hash of cacert-2019-08-28.pem ... ERROR Hash check failed!
App:         main/cacert
URL:         https://curl.haxx.se/ca/cacert-2019-08-28.pem#/cacert.pem
First bytes: 23 23 0A 23 23 20 42 75
Expected:    cb2eca3fbfa232c9e3874e3852d43b33589f27face98eef10242a853d83a437a
Actual:      38b6230aa4bee062cd34ee0ff6da173250899642b1937fc130896290b6bd91e3
