### ISSUE TITLE
Posgresql not working psql to log in

### ISSUE THREAD

**Issue by jhoriascos** [ScoopInstaller/Main#3832]
## Bug Report
**Package Name:** posgresql

Hello,

I have installed the latest version of postgresql (14.5) with scoop then I got the installation successful message.
 
Then I have configured with the notes or information provided by the package on how to build a new PostgreSQL service? and how to start a PostgreSQL service?

In the end when in the CMD, I go to run 'psql -U postgres'. I get the following error:

`psql: error: falló la conexión al servidor en «localhost» (::1), puerto 5432: FATAL:  role "postgres" does not exist`

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**  5.1.22000.832

![image](https://user-images.githubusercontent.com/66481268/184995219-856a4f85-84e3-400c-b31d-aa6014df0855.png)

![image](https://user-images.githubusercontent.com/66481268/184995081-b0861193-8abe-4510-ad8a-eaa8a350e2d5.png)

how can I enter the psql with the postgres user, I do not know if I need to configure something and also if possible can you help me to load the Admin 4 that comes with the same package that I have noticed that it does not load the data.

**Comment by rashil2000** [comment]
You need to create the use using the `createuser` command before using psql. For more details see https://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist

**Comment by jhoriascos** [comment]
I used the command *`createuser -s postgres,`* but I didn't get any result. I keep getting the same error.

![image](https://user-images.githubusercontent.com/66481268/185177982-a2f02c3f-80be-4b89-8585-945bd6569b8b.png)

**Comment by rashil2000** [comment]
Does this issue happen if you install Postgresql from their official installer?

**Comment by jhoriascos** [comment]
No, I use the same version on my Macbook Pro with brew and it's fine, but I recently installed coop as application manager for windows and I thought I made a mistake in some step of the installer.  I found a solution that specifies delete the data folder, create a new data with permissions and after that the psql command is fine, but on inspection I notice that in the windows root C: it has installed a new psql and not in the postgresql application folder that scoop created and I also found that it deletes the admin 4 shorcut. 

https://aeadedoyin.medium.com/getting-started-with-postgresql-on-windows-201906131300-ee75f066df78

**Comment by rashil2000** [comment]
The reason I ask if you used the official installer is that this problem is unlikely to be related to Scoop. I'm not familiar with PostgreSQL and haven't used it, and its setup on Windows will obviously be different from Unix systems, whether you use Scoop or not.

**Comment by JuanMM94** [comment]
Installer also doesn't create a Service, which is remediated with `pg_ctl start`. It would be nice to have the automatic service, though. Original bug still applies for me as well.

**Comment by rminderhoud** [comment]
I had the same issue on Windows 10 + PostgreSQL 14.5 installed via scoop. Here was how I resolved the issue:

1. Stop the server if it is running
2. Delete contents of `C:\Users\<user>\scoop\persist\postgresql\data` folder
3. Run `C:\Users\<user>\scoop\apps\postgresql\current\bin\initdb.exe`
4. Run `C:\Users\<user>\scoop\apps\postgresql\current\bin\createuser.exe -s postgres`

After this the default superuser `postgres` exists with a blank password and connections work.

**Comment by YauHsien** [comment]
Full check under PowerShell 7 (7.2.7)
|Name|Version|Bucket|Status|
|----|-------|------|------|
|postgresql|14.5|main|Fixed|
|postgrest|10.1.0|main|N/A|
|postgresql10|10.22|versions|Working|
|postgresql11|11.17|versions|Not working|
|postgresql12|12.12|versions|Not working|
|postgresql13|13.8|versions|Not working|
