### ISSUE TITLE
oh-my-posh@8.31.0: decompress error

### ISSUE THREAD

**Issue by haonny** [ScoopInstaller/Main#3834]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by haonny** [comment]
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\Users\moon\scoop\apps\scoop\current\lib\decompress.ps1:44 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\moon\scoop\apps\oh-my-posh\8.31.0\posh-windows-amd64.7z.
Log file:
  ~\scoop\apps\oh-my-posh\8.31.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=oh-my-posh%408.31.0%3a+decompress+error

**Comment by rashil2000** [comment]
Unable to reproduce. 
![image](https://user-images.githubusercontent.com/46838874/185076097-b91a1e5d-b2c0-415e-abda-de20fd68d6c9.png)

Please clear your cache and try again.

**Comment by haonny** [comment]
Thank you,I had take this question already by change my user name.
