### ISSUE TITLE
[Request] oha - HTTP load generator, inspired by rakyll/hey with tui animation

### ISSUE THREAD

**Issue by beatbrot** [ScoopInstaller/Main#3840]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** oha

**Description:** oha is a tiny program that sends some load to a web application and show realtime tui inspired by [rakyll/hey](https://github.com/rakyll/hey)

**Homepage:** [[a URL/link]](https://github.com/hatoo/oha)

**Download link(s):** [[URL(s)/link(s)]](https://github.com/hatoo/oha/releases)

**Some indication of popularity/repute:** 1.2k stars, featured a lot at https://fasterthanli.me/

I already have it working on my machine and will happily submit a PR for it :) Everything works, including autoupdate.

**Comment by rashil2000** [comment]
Please make a PR!
