### ISSUE TITLE
[Request] Swift Compiler

### ISSUE THREAD

**Issue by fwcd** [ScoopInstaller/Main#3844]
## Package Request

It would be cool to have the Swift compiler as a package.

### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** `swift`

**Description:** The toolchain for Apple's programming language Swift

**Homepage:** https://www.swift.org/

**Download link(s):** https://download.swift.org/swift-5.6.2-release/windows10/swift-5.6.2-RELEASE/swift-5.6.2-RELEASE-windows10.exe

**Some indication of popularity/repute:** 60k stars on GitHub (and generally pretty well-known): https://github.com/apple/swift

**Comment by rashil2000** [comment]
Hi! Could you make a PR?

**Comment by KrisSchneider** [comment]
The installer type is unknown, it's not an inno setup or WiX. I believe this package should be implemented as a non-portable due to the package's unportable functionality.

**Comment by rashil2000** [comment]
Does it work with Dark? Like python: https://github.com/ScoopInstaller/Main/blob/master/bucket/python.json

**Comment by KrisSchneider** [comment]
I'll try it with dark uncompiler.

**Comment by KrisSchneider** [comment]
@rashil2000 it works with dark.exe

**Comment by rashil2000** [comment]
Hmm, so we'll need to do something like python

**Comment by KrisSchneider** [comment]
This is the command I used to extract the files from the wix archive:  
`dark.exe 'C:\Users\krist\Downloads\swift-5.7-RELEASE-windows10.exe' -x 'C:\Users\krist\Downloads\3'`

This is what it results in:
![(firefox)7194M2_09-26-2022](https://user-images.githubusercontent.com/101912712/192353747-86074968-ca21-4927-9af6-4b25edf67e31.jpg)

![(%pn)-v2h4d5_09-26-2022](https://user-images.githubusercontent.com/101912712/192353670-7c4b75b6-d1e0-4c8e-b781-3d21647f33c6.jpg)

![(%pn)-R354E3_09-26-2022](https://user-images.githubusercontent.com/101912712/192353837-0c935de3-d22b-4af2-9b10-653b81ea7647.jpg)
