### ISSUE TITLE
lynx installation error

### ISSUE THREAD

**Issue by onurbbr** [ScoopInstaller/Main#3846]
## Bug Report

**Package Name:** lynx

### Current Behaviour

Installation fails due to OpenSSL Light not being found.

### Expected Behaviour

Hassle-free installation.

### Possible Solution
Update OpenSSL_Light to 1.1.1q from [here](https://slproweb.com/download/Win32OpenSSL_Light-1_1_1q.exe)

### System details

**Windows version:** 11

**OS architecture:**  64-bit

**PowerShell version:** 7.2.6

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-08-21T12:39:58.6633165+03:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Please make a PR for the fix!
