### ISSUE TITLE
Miktex package does not create all shims

### ISSUE THREAD

**Issue by eberkund** [ScoopInstaller/Main#3850]
## Bug Report

**Package Name:** miktex/latex

### Current Behaviour

Only `miktex-console` is added as a shim to the PATH

### Expected Behaviour

I expect shims to be created for all bin files, such as `pdflatex`

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
The folder `texmfs\\install\\miktex\\bin\\x64` is appended to the PATH variable, so all binaries should be accessible. Just restart your shell.
