### ISSUE TITLE
curl install not working in Windows Server 2012R2

### ISSUE THREAD

**Issue by axtens** [ScoopInstaller/Main#3854]
## Bug Report

**Package Name:** 
curl

### Current Behaviour
>scoop install curl
Installing 'curl' (7.84.0_9) [64bit] from main bucket
The SSL connection could not be established, see inner exception.
URL https://curl.haxx.se/windows/dl-7.84.0_9/curl-7.84.0_9-win64-mingw.tar.xz is not valid
### Expected Behaviour
Installation
### System details

**Windows version:** [e.g. 7, 8, 10]
11

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.2

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-08-24T15:34:16.8230419+08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
See https://github.com/curl/curl-www/issues/182
