### ISSUE TITLE
llvm-14.0.6 - failing to install 

### ISSUE THREAD

**Issue by cloudyd3** [ScoopInstaller/Main#3865]
## Bug Report

**Package Name:** llvm-14.0.6

### Current Behavior
Installation fails because of this
`Creating shim for 'clang-import-test'.
Can't shim 'bin\clang-import-test.exe': File doesn't exist.`

### Expected Behavior
Installation should be completed successfully.

### Additional context/output
<details open>
<summary>output</summary>

`Installing 'llvm' (14.0.6) [64bit] from backit bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1738ba|OK  |   9.0MiB/s|C:/Users/hedhe.DESKTOP-3UGK7IV/scoop/cache/llvm#14.0.6#https_github.com_llvm_llvm-project_releases_download_llvmorg-14.0.6_LLVM-14.0.6-win64.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of LLVM-14.0.6-win64.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...
Linking ~\scoop\apps\llvm\current => ~\scoop\apps\llvm\14.0.6
Creating shim for 'clang'.
Creating shim for 'clang++'.
Creating shim for 'clang-apply-replacements'.
Creating shim for 'clang-change-namespace'.
Creating shim for 'clang-check'.
Creating shim for 'clang-cl'.
Creating shim for 'clang-cpp'.
Creating shim for 'clangd'.
Creating shim for 'clang-doc'.
Creating shim for 'clang-extdef-mapping'.
Creating shim for 'clang-format'.
Creating shim for 'clang-import-test'.
Can't shim 'bin\clang-import-test.exe': File doesn't exist.`
</details>

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.3.0.preview.7

#### Scoop Configuration
```json
{
  "lastupdate": "2022-09-01T04:42:29.3171451+03:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Please open this issue in the backit bucket. Or install llvm from main bucket by `scoop install main/llvm`.
