### ISSUE TITLE
Installation of busybox fails with SSL connection error

### ISSUE THREAD

**Issue by Etherian** [ScoopInstaller/Main#3868]
## Bug Report

**Package Name:** busybox & busybox-lean

### Current Behaviour

Attempting to install the `busybox` or `busybox-lean` packages results in an SSL error. I received the same error when I tried a few months ago, with busybox build `4621-gf3c5e8bc3`.

```
> scoop install busybox
Installing 'busybox' (4716-g31467ddfc) [64bit]
The SSL connection could not be established, see inner exception.
URL https://frippery.org/files/busybox/busybox-w64-FRP-4716-g31467ddfc.exe#/busybox.exe is not valid
```

```
> scoop install busybox-lean
Installing 'busybox-lean' (4716-g31467ddfc) [64bit] from main bucket
The SSL connection could not be established, see inner exception.
URL https://frippery.org/files/busybox/busybox-w64-FRP-4716-g31467ddfc.exe#/busybox.exe is not valid
```

### Expected Behaviour

Successful installation

### Additional context/output

All other packages I have tried install as expected.

Curl (via MSYS2) feels the site's certificate has expired
```
****@**** MINGW64 ~
$ curl -O https://frippery.org/files/busybox/busybox-w64-FRP-4716-g31467ddfc.exe#/busybox.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
```
but Firefox downloads the file without complaint.

### System details

**Windows version:** 7 SP1

**OS architecture:** 64bit

**PowerShell version:** 7.1.3

#### Scoop Configuration
``` json
{
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2022-09-02T16:33:03.1711716-04:00"
}
```

**Comment by rashil2000** [comment]
Some websites have removed support for Windows 7. This error looks related. See:

https://github.com/curl/curl-www/issues/182
and 
https://github.com/ScoopInstaller/Main/issues/3593

**Comment by Etherian** [comment]
Like described in https://github.com/curl/curl-www/issues/182, none of the ciphers accepted by https://frippery.org/ 

```
> sslscan https://frippery.org/

[ ... snipped ... ]

  Supported Server Cipher(s):
Preferred TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519 DHE 253
Accepted  TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519 DHE 253
Accepted  TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519 DHE 253
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  DHE-RSA-AES256-GCM-SHA384     DHE 4096 bits
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  DHE-RSA-AES128-GCM-SHA256     DHE 4096 bits

[ ... snipped ... ]
```

seem to be on the [list of ciphers supported by IE11 on Windows 7](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36). However, does Scoop depend on Internet Explorer's ciphers for TLS?

**Comment by rashil2000** [comment]
The underlying system libraries and methods used by PowerShell (which Scoop is written in) and Internet Explorer are the same. Hence the issue. 

As a last resort, you can install PowerShell Core and try installing busybox from there.

**Comment by Etherian** [comment]
Thanks. I'll see if I can find a workaround. If not, it shouldn't be too difficult to install it manually.

**Comment by Etherian** [comment]
Success!

With the following steps, I was able to successfully download and install `busybox-lean`. (Unfortunately, attempting to install `curl` still yields the same error. Maybe [haxx.se](https://curl.haxx.se/) uses a different set of ciphers?) I do not know which steps are important or if their order matters. This worked for Windows 7 SP1; the steps will likely be a little different for Windows 8.1 and Windows Server.

1. I installed update [KB3140245](https://catalog.update.microsoft.com/search.aspx?q=kb3140245) as described in [Update to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows](https://support.microsoft.com/en-au/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392)
2. I ran the [Easy Fix](https://support.microsoft.com/en-au/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392#bkmk_easy) to make the necessary registry changes.
3. I manually added the ["DisabledByDefault" registry entries](https://support.microsoft.com/en-au/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392#bkmk_easy_1) (Why these were not included as part of the "Easy Fix", I don't know).
4. I restarted my computer
    a. I attempted to install `busybox-lean` at this point, which failed, so I continued.
5. I installed [KB3020369](https://support.microsoft.com/en-us/topic/april-2015-servicing-stack-update-for-windows-7-and-windows-server-2008-r2-437ee749-51e0-6265-be9e-73fbd115d315) in preparation for KB3042058, [as suggested](https://support.microsoft.com/en-us/topic/microsoft-security-advisory-update-to-default-cipher-suite-priority-order-may-12-2015-bb018496-3161-2a28-d2e1-7c82cfef7a55#bkmk_prerequisites). (The download links are under "Method 2: Microsoft Download Center")
6. I installed [KB3042058](https://support.microsoft.com/en-us/topic/microsoft-security-advisory-update-to-default-cipher-suite-priority-order-may-12-2015-bb018496-3161-2a28-d2e1-7c82cfef7a55). (The download links are again under "Method 2: Microsoft Download Center")
7. I restarted my computer.
8. `scoop install busybox-lean` succeeded!

I hope this helps other people. Too bad it doesn't seem to work for `curl`.

**Comment by rashil2000** [comment]
Thanks @Etherian for the detailed write-up! Will be very useful for people who run into this in future.
