### ISSUE TITLE
[Error] Docker: Error response from daemon: failed to start service utility VM (createreadwrite): kernel 'C:\Program Files\Linux Containers\kernel' not found.

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Main#3878]
## Bug Report

**Package Name:** docker

### Current Behaviour
Docker failed to start service due to lack of directory.
Step to reproduce:
- open `cmd.exe` as admin and run `dockerd -D --experimental`
- open another terminal and pull sqlserver with `docker pull mcr.microsoft.com/mssql/server:2022-latest`
- run docker run `docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest`

### Expected Behaviour

No error anymore.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 

```
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/blob/934da8cb290c10b7249da2b148a4532bd2226df2/bucket/docker.json#L28
