### ISSUE TITLE
Elixir changed release notes and assets format

### ISSUE THREAD

**Issue by princemaple** [ScoopInstaller/Main#3886]
## Bug Report

**Package Name:** elixir

### Current Behaviour

Elixir 1.14 changed how it's released. Currently scoop is failing to install the latest version.

### Expected Behaviour

Expect to install latest version (1.14.0) successfully.

### Additional context/output

Scoop is not the only one taking the shot. [Renovate](https://docs.renovatebot.com/) is also failing.

### Possible Solution

https://discord.com/channels/557172283978809344/574965255470579714/1016881982854152262 Some replied on discord to add a new manifest. I posted on Elixir forum to explore whether the release change can be less destructive. https://elixirforum.com/t/elixir-1-14-github-release-format-change-causing-some-issues/50095.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-09-07T15:59:22.3508017+10:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "gh_token": "[REDACTED]"
}

```

**Comment by rashil2000** [comment]
The URL is now https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-25.zip and hash URL is https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-25.zip.sha256sum

Can you make a PR for this?

**Comment by princemaple** [comment]
> The URL is now https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-25.zip and hash URL is https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-25.zip.sha256sum
> 
> Can you make a PR for this?

Would this change prevent older versions from being installed?

**Comment by tech189** [comment]
Is elixir-otp-25 the recommended/default/stable edition? If so we should also add the other versions to Versions bucket.

**Comment by princemaple** [comment]
> Would this change prevent older versions from being installed?

Meaning for example 1.13.4

**Comment by princemaple** [comment]
> Is elixir-otp-25 the recommended/default/stable edition? If so we should also add the other versions to Versions bucket.

Default should normally be the lowest OTP version - OTP 23 for elixir 1.14

They are all stable though. They just need different versions of Erlang (OTP). Higher version of Erlang OTP can run lower version code. If Erlang 25 is installed, it's fine to install elixir 1.14 with OTP 23. If Erlang 24 is installed, you may encounter issues if you install elixir compiled with OTP 25.

Previously the precompiled was only with the lowest OTP. Now they provide multiple versions.

**Comment by rashil2000** [comment]
> Elixir v1.14 is the last version to support Erlang/OTP 23. Consider updating to Erlang/OTP 24 or Erlang/OTP 25.

It is worth noting that they recommend using the latest OTP 25 on their releases page.

> Would this change prevent older versions from being installed?

Sadly yes.

**Comment by princemaple** [comment]
> It is worth noting that they recommend using the latest OTP 25 on their releases page

Huh, maybe it's finally time to default to latest OTP now. Great.

**Comment by princemaple** [comment]
I'm going to wait a bit to see if there are other suggestions or if the elixir community decides to fix it for the tools, before sending a PR.

Thanks 👍

**Comment by simonmcconnell** [comment]
where does the action (e.g. for this [commit](https://github.com/ScoopInstaller/Main/commit/0d4780034a005170f10c38fbaecac75b08f95675)) that was updating the manifest live?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/blob/master/.github/workflows/excavator.yml

**Comment by princemaple** [comment]
Before I go and send a PR...

So, Elixir runs on Erlang VM (or Erlang OTP). A specific Elixir version most likely supports 3 Erlang versions.

Elixir 1.14.0 supports Erlang OTP 23, 24, 25 - hence the 3 zips in the assets.
The way I understand it is to use otp 25 in `Main` and `otp-23`, `otp-24` in `Versions`. Correct me if I'm wrong.

However, none of them would work if a user tries to install an earlier version of Elixir because of the different release format, correct?

**Comment by simonmcconnell** [comment]
@princemaple yeah, I think the `Main` bucket should have latest Elixir on latest OTP, `1.14-otp-25` currently, and `Versions` bucket would have `elixir1-14-otp-25`, `elixir1-14-otp-24`, `elixir1-14-otp-23`, `elixir1-13-otp-24`, `elixir1-13-otp-23`, ... back so that the last few versions are covered?

'tis a shame we can't have a conditional in there to handle the older versions.

**Comment by wingyplus** [comment]
Hi, 

I'm the author of the package changes in Release page. I need to sorry that it's break the package. After discuss in https://github.com/elixir-lang/elixir/issues/12134. The conclusion is package from hex.pm would better. So I open a PR to tackle this issue at #3921. But I'm not expert in scoop manifest. Feel free to comment if anything wrong. 🙇
