### ISSUE TITLE
imagemagick@7.1.0-47 unable to be installed

### ISSUE THREAD

**Issue by kilacoda** [ScoopInstaller/Main#3906]
## Bug Report

**Package Name:** imagemagick

### Current Behaviour

Raises a 404 error on running `scoop install imagemagick`

### Expected Behaviour

The package installs without any issues.

### Additional context/output

```terminal
➜ scoop install imagemagick
Installing 'imagemagick' (7.1.0-47) [64bit] from main bucket
The remote server returned an error: (404) Not Found.
URL https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-47-Q16-HDRI-x64-dll.exe is not valid
```

### Possible Solution

An inspection of https://imagemagick.org/archive/binaries/ shows that the latest version of `imagemagick` up for download is 7.1.0-4**8**, not 47. Thus, changing this version number should likely fix the problem.

### System details

**Windows version:** [e.g. 7, 8, 10]
10

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-09-11T13:38:38.8571475-04:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/commit/aee8fa6015bc0271c1fbb77b4ad609e32ade8ac8
