### ISSUE TITLE
[Request] tfswitch

### ISSUE THREAD

**Issue by kennedy** [ScoopInstaller/Main#3910]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** tfswitch

**Description:** The tfswitch command line tool lets you switch between different versions of [terraform](https://www.terraform.io/). If you do not have a particular version of terraform installed, tfswitch lets you download the version you desire.

**Homepage:** https://tfswitch.warrensbox.com/

**Download link(s):** https://github.com/warrensbox/terraform-switcher/releases/download/0.13.1288/terraform-switcher_0.13.1288_windows_amd64.zip

**Some indication of popularity/repute:** Github 1k stars. Referenced quite often by devops communities

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
