### ISSUE TITLE
Upstream mdcat repo no longer has binaries with its releases

### ISSUE THREAD

**Issue by dstcruz** [ScoopInstaller/Main#3914]
mdcat moved its code repo from github to codeberg, and a side effect of this has been that it no longer creates binaries with its release. As a result, the mdcat version used by scoop is no longer the latest. Is there a way to handle this in scoop? I'm the mdcat package maintainer of Chocolatey, and a scoop user, so I'm extra curios. If there is a solution for this in scoop, I would like to also use it in the Chocolatey package.

This is not a bug, per se, mostly a question.

**Comment by rashil2000** [comment]
> Is there a way to handle this in scoop?

I'm afraid we can't do anything. Unless someone runs a build script to build binaries and uploads them on each new release.

**Comment by dstcruz** [comment]
I guess I could make a fork of the upstream repo in either gitlab or here (github) adding a CI that generates the binaries, but I'm not sure I'm up for that at the moment. I'm not a lawyer, so no idea if that would even be OK with the license, or if that would be a no-no in the open source world.
