### ISSUE TITLE
png2html is down

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Main#3916]
The direct link (as listened on json file) is down, either remotely removed or other reasons. This package can't be installed.

**Comment by rashil2000** [comment]
The manifest will have to be deprecated, unfortunately.

**Comment by tech189** [comment]
We could upload the Internet Archive's copy to the Binary repo and restore the package. I just checked the hashes match: https://web.archive.org/web/20171201174516/http://www.engr.mun.ca/~holden/png2html.exe

**Comment by rashil2000** [comment]
Oh yes, I forgot we could use the archive. Please go ahead!

**Comment by tech189** [comment]
I have restored the package and it can now be installed again!

**Comment by gphg** [comment]
Thanks for the action.
