### ISSUE TITLE
How to find install a specific version of app?

### ISSUE THREAD

**Issue by GAlfstad** [ScoopInstaller/Main#3930]
I have install the latest version of Git with scoop. E.g. "scoop install git" which installed 2.37.3.windows.1" but I want the 2.32.0 version. 
How I use scoop to search versions available for install when you ?

I did find : https://github.com/ScoopInstaller/Main/commit/2221e05518a8b4eb97747db2c3d733c49b68f3cd
but when i try:
scoop install git@2.32.0.windows.2

C:\Users\alfstglo>scoop install git@2.32.0.windows.2
WARN  Given version (2.32.0.windows.2) does not match manifest (2.37.3.windows.1)
WARN  Attempting to generate manifest for 'git' (2.32.0.windows.2)
Autoupdating git
Searching hash for PortableGit-$matchFull-32-bit.7z.exe in https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.2
Could not find hash in https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.2
Downloading PortableGit-$matchFull-32-bit.7z.exe to compute hashes!
The request was aborted: The connection was closed unexpectedly.
URL https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-$matchFull-32-bit.7z.exe#/dl.7z is not valid
Could not install git@2.32.0.windows.2

**Comment by rashil2000** [comment]
You'll have to use `scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/2221e05518a8b4eb97747db2c3d733c49b68f3cd/bucket/git.json` here, as the manifest here is too complex to be generated automatically.

**Comment by GAlfstad** [comment]
The only installs the latest.

I still get

`
C:\\projects>scoop install git@2.32.0.windows.2
WARN  Given version (2.32.0.windows.2) does not match manifest (2.37.3.windows.1)
WARN  Attempting to generate manifest for 'git' (2.32.0.windows.2)
Autoupdating git
Searching hash for PortableGit-$matchFull-32-bit.7z.exe in https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.2
Could not find hash in https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.2
Downloading PortableGit-$matchFull-32-bit.7z.exe to compute hashes!
The request was aborted: The connection was closed unexpectedly.
URL https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-$matchFull-32-bit.7z.exe#/dl.7z is not valid
Could not install git@2.32.0.windows.2
Select-CurrentVersion : Cannot bind argument to parameter 'AppName' because it is an empty string.
At C:\Users\alfstglo\scoop\apps\scoop\current\lib\core.ps1:236 char:54
+     return $null -ne (Select-CurrentVersion -AppName $app -Global:$gl ...
+                                                      ~~~~
    + CategoryInfo          : InvalidData: (:) [Select-CurrentVersion], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Select-CurrentVersion

You cannot call a method on a null-valued expression.
At C:\Users\alfstglo\scoop\apps\scoop\current\lib\manifest.ps1:36 char:5
+     $app = $app.TrimStart('/')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Couldn't find manifest for ''.
`

**Comment by rashil2000** [comment]
Use the command that I wrote in my comment
