### ISSUE TITLE
[Request] add HiGHS

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Main#3936]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** HiGHS

**Description:** high performance software for linear optimization

**Homepage:** https://www.maths.ed.ac.uk/hall/HiGHS/

**Download link(s):** https://github.com/ERGO-Code/HiGHS/archive/refs/tags/v1.2.2.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

- 380 stars on GitHub
- Recommended solver of popular software [SciPy](https://github.com/scipy/scipy)'s optimization module
- Recommended solver of popular software [JuMP](https://github.com/jump-dev/JuMP.jl)

**Comment by rashil2000** [comment]
Hi! Please make a PR!
