### ISSUE TITLE
【gcc(10.3.0-5)】Can't find out the path 

### ISSUE THREAD

**Issue by mtuwei** [ScoopInstaller/Main#3942]
## Bug Report

**Package Name:** [gcc]

### Current Behaviour

 1. 【downloading, checking, extracting】are OK  
![image](https://user-images.githubusercontent.com/32591958/191205256-f8e8fa52-3090-4937-bd8d-e733a388f869.png)
![image](https://user-images.githubusercontent.com/32591958/191205304-0497de0d-e16d-4eb5-9146-d88e5485d2aa.png)

2. 【Run pre_install script】: error message are pasted below

```
Move Item: The path "D: \Scoop\apps\gcc\10.3.0-5\mingw64" cannot be found because it does not exist.
Line at position: 2 characters: 1
+ Move-Item "$dir\mingw$a\*" "$dir"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (D:\Scoop\apps\gcc\10.3.0-5\mingw64:String) [Move-Item], ItemNotFound
Exception
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
Remove AppdirItem: The 'Remove AppdirItem' item cannot be recognized as the name of a cmdlet, function, script file, or runnable program. Please check the spelling of the name,
If you include a path, make sure the path is correct, and then try again.
Line at position: 3 characters: 1
+ Remove-AppdirItem "mingw$a", '.*'
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Remove-AppdirItem:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
Confirm DirectoryExistence: The 'Confirm DirectoryExistence' item cannot be recognized as the name of a cmdlet, function, script file, or runnable program.
Check the spelling of the name. If the path is included, make sure the path is correct, and then try again.
Line at position: 4 characters: 1
+ Confirm-DirectoryExistence "$dir\bin\bak" | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Confirm-DirectoryExistence:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
Move Item: The path "D:  Scoop  apps  gcc  10.3.0-5  bin" cannot be found because it does not exist.
Line at position: 5 characters: 1
+ Move-Item "$dir\bin\python*.exe" "$dir\bin\bak"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (D:\Scoop\apps\gcc\10.3.0-5\bin:String) [Move-Item], ItemNotFoundExce
ption
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
```

### System details

**Windows version:** [10]

**OS architecture:** [64bit]

**PowerShell version:** [5.1]

**Additional software:** []

#### Scoop Configuration
```json
{
    "lastupdate":  "2022-09-20T15:57:17.3084415+08:00",
    "SCOOP_REPO":  "https://gitee.com/glsnames/scoop-installer",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Your Main bucket is very out of date. Please update it.

**Comment by mtuwei** [comment]
> Your Main bucket is very out of date. Please update it and try again.
I've update the scoop, but the error happens again.
![image](https://user-images.githubusercontent.com/32591958/191232976-932fc0a5-e5ed-490e-a289-837163949605.png)

**Comment by mtuwei** [comment]
> What is the output of `scoop bucket list`?

![image](https://user-images.githubusercontent.com/32591958/191234256-49666a58-eb0f-45ee-b9e4-f47f1ebd0aa4.png)

**Comment by rashil2000** [comment]
Run these commands:
```
scoop config SCOOP_REPO https://github.com/ScoopInstaller/Scoop
scoop update
scoop bucket rm main
scoop bucket rm extras
scoop update
scoop bucket add main
scoop bucket add extras
```

**Comment by mtuwei** [comment]
> scoop update
> scoop bucket rm main
> scoop bucket rm extras
> scoop update
> scoop bucket add main
> scoop bucket add extras

I have network trouble in accessing GitHub. How should I set the proxy in the cmds?  Thank you

**Comment by rashil2000** [comment]
Try this: https://github.com/ScoopInstaller/Scoop/discussions/4872

**Comment by mtuwei** [comment]
> Your Main bucket is very out of date. Please update it and try again.

That's work, thanks again👍
