### ISSUE TITLE
[Request] add Nats-Server

### ISSUE THREAD

**Issue by Lemorz56** [ScoopInstaller/Main#3953]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** nats-server

**Description:**  A server for NATS, the cloud and edge native messaging system supporting lots of different features for communication and messaging.

**Homepage:** https://github.com/nats-io/nats-server

**Download link(s):** https://github.com/nats-io/nats-server/releases/

**Some indication of popularity/repute:** 1.1k forks, 11.5k stars. https://nats.io/ list of big companies using NATS.

**Comment by Lemorz56** [comment]
I have created the manifest in a fork, just waiting for confirmation that it is OK before creating a PR.

**Comment by rashil2000** [comment]
Sure, go ahead!
