### ISSUE TITLE
yt-dlp: external plugins are not persisted

### ISSUE THREAD

**Issue by jpovixwm** [ScoopInstaller/Main#3954]
## Bug Report

**Package Name:** yt-dlp

### Current Behaviour

The directory "ytdlp_plugins" is not persisted.

### Expected Behaviour

The directory should be persisted.

### Additional context/output

As documented [here](https://github.com/yt-dlp/yt-dlp/blob/2022.09.01/README.md#plugins), yt-dlp loads external plugins from a directory named "ytdlp_plugins" located next to the main executable file, `yt-dlp.exe`.
Currently, this directory is not persisted and my custom plugins break whenever I update yt-dlp via scoop.

### Possible Solution

```diff
diff --git a/bucket/yt-dlp.json b/bucket/yt-dlp.json
index 5e68568c7..97ad0a80f 100644
--- a/bucket/yt-dlp.json
+++ b/bucket/yt-dlp.json
@@ -17,12 +17,8 @@
         }
     },
     "bin": "yt-dlp.exe",
-    "pre_install": [
-        "$manifest.persist | ForEach-Object {",
-        "    if (-not (Test-Path \"$persist_dir\\$_\")) { New-Item \"$dir\\$_\" -ItemType file | Out-Null }",
-        "}"
-    ],
-    "persist": "yt-dlp.conf",
+    "pre_install": "if (-not (Test-Path \"$persist_dir\\yt-dlp.conf\")) { New-Item \"$dir\\yt-dlp.conf\" -ItemType file | Out-Null }",
+    "persist": ["yt-dlp.conf", "ytdlp_plugins"],
     "checkver": "github",
     "autoupdate": {
         "architecture": {
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682
```

**Additional software:** N/A

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-09-21T20:15:17.0178664+00:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Please make a PR!
