### ISSUE TITLE
[Bug Report] The version of scc is not updated

### ISSUE THREAD

**Issue by StudentWeis** [ScoopInstaller/Main#3967]
## Bug Report

**Package Name:** scc

### Current Behaviour

The version of scc is not updated, but I successfully tested it's manifest locally.

---

![main-scc](https://s2.loli.net/2022/09/25/KoFBiMEjs1GUAtR.png)

---

![real-scc](https://s2.loli.net/2022/09/25/U7e8hXc4PqRsiwC.png)

---

![local-check-scc](https://s2.loli.net/2022/09/25/MUYk9dqA6mrXfzH.png)

---

### Expected Behaviour

The version of scc bump to 3.1.0 by the Github Actions.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-09-25T21:52:07.7043557+08:00",
  "proxy": "127.0.0.1:41091",
  "aria2-warning-enabled": false,
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Should be simple to fix (just need a change in URLs). Can you make a PR?

**Comment by StudentWeis** [comment]
I just don't know why this happen. Shouldn't it be automatically updated in Github Actions?
