### ISSUE TITLE
[Bug] ERROR Application "deno" is still running. Close all instances and try again.

### ISSUE THREAD

**Issue by radiorz** [ScoopInstaller/Main#3969]
## Bug Report

**Package Name:** [name of package which has bug(s)]
**Deno:** deno is always running

### Current Behaviour

when installed deno is always running...

### Expected Behaviour

deno dont run anytime

### System details

**Windows version:** [e.g. 7, 8, 10] 
windows 11

**OS architecture:** [e.g. 32bit, 64bit] 
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7

**Additional software:** [(optional) e.g. ConEmu, Git]
git 2.6.1

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
You need to do this yourself. Maybe some app server is still running - check the Task Manager to be sure.

Scoop will not close deno while updating
