### ISSUE TITLE
[Request] WireGuard

### ISSUE THREAD

**Issue by linsui** [ScoopInstaller/Main#397]
WireGuard use msi installer and need privilege to install wintun driver. Before 0.0.17, something like this may work.

```json
    "installer": {
        "script": "Invoke-ExternalCommand pnputil -ArgumentList \"/add-driver `\"$dir\\WireGuard\\wintun.inf`\"\" -RunAs"
    },
    "uninstaller": {
        "script": "Invoke-ExternalCommand pnputil -ArgumentList \"/delete-driver wintun.inf\" -RunAs"
    },
```

But after several updates, lessmsi can't extract wintun driver file anymore. Dark can extract a dll file but I can't extract wintun driver from it. 

```json
    "msi": {
        "code": "620E1CAA-61DB-4767-90F2-59ADB37ECA36"
    },
```
This works, but wireguard will be installed in `Program Files` . `msi` will be removed in https://github.com/lukesampson/scoop/pull/3502 . Should we keep `msi` or move it to `installer.type.msi` ?

**Comment by linsui** [comment]
Still impossible. Closed.

**Comment by zx2c4** [comment]
The installer no longer installs wintun, or any driver. Instead, the app does this when it needs to.
