### ISSUE TITLE
[Request] lua-language-server

### ISSUE THREAD

**Issue by Pkcarreno** [ScoopInstaller/Main#3989]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** Lua Language Server

**Description:** Adds language features for Lua

**Homepage:** [https://github.com/sumneko/lua-language-server](https://github.com/sumneko/lua-language-server)

**Download link(s):** [https://github.com/sumneko/lua-language-server/releases](https://github.com/sumneko/lua-language-server/releases)

**Some indication of popularity/repute:** 1.7k Stars and half a million vscode installations

**Comment by KrisSchneider** [comment]
Done in #3993

**Comment by Pkcarreno** [comment]
Thanks @KrisSchneider

**Comment by KrisSchneider** [comment]
> Thanks @KrisSchneider 

No problem.
