### ISSUE TITLE
[Request] git-branchless

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Main#3995]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** git-branchless

**Description:** High-velocity, monorepo-scale workflow for Git

**Homepage:** https://github.com/arxanas/git-branchless

**Download link(s):** https://github.com/arxanas/git-branchless/releases/download/v0.5.1/git-branchless-v0.5.1-x86_64-pc-windows-msvc.zip

**Some indication of popularity/repute:** Stars > 2.1k

**Comment by Zliced13** [comment]
Done in #4003

**Comment by ivaquero** [comment]
Thank you!

**Comment by Zliced13** [comment]
Your Welcome!
