### ISSUE TITLE
dark@3.11.2: decompress error

### ISSUE THREAD

**Issue by Foggygu** [ScoopInstaller/Main#4004]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Foggygu** [comment]
Who can help me about the error? Many thanks.

ERROR 'dark' isn't installed correctly.
Removing older version (3.11.2).
'dark' was uninstalled.
Installing 'dark' (3.11.2) [64bit] from main bucket
Loading dark-3.11.2.zip from cache
Checking hash of dark-3.11.2.zip ... ok.
Extracting dark-3.11.2.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\foggy\scoop\apps\dark\3.11.2\dark-3.11.2.zip.
Log file:
  ~\scoop\apps\dark\3.11.2\7zip.log

**Comment by rashil2000** [comment]
What's in the log?

**Comment by Zliced13** [comment]
Have you tried uninstalling **dark** and removing the cache with, `scoop uninstall dark; scoop cache rm *`?

**Comment by rashil2000** [comment]
Closing due to no response
