### ISSUE TITLE
Vim from the main bucket is not compiled with Python

### ISSUE THREAD

**Issue by rubycornish** [ScoopInstaller/Main#4017]
## Bug Report

**Package Name:** Vim

### Current Behaviour

Existing Vim package is not compiled with Python (or Ruby and Perl for that matter). This can be verified by running :version in vim.

### Expected Behaviour

I believe it used to be the case that Vim package came with Python. Unfortunately I don't know if there is a binary available.

### System details

**Windows version:** 10
**OS architecture:** 64bit

#### Scoop Configuration
```json
{
    "scoop_branch":  "master",
    "last_update":  "2022-10-13T13:01:07.1305678+01:00",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
```

**Comment by rashil2000** [comment]
```
scoop bucket add versions
scoop install vim-tux
```
