### ISSUE TITLE
sox should also exist as 'play'and 'rec'

### ISSUE THREAD

**Issue by nklamann** [ScoopInstaller/Main#4027]
## Bug Report

**sox** 

### Current Behaviour

sox doesn not install play and rec.

### Expected Behaviour

sox.exe  should also exist as play.exe  and rec.exe as in linux.  See  https://sox.sourceforge.net/sox.html

### Additional context/output

Some months ago i installed a sox.exe (forgot from where, sorry)  and copied the file to rec.exe and play.exe and play.exe worked fine

### Possible Solution

Create an additional shim ?  

### System details

**Windows version:** [e.g. 7, 8, 10]
10
**OS architecture:** [e.g. 32bit, 64bit]
64
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      6
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "scoop_branch": "master",
  "last_update": "2022-10-13T16:49:23.7181308+02:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by rashil2000** [comment]
The sox package for Windows does not contains those binaries.

**Comment by nklamann** [comment]
But it should. They are simple copies of sox.exe

**Comment by rashil2000** [comment]
Okay, just renaming them works. Can you make a PR?

**Comment by nklamann** [comment]
> Okay, just renaming them works. Can you make a PR?

Unfortunately no, I don't know anythin abput the inner workings of scoop. 

I fixed the problem for me with scopying of sox.shm. sox.exe and sox.exe in the current directory.
