### ISSUE TITLE
关于下载maven慢的问题.

### ISSUE THREAD

**Issue by Safe-And-Sound** [ScoopInstaller/Main#404]
使用scoop 进行安装maven 时 8M大小的东西需要下载4分钟 ,但是我去官网下载就只需要10秒左右,是秒下的,对比发现了 main bucket 里用的 https://www.apache.org/dist
而我在官网里下载用的是 https://mirrors.tuna.tsinghua.edu.cn/apache 
能否换下??

**Comment by niheaven** [comment]
Use your own manifest or bucket for these cases.
