### ISSUE TITLE
main/neofetch fails to install if git isn't installed

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Main#4056]
## Bug Report

main/neofetch

### Current Behaviour

On clean windows system, install scoop and then run `scoop install neofetch`

it will fail as `(Get-Command git)` throws an exception.

### Expected Behaviour

Should attempt to scoop install git first, or should fail install with a clear message.

### Additional context/output

`ForEach-Object : Cannot bind argument to parameter 'Path' because it is null.`

### Possible Solution

Should attempt to scoop install git first, or should fail install with a clear message.

### System details

Windows 10, 64-bit, PowerShell 5

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by HUMORCE** [comment]
<del>Should attempt to scoop install git first</del>

- scoop accepts external installs of git
- scoop cannot/will not force to install a git package. (`scoop search git`)

**should fail install with a clear message.**

It looks like this needs to be improved in Scoop Core.

**Comment by niheaven** [comment]
A simple solution: change 'suggest git` to `depends on git`.
