### ISSUE TITLE
main/curl fails to install if git isn't installed

### ISSUE THREAD

**Issue by qljiange** [ScoopInstaller/Main#4061]
Bug Report
main/curl

Current Behaviour
On clean windows system, install scoop and then run `scoop install curl`

Additional context/output
Installing 'curl' (7.85.0_9) [64bit] from main bucket
Download: 10/25 15:28:36 [ERROR] CUID#8 - Download aborted. URI=https://curl.haxx.se/windows/dl-7.85.0_9/curl-7.85.0_9-win64-mingw.tar
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://curl.haxx.se/windows/dl-7.85.0_9/curl-7.85.0_9-win64-mingw.tar.x
Download: gid   |stat|avg speed  |path/URI
Download: ae8eb2|ERR |       0B/s|D:/Scoop/cache/curl#7.85.0_9#https_curl.haxx.se_windows_dl-7.85.0_9_curl-7.85.0_9-win64-mingw.tar.xz
Download: Status Legend:
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://curl.haxx.se/windows/dl-7.85.0_9/curl-7.85.0_9-win64-mingw.tar.xz
    referer=https://curl.haxx.se/windows/dl-7.85.0_9/
    dir=D:\Scoop\cache
ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\curl.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10448 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=curl%407.85.0_9%3a+download+via+aria2+failed

System details
PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)

**Comment by rashil2000** [comment]
?? This has nothing to do with git.

Please disable aria2 and then try.
