### ISSUE TITLE
[Request] tere

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Main#4072]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** tere

**Description:** Rusty Terminal File Explorer

**Homepage:** https://github.com/mgunyho/tere

**Download link(s):** https://github.com/mgunyho/tere/releases/download/v1.3.0/tere-1.3.0-x86_64-pc-windows-gnu.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

- 1.3k stars on GitHub

**Comment by Zliced13** [comment]
This is honestly a pretty cool CLI app.

**Comment by ivaquero** [comment]
Thank you!
