### ISSUE TITLE
[Request] LuaJIT

### ISSUE THREAD

**Issue by flaribbit** [ScoopInstaller/Main#4074]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** LuaJIT

**Description:** LuaJIT is a Just-In-Time (JIT) compiler for the Lua programming language.

**Homepage:** https://luajit.org/

**Download link(s):** https://luajit.org/download/LuaJIT-2.1.0-beta3.zip

**Some indication of popularity/repute:** Github 3.5k stars

**Comment by Zliced13** [comment]
I don't think this should be added to scoop, there are no compiled binaries that scoop can make use of.
