### ISSUE TITLE
azure-cli@2.41.0: decompress error -> results in killing `scoop update *`

### ISSUE THREAD

**Issue by bartvanandel** [ScoopInstaller/Main#4076]
#### Scoop Configuration

```json
{
  "scoop_branch": "master",
  "last_update": "2022-10-31T09:34:18.2571988+01:00",
  "scoop_repo": "https://github.com/lukesampson/scoop"
}
```

Output for updating azure-cli as part of `scoop update -g *`:

```
Updating 'azure-cli' (2.40.0 -> 2.41.0)
Downloading new version
Loading azure-cli-2.41.0.msi from cache
Checking hash of azure-cli-2.41.0.msi ... ok.
Uninstalling 'azure-cli' (2.40.0)
Installing 'azure-cli' (2.41.0) [64bit] from main bucket
Loading azure-cli-2.41.0.msi from cache
Extracting azure-cli-2.41.0.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\ProgramData\scoop\apps\azure-cli\2.41.0\azure-cli-2.41.0.msi.
Log file:
  C:\ProgramData\scoop\apps\azure-cli\2.41.0\msi.log
```

The mentioned log file is empty however, so can't help you out with details.

This error is annoying, but more annoyingly, it kills the entire `scoop update *` flow by breaking out of it, which means I'm going to have to type a very long update command just to skip the broken package.

**Comment by rashil2000** [comment]
`MSI Error 1618: 'Another installation is already in progress' during installation/uninstallation`

**Comment by bartvanandel** [comment]
@rashil2000 
a) Tried it again right after it broke, that didn't fix it. If you mean the package has been updated and should now work: I can indeed confirm that it does. However...
b) Please take note of the second part of the issue title: when this happens, the **entire** command is terminated, even if it's the first package in a long list of packages to update. That's the annoying part.

Could you reopen this, or do you want a separate issue for this with a pretty much verbatim copy of all the info I've provided above?

**Comment by rashil2000** [comment]
The second part of your issue is being tracked here: https://github.com/ScoopInstaller/Scoop/issues/4135
