### ISSUE TITLE
[Request] Nexttrace

### ISSUE THREAD

**Issue by soenggam** [ScoopInstaller/Main#4089]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:**  nexttrace

**Description:**  An open source visual route tracking CLI tool

**Homepage:** https://github.com/sjlleo/nexttrace

**Download link(s):** https://github.com/sjlleo/nexttrace/releases

**Some indication of popularity/repute:** 532 stars

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/issues/9652
