### ISSUE TITLE
autoit@3.3.16.1: Trojan / Virus has been detected

### ISSUE THREAD

**Issue by mesmariusz** [ScoopInstaller/Main#4107]
Hi. There is a virus warning during AutoIT installation. 
Anstallation has been aborted. 

![image](https://user-images.githubusercontent.com/3919173/200958809-ed508b7b-d999-4d1c-addc-b8185844c317.png)

![image](https://user-images.githubusercontent.com/3919173/200958842-11038800-8ac7-40b6-943f-92be8d1f0d36.png)

Scoop Configuration
{
    "last_update":  "2022-11-08T14:52:42.4251754+01:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

**Comment by niheaven** [comment]
autoit will occasionally trigger AV warning, since it is an auto script tools. This is because of autoit itself and not due to scoop.
