### ISSUE TITLE
[Request]: Add ossutil

### ISSUE THREAD

**Issue by YangHanlin** [ScoopInstaller/Main#4121]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

ossutil

### Description

A user friendly command line tool to access AliCloud OSS

### Homepage

https://github.com/aliyun/ossutil

### Download Link(s)

https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64.zip

### Some Indication of Popularity/Repute

`ossutil` is the official CLI tool for interacting with [Alibaba Cloud Object Storage Service](https://www.alibabacloud.com/en/product/object-storage-service) (see the [official documentation](https://www.alibabacloud.com/help/en/object-storage-service/latest/ossutil-overview)). Considering the popularity of Alibaba Cloud in China, `ossutil` is likely to be widely used by developers and operators in China.

The repository of `ossutil` [aliyun/ossutil](https://github.com/aliyun/ossutil) does not have enough stars (356 stars), but it's not an indication of the lack of popularity of this tool, as most of the users might just follow the [official docs](https://www.alibabacloud.com/help/en/object-storage-service/latest/download-and-installation) for download and installation instructions instead of visiting the repository.

**Comment by ViCrack** [comment]
e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks

**Comment by YangHanlin** [comment]
> e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks

@ViCrack Thanks for your comment! The repository of `ossutil` does not have enough stars, but I think the lack of stars might not be an indication of its lack of popularity because most of the users might just visit the official documentation, instead of visiting the repository and adding a star for it (as stated above in "Some Indication of Popularity/Repute" section).

If you could [search](https://scoop.sh/#/apps?q=ossutil&s=0&d=1&o=false) for `ossutil` across Scoop buckets across GitHub, you can see there have been buckets with this tool included, which also indicates its popularity.

**Comment by rashil2000** [comment]
I think it's the official tool from Aliyun, so it should be fine here. Please make a PR!

**Comment by YangHanlin** [comment]
> I think it's the official tool from Aliyun, so it should be fine here. Please make a PR!

@rashil2000 I've proposed a PR #4132; please review when you have time.
