### ISSUE TITLE
[Request]: Fix patch utility home page link

### ISSUE THREAD

**Issue by jaeger-2601** [ScoopInstaller/Main#4125]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

patch

### Description

The current link pointing to patch utility is outdated and takes the user to an empty site.

### Homepage

https://www.msys2.org/

### Download Link(s)

https://packages.msys2.org/base/patch

### Some Indication of Popularity/Repute

The msys2 packages have over 1.2k stars on Github. [Repo link](https://github.com/msys2/MSYS2-packages)

**Comment by rashil2000** [comment]
Fixed in https://github.com/ScoopInstaller/Main/commit/152bc96de76a85be5ef34be4363d2ef1ba72af60

MSYS2 is not related to the original Mingw project
