### ISSUE TITLE
[Request]: Add Veracrypt

### ISSUE THREAD

**Issue by sxge** [ScoopInstaller/Main#4129]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Veracrypt

### Description

Disk Encryption Program

### Homepage

https://www.veracrypt.fr

### Download Link(s)

https://launchpad.net/veracrypt/trunk/1.25.9/+download/VeraCrypt%20Setup%201.25.9.exe

### Some Indication of Popularity/Repute

Veracrypt is a well known open source programm to encrypt hard drives

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Extras/issues/2381
