### ISSUE TITLE
[Request]: Sapling

### ISSUE THREAD

**Issue by Ryanjiena** [ScoopInstaller/Main#4140]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Sapling

### Description

Sapling SCM is a cross-platform, highly scalable, Git-compatible source control system.

### Homepage

https://sapling-scm.com/

### Download Link(s)

https://github.com/facebook/sapling/releases/download/20221116-203146-2c1a971a/sapling_windows_20221116.203146.2c1a971a_amd64.zip

### Some Indication of Popularity/Repute

GitHub stars: 3.3k+

**Comment by fire** [comment]
How does the powershell command work?

```
> Add-Content -Path $Profile -Value "`nSet-Alias -Name sl -Value `"`$(scoop prefix sapling)\sl.exe`" -Force -Option Constant,ReadOnly,AllScope"
Add-Content : Could not find a part of the path
'C:\Users\ernes\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
At line:1 char:1
+ Add-Content -Path $Profile -Value "`nSet-Alias -Name sl -Value `"`$(s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ernes\...ell_profile.ps1:String) [Add-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand
```

**Comment by rashil2000** [comment]
Run this first: `New-Item $PROFILE -Force`

**Comment by fire** [comment]
Works! Please add to the instructions.
