### ISSUE TITLE
[Bug]: Pyenv broken?

### ISSUE THREAD

**Issue by melMass** [ScoopInstaller/Main#4143]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

pyenv-win

### Expected/Current Behaviour

As reported here, https://github.com/pyenv-win/pyenv-win/issues/449 the current recipe is not working and returns ` error installing "core" component MSI.` when trying to install python versions

![image](https://user-images.githubusercontent.com/7041726/202868032-99cf0a40-7e1d-45f0-a468-b3b30863d3f6.png)

### Steps to Reproduce

```console
> $> pyenv install 3.10.8
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.10.8 ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe
:: [Downloading] ::  To   C:\Users\User\scoop\apps\pyenv\current\pyenv-win\install_cache\python-3.10.8-amd64.exe
:: [Installing] ::  3.10.8 ...
:: [Error] :: error installing "core" component MSI.
:: [Error] :: couldn't install 3.10.8
```

### Possible Solution

Someone in the issue linked mentioned that it had something to do with symlinks, but I cannot tell yet.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
f641d6691 (HEAD -> master, origin/master, origin/HEAD) reshade: Update to version 5.5.0

'main' bucket:
e9116c159 (HEAD -> master, origin/master, origin/HEAD) trid: Update to version 2.24-22.11.19
```

### Scoop Config

```console
last_update           scoop_branch scoop_repo
-----------           ------------ ----------
11/19/2022 8:05:46 PM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
Did you run `pyenv update` as suggested in the linked issue?

**Comment by melMass** [comment]
> Did you run `pyenv update` as suggested in the linked issue?

Yes. I also use regular pyenv in other oses and was using pyenv-win with choco but I'm trying to get rid of choco

**Comment by melMass** [comment]
> Did you run `pyenv update` as suggested in the linked issue?

The issue I linked just shows the same thing and why for now they did not add scoop instructions until it's working

**Comment by TinkerSteve** [comment]
same issue here.
worked around by downgrading pyenv to 2.x
> scoop install pyenv@2.64.11
> scoop hold pyenv

**Comment by rashil2000** [comment]
If an older version of pyenv is working fine, the issue is not with the Scoop package

**Comment by melMass** [comment]
> If an older version of pyenv is working fine, the issue is not with the Scoop package

What makes you say that? 

It works in other package managers so I'm pretty sure it's due to the pyenv-win scoop package, it was updated recently and the issues/comment I could find correlates with that last PR

**Comment by rashil2000** [comment]
> What makes you say that?

1. The manifest is practically unchanged since version 2.64.11 - except for the addition of PYENV_ROOT and PYENV_HOME environment variables
2. The manifest itself is extremely simple - it just unarchives files and sets environment variables. What do you think is broken here?

**Comment by chawyehsu** [comment]
I'm using the same version/manifest of pyenv and cannot reproduce this. There should not be a manifest issue I think.

```
DESKTOP in ~
❯ pyenv --version
pyenv 3.1.1
DESKTOP in ~
❯ pyenv install 3.10.8
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.10.8 ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe
:: [Downloading] ::  To   C:\Users\me\scoop\apps\pyenv\current\pyenv-win\install_cache\python-3.10.8-amd64.exe
:: [Installing] ::  3.10.8 ...
:: [Info] :: completed! 3.10.8
DESKTOP in ~
❯ which python
C:\Users\me\scoop\apps\pyenv\current\pyenv-win\shims\python
```

**Comment by arbaleast** [comment]
Any help?🤔
```
 pyenv install 3.9.0
:: [Info] ::  Mirror: https://www.python.org/ftp/python
:: [Downloading] ::  3.9.0 ...
:: [Downloading] ::  From https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe
:: [Downloading] ::  To   D:\Env\UserScoop\apps\pyenv\current\pyenv-win\install_cache\python-3.9.0-amd64.exe
:: [Installing] ::  3.9.0 ...
:: [Error] :: error installing "core" component MSI.
:: [Error] :: couldn't install 3.9.0
```

**Comment by TinkerSteve** [comment]
> Any help?🤔
> 
> ```
>  pyenv install 3.9.0
> :: [Info] ::  Mirror: https://www.python.org/ftp/python
> :: [Downloading] ::  3.9.0 ...
> :: [Downloading] ::  From https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe
> :: [Downloading] ::  To   D:\Env\UserScoop\apps\pyenv\current\pyenv-win\install_cache\python-3.9.0-amd64.exe
> :: [Installing] ::  3.9.0 ...
> :: [Error] :: error installing "core" component MSI.
> :: [Error] :: couldn't install 3.9.0
> ```

see my suggestion above:

scoop install pyenv@2.64.11
scoop hold pyenv

**Comment by melMass** [comment]
> I'm using the same version/manifest of pyenv and cannot reproduce this. There should not be a manifest issue I think.
> 
> ```
> DESKTOP in ~
> ❯ pyenv --version
> pyenv 3.1.1
> DESKTOP in ~
> ❯ pyenv install 3.10.8
> :: [Info] ::  Mirror: https://www.python.org/ftp/python
> :: [Downloading] ::  3.10.8 ...
> :: [Downloading] ::  From https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe
> :: [Downloading] ::  To   C:\Users\me\scoop\apps\pyenv\current\pyenv-win\install_cache\python-3.10.8-amd64.exe
> :: [Installing] ::  3.10.8 ...
> :: [Info] :: completed! 3.10.8
> DESKTOP in ~
> ❯ which python
> C:\Users\me\scoop\apps\pyenv\current\pyenv-win\shims\python
> ```

Yes but try 3.9.10 for instance, that's the issue

**Comment by cderv** [comment]
I believe @rminderhoud got to the bottom of it with https://github.com/pyenv-win/pyenv-win/issues/449#issuecomment-1374159205

Probably an issue with Junction paths used by scoop and how `msiexec` is used on the .exe file using the symlinked path in `current/` whereas the file actually lives in the `persist` folder. 

I don't know if something can be done at Scoop level for that. Maybe at `pyenv-win` level - but it would be best for the MSI to work with Junction path. I don't think all MSI has this issue. 

In the meantime, `pyenv` with Scoop maybe broken

**Comment by tyePhDCandy** [comment]
> > Any help?🤔
> > ```
> >  pyenv install 3.9.0
> > :: [Info] ::  Mirror: https://www.python.org/ftp/python
> > :: [Downloading] ::  3.9.0 ...
> > :: [Downloading] ::  From https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe
> > :: [Downloading] ::  To   D:\Env\UserScoop\apps\pyenv\current\pyenv-win\install_cache\python-3.9.0-amd64.exe
> > :: [Installing] ::  3.9.0 ...
> > :: [Error] :: error installing "core" component MSI.
> > :: [Error] :: couldn't install 3.9.0
> > ```
> 
> see my suggestion above:
> 
> scoop install pyenv@2.64.11 scoop hold pyenv

the solution works. thanks

**Comment by bymcs** [comment]
hello i am having this problem, my computer is connected to the domain, my user has admin authorization is there any clue that causes this error ?

**Comment by melMass** [comment]
Hey I'm going to unsubscribe as I never found the culprit. I tried to tell both project about the issue, on the pyenv-win side they say it's a scoop issue.
It's the only issue I have with scoop, so I installed it manualy (basically it's just cloning a folder and adding its shims to PATH..)

IIRC it only affects older python installers

**Comment by ddiaz2380** [comment]
Solution:

1:  Set-ExecutionPolicy RemoteSigned
2:  Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"
3:  Get-ExecutionPolicy
4:  pyenv install -l
5:  pyenv install 3.12.0
6:  pyenv global 3.12.0

I hope it serves them. Greetings!

**Comment by bersbersbers** [comment]
> Is there a reason this is closed ?

Yes, given above.

**Comment by kvfi** [comment]
Holding the version doesn't work for me any longer. How can we fix this?
