### ISSUE TITLE
winflexbison 2.5.19: "data/m4sugar/m4sugar.m4 not found"

### ISSUE THREAD

**Issue by bscottm** [ScoopInstaller/Main#415]
@r15ch13 , @issaclin32 : The file actually exists. The error has the general feel that an environment variable hasn't been set that tells `win_flex` and `win_bison` the `~/scoop/apps/winflexbison/2.5.19` install directory's location. However, this error makes `winflexbison` unusable.

**Comment by niheaven** [comment]
How to reproduce it? I didn't use this and cannot make a fix.

**Comment by bscottm** [comment]
It's not hard to reproduce. Just run `win_bison` on your favorite Yacc input. I'll try to capture output for you.

**Comment by bscottm** [comment]
UTR as well. Closing.
