### ISSUE TITLE
[Bug]: Failed to extract files from aws-sam-cli\1.65.0\AWS_SAM_CLI_64_PY3.msi

### ISSUE THREAD

**Issue by InTEGr8or** [ScoopInstaller/Main#4159]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

AWS_SAM_CLI_64_PY3.msi

### Expected/Current Behaviour

Scoop usually just works so well.

### Steps to Reproduce

```console
scoop install aws-sam-cli
```

### Possible Solution

I have no idea but the scoop command output told me I might want to log an issue here.

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a353fe8cb (HEAD -> master, origin/master, origin/HEAD) autoclicker@1.0.0.2: Fix hash (#9824)

'main' bucket:
73d19058e (HEAD -> master, origin/master, origin/HEAD) fio: Update to version 3.33 (#4158)

'nerd-fonts' bucket:
14e63c7 (HEAD -> master, origin/master, origin/HEAD) (chore): add descriptions to default nerd font manifests (#211)
```

### Scoop Config

```console
❯ scoop config   

last_update           scoop_repo                              scoop_branch
-----------           ----------                              ------------
11/22/2022 7:14:49 PM https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
❯ $PSVersionTable                

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

it's very strange that it's trying to write to that location:

❯ cat ~\scoop\apps\aws-sam-cli\1.65.0\msi.log
=== Logging started: 11/22/2022  19:16:59 ===
Error 1304. Error writing to file: C:\Users\mstouffer\scoop\apps\aws-sam-cli\1.65.0\_tmp\SourceDir\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\init\templates\cookiecutter-aws-sam-hello-java-gradle\{{cookiecutter.project_name}}\HelloWorldFunction\src\main\java\helloworld\GatewayResponse.java. Verify that you have access to that directory.
=== Logging stopped: 11/22/2022  19:17:49 ===

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+aws-sam-cli+is%3Aclosed
