### ISSUE TITLE
[Bug]: QEMU 7.2.0-rc2 unable to extract qemu-uninstall.exe.nsis

### ISSUE THREAD

**Issue by HeWhoWatches** [ScoopInstaller/Main#4164]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

QEMU

### Expected/Current Behaviour

Expected behaviour is to successfully install/update qemu.
Current behaviour is that 7z is unable to extract lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis from the archive during the installation process.
[7zip.log](https://github.com/ScoopInstaller/Main/files/10082934/7zip.log)

### Steps to Reproduce

```console
PS> scoop install qemu -k
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'qemu' (7.2.0-rc2) [64bit] from main bucket
WARN  Cache is being ignored.
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 27e395|OK  |   6.9MiB/s|C:/Tools/Scoop/cache/qemu#7.2.0-rc2#https_qemu.weilnetz.de_w64_qemu-w64-setup-20221123.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of qemu-w64-setup-20221123.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Tools\Scoop\apps\qemu\7.2.0-rc2\dl.7z.
Log file:
  C:\Tools\Scoop\apps\qemu\7.2.0-rc2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=qemu%407.2.0-rc2%3a+decompress+error
```

### Possible Solution

While I don't have a solution, I did note that the same error occurs in the GUI version of 7-zip 22.01 if you try to manually extract the executable. The file that causes the error may be related to this change in the history notes for the new version:
2022-11-23: New QEMU installers (7.2.0-rc2). Signed uninstaller, enhanced file properties.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
ca9395116 (HEAD -> master, origin/master, origin/HEAD) winscan2pdf: Update to version 8.31

'java' bucket:
6ca994b1 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.362-3.0.202211231817

'main' bucket:
a9e99dd18 (HEAD -> master, origin/master, origin/HEAD) git-istage: Update to version 0.3.88

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2022-11-24T08:33:58.7296808+00:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Zzyzx-Wolfe** [comment]
Can confirm that I am having the same issue:
```
 ⚡Zzyzx ❯❯ scoop update qemu -k
qemu: 7.2.0-rc1 -> 7.2.0-rc2
Updating one outdated app:
Updating 'qemu' (7.2.0-rc1 -> 7.2.0-rc2)
Downloading new version
Loading qemu-w64-setup-20221123.exe from cache
Checking hash of qemu-w64-setup-20221123.exe ... ok.
Uninstalling 'qemu' (7.2.0-rc1)
Unlinking ~\scoop\apps\qemu\current
Installing 'qemu' (7.2.0-rc2) [64bit] from main bucket
WARN  Cache is being ignored.
qemu-w64-setup-20221123.exe (143.2 MB) [======================================================================] 100%
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Zzyzx\scoop\apps\qemu\7.2.0-rc2\dl.7z.
Log file:
  ~\scoop\apps\qemu\7.2.0-rc2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=qemu%407.2.0-rc2%3a+decompress+error
 ⚡Zzyzx ❯❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
1f79ece33 (HEAD -> master, origin/master, origin/HEAD) tartube: Update to version 2.4.165

'main' bucket:
7b1ce9d17 (HEAD -> master, origin/master, origin/HEAD) zeebe: Update to version 8.1.4

 ⚡Zzyzx ❯❯ scoop config

aria2-enabled : False
last_update   : 11/24/2022 9:31:38 AM
use_lessmsi   : True
scoop_repo    : https://github.com/lukesampson/scoop
scoop_branch  : master


 ⚡Zzyzx ❯❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
Can confirm this: `lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis` is not extractable

**Comment by onurbbr** [comment]
I can confirm too.
In the latest version of QEMU, the uninstaller is signed. So 7zip may not be able to extract this file.
![Screenshot_20221126_130406](https://user-images.githubusercontent.com/47495526/204083263-590d22f3-b5f0-49da-9968-f79e1c7ab588.png)

**Comment by maxence-lagalle** [comment]
I can also confirm this issue with this version, and also with qemu 7.2.0-rc3.
On the 7zip log, I have also this message :
```
Sub items Errors: 1
ERROR: Data Error : lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis
```

**Comment by hgkamath** [comment]
I typed this all up, and then realized I have nothing new to add. sry, but yes, the signing is the main change in qemu-7.2-rc2 .

The nsis-installer command works directly 
```
PS C:\> C:\tmpq\Downloads\qemu-w64-setup-20221130.exe
```
but not via 
```scoop update -g qemu```

The decompression error is also shown in the log-dialogbox when executing a ```test``` operation on the exe from within 7zFM 22.01 

Recently, there have been some changes in how qemu generates the windows nsis exectuables
- changes
  - the windows executable is built using msys/mingw64 
    - the installer build artifacts are generated inside gitlab
    - previously stweil was separately building w64-qemu and w32-qemu and packaging the dlls manually into the nsis-exe. I believe he recently updated the build scripts to include the mingw/gnome-dls during the gitlab build process
    - https://lore.kernel.org/qemu-devel/20221031091406.382872-1-sw@weilnetz.de/
- the windows installer is signed 
    - 2022-11-23: New QEMU installers (7.2.0-rc2). Signed uninstaller, enhanced file properties.
    - see changelog on https://qemu.weilnetz.de/w64/ 


last lines of log C:\vol\scoop_01\SCOOPG\apps\qemu\7.2.0-rc2\7zip.log
```
Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1
ERROR: Data Error : lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis
```

I had filed a bug in qemu-project. But it seems that this has to be handled properly by scoop's 7z unpackager. 
https://gitlab.com/qemu-project/qemu/-/issues/1349

**Comment by jpovixwm** [comment]
A hacky workaround exists for those who just want to install QEMU with scoop today:
1. Locate your `7z.shim` file (e.g. `~/scoop/shims/7z.shim`)
2. Append the line `args = -xr!lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis` to it
3. (Optional) Inspect the value of Scoop's `use_external_7z` config option, so that you can later restore it to the initial value: `scoop config use_external_7z`
4. Instruct scoop to use an external 7zip executable: `scoop config use_external_7z true` (this will only work under the assumption that `~/scoop/shims/` is in your PATH and `~/scoop/shims/7z.exe` is the first match for `7z.exe`)
5. Run `scoop install qemu` as usual
6. Revert the changes made to the `7z.shim` file and to your Scoop configuration: `scoop config rm use_external_7z` (if it was unset previously) or `scoop config use_external_7z initial_value`

**Comment by ciarancourtney** [comment]
> A hacky workaround exists for those who just want to install QEMU with scoop today:
> 
> 1. Locate your `7z.shim` file (e.g. `~/scoop/shims/7z.shim`)
> 2. Append the line `args = -xr!lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis` to it
> 3. (Optional) Inspect the value of Scoop's `use_external_7z` config option, so that you can later restore it to the initial value: `scoop config use_external_7z`
> 4. Instruct scoop to use an external 7zip executable: `scoop config use_external_7z true` (this will only work under the assumption that `~/scoop/shims/` is in your PATH and `~/scoop/shims/7z.exe` is the first match for `7z.exe`)
> 5. Run `scoop install qemu` as usual
> 6. Revert the changes made to the `7z.shim` file and to your Scoop configuration: `scoop config rm use_external_7z` (if it was unset previously) or `scoop config use_external_7z initial_value`

@jpovixwm Spotted a typo there, the correct config var is `use_external_7zip`, not `use_external_7z `

**Comment by Lutra-Fs** [comment]
it seems like there is the same issue with tesseract@5.3.0.20221214

**Comment by rashil2000** [comment]
> Code:
> ```
> 7z x -y dl.7z -xr!lib\gdk-pixbuf-2.0\2.10.0\qemu-uninstall.exe.nsis
> ```

As a temporary fix (for both qemu and tesseract), we can use `Expand-7zipArchive` in the pre_install field of the manifest to exclude the uninstaller file. See https://github.com/ScoopInstaller/Extras/blob/master/bucket/cdex.json#L10 for example.

Can someone submit a PR?
