### ISSUE TITLE
[Request]: update msys2

### ISSUE THREAD

**Issue by Ymigmli** [ScoopInstaller/Main#4166]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

msys2-installer

### Description

now version:2022-10-28 last version:2022-09-04

### Homepage

https://github.com/msys2/msys2-installer

### Download Link(s)

https://github.com/msys2/msys2-installer/releases/tag/2022-10-28

### Some Indication of Popularity/Repute

now version:2022-10-28
last version:2022-09-04

**Comment by rashil2000** [comment]
The checkver URL needs to be updated to `https://github.com/msys2/msys2-installer/releases`. Can you make a PR?

**Comment by Ymigmli** [comment]
emm... I need to learn how to pull request
