### ISSUE TITLE
[Bug]: cygwin@2.924: hash check failed

### ISSUE THREAD

**Issue by naderi** [ScoopInstaller/Main#4170]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

cygwin

### Expected/Current Behaviour

App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    c0a26f4693ba25cc2039033126b0d95ac0f6fbc833b84857fdfa4ab11fd79411
Actual:      edd0a64dc65087ffe453ca94b267169b39458a983b29ac31320fcaa983d0f97e

### Steps to Reproduce

```console
scoop update cygwin
```

### Possible Solution

Fixing hash

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15
```

### Scoop Config

```console
aria2-enabled : True
alias         :
last_update   : 25.11.2022 23:38:34
use_lessmsi   : True
scoop_branch  : master
scoop_repo    : https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by naderi** [comment]
Your new reporting system is incredibly complicated. That was just a "hash check failed" bug and I had to fill 5 text boxes!

**Comment by rashil2000** [comment]
@niheaven have blank issues been disabled in the bucket repos? They should be enabled, otherwise automated new-issue links (like hash failures and decompression failures) will cause a lot of hassles.

**Comment by niheaven** [comment]
No, they are not disabled if users click the URL provided in error system, at least I could create one...

**Comment by rashil2000** [comment]
In the config file they are disabled https://github.com/ScoopInstaller/Main/blob/08a62b58b61688561730d6646176f3ee087dac36/.github/ISSUE_TEMPLATE/config.yml#L1

This might be causing problems for outside contributors

**Comment by sriyash421** [comment]
> No, they are not disabled if users click the URL provided in error system, at least I could create one...

This is the screen I see when clicking on the auto issue creation link. 
![image](https://user-images.githubusercontent.com/45433521/204143258-46b75a0a-1100-4f5d-944d-d08a34a102a8.png)

**Comment by kwsp** [comment]
Indeed I cannot open a blank issue either. Clicking on the `Please try again or create a new issue by using the following link and paste your console output:` link no longer creates a new issue.
