### ISSUE TITLE
[Bug]: ERROR Hash check failed!@main/cygwin

### ISSUE THREAD

**Issue by areen-c** [ScoopInstaller/Main#4175]
### Prerequisites

- [x] I have written a descriptive issue title.
- [ ] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

main/cygwin

### Expected/Current Behaviour

App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    c0a26f4693ba25cc2039033126b0d95ac0f6fbc833b84857fdfa4ab11fd79411
Actual:      edd0a64dc65087ffe453ca94b267169b39458a983b29ac31320fcaa983d0f97e

### Steps to Reproduce

```console
scoop update cygwin
```

### Possible Solution

Fix hash

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.0 - Released at 2022-10-10


'main' bucket:
e9458597a (HEAD -> master, origin/master, origin/HEAD) oh-my-posh: Update to version 12.21.0
```

### Scoop Config

```console
last_update           : 27/11/2022 20.41.48
use_lessmsi           : $true
aria2-warning-enabled : False
scoop_repo            : https://github.com/lukesampson/scoop
scoop_branch          : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by niheaven** [comment]
Closed by https://github.com/ScoopInstaller/Main/commit/08a62b58b61688561730d6646176f3ee087dac36
