### ISSUE TITLE
qemu@7.2.0-rc3: decompress error

### ISSUE THREAD

**Issue by thgwalter** [ScoopInstaller/Main#4185]
Same as with rc2 ; there is a decompress error.

**Comment by SamJakob** [comment]
Whilst I get the decompress error it does seem to successfully install so I'm not sure exactly what's failing to decompress.

**Comment by SamJakob** [comment]
Ah, indeed I think this is the same issue as #4164

**Comment by rashil2000** [comment]
Duplicate of #4164
