### ISSUE TITLE
imagemagick@7.1.0-52: decompress error

### ISSUE THREAD

**Issue by tch123** [ScoopInstaller/Main#4195]
Extracting ImageMagick-7.1.0-52-Q16-HDRI-x64-dll.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\my\scoop\apps\imagemagick\7.1.0-52\ImageMagick-7.1.0-52-Q16-HDRI-x64-dll.exe.
Log file:
  ~\scoop\apps\imagemagick\7.1.0-52\innounp.log

-------------------------
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.

**Comment by rashil2000** [comment]
Try this: https://github.com/ScoopInstaller/Main/issues/3964
