### ISSUE TITLE
[Bug]: vulkan package doesn't write necessary registry keys

### ISSUE THREAD

**Issue by Locietta** [ScoopInstaller/Main#4218]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

vulkan

### Expected/Current Behaviour

Official Vulkan SDK installer writes windows registry to register VK layers provided by Khronos. Current manifest doesn't write those keys nor give any notes about it. 

Without registries written, corresponding layers can't be found by vulkan programs. (Which causes tutorials like https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers fail.)

### Steps to Reproduce

```console
scoop install vulkan
```

### Possible Solution

I've implemented a solution at my personal bucket 👉 [manifest](https://github.com/Locietta/sniffer/blob/master/bucket/vulkansdk.json)

Post-install & pre-uninstall scripts are used to write registries. For non-global installation, registries are written to HKCU (modification of which doesn't require elevated rights). For global installation with elevated rights, registries are written to HKLM. And all added entries will be deleted with pre-uninstall scripts.

I can open a PR if people here feel the solution is ok.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
cec6e4513 (HEAD -> master, origin/master, origin/HEAD) xdelta3-cross-gui: Update to version 1.3.1

'java' bucket:
93dd38f8 (HEAD -> master, origin/master, origin/HEAD) graalvm-nightly: Update to version 23.0.0-dev-20221212_0450

'main' bucket:
4519a8e41 (HEAD -> master, origin/master, origin/HEAD) ImageMagick: Update to version 7.1.0-54 (#4216)

'sniffer' bucket:
a8459b6 (HEAD -> master, origin/master, origin/HEAD) xanmod-WSL2: Update to version 6.0.12-1.1
```

### Scoop Config

```console
PS> scoop config

proxy                 : 127.0.0.1:7890
last_update           : 2022/12/12 19:11:19
gh_token              : <Removed>
aria2-enabled         : False
aria2-warning-enabled : False
root_path             : D:\Scoop
global_path           : D:\Scoop\global
scoop_branch          : master
scoop_repo            : git@github.com:ScoopInstaller/Scoop.git
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
We can create a script that does this, and tell people about it in the notes. I think there was a PR to handle it: https://github.com/ScoopInstaller/Main/pull/1632

**Comment by Locietta** [comment]
> We can create a script that does this, and tell people about it in the notes.

Yes, we can create install-xxx.ps1 & uninstall-xxx scripts.ps1 to write and delete registries. (And it seems the standard way.) 

But just for curiosity, why can't we just put them into the manifest to make everything silently done? I think people are likely to forget to run uninstall-xxx because there's no any notes about it during `scoop uninstall`. It sounds good to let scoop handle everything.

> I think there was a PR to handle it: #1632

Ahh, I missed this one.

But looks like It's about debug libs that aren't zipped in the installer itself, thus requiring to download from extra urls. This issue here is about correctly registering stuffs (already under Bin/Bin32) into windows registry. It's not quite the same though.

**Comment by rashil2000** [comment]
> But just for curiosity, why can't we just put them into the manifest to make everything silently done? I think people are likely to forget to run uninstall-xxx because there's no any notes about it during `scoop uninstall`. It sounds good to let scoop handle everything.


Scoop does not automatically touch the registry, as part of its philosophy - it stays as unobtrusive as possible. But you're right about the uninstallation part. For that, we can handle it the way `everything` handles it: https://github.com/ScoopInstaller/Extras/blob/master/bucket/everything.json#L48, i.e. addition is done by user, and deletion is done automatically, if it exists.

**Comment by Locietta** [comment]
> It stays as unobtrusive as possible.

To my understanding, touching registries is unfavorable and often avoided just because it normally causes UAC pop ups, which is quite annoying.

But writing registries to HKCU(HKEY_CURRENT_USER) doesn't requires UAC actually... **People get UAC pop-ups because of the limitation of `reg import`/`regedit`**. 

Somehow, `regedit` ALWAYS requires elevated privileges if current user is an administrator (even when you only write registries to HKCU). If current user isn't an administrator, however, `regedit` will just open normally without UAC, and with only HKCU accessibility.

Writing to HKCU directly with powershell or .NET built-in API doesn't invoke any UAC, it's clean and _unobtrusive_.

As an example, this script writes a new entry to `HKEY_CURRENT_USER\Software\Khronos\Vulkan\ExplicitLayers` without UAC, and you can test it :)
```powershell
$reg_path = 'SOFTWARE\Khronos\Vulkan\ExplicitLayers'
$HKCU = [Microsoft.Win32.Registry]::CurrentUser # .NET HKCU object
$reg = $HKCU.CreateSubKey($reg_path)            # Create key path, or open it if already exists

$entry_name = 'haha'
$entry_value = 2
$entry_type = [Microsoft.Win32.RegistryValueKind]::DWord

$reg.SetValue($entry_name, $entry_value, $entry_type)
```

Correct me if I'm wrong.

**Comment by rashil2000** [comment]
The issue is not just about UAC, it's about leaving traces behind (after uninstallation, for example). As an official package, Scoop (the package manager) will not write to registry unless manually instructed by the user (see `python`, for example).
