### ISSUE TITLE
[Request]: Add passbolt-cli

### ISSUE THREAD

**Issue by polaris940** [ScoopInstaller/Main#4221]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

passbolt-cli

### Description

CLI for the open source password manager for teams

### Homepage

https://www.passbolt.com/

### Download Link(s)

https://github.com/passbolt/go-passbolt-cli

### Some Indication of Popularity/Repute

Main passbolt-api GitHub project has 3.3K stars and 250 forks. This is a request for the accompanying CLI.

**Comment by rashil2000** [comment]
Please make a PR!
