### ISSUE TITLE
[Request]: natscli

### ISSUE THREAD

**Issue by fingul** [ScoopInstaller/Main#4267]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

natscli

### Description

The NATS Command Line Interface

### Homepage

https://github.com/nats-io/natscli

### Download Link(s)

https://github.com/nats-io/natscli/releases/

### Some Indication of Popularity/Repute

- fork : 45 / start : 251
- it actually companion app for nats server - star : 1200k (https://github.com/ScoopInstaller/Main/blob/master/bucket/nats-server.json)

**Comment by fingul** [comment]
Currently, i use below code tempolarily.
```
{
  "version": "v0.0.34",
  "description": "nats-client",
  "homepage": "https://nats.io",
  "license": "Apache-2.0",
  "architecture": {
    "64bit": {
      "extract_dir": "nats-0.0.34-windows-amd64",
      "url": "https://github.com/nats-io/natscli/releases/download/v0.0.34/nats-0.0.34-windows-amd64.zip"
    }
  },
  "bin": "nats.exe"
}
```

**Comment by fingul** [comment]
It may (or shoul be) same format like below manifest.

https://github.com/ScoopInstaller/Main/blob/master/bucket/nats-server.json

**Comment by rashil2000** [comment]
Please make a PR!
