### ISSUE TITLE
[Request]: marksman

### ISSUE THREAD

**Issue by pynappo** [ScoopInstaller/Main#4286]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

marksman

### Description

Write Markdown with code assist and intelligence in the comfort of your favourite editor.

### Homepage

https://github.com/artempyanykh/marksman

### Download Link(s)

https://github.com/artempyanykh/marksman/releases

### Some Indication of Popularity/Repute

668 GitHub stars.

### Notes

Initial draft of manifest can be found here: https://github.com/ScoopInstaller/Main/compare/master...pynappo:Main:master, just wanted approval before sending the PR.

It's a language server for Markdown documents.

**Comment by rashil2000** [comment]
Sure!
