### ISSUE TITLE
[Bug] Installing JDTLS | Can't shim '': couldn't find ''.

### ISSUE THREAD

**Issue by jeeeem** [ScoopInstaller/Main#4287]
#### Current Behavior
Cannot install JDTLS due to some error

#### Expected Behavior

Successfully installed JDTLS package

#### Additional context/output

<img width="476" alt="jdtls" src="https://user-images.githubusercontent.com/51053482/209809009-141e18f8-71ec-4d35-ada2-d1061ee1e8c8.png">

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11

**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.3.1

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
{
  "last_update": "2022-12-27T18:32:08.1843096+08:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by jeeeem** [comment]
I have python installed. 

![image](https://user-images.githubusercontent.com/51053482/209899856-35ca71fa-143b-4275-933e-d53387d04155.png)

**Comment by jeeeem** [comment]
Does it required the `python.exe` specifically? I have python installed thru pyenv

![image](https://user-images.githubusercontent.com/51053482/209899950-2154310a-d9fd-464a-a7eb-4d620b456c3d.png)

**Comment by jeeeem** [comment]
Closing this as I find the solution by not using the pyenv python version.

**Comment by HUMORCE** [comment]
the manifest requires `python.exe` to be found on your OS($env:PATH).
