### ISSUE TITLE
libvips: bin should be added to path so its dlls can be used

### ISSUE THREAD

**Issue by CoolingTool** [ScoopInstaller/Main#4313]
### Discussed in https://github.com/ScoopInstaller/Main/discussions/4288

<div type='discussions-op-text'>

<sup>Originally posted by **CoolingTool** December 28, 2022</sup>
Would be nice cause I installed the package so I could specifically use ./bin/libvips-42.dll and not its binaries
(also the package has lib in it's name so it makes sense)</div>

**Comment by rashil2000** [comment]
Please make a PR!
