### ISSUE TITLE
[Bug]: Pwsh manifest should persist Microsoft.VSCode_profile.ps1

### ISSUE THREAD

**Issue by cesaryuan** [ScoopInstaller/Main#4326]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

pwsh

### Expected/Current Behaviour

[pwsh manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json) should persist Microsoft.VSCode_profile.ps1 according to [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3&viewFallbackFrom=powershell-7.1#the-profile-files:~:text=All%20users%2C%20Current%20Host%20%2D%20%24PSHOME%5CMicrosoft.VSCode_profile.ps1)

### Steps to Reproduce

```console
No need.
```

### Possible Solution

Add `Microsoft.VSCode_profile.ps1` to persist array.

### Scoop and Buckets Version

```console
No need.
```

### Scoop Config

```console
No need.
```

### PowerShell Version

```console
No need.
```

**Comment by rashil2000** [comment]
Please make a PR!
