### ISSUE TITLE
[Request]: libheif

### ISSUE THREAD

**Issue by benf-write** [ScoopInstaller/Main#4328]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

libheif

### Description

A decoder and encoder for the heif and avif formats

### Homepage

https://github.com/strukturag/libheif

### Download Link(s)

https://github.com/pphh77/libheif-Windowsbinary/releases/tag/v1.14.0

### Some Indication of Popularity/Repute

Active project, 1139 stars, 218 forks.

If I get a thumbs up on this I'll submit a PR.

**Comment by rashil2000** [comment]
Is there any indication that https://github.com/pphh77/libheif-Windowsbinary is the official binary distribution repo for https://github.com/strukturag/libheif?

**Comment by benf-write** [comment]
That's a good point, I may have to reconsider.

People in strukturag/libheif 's issues page do point to the project, but it's likely not official. https://github.com/strukturag/libheif/issues/200

The official way to get Windows binaries is this,

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install libheif
```
which might be too heavy for Scoop... I might have to close this ticket.

**Comment by rashil2000** [comment]
Yeah, building packages is not currently supported by Scoop. If the libheif authors can give a thumbs up to the above binaries, we can have them.

**Comment by benf-write** [comment]
Thanks @rashil2000 for the quick responses. Closing this ticket unfortunately because the official way to get it is through vcpkg. Makes sense that we'd want official binaries.
