### ISSUE TITLE
python@3.7.4: decompress error

### ISSUE THREAD

**Issue by onlylhf** [ScoopInstaller/Main#433]
> PS C:\Users\li542> scoop install python                                                                                                                              Updating Scoop...                                                                                                                                                    fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to github.com port 443: Timed out
> Update failed.
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.                                                                                  Installing 'python' (3.7.4) [64bit]
> Loading python-3.7.4-amd64.exe from cache.
> Checking hash of python-3.7.4-amd64.exe ... ok.
> Running installer script...
> Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试该命令。
> 所在位置 C:\Users\li542\scoop\apps\scoop\current\lib\decompress.ps1:281 字符: 38                                                                                     + ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...                                                                                      +                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                      + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException                                                             + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand                                                                                
> Failed to extract files from C:\Users\li542\scoop\apps\python\3.7.4\python-3.7.4-amd64.exe.
> Log file:
>   ~\scoop\apps\python\3.7.4\dark.log
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/ScoopInstaller/Main/issues/new?title=python%403.7.4%3a+decompress+error

**Comment by linsui** [comment]
Try
```
scoop install dark
```

**Comment by onlylhf** [comment]
> Try
> 
> ```
> scoop install dark
> ```

Thank you
