### ISSUE TITLE
[Bug]: When installing llvm from main, clang,clang++ etc. dont get shimmed.

### ISSUE THREAD

**Issue by mundusnine** [ScoopInstaller/Main#4337]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

llvm

### Expected/Current Behaviour

Current behaviour:
![image](https://user-images.githubusercontent.com/29337013/211626188-a4079b44-085f-40f2-b5d3-70cf94a6f700.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/29337013/211626339-2fea0c46-a409-4e59-9893-dfb0eefc9cda.png)

### Steps to Reproduce

```console
scoop install llvm

clang hello.c -o hello.exe

Command clang not found
```

### Possible Solution

copy-pasta from : https://raw.githubusercontent.com/batkiz/backit/master/bucket/llvm.json

### Scoop and Buckets Version

```console
scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15
```

### Scoop Config

```console
scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-01-10T12:32:33.0902337-05:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rashil2000** [comment]
Shimming is not required because the bin directory is appended to PATH: https://github.com/ScoopInstaller/Main/blob/master/bucket/llvm.json#L17
