### ISSUE TITLE
gcc@11.2.0: decompress error

### ISSUE THREAD

**Issue by AlexanderKomi** [ScoopInstaller/Main#4339]
PS C:\Users\Alex> scoop install gcc
Updating Scoop...
Updating 'extras' bucket...
 * 1934d9e87 windowsdesktop-runtime-lts: Update to version 6.0.13        81 minutes ago
 * 3bc2dd84a webex: Update to version 43.1.0.24716                       81 minutes ago
 * 474de6a7c vscode: Update to version 1.74.3                            82 minutes ago
 * e2ce60aa3 propertree: Update to version 0.2023.01.10                  82 minutes ago
 * 0ad3ce9d0 ocenaudio: Update to version 3.11.22                        82 minutes ago
 * a52f03503 kapow-punch-clock: Update to version 1.6.1                  82 minutes ago
 * 645ec1062 jira-cli: Update to version 1.3.0                           82 minutes ago
 * d6d7c1fa4 gcloud: Update to version 413.0.0                           82 minutes ago
 * d8c01003e nexttrace: Update to version 0.2.6                          5 hours ago
 * c9d2becec manifold: Update to version 9.0.179                         5 hours ago
 * 5bd1b59ac manifold-viewer: Update to version 9.0.179                  5 hours ago
 * f57cd9d04 linphone: Update to version 5.0.6                           5 hours ago
 * 55b2ccda0 kibana: Update to version 8.6.0                             5 hours ago
 * 09e464e0c jetbrains-hub: Update to version 2022.3.15381               5 hours ago
 * 9e9f985a7 fileoptimizer: Update to version 16.20.2771                 5 hours ago
 * 483eef64f elasticsearch: Update to version 8.6.0                      5 hours ago
Updating 'java' bucket...
Updating 'main' bucket...
 * 57b2e98b8 refreshenv: Update to version 5.11.1                        83 minutes ago
 * 89a1f58a2 quarkus-cli: Update to version 2.15.3                       83 minutes ago
 * 2250aeeba plex-server: Update to version 1.30.1.6562-915986d62        83 minutes ago
 * 9c3949e6d pester: Update to version 5.4.0                             83 minutes ago
 * bae30d711 oh-my-posh: Update to version 12.38.1                       83 minutes ago
 * 1079a8f44 nixpacks: Update to version 1.0.5                           83 minutes ago
 * 6ff5f9d1c nano: Update to version 7.1-13                              83 minutes ago
 * a543bc989 gotify-server: Update to version 2.2.4                      83 minutes ago
 * 756187cc9 go: Update to version 1.19.5                                83 minutes ago
 * 1c585e367 edgedriver: Update to version 111.0.1613.0                  83 minutes ago
 * 48cf1eb23 dotnet-sdk: Update to version 7.0.102                       83 minutes ago
 * 76b254193 centrifugo: Update to version 4.1.1                         83 minutes ago
 * 4ba4edd8a argocd: Update to version 2.5.6                             83 minutes ago
 * 09bb063cd retdec: Update to version 5.0 (#4335)                       4 hours ago
 * 4530d7234 zeebe: Update to version 8.1.6                              5 hours ago
 * ff4443637 symfony-cli: Update to version 5.4.21                       5 hours ago
 * f0fa82374 poetry: Update to version 1.3.2                             5 hours ago
 * 67fadda21 pnpm: Update to version 7.24.2                              5 hours ago
 * 12704992d oh-my-posh: Update to version 12.38.0                       5 hours ago
 * d07c12f0b nano: Update to version 7.1-12                              5 hours ago
 * 95d102543 jenkins: Update to version 2.386                            5 hours ago
 * 23a401325 flux: Update to version 0.38.3                              5 hours ago
 * 57722c208 edgedriver: Update to version 111.0.1612.0                  5 hours ago
 * 528e7d5b7 curl: Update to version 7.87.0_2                            5 hours ago
 * aa2bad90b camunda-operate: Update to version 8.1.6                    5 hours ago
 * c4eb73256 bazel-buildtools: Update to version 6.0.0                   5 hours ago
 * 0ca5a3001 balena-cli: Update to version 15.0.1                        5 hours ago
Updating 'nerd-fonts' bucket...
Scoop was updated successfully!
Installing 'gcc' (11.2.0) [64bit] from main bucket
components-18.0.7z (96,4 MB) [====================================================================================================================================================================================================] 100%
Checking hash of components-18.0.7z ... ok.
Extracting components-18.0.7z ... Invoke-ExternalCommand : Das Argument für den Parameter "FilePath" kann nicht überprüft werden. Das Argument ist NULL oder leer. Geben Sie ein Argument an, das nicht NULL oder leer ist, und führen Sie den Befehl erneut aus.
In C:\Users\Alex\scoop\apps\scoop\current\lib\decompress.ps1:45 Zeichen:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\Alex\scoop\apps\gcc\11.2.0\components-18.0.7z.
Log file:
  ~\scoop\apps\gcc\11.2.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gcc%4011.2.0%3a+decompress+error

**Comment by rashil2000** [comment]
Please translate the error.

What's in the log file?

**Comment by rashil2000** [comment]
Closing due to no feedback
