### ISSUE TITLE
swift@5.7.2 hash check failed

### ISSUE THREAD

**Issue by doesnotsitproperly** [ScoopInstaller/Main#4348]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

swift@5.7.2

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/commit/e136a1a9f7eb0537f9da640e3c9775167da35cd3
