### ISSUE TITLE
LLVM not being updated to 9.0.0

### ISSUE THREAD

**Issue by DaanDeMeyer** [ScoopInstaller/Main#436]
What's the usual delay on autoupdate? LLVM 9.0.0 has been out for about 2 days but the scoop version is still stuck at 9.0.0.

checkver.ps1 correctly reports that a new version is available so I'm wondering how long it takes to be applied to the main scoop repository.

**Comment by linsui** [comment]
It's a bug. Scoop downloads llvm from github but llvm 9.0.0 is not punlished on github. See https://github.com/llvm/llvm-project/releases.
