### ISSUE TITLE
After I installed mongodb, how to start its service in windows

### ISSUE THREAD

**Issue by dong-lufei** [ScoopInstaller/Main#4375]
scoop install main/mongodb

v6.1.1

**Comment by HUMORCE** [comment]
`scoop info mongodb` to show helpful information of this package, e.g. it's binaries(shims), notes, etc.

`mongod --help`, and package `extras/mongosh` is suggested.

**Comment by dong-lufei** [comment]
Since the new version does not include mongosh, you can do a prompt after installation

**Comment by HUMORCE** [comment]
Done. https://github.com/ScoopInstaller/Main/commit/79fdd2ebfa601232d76c0fe930bff69b13382fd2
