### ISSUE TITLE
gping@1.8.0: decompress error

### ISSUE THREAD

**Issue by sedlund** [ScoopInstaller/Main#4393]
Extracting gping-Windows-x86_64.zip ... ERROR Exception calling "Start" with "0" argument(s): "The directory name is invalid"
Failed to extract files from C:\Users\Scott\scoop\apps\gping\1.8.0\gping-Windows-x86_64.zip.
Log file:
  ~\scoop\apps\gping\1.8.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gping%401.8.0%3a+decompress+error

The log file stated above does not exist.

uninstall and then reinstall fixed.

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop install gping
Installing 'gping' (1.8.0) [64bit] from main bucket
Loading gping-Windows-x86_64.zip from cache
Checking hash of gping-Windows-x86_64.zip ... ok.
Extracting gping-Windows-x86_64.zip ... done.
Linking ~\scoop\apps\gping\current => ~\scoop\apps\gping\1.8.0
Creating shim for 'gping'.
'gping' (1.8.0) was installed successfully!
```
