### ISSUE TITLE
go@1.12.5: download via aria2 failed

### ISSUE THREAD

**Issue by CalElFe** [ScoopInstaller/Main#44]
The download link recorded in the main bucket for golang is blocked by China GFW internet censorship, due to that specific link is located at googleapis.com. Could you please consider to add an extra entry for Chinese user? i.e. go-China. 

A workable link for download golang in China would be [https://golang.google.cn/doc/install?download=go1.12.5.windows-amd64.msi](https://golang.google.cn/doc/install?download=go1.12.5.windows-amd64.msi). 

Thank you a lot.
The console log is attached as following:

Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: [#74d825 0B/0B CN:1 DL:0B]
Download: 05/09 06:32:06 [ERROR] CUID#8 - Download aborted. URI=https://storage.googleapis.com/golang/go1.12.5.windows-amd64.zip
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 74d825|ERR |       0B/s|C:/Users/CalElFe/scoop/cache/go#1.12.5#https_storage.googleapis.com_golang_go1.12.5.windows-amd64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://storage.googleapis.com/golang/go1.12.5.windows-amd64.zip
    referer=https://storage.googleapis.com/golang/
    dir=C:\Users\CalElFe\scoop\cache
    out=go#1.12.5#https_storage.googleapis.com_golang_go1.12.5.windows-amd64.zip

ERROR & 'C:\Users\CalElFe\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\CalElFe\scoop\cache\go.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9012 --continue

**Comment by h404bi** [comment]
You can let scoop to use a proxy by using `scoop config proxy "<your proxy server>"`

**Comment by CalElFe** [comment]
ok
