### ISSUE TITLE
[Request]: luau

### ISSUE THREAD

**Issue by xhayper** [ScoopInstaller/Main#4420]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

luau

### Description

A fast, small, safe, gradually typed embeddable scripting language derived from Lua 

### Homepage

https://luau-lang.org/

### Download Link(s)

https://github.com/Roblox/luau/releases

### Some Indication of Popularity/Repute

2.9k Github Stars
253 Fork

**Comment by rashil2000** [comment]
Please make a PR!
