### ISSUE TITLE
[Bug]: NanaZip "Unknown Error" when launching UI

### ISSUE THREAD

**Issue by leumasme** [ScoopInstaller/Main#4425]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

nanazip

### Expected/Current Behaviour

When installing NanaZip and launching the UI from the Windows Shortcut, a popup opens with the text "Unknown Error" and no further information.
![0024301](https://user-images.githubusercontent.com/29953391/217098880-8882f5a5-15ff-4c68-8b92-4495391df7df.png)

### Steps to Reproduce

```console
❯ scoop install nanazip
Installing 'nanazip' (2.0.450) [64bit] from main bucket
Loading 40174MouriNaruto.NanaZip_2.0.450.0_gnj4mf6z9tkrc.msixbundle from cache
Checking hash of 40174MouriNaruto.NanaZip_2.0.450.0_gnj4mf6z9tkrc.msixbundle ... ok.
Extracting dl.7z ... done.
Running pre_install script...
Linking S:\Apps\Scoop\apps\nanazip\current => S:\Apps\Scoop\apps\nanazip\2.0.450
Creating shim for '7z'.
WARN  Overwriting shim ('7z.exe' -> 'NanaZipC.exe') installed from 7zip-zstd
Creating shim for '7zG'.
WARN  Overwriting shim ('7zg.exe' -> 'NanaZipG.exe') installed from 7zip-zstd
Creating shortcut for NanaZip (NanaZip.exe)
'nanazip' (2.0.450) was installed successfully!
```

### Possible Solution

?

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
b6c8eaf61 (HEAD -> master, origin/master, origin/HEAD) xmedia-recode: Update to version 3.5.7.0

'games' bucket:
5e7a5f37 (HEAD -> master, origin/master, origin/HEAD) snes9x-dev: Update to version 1.61-1098

'java' bucket:
261d4c3d (HEAD -> master, origin/master, origin/HEAD) temurin19-nightly-jdk: Update to version 19.0.2-7.0.202302040347

'main' bucket:
c2317503a (HEAD -> master, origin/master, origin/HEAD) nats-server: Update to version 2.9.14

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.

'versions' bucket:
f1525df2a (HEAD -> master, origin/master, origin/HEAD) ipfilter-nightly: Update to version 1675699336
```

### Scoop Config

```console
❯ scoop config

last_update                       aria2-enabled scoop_branch scoop_repo
-----------                       ------------- ------------ ----------
2023-02-06T22:26:55.4022859+01:00         False master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

Possibly related installed scoop packages:
- 7zip
- 7zip-zstd
- asar7z (hooked into 7zip-zstd)
On that note, asar7z uses `scoop which 7z` to find the 7zip path and then put it into the "Formats" folder. This won't work if nanazip is installed. See also: https://github.com/ScoopInstaller/Extras/issues/10445

Also tested on anothe device that only has `7zip` installed via scoop, not the other packages

**Comment by rashil2000** [comment]
I think you should report it in their upstream repo

**Comment by leumasme** [comment]
@rashil2000 Installing nanazip regularly via the .msix package linked in [their Github Releases](https://github.com/M2Team/NanaZip/releases) works fine.

**Comment by rashil2000** [comment]
I'm afraid nothing can be done in this case. Scoop just extract the MSIX file - that's all.
