### ISSUE TITLE
Question on the contents of the graphviz package

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ScoopInstaller/Main#4428]
This package distributes multiple executables besides the usual `dot` - `neato`, `twopi`, `fdp` and so on.

Essentially, they provide another default layout for `dot` depending on the name of the executable. I found that back in 2020 (commit 453df2929ffb35caa64b7954fa7690a5a1f66a28) these executables were removed from the manifest. The commit message was not really clear on why exactly they were removed.

I would like to re-add these executables in the form of symlinks/shims as specified in the documentation.

The full list of such layouts:
- circo
- fdp
- neato
- osage
- patchwork
- sfdp
- twopi

I wonder if there are drawbacks or objections to that approach. I guess I'll manage a PR in the coming days.

**Comment by rashil2000** [comment]
Please make a PR to add them back!
