### ISSUE TITLE
elixir: Erlang should be a required (not suggested) dependency

### ISSUE THREAD

**Issue by Keyacom** [ScoopInstaller/Main#4435]
When I installed Elixir and tried to run `iex.bat` without Erlang, it errored out (Erlang missing), so I installed Erlang. This means that installing Elixir should also install Erlang (Elixir is unfortunately not self-contained).

**Comment by rashil2000** [comment]
Hard dependencies are not generally a good idea - people might install Erlang through sources other than Scoop, or worse, they might install a non-latest Erlang version or a version from some different bucket. In that case we shouldn't automatically install Erlang again.
