### ISSUE TITLE
python reset not working

### ISSUE THREAD

**Issue by hagaigold** [ScoopInstaller/Main#444]
PR https://github.com/ScoopInstaller/Main/pull/316 break the reset option for python.

adding the root directory of python installed directory, "hide" the shims directory, and those the reset to older version of python stoped to work.

```
> where python
C:\Users\hagai\scoop\apps\python\current\python.exe
C:\Users\hagai\scoop\shims\python.exe

```

**Comment by r15ch13** [comment]
The simplest solution would be to change the order in your `PATH`. Put the shims directory after the `python\current` directory in the list and it should work again.

**Comment by jeff-hykin** [comment]
shouldn't scoop place shims above apps?
