### ISSUE TITLE
[Request]: Chafa

### ISSUE THREAD

**Issue by LaunchLee** [ScoopInstaller/Main#4441]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

chafa

### Description

📺🗿 Terminal graphics for the 21st century.

### Homepage

https://hpjansson.org/chafa/

### Download Link(s)

Download Website: https://hpjansson.org/chafa/download/
Download link(1.12.4-1): https://hpjansson.org/chafa/releases/static/chafa-1.12.4-1-x86_64-windows.zip

### Some Indication of Popularity/Repute

GitHub Page: https://github.com/hpjansson/chafa

Stars: 1.9k stars
Watchers: 29
Forks: 43 forks

**Comment by rashil2000** [comment]
Please make a PR!
