### ISSUE TITLE
aws-sam-cli@1.73.0: decompress error

### ISSUE THREAD

**Issue by sobert-moe** [ScoopInstaller/Main#4458]
$ scoop install aws-sam-cli
WARN  Purging previous failed installation of aws-sam-cli.
ERROR 'aws-sam-cli' isn't installed correctly.
Removing older version (1.73.0).
'aws-sam-cli' was uninstalled.
Installing 'aws-sam-cli' (1.73.0) [64bit] from main bucket
Loading AWS_SAM_CLI_64_PY3.msi from cache
Checking hash of AWS_SAM_CLI_64_PY3.msi ... ok.
Extracting AWS_SAM_CLI_64_PY3.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\sobert\scoop\apps\aws-sam-cli\1.73.0\AWS_SAM_CLI_64_PY3.msi.
Log file:
  ~\scoop\apps\aws-sam-cli\1.73.0\msi.log

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+aws-sam-cli+is%3Aclosed+
