### ISSUE TITLE
[Request] git: Shell menu integration

### ISSUE THREAD

**Issue by dong-lufei** [ScoopInstaller/Main#4462]
scoop install git

v2.39.2.windows.1

Shell integration - just right click on a folder in Windows Explorer to access BASH or GUI

**Comment by rashil2000** [comment]
Someone will have to write a reg file for it, similar to 7zip: https://github.com/ScoopInstaller/Main/tree/master/scripts/7-zip

**Comment by skaravos** [comment]
I'm working on this, will submit a PR soon.
