### ISSUE TITLE
python@3.7.4: decompress error

### ISSUE THREAD

**Issue by MarcoPortmannTT** [ScoopInstaller/Main#447]
ERROR Exit code was 1!
Failed to extract files from ~\scoop\apps\python\3.7.4\python-3.7.4-amd64.exe.
Log file:
  ~\scoop\apps\python\3.7.4\dark.log

### content of ~\scoop\apps\python\3.7.4\dark.log

```log
python-3.7.4-amd64.exe
dark.exe : error DARK0001 : Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.


Exception Type: System.IO.IOException

Stack Trace:
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.__Error.WinIOError()
   bei System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   bei Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
   bei Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   bei Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
   bei Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)
```

**Comment by linsui** [comment]
Please try `scoop install dark`

**Comment by MarcoPortmannTT** [comment]
~ $ scoop install dark
Installing 'dark' (3.11.1) [64bit]
Loading dark-3.11.1.zip from cache
Checking hash of dark-3.11.1.zip ... ok.
Extracting dark-3.11.1.zip ... done.
Linking ~\scoop\apps\dark\current => ~\scoop\apps\dark\3.11.1
Creating shim for 'dark'.
'dark' (3.11.1) was installed successfully!

~ $ scoop install python
Installing 'python' (3.7.4) [64bit]
Loading python-3.7.4-amd64.exe from cache
Checking hash of python-3.7.4-amd64.exe ... ok.
Running installer script...
ERROR Exit code was 1!
Failed to extract files from C:\Users\m.portmann\scoop\apps\python\3.7.4\python-3.7.4-amd64.exe.
Log file:
  ~\scoop\apps\python\3.7.4\dark.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.7.4%3a+decompress+error

**Comment by Ash258** [comment]
> ~\scoop\apps\python\3.7.4\dark.log

Post log file...

**Comment by MarcoPortmannTT** [comment]
ERROR Exit code was 1!
Failed to extract files from ~\scoop\apps\python\3.7.4\python-3.7.4-amd64.exe.
Log file:
~\scoop\apps\python\3.7.4\dark.log

python-3.7.4-amd64.exe
dark.exe : error DARK0001 : Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

Exception Type: System.IO.IOException

Stack Trace:
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
bei System.IO.__Error.WinIOError()
bei System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
bei Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
bei Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
bei Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
bei Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)

**Comment by niheaven** [comment]
ref #242
uninstall dark then reinstall it and try install Python again.

**Comment by MarcoPortmannTT** [comment]
uninstall dark and reinstall solves the problem.
Thanks.
