### ISSUE TITLE
[Bug]: Unable to uninstall DosBox?

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Main#4483]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

dosbox

### Expected/Current Behaviour

Unable to unistall DosBox. Expected behavior is it get uninstalled, but return an error instead.

### Steps to Reproduce

```console
PS> scoop uninstall dosbox
Uninstalling 'dosbox' (0.74-3).
Running uninstaller... error.
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
Uninstallation aborted.
```

### Possible Solution

Get it uninstalled. Maybe I have to remove it manually?

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
ba8c447c (HEAD -> master, origin/master, origin/HEAD) megasync@4.8.7.0: Fix hash (Closes #10609)

'games' bucket:
f635a937 (HEAD -> master, origin/master, origin/HEAD) pcsx2-dev: Update to version 1.7.4136

'java' bucket:
45e7585b (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.372-4.0.202302241816

'main' bucket:
51883f90 (HEAD -> master, origin/master, origin/HEAD) flyctl: Update to version 0.0.469
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-02-25T13:57:47.2364828+07:00 master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

PS> scoop info dosbox

Name        : dosbox
Description : DOSBox emulates an Intel x86 PC, complete with sound, graphics, mouse, joystick, modem, etc.
Version     : 0.74-3
Website     : https://www.dosbox.com
License     : GPL-2.0-only
Updated at  : 11/23/2021 3:00:36 AM
Updated by  : Richard Kuhnt
Installed   : 0.74-3
Binaries    : DOSBox.exe

**Comment by rashil2000** [comment]
There's no uninstaller in https://github.com/ScoopInstaller/Main/blob/master/bucket/dosbox.json. 

What is the output of `scoop list`?

**Comment by gphg** [comment]
> What is the output of `scoop list`?

Many. Here's the list shows dosbox only:
```
Name                       Version           Source Updated             Info
----                       -------           ------ -------             ----
dosbox                     0.74-3            main   2019-07-09 15:58:20
```

**Comment by rashil2000** [comment]
Can you try uninstalling through administrator terminal?

**Comment by gphg** [comment]
Uninstalling through administrator terminal worked! I checked `scoop list`, the dosbox doesn't appear on list anymore.
