### ISSUE TITLE
openssl@1.1.1b: hash check failed

### ISSUE THREAD

**Issue by GeraldKaeferle** [ScoopInstaller/Main#45]
PS H:\> scoop install openssl
Installing 'openssl' (1.1.1b) [64bit]
Win64OpenSSL-1_1_1b.exe (3,2 KB) [============================================================================] 100%
Checking hash of Win64OpenSSL-1_1_1b.exe ... ERROR Hash check failed!
App:         main/openssl
URL:         https://slproweb.com/download/Win64OpenSSL-1_1_1b.exe
First bytes: 0D 0A 3C 21 44 4F 43 54
Expected:    a0576f772f8ac7f7ab26be0458ed9cedcd5024f1f130bdc41809c4f7d2ffda128ea94bf86898894c1439a3120772ec335f9579d4786
3ddaa9ae4233548800850
Actual:      b7559fd5c5a3c4c6c14bfbc5fb0c61144283a3771e06626751e10820edddd47139602ed89ae7683999c3937a2f0ca119f9559390fcf
1746dbd87897e0a3a00c7

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=openssl%401.1.1b%3a+hash+check+failed

**Comment by r15ch13** [comment]
The hash is correct. Webserver failed, please run `scoop cache rm openssl` and try again.

**Comment by GeraldKaeferle** [comment]
Sorry but I  get this error again ...

PS H:\>` scoop uninstall openssl`
Uninstalling 'openssl' (1.1.1b).
'openssl' was uninstalled.
PS H:\> `scoop cache rm openssl`
PS H:\>` scoop install openssl`
Installing 'openssl' (1.1.1b) [64bit]
Win64OpenSSL-1_1_1b.exe (3,2 KB) [============================================================================] 100%
Checking hash of Win64OpenSSL-1_1_1b.exe ... ERROR Hash check failed!
App:         main/openssl
URL:         https://slproweb.com/download/Win64OpenSSL-1_1_1b.exe
First bytes: 0D 0A 3C 21 44 4F 43 54
Expected:    a0576f772f8ac7f7ab26be0458ed9cedcd5024f1f130bdc41809c4f7d2ffda128ea94bf86898894c1439a3120772ec335f9579d4786
3ddaa9ae4233548800850
Actual:      c20abc59bcc308c4af5ede71acc3453588950c79b1504f95ae55dfff78209cd50816ead7876c4b3b28263e385ad6456080d4618a8fd
f2538dc998ee38886880e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=openssl%401.1.1b%3a+hash+check+failed
PS H:\>

**Comment by Ash258** [comment]
First actual:
```
Actual: b7559fd5c5a3c4c6c14bfbc5fb0c61144283a3771e06626751e10820edddd47139602ed89ae7683999c3937a2f0ca119f9559390fcf
1746dbd87897e0a3a00c7
```
Second actual

```
Actual: c20abc59bcc308c4af5ede71acc3453588950c79b1504f95ae55dfff78209cd50816ead7876c4b3b28263e385ad6456080d4618a8fd
f2538dc998ee38886880e
```
In both your messages actual is different

**Comment by r15ch13** [comment]
Please try downloading it from a browser. The magic bytes show that the downloaded content starts with `<!DOCT` (HTML).
