### ISSUE TITLE
[Request]: Process Governor

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Main#4536]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Process Governor

### Description

This application allows you to set constraints on Windows processes such as number of CPU usage and memory limit.

### Homepage

https://github.com/lowleveldesign/process-governor

### Download Link(s)

https://github.com/lowleveldesign/process-governor/releases

### Some Indication of Popularity/Repute

This software is very technical.

It isn't reached 500 GitHub repo stars, yet. 405 as this request submitted.

It's available on [Chocolatey](https://community.chocolatey.org/packages/procgov) .

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by gphg** [comment]
I'm working on it.

**Comment by gphg** [comment]
I did it wrong. I made a PR on wrong repo. Should I recreate another one?

I definitely need an assistance.
