### ISSUE TITLE
gpg: Add alias for gpg2

### ISSUE THREAD

**Issue by ObsoleteXero** [ScoopInstaller/Main#4548]
# Issue
There is an issue when signing commits on Windows with gpg, where you have to configure git to use gpg2 (See: https://stackoverflow.com/a/61849206)
The version of gpg installed by scoop is 2.4+
Scoop doesn't currently add an alias for gpg2

# Solution
Creating a symlink called `gpg2.exe` in the binaries directory that points to `gpg.exe` (in the same directory) fixes the issue.
`New-Item -Path gpg2.exe -ItemType SymbolicLink -Value gpg.exe` 
I suggest that scoop do this automatically.
Since creating a Symbolic Link [requires elevation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3#-itemtype), alternatively, copy `gpg.exe` to `gpg2.exe`

**Comment by rashil2000** [comment]
> copy gpg.exe to gpg2.exe

Hi, please make a PR for the fix
