### ISSUE TITLE
[Bug] neofetch: The system cannot find the path specified

### ISSUE THREAD

**Issue by mariobrostech** [ScoopInstaller/Main#4564]
When trying to run neofetch after installing it via Scoop, I am presented with an error message saying "The system cannot find the path specified." Is there any way to fix this?

Thanks in advance!

**Comment by rashil2000** [comment]
Have you installed git?

**Comment by mariobrostech** [comment]
After you asked that, I did some more testing since I personally prefer to use `mingit` over the standard `git` package. Here's what I found:
- Uninstalling `mingit` and then installing `git` didn't seem to fix the problem.
- Next, I tried reinstalling both `git` and `neofetch`, which did work. Interesting!
- What ultimately solved the problem was uninstalling `neofetch`, then installing `git`, and lastly installing `neofetch` again, all in that order.

That leaves us with the following:
- `git` must be installed for `neofetch` to install successfully. Therefore, installing `git` shouldn't merely be a suggestion and should instead be marked as a dependency for `neofetch`.
- Why would `mingit` not work here if the full `git` package does? Is `neofetch` utilizing functions that available through `mingit`? Or, is the installation script only utilizing `git` explicitly? Is there a way to add support for `mingit` if this is the case?

Thanks again for your help!

**Comment by rashil2000** [comment]
Git is not required, precisely. The 'bash' executable is required, because neofetch is a bash script. `git` package includes bash, while `mingit` does not. 

I would suggest installing `winfetch` instead of `neofetch` as it does not require any dependencies and is like ~100 times faster.
