### ISSUE TITLE
[Request]: aliyundrive-webdav

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/Main#4566]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

aliyundrive-webdav

### Description

WebDAV service by wrapping the interface of Aliyun Drive

### Homepage

https://github.com/messense/aliyundrive-webdav

### Download Link(s)

https://github.com/messense/aliyundrive-webdav/releases/download/v2.0.5/aliyundrive-webdav-v2.0.5.x86_64-pc-windows-msvc.zip

### Some Indication of Popularity/Repute

There are 7600+ stars on Github.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
