### ISSUE TITLE
[Request]: cloudflare-warp

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/Main#4573]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Cloudflare WARP

### Description

1.1.1.1 with WARP replaces the connection between your device and the Internet with a modern, optimized, protocol.

### Homepage

https://one.one.one.one/

### Download Link(s)

https://1111-releases.cloudflareclient.com/windows/Cloudflare_WARP_Release-x64.msi

### Some Indication of Popularity/Repute

Provided by a very large CDN integrated provider. Users may use the tool warp-cli.exe.

**Comment by rashil2000** [comment]
This looks like a GUI application? https://developers.cloudflare.com/warp-client/get-started/windows/

**Comment by StarsbySea** [comment]
This is a GUI program, but can be used via the CLI without the GUI.
![图片](https://user-images.githubusercontent.com/66008060/226156429-a0c1a167-783c-47f8-ab1c-615d20a2be93.png)
So what do you think?

**Comment by rashil2000** [comment]
The standard convention for GUI programs (with accompanying CLI) is the Extras bucket. I think it should go there.

**Comment by StarsbySea** [comment]
OK, let me add a new request issue for a manifest file to the Extras repository.
