### ISSUE TITLE
[Request]: code CLI

### ISSUE THREAD

**Issue by cglong** [ScoopInstaller/Main#4577]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

code-cli

### Description

VS Code command line interface

### Homepage

https://code.visualstudio.com/docs/editor/command-line

### Download Link(s)

https://code.visualstudio.com/#alt-downloads

### Some Indication of Popularity/Repute

OSS base has 144k stars [on GitHub](https://github.com/microsoft/vscode)

**Comment by amreus** [comment]
in the past, the `vscode` manifest did add a `code.shim` for the command line - is there a reason it no longer does?

**Comment by rashil2000** [comment]
https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b3775030ed1a69b13e4f4c628c612102e30a681/vscode_cli_win32_x64_cli.zip contains a single file "code.exe" - which I don't think can be used standalone. 

I think @amreus is right - the CLI provided by the vscode package should be sufficient.
