### ISSUE TITLE
`checkver` CI fails but works locally

### ISSUE THREAD

**Issue by mittsq** [ScoopInstaller/Main#4582]
I'm trying to add typst (as in PR #4581) but the checkver and autoupdate checks fail.  
Documentation says that it the version checkver finds must match the version being submitted.  
As of writing, this should be the case.  
Locally running checkver also confirms this, see output below.  

```powershell
.\bin\checkver.ps1 -Dir E:\Libraries\Documents\manifests -App typst
# typst: 22-03-21-2
```

**Comment by niheaven** [comment]
It 'cos typst hasn't `latest` release (a.k.a. only pre-release), and https://api.github.com/repos/typst/typst/releases/latest is not valid (which is used by CI to find version).

See my commit in #4581.
