### ISSUE TITLE
[Bug]: The volta package does not install the required `*.cmd` files

### ISSUE THREAD

**Issue by natesilva** [ScoopInstaller/Main#4585]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

volta

### Expected/Current Behaviour

The package for Volta does not install the `*.cmd` files such as `npm.cmd`. It only installs the `.exe` files.

[The AWS command-line utility requires `npm.cmd`](https://github.com/aws/aws-cli/blob/1b5cac163886abcb31d5b2d459c1089a89dd8b48/awscli/customizations/codeartifact/login.py#L296).

### Steps to Reproduce

```console
PS C:\Users\nate> scoop install volta
Installing 'volta' (1.1.1) [64bit] from main bucket
volta-1.1.1-windows.zip (5.8 MB) [============================================================================] 100%
Checking hash of volta-1.1.1-windows.zip ... ok.
Extracting volta-1.1.1-windows.zip ... done.
Running installer script...
Linking ~\scoop\apps\volta\current => ~\scoop\apps\volta\1.1.1
Persisting appdata
'volta' (1.1.1) was installed successfully!
Notes
-----
To use volta tab-completions, add following code to your PowerShell PROFILE:

(& volta completions powershell) | Out-String | Invoke-Expression
PS C:\Users\nate> npm.cmd
npm.cmd: The term 'npm.cmd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Possible Solution

To fix this, make Scoop install all the same files as [the MSI installer](https://docs.volta.sh/guide/getting-started):

![via-scoop](https://user-images.githubusercontent.com/160467/226996844-b2b4df02-6207-4fb7-9a67-25175886c446.png)
![installed-from-msi](https://user-images.githubusercontent.com/160467/226996859-16d4911c-9ca3-4f96-8024-10c931435a86.png)

### Scoop and Buckets Version

```console
PS C:\Users\nate> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15
PS C:\Users\nate> scoop bucket list

Name Source               Updated               Manifests
---- ------               -------               ---------
main ~\scoop\buckets\main 3/22/2023 10:16:49 AM      1179
```

### Scoop Config

```console
PS C:\Users\nate> scoop config

last_update
-----------
3/22/2023 10:33:52 AM
```

### PowerShell Version

```console
PS C:\Users\nate> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
Can you make a PR for the fix?
