### ISSUE TITLE
[Request]: whisper.cpp

### ISSUE THREAD

**Issue by leumasme** [ScoopInstaller/Main#4616]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

whisper-cpp (or whisper.cpp?)

### Description

High-performance inference of OpenAI's Whisper automatic speech recognition (ASR) model

### Homepage

https://github.com/ggerganov/whisper.cpp

### Download Link(s)

https://github.com/ggerganov/whisper.cpp/releases

### Some Indication of Popularity/Repute

13.8k stars, 1.1k forks

### Note

Model Weights can be separately downloaded here: https://huggingface.co/ggerganov/whisper.cpp
This should likely be mentioned in the package note, as they are required to actually use the application.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
