### ISSUE TITLE
[Request] Add memcached

### ISSUE THREAD

**Issue by star2000** [ScoopInstaller/Main#462]
https://github.com/memcached/memcached

**Comment by issaclin32** [comment]
Is there a pre-compiled source of `memcached`?

It is possible to compile it in `installer.script`, but that will be error-prone / hard to maintain. Also it will not be accepted in the official buckets.

**Comment by star2000** [comment]
> Is there a pre-compiled source of `memcached`?
> 
> It is possible to compile it in `installer.script`, but that will be error-prone / hard to maintain. Also it will not be accepted in the official buckets.

https://github.com/nono303/memcached
