### ISSUE TITLE
[Bug]: vcpkg fails to install package because vcpkg is not a git repo

### ISSUE THREAD

**Issue by MarkKoz** [ScoopInstaller/Main#4625]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

vcpkg

### Expected/Current Behaviour

vcpkg fails to install a package because it relies on its root directory being a git repository https://github.com/microsoft/vcpkg/issues/22582#issuecomment-1015043685. I expect vcpkg to be able to install the package.

```
-- Running vcpkg install
Error: while checking out port boost-program-options with git tree 306ab169b6f177e71d82cb08c77a8629337a1b6a
Error: Failed to tar port directory
error: tar failed with exit code: (128).
fatal: not a git repository: 'C:\Users\Mark\scoop\apps\vcpkg\current\.git'

-- Running vcpkg install - failed
CMake Error at C:/Users/Mark/scoop/apps/vcpkg/current/scripts/buildsystems/vcpkg.cmake:886 (message):
  vcpkg install failed.  See logs for more information:
  C:\Repositories\bethesda\Champollion\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Users/Mark/scoop/apps/cmake/3.26.2/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:16 (project)


-- Configuring incomplete, errors occurred!
```

### Steps to Reproduce

```console
scoop install git cmake vcpkg

git clone git@github.com:Orvid/Champollion.git
cd Champollion
cmake -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:\Users\Mark\scoop\apps\vcpkg\current\scripts\buildsystems\vcpkg.cmake
```

### Possible Solution

I did not look into why exactly vcpkg needs a git repo. However, the following did manage to get the build I needed to work:

```
cd C:\Users\Mark\scoop\apps\vcpkg\current\
git init
git remote add origin git@github.com:microsoft/vcpkg.git
git fetch origin
git symbolic-ref HEAD refs/heads/2023.02.24
```

That is probably hacky. If it's possible to specify in the manifest that scoop should use git to clone the repo instead of downloading a zip, that would be ideal.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'dorado' bucket:
65e1af7e (HEAD -> master, origin/master, origin/HEAD) zap: Update to version 0.7.7-beta

'extras' bucket:
61554af46 (HEAD -> master, origin/master, origin/HEAD) todolist: Update to version 8

'java' bucket:
b94e23bd (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-16-ea

'main' bucket:
f5fbf9b31 (HEAD -> master, origin/master, origin/HEAD) slang: Update to version 0.27.5

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.

'nonportable' bucket:
edd19da (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.6

'versions' bucket:
1c6be06a1 (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20230403
```

### Scoop Config

```console
last_update         aria2-enabled scoop_branch scoop_repo
-----------         ------------- ------------ ----------
2023-04-02 22:08:51         False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
vcpkg has been present in the bucket for a long time now, which means this used to work before. Did something change upstream?

**Comment by MarkKoz** [comment]
> vcpkg has been present in the bucket for a long time now, which means this used to work before. Did something change upstream?

It looks like vcpkg has a "versioning" feature, which is a relatively new addition (2021 release?), and when using a vcpkg.json that makes use of this versioning feature (i.e. has version constraints for package dependencies), then things break. It's unclear why specifying version constraints for packages requires vcpkg itself to be a git repo. My guess this is an implementation detail, and vcpkg assumes it's a git repo since its official installation instructions use `git clone` to download vcpkg.

Hoping someone more experienced with vcpkg can chime in on this.
