### ISSUE TITLE
[Bug] URL https://downloads.sourceforge.net/project/scons/scons-local/4.5.2/scons-local-4.5.2.zip is not valid

### ISSUE THREAD

**Issue by weixu-tf4** [ScoopInstaller/Main#4629]
## Bug Report
URL https://downloads.sourceforge.net/project/scons/scons-local/4.5.2/scons-local-4.5.2.zip is not valid
### System details

**Windows version:** [e.g. 7, 8, 10, 11]

**OS architecture:** [e.g. 32bit, 64bit, arm64]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop download scons
INFO  Downloading 'scons' [64bit] from main bucket
scons-local-4.5.2.zip (7.8 MB) [==========================================================================================] 100%
Checking hash of scons-local-4.5.2.zip ... ok.
'scons' (4.5.2) was downloaded successfully!
```
