### ISSUE TITLE
[Bug]: GlslViewer does not start due to wrong ffmpeg-shared version

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Main#4634]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

glslviewer

### Expected/Current Behaviour

GlslViewer does not start at all. No error message produced when running from command line. When opened directly from File Explorer, an error reporting that `avdevice-58.dll`, `avformat-58.dll`, `swscale-5.dll`, `avcodec-58.dll` were not found. In the folder are versions of these dll files with `-60` and `-7` instead.

### Steps to Reproduce

```console
❯ glslviewer --version

~
❯
```

### Possible Solution

If you manually download [FFmpeg 4.4](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n4.4-latest-win64-gpl-shared-4.4.zip) and paste the correct dlls, it works.

Would it be possible to change the ffmpeg-shared dependency to the correct version?

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a97718876 (HEAD -> master, origin/master, origin/HEAD) tailscale: Add note and scripts for adding to startup programs (#10330)

'java' bucket:
6064688e (HEAD -> master, origin/master, origin/HEAD) temurin17-nightly-jre: Update to version 17.0.7-5.0.202304050103

'main' bucket:
dcf2bb06e (HEAD -> master, origin/master, origin/HEAD) flaresolverr: Update to version 3.1.2

'nonportable' bucket:
8402b15 (HEAD -> master, origin/master, origin/HEAD) mullvadvpn-np: Update to version 2023.3

'versions' bucket:
818127c6a (HEAD -> master, origin/master, origin/HEAD) vscode-insiders@1.78.0-insider: Fix hash (Closes #1138)
```

### Scoop Config

```console
alias                           : @{reinstall=scoop-reinstall; purge=scoop-purge}
debug                           : False
use_lessmsi                     : True
last_update                     : 05/04/2023 22:08:45
scoop_repo                      : https://github.com/ScoopInstaller/Scoop
scoop_branch                    : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
> Would it be possible to change the ffmpeg-shared dependency to the correct version?

I don't think so. 

Has this issue been reported upstream? It seems they have locked the dependency to a very old ffmpeg 4.4.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/discussions/11098

**Comment by tech189** [comment]
>Has this issue been reported upstream? It seems they have locked the dependency to a very old ffmpeg 4.4.

It hasn't been reported yet but the developers don't seem to be active in the issues at the moment.

> https://github.com/ScoopInstaller/Extras/discussions/11098

Installing `ffmpeg-shared@4.4` doesn't work as that build isn't hosted on the site - but there is a version 4.4 available on their GitHub releases mirror, https://github.com/GyanD/codexffmpeg/releases/tag/4.4. Shall I make a manifest for that one in Versions?

**Comment by HUMORCE** [comment]
Of course, otherwise the GlslViewer installed via Scoop will not work properly.
