### ISSUE TITLE
[Bug]: mvndaemon.json is currently broken

### ISSUE THREAD

**Issue by TheRealChrisS** [ScoopInstaller/Main#4636]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mvndaemon

### Expected/Current Behaviour

`scoop install mvndaemon` should install mvndaemon but it currently fails, because version 0.9.0 is no longer available on https://dist.apache.org/repos/dist/release/maven/mvnd/

There is a new version 1.0-m6 but also the auto update doesn't work because the actual files have a different pattern including a term like m39 or m40:
[maven-mvnd-1.0-m6-m40-windows-amd64.tar.gz](https://dist.apache.org/repos/dist/release/maven/mvnd/1.0-m6/maven-mvnd-1.0-m6-**m40**-windows-amd64.tar.gz)
[maven-mvnd-1.0-m6-m39-windows-amd64.tar.gz](https://dist.apache.org/repos/dist/release/maven/mvnd/1.0-m6/maven-mvnd-1.0-m6-**m39**-windows-amd64.tar.gz)

### Steps to Reproduce

```console
`scoop install mvndaemon`

Result: URL https://dist.apache.org/repos/dist/release/maven/mvnd/0.9.0/maven-mvnd-0.9.0-windows-amd64.zip is not valid

`scoop install mvndaemon@1.0-m6`

Result:
URL https://dist.apache.org/repos/dist/release/maven/mvnd/1.0-m6/maven-mvnd-1.0-m6-windows-amd64.zip.sha256 is not valid
Could not find hash in https://dist.apache.org/repos/dist/release/maven/mvnd/1.0-m6/maven-mvnd-1.0-m6-windows-amd64.zip.sha256
URL https://dist.apache.org/repos/dist/release/maven/mvnd/1.0-m6/maven-mvnd-1.0-m6-windows-amd64.zip is not valid
Could not install mvndaemon@1.0-m6
```

### Possible Solution

mvndaemon.json has to be updated to 1.0-m6 using the right filename.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
3490fed2d (HEAD -> master, origin/master, origin/HEAD) todolist: Update to version 8

'java' bucket:
6064688e (HEAD -> master, origin/master, origin/HEAD) temurin17-nightly-jre: Update to version 17.0.7-5.0.202304050103

'main' bucket:
73e2ab36d (HEAD -> master, origin/master, origin/HEAD) influx@2.7.1: Remove extract_dir
```

### Scoop Config

```console
last_update                       proxy         scoop_branch scoop_repo
-----------                       -----         ------------ ----------
2023-04-06T08:20:08.4442759+02:00 de-proxy:8080 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by janxb** [comment]
Another alternative would be switching the package source from `dist.apache.org` to the releases hosted directly at `github.com` (https://github.com/apache/maven-mvnd/releases)

**Comment by tech189** [comment]
I've pushed a fix, should stay up to date now. According to https://github.com/apache/maven-mvnd/issues/831#issuecomment-1494197168:
> `m40` is for "with an alpha version of Maven 4.0", `m39` is for "with a stable version of Maven 3.9.x"

So I have selected the stable version for the Scoop package.
