### ISSUE TITLE
[Request]: juicefs

### ISSUE THREAD

**Issue by yuhr123** [ScoopInstaller/Main#4639]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

juicefs

### Description

JuiceFS is a distributed POSIX file system built on top of Redis and S3.

### Homepage

https://github.com/juicedata/juicefs

### Download Link(s)

https://github.com/juicedata/juicefs/releases/download/v1.0.4/juicefs-1.0.4-windows-amd64.tar.gz

### Some Indication of Popularity/Repute

JuiceFS has 7.8k Github stars and 681 forks.

**Comment by yuhr123** [comment]
I have done the [juicefs.json](https://github.com/yuhr123/scoop-main/blob/juicefs/bucket/juicefs.json) and tested on my local pc.

Waiting for your confirmation, I can submit a PR at any time.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
