### ISSUE TITLE
[Bug]: `clipboard` package outputs "Can't shim 'clipboard.exe': File doesn't exist." error message for version `0.6.0`

### ISSUE THREAD

**Issue by Elkiwa** [ScoopInstaller/Main#4643]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

clipboard

### Expected/Current Behaviour

# Current: scoop can't find the clipboard.exe
```
Creating shim for 'clipboard'.
Can't shim 'clipboard.exe': File doesn't exist.
```
# Expected: 
```
Creating shim for 'clipboard'.
Creating shim for 'cb'.
'clipboard' (0.6.0) was installed successfully!
```

### Steps to Reproduce

```console
PS> scoop install clipboard
Installing 'clipboard' (0.6.0) [64bit] from main bucket
Loading clipboard-windows-amd64.zip from cache.
Checking hash of clipboard-windows-amd64.zip ... ok.
Extracting clipboard-windows-amd64.zip ... done.
Linking ~\scoop\apps\clipboard\current => ~\scoop\apps\clipboard\0.6.0
Creating shim for 'clipboard'.
Can't shim 'clipboard.exe': File doesn't exist.
PS>
```

### Possible Solution

Change the field of "extract_dir" of the manifest `https://github.com/ScoopInstaller/Main/blob/master/bucket/clipboard.json` 
from "bin" to "Release\bin"

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9cbde271d (HEAD -> master, origin/master, origin/HEAD) mpv-git: Update to version 20230409

'java' bucket:
f27532e3 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.372-6.0.202304071827

'jbangdev' bucket:
ffb7df7 (HEAD -> main, tag: v0.106.1, origin/main, origin/HEAD) jbang v0.106.1

'main' bucket:
04d2fa81d (HEAD -> master, origin/master, origin/HEAD) wgcf: Update to version 2.2.16
```

### Scoop Config

```console
PS> scoop config

aria2-warning-enabled last_update          scoop_repo                              scoop_branch
--------------------- -----------          ----------                              ------------
                False 4/9/2023 10:17:13 AM https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Elkiwa** [comment]
I noticed the package author @Slackadays contributed to the `main` bucket directly in the past. Is it fine for me to ask of you for some comments? I'm not really using the package in the mean time though.

**Comment by Slackadays** [comment]
@Elkiwa This happened because of the latest 0.6.0 release removing `clipboard.exe` in place of `cb.exe`. Unfortunately, I didn't see that Scoop wouldn't work with the new setup, but this should be super quick fix.

**Comment by Slackadays** [comment]
@Elkiwa Done, fixed the CMakeLists to not put Windows builds in the Release folder

However, it may not work next release because of a deprecation of `clipboard.exe`, but that's actually a completely unrelated issue.
