### ISSUE TITLE
[Request]: SyncthingWindowsSetup

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Main#4660]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

SyncthingWindowsSetup

### Description

Syncthing Windows Setup is a lightweight yet full-featured Windows installer for the open-source Syncthing file-synchronization application.

### Homepage

https://github.com/Bill-Stewart/SyncthingWindowsSetup

### Download Link(s)

https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/download/v1.23.3/syncthing-1.23.3-setup.exe

### Some Indication of Popularity/Repute

https://github.com/Bill-Stewart/SyncthingWindowsSetup

**Comment by rashil2000** [comment]
This is an installer?

**Comment by soredake** [comment]
@rashil2000 yes

**Comment by rashil2000** [comment]
Why not add a package for Syncthing itself? A package for its installer makes little sense.
