### ISSUE TITLE
openssl@1.1.1L: hash check failed

### ISSUE THREAD

**Issue by fengshuo2004** [ScoopInstaller/Main#4667]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

openssl@1.1.1L

**Comment by fengshuo2004** [comment]
For my specific purpose which is [setting up a Postman proxy](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-https-traffic/), I need OpenSSL version 1.x and not 3.x

`1.1.1L` is the last 1.x version in this bucket, but the hashes at https://github.com/slproweb/opensslhashes only contains `1.1.1t` and `3.0.8`.

**Comment by rashil2000** [comment]
Install `openssl1` from the Versions bucket. See https://github.com/ScoopInstaller/Versions/blob/master/bucket/openssl1.json
