### ISSUE TITLE
None of the GNU utilities in coreutils.json are actually included in coreutils

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Main#467]
The [coreutils.json description](https://github.com/ScoopInstaller/Main/blob/master/bucket/coreutils.json) says:

> "description": "A collection of GNU utilities such as bash, make, gawk and grep",

None of these utilities are actually included and available in the package.

**Comment by pedrogarcia** [comment]
How can I check the integrity of installed packages? I noticed some packages where missing shims, but `scoop status` and `scoop checkup` say everything is ok.
