### ISSUE TITLE
nodejs@12.11.1: decompress error

### ISSUE THREAD

**Issue by cruzpaulajoanna** [ScoopInstaller/Main#469]
Extracting node-v12.11.1-win-x64.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\tcbpacru\scoop\apps\scoop\current\lib\decompress.ps1:81 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\tcbpacru\scoop\apps\nodejs\12.11.1\node-v12.11.1-win-x64.7z.

**Comment by linsui** [comment]
Please install 7zip and try again
```
scoop install 7zip
```
