### ISSUE TITLE
mysql-workbench@8.0.33: decompress error

### ISSUE THREAD

**Issue by azmankudus** [ScoopInstaller/Main#4712]
Updating 'mysql-workbench' (8.0.32 -> 8.0.33)
Downloading new version
Loading mysql-workbench-community-8.0.33-winx64.msi from cache
Checking hash of mysql-workbench-community-8.0.33-winx64.msi ... ok.
Uninstalling 'mysql-workbench' (8.0.32)
Installing 'mysql-workbench' (8.0.33) [64bit] from main bucket
Loading mysql-workbench-community-8.0.33-winx64.msi from cache
Extracting mysql-workbench-community-8.0.33-winx64.msi ... ERROR Exit code was 1603!
Failed to extract files from E:\Users\6r6m1\scoop\apps\mysql-workbench\8.0.33\mysql-workbench-community-8.0.33-winx64.msi.
Log file:
  ~\scoop\apps\mysql-workbench\8.0.33\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=mysql-workbench%408.0.33%3a+decompress+error

**Comment by HUMORCE** [comment]
<html>
<body>


ERROR_INSTALL_FAILURE | 1603 | A fatal error occurred during installation.
-- | -- | --



</body>
</html>

Cannot reproduce. try toggle this config item or reboot pc before install the app:

`scoop config use_lessmsi true|false`

```
❯ scoop install mysql-workbench
Installing 'mysql-workbench' (8.0.33) [64bit] from main bucket
mysql-workbench-community-8.0.33-winx64.msi (45.5 MB) [===================================================================] 100%
Checking hash of mysql-workbench-community-8.0.33-winx64.msi ... ok.
Extracting mysql-workbench-community-8.0.33-winx64.msi ... done.
Linking ~\scoop\apps\mysql-workbench\current => ~\scoop\apps\mysql-workbench\8.0.33
Creating shim for 'MySQLWorkbench'.
Creating shim for 'mysql'.
Creating shim for 'mysqldump'.
Creating shortcut for MySQLWorkbench (MySQLWorkbench.exe)
'mysql-workbench' (8.0.33) was installed successfully!
```
