### ISSUE TITLE
[Bug]: Python versioning (registry)

### ISSUE THREAD

**Issue by luxzg** [ScoopInstaller/Main#4718]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

python

### Expected/Current Behaviour

I've accidentally noticed that some entries in registry do not update on python update.

For example:
```
\Software\Python\PythonCore\3.11\PythonPath
```
has default value
```
C:\Users\<myuser>\scoop\apps\python\3.11.0\Lib\;C:\Users\<myuser>\scoop\apps\python\3.11.0\DLLs\
```
IMHO it should be:
```
scoop\apps\python\current
```
Because now I'm at `scoop\apps\python\3.11.3` and folder `3.11.0` no longer exists

Edit: this happens in other multiple regitry keys in this path:
```
Computer\HKEY_USERS\S-1-5-21-<UUID>\Software\Python\PythonCore\3.11
   \PythonCore\3.11\Help\Main Python Documentation
   \PythonCore\3.11\InstallPath
   \PythonCore\3.11\PythonPath
```

### Steps to Reproduce

```console
Not completely sure, but I guess:
scoop install python
(wait for new version)
scoop update
```

### Possible Solution

I believe paths should be using `current`, or otherwise get updated when `scoop update` installs newer version

Edit: I have found this file (after posting this as a bug)
``` C:\scoop\apps\python\current\install-pep-514.reg ```
I can see it updated the reg file itself with new versions eg. 
```
[HKEY_CURRENT_USER\Software\Python\PythonCore\3.11\InstallPath]
@="C:\\scoop\\apps\\python\\3.11.3"
```
But it did not apply on update (?) or should I have ran the .reg every time after update? Now I'm unsure if it's bug or my own mistake. For now I've added the reg import into my updating script, so it runs after scoop updates all apps. Could still someone check this so I know if it's bug or my own "bug" in way of thinking how it works.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
d195c12b2 (HEAD -> master, origin/master, origin/HEAD) dbeaver@23.0.3: Fix hash (Closes #11126)

'java' bucket:
aadb1b61 (HEAD -> master, origin/master, origin/HEAD) zulufx8-jre: Update to version 8.70.0.23

'main' bucket:
cb9da8bd5 (HEAD -> master, origin/master, origin/HEAD) snapraid: Update to version 12.1

'php' bucket:
8514185 (HEAD -> master, origin/master, origin/HEAD) php8.1: Update to version 8.1.18
```

### Scoop Config

```console
last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
24.4.2023. 10:14:03 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
>  should I have ran the .reg every time after update?

Yes, because Scoop does not modify the registry on its own.
