### ISSUE TITLE
[Request]: IntelliJ HTTP Client (`ijhttp`)

### ISSUE THREAD

**Issue by nagromc** [ScoopInstaller/Main#4721]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

ijhttp

### Description

It allows you to run HTTP requests from a terminal, without the IDE, or include HTTP request testing in your CI workflow.

### Homepage

https://www.jetbrains.com/help/idea/http-client-cli.html

### Download Link(s)

https://jb.gg/ijhttp/2023.1

### Some Indication of Popularity/Repute

- Comes from JetBrains, one of the most known software company and open-source contributor (IntelliJ IDEA Community, Kotlin, etc.) 
- Recent presentation on YouTube: https://www.youtube.com/watch?v=mwiHAukbWjM

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
