### ISSUE TITLE
λ scoop update gpg

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Main#4741]
λ scoop update gpg
gpg: 2.4.0 -> 2.4.1
Updating one outdated app:
Updating 'gpg' (2.4.0 -> 2.4.1)
Downloading new version
OperationStopped: C:\Users\<user>\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.

_Originally posted by @AntonOks in https://github.com/ScoopInstaller/Main/issues/4740#issuecomment-1527637880_

**Comment by rashil2000** [comment]
The URL https://www.gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.4.1_20230428.exe is accessible for me, both via Scoop and the web browser:

![image](https://user-images.githubusercontent.com/46838874/235295636-931d70b6-455f-4d8e-b4a7-22d48b02ccf1.png)
