### ISSUE TITLE
tesseract-languages@4.1.0: decompress error

### ISSUE THREAD

**Issue by Roseleaves** [ScoopInstaller/Main#4743]
Extracting 4.1.0.zip ... ERROR Exit code was 2!
Failed to extract files from D:\Scoop\apps\tesseract-languages\4.1.0\4.1.0.zip.
Log file:
  D:\Scoop\apps\tesseract-languages\4.1.0\7zip.log

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 351046435 bytes (335 MiB)

Extracting archive: D:\Scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
--
Path = D:\Scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
Type = zip
Physical Size = 351046435
Comment = 65727574dfcd264acbb0c3e07860e4e9e9b22185

Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
ERROR: Cannot create symbolic link :  ͻ   û         Ȩ   : D:\Scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\configs
ERROR: Cannot create symbolic link :  ͻ   û         Ȩ   : D:\Scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\pdf.ttf

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+tesseract-languages+is%3Aclosed
