### ISSUE TITLE
[Request]: Haskell Toolchain Setup program: GHCup.

### ISSUE THREAD

**Issue by langshangyuan** [ScoopInstaller/Main#4749]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

GHCup

### Description

GHCup is the officially recommended way to install the Haskell toolchains including latest GHC, cabal, stack and haskell language server

### Homepage

https://www.haskell.org/ghcup/

### Download Link(s)

https://downloads.haskell.org/~ghcup/${version}/x86_64-mingw64-ghcup-0.1.18.0.ex

### Some Indication of Popularity/Repute

GHCup is the main installer for the general purpose language [Haskell](https://www.haskell.org/).

GHCup makes it easy to install specific versions of GHC on GNU/Linux, macOS (aka Darwin), FreeBSD and Windows and can also bootstrap a fresh [Haskell developer environment](https://www.haskell.org/ghcup/install/#supported-tools) from scratch. It follows the UNIX philosophy of [do one thing and do it well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). Similar in scope to [rustup](https://github.com/rust-lang-nursery/rustup.rs), [pyenv](https://github.com/pyenv/pyenv) and [jenv](http://www.jenv.be/).

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
