### ISSUE TITLE
7zip@22.01: decompress error

### ISSUE THREAD

**Issue by sarvex** [ScoopInstaller/Main#4786]
Failed to extract files from C:\Scoop\apps\7zip\22.01\7z2201-x64.msi.
Log file:
  C:\Scoop\apps\7zip\22.01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4022.01%3a+decompress+error

The contents of the msi.log file are nill

**Comment by HUMORCE** [comment]
Cannot reproduce. try toggle this config item or reboot pc before install the app:

`scoop config use_lessmsi true|false` (default: false)

**Comment by sarvex** [comment]
`scoop config use_lessmsi true` installs the lessmsi and 7zip.
