### ISSUE TITLE
[Request]: Rome tools

### ISSUE THREAD

**Issue by thesobercoder** [ScoopInstaller/Main#4787]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Rome

### Description

Rome is a formatter, linter, bundler, and more for JavaScript, TypeScript, JSON, HTML, Markdown, and CSS.

### Homepage

https://rome.tools/

### Download Link(s)

https://github.com/rome/tools/releases/download/cli%2Fv12.0.0/rome-win32-x64.exe

### Some Indication of Popularity/Repute

[Repo](https://github.com/rome/tools)
GitHub stars: 23K
Written in Rust and distributed as a single executable binary.

**Comment by rashil2000** [comment]
Closing in favour of #5061
