### ISSUE TITLE
imagemagick@7.1.1-10: decompress error

### ISSUE THREAD

**Issue by indiscible** [ScoopInstaller/Main#4828]
scoop install imagemagick
Installing 'imagemagick' (7.1.1-10) [64bit] from main bucket
Loading ImageMagick-7.1.1-10-Q16-HDRI-x64-dll.exe from cache
Checking hash of ImageMagick-7.1.1-10-Q16-HDRI-x64-dll.exe ... ok.
Extracting ImageMagick-7.1.1-10-Q16-HDRI-x64-dll.exe ... ERROR Exit code was 1!
Failed to extract files from scoop\apps\imagemagick\7.1.1-10\ImageMagick-7.1.1-10-Q16-HDRI-x64-dll.exe.
Log file:
  ~\scoop\apps\imagemagick\7.1.1-10\innounp.log

[innounp.log](https://github.com/ScoopInstaller/Main/files/11536445/innounp.log)

**Comment by HUMORCE** [comment]
`scoop list inno`

**Comment by HUMORCE** [comment]
Temporarily closed.

**Reasons:**
- Cannot reproduce.
- No response and additional information

Feel free to reopen this issue, if the problem still occurs.
