### ISSUE TITLE
git-town@9.0.0: Download via aria2 failed

### ISSUE THREAD

**Issue by jshifrin25** [ScoopInstaller/Main#4835]
Download failed! 

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/git-town/git-town/releases/download/untagged-c5121e4d876a7f56b01f/git-town_9.0.0_windows_intel_64.zip
    referer=https://github.com/git-town/git-town/releases/download/untagged-c5121e4d876a7f56b01f/
    dir=C:\Users\221027930\scoop\cache
    out=git-town#9.0.0#https_github.com_git-town_git-town_releases_download_untagged-c5121e4d876a7f56b01f_git-town_9.0.0_windows_intel_64.zip

ERROR & 'C:\Users\221027930\scoop\apps\aria2\1.36.0-1\aria2c.exe' --input-file='C:\Users\221027930\scoop\cache\git-town.txt' --user-agent='Shovel/1.0 (+https://shovel.ash258.com) PowerShell/7.3 (Windows NT 10.0.19045.0; Win64; x64;)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=63340 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=git-town%409.0.0%3a+Download+via+aria2+failed&body=Download+failed!+(Error+3)+Resource+was+not+found
ERROR This application failed to update: git-town

**Comment by JP-Ellis** [comment]
I am able to replicate this issue:

```text
❯ scoop install git-town
Installing 'git-town' (9.0.0) [64bit] from main bucket
The remote server returned an error: (404) Not Found.
URL https://github.com/git-town/git-town/releases/download/untagged-c5121e4d876a7f56b01f/git-town_9.0.0_windows_intel_64.zip is not valid
```
