### ISSUE TITLE
winpython@3.10.11.1: decompress error

### ISSUE THREAD

**Issue by yuguuk** [ScoopInstaller/Main#4850]
[7zip.log](https://github.com/ScoopInstaller/Main/files/11598632/7zip.log)

**Comment by HUMORCE** [comment]
Wrong files released upstream?

![screenshot_230530_221343](https://github.com/ScoopInstaller/Main/assets/4353480/105fc732-ad8b-47ee-bfdb-d3a3d28a4abb)

**Comment by HUMORCE** [comment]
![screenshot_230601_234654](https://github.com/ScoopInstaller/Main/assets/4353480/af6a851c-2b81-438b-9a5a-1f14cffe6952)

[Manifest updated to 3.11.3.1](https://github.com/ScoopInstaller/Main/commit/8618f96d3e09756200cdb49a84943fdff71db70b), and version 3.10.11.1 has been fixed.
