### ISSUE TITLE
7zip@22.01: decompress error

### ISSUE THREAD

**Issue by jslaroch** [ScoopInstaller/Main#4859]
7zip does not install and I have the following error message:

Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (29.4 KB) [====================================================================================] 100%
Extracting 7z2201-x64.msi ... ERROR Exit code was 1620!
Failed to extract files from D:\Apps\scoop\apps\7zip\22.01\7z2201-x64.msi.
Log file:
  D:\Apps\scoop\apps\7zip\22.01\msi.log

**Comment by HUMORCE** [comment]
Cannot reproduce. try toggle this config item or reboot pc before install the app:

`scoop config use_lessmsi true|false` (default: false)

Check the error code on this page: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
