### ISSUE TITLE
Request For Modification in Maven Package

### ISSUE THREAD

**Issue by SinaMobasheri** [ScoopInstaller/Main#4863]
currently, maven package's manifest adds the whole maven binary path to the os path, but it seems unnecessary, it's a cleaner approach to create a link for maven's binary like gradle package's manifest, removing `"env_add_path": "bin",` from maven package's manifest and replace it with `"bin": "bin\\mvn.cmd",`

**Comment by HUMORCE** [comment]
The package provides sh scripts also.
