### ISSUE TITLE
[Request]: Improve Multipass with  service/daemon install

### ISSUE THREAD

**Issue by gianluca-sabena** [ScoopInstaller/Main#4870]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Multipass

### Description

Ubuntu VMs on demand

### Homepage

https://multipass.run/

### Download Link(s)

https://multipass.run/

### Some Indication of Popularity/Repute

I know multipass is available in scoop, but scoop doesn't install multipassd service on windows.
Multipassd is required for multipass to work. Have to start multipassd from console with list of parameters is not practical.
I suggest to add support for multipass windows service install to reproduce same behaviors of official package download.

**Comment by HUMORCE** [comment]
Execute `sudo multipassd /install|uninstall` to install/uninstall multipass service.

Running multipassd from console does not require admin right, instead, creating service does.

**Comment by rashil2000** [comment]
Scoop does not install/uninstall services by design. See https://github.com/ScoopInstaller/Scoop/issues?q=is%3Aissue+is%3Aopen+services
