### ISSUE TITLE
[Request]: Dooit

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Main#4889]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Dooit

### Description

A TUI todo manager

### Homepage

https://github.com/kraanzu/dooit

### Download Link(s)

https://github.com/kraanzu/dooit/archive/refs/tags/v1.0.1.zip

### Some Indication of Popularity/Repute

GitHub stars: 1.6k

**Comment by rashil2000** [comment]
The developer does not provide precompiled packages. 

Use `pip` to install it.
