### ISSUE TITLE
[Bug]: Error: The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by momomobinx** [ScoopInstaller/Main#4895]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

CMake mingw

### Expected/Current Behaviour

scoop install cmake

Installing 'cmake' (3.26.4) [64bit]
根据验证过程，远程证书无效。
URL https://hub.fastgit.org/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.zip is not valid

### Steps to Reproduce

```console
scoop install cmake

Installing 'cmake' (3.26.4) [64bit]
根据验证过程，远程证书无效。
URL https://hub.fastgit.org/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.zip is not valid
```

### Possible Solution

i dont know

### Scoop and Buckets Version

```console
Current Scoop version:
7dd7b0ba (HEAD -> master, origin/master, origin/HEAD) merge upstream

'dorado' bucket:
b913aea1 (HEAD -> master, origin/master, origin/HEAD) tianyi-ecloud: Update to version 6.5.8

'extras' bucket:
fc44de32f (HEAD -> master, origin/master, origin/HEAD) okular: Update to version 23.04.2-1420

'java' bucket:
17fba9cf (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.382-3.0.202306161810

'main' bucket:
fc95c0efa (HEAD -> master, origin/master, origin/HEAD) edgedriver: Update to version 114.0.1823.51

'versions' bucket:
db72e5842 (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20230617
```

### Scoop Config

```console
{
    "last_update":  "2023-06-02T09:07:52.7889700+08:00",
    "proxy":  "127.0.0.1:7890",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop",
    "lastupdate":  "2023-06-17T16:04:18.4278080+08:00"
}
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
You are installing `cmake` from another bucket, and the manifest point the download url to a github mirror.

When I open `https://hub.fastgit.org/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.zip` in browser, it just shows a network error with no HTTP status code.

When I open `http://hub.fastgit.org/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.zip` in browser, 403 with output:
```
{"message":"API rate limit exceeded for 104.28.215.70. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

Please report the issue to the repo that the manifest actually located instead of main bucket.
