### ISSUE TITLE
[Bug]: nodejs-lts is not updated to `18.16.1` and lacks arm64 package support

### ISSUE THREAD

**Issue by Elkiwa** [ScoopInstaller/Main#4898]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

nodejs-lts

### Expected/Current Behaviour

1. The latest version should be `18.16.1` but the bucket manifest stays on version `18.16.0` instead.
2. There is no arm64 package support for now. (Found this through source code)

### Steps to Reproduce

```console
PS C:\Users\xxx> scoop info nodejs-lts

Name        : nodejs-lts
Description : As an asynchronous event driven JavaScript runtime, Node is designed to build scalable network applications. (Long Term Support)
Version     : 18.16.0
Bucket      : main
Website     : https://nodejs.org
License     : MIT
Updated at  : 4/13/2023 1:29:33 PM
Updated by  : github-actions[bot]
Installed   : 18.16.0
Path Added  : <root>\bin
              <root>
```

### Possible Solution

1. I'm not experienced in `scoop`'s github action flow.
2. The [nodejs](https://github.com/ScoopInstaller/Main/blob/master/bucket/nodejs.json) package manifest provides `arm64` package support, and `nodejs-lts` should provide it as well.

### Scoop and Buckets Version

```console
PS C:\Users\xxx> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
bbbafba15 (HEAD -> master, origin/master, origin/HEAD) spicetify-themes: Update to version 2023-06-21T00.17.59

'java' bucket:
54659199 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.20-6.0.202306201812

'jbangdev' bucket:
f9fa6b1 (HEAD -> main, tag: v0.108.0, origin/main, origin/HEAD) jbang v0.108.0

'main' bucket:
916bb17be (HEAD -> master, origin/master, origin/HEAD) vcpkg: Update to version 2023.06.20
```

### Scoop Config

```console
PS C:\Users\kiwap> scoop config

aria2-warning-enabled last_update           scoop_branch scoop_repo
--------------------- -----------           ------------ ----------
                False 6/21/2023 10:43:31 AM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\kiwap> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
> The latest version should be 18.16.1 but the bucket manifest stays on version 18.16.0 instead.

```
❯ (Invoke-WebRequest https://nodejs.org/en/download).Content -match 'LTS'
False
```
Checkver Updated: https://github.com/ScoopInstaller/Main/commit/21a616f87a97696a37389ed769153293fc080f88

> There is no arm64 package support for now. (Found this through source code)

Upstream does not provides arm64 package for 18.x.
