### ISSUE TITLE
[Bug]: failed to uninstall cygwin

### ISSUE THREAD

**Issue by felixmaker** [ScoopInstaller/Main#4899]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

cygwin

### Expected/Current Behaviour

I try to uninstall cygwin, but failed. It's not in use by other program.
As I research, the "persist" directories is not in manifest file.
So the uninstaller failed to unlink the junction ("packages", "root"), thus failed to remove 2.926.

### Steps to Reproduce

```console
PS C:\Users\Felixmaker> scoop uninstall cygwin
ERROR 'cygwin' isn't installed correctly.
Uninstalling 'cygwin' (2.926).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Cygwin.lnk
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Cygwin Terminal.lnk
ERROR Couldn't remove '~\scoop\apps\cygwin\2.926'; it may be in use.
```

### Possible Solution

By adding such field in its manifest file:

```
"persist": [
    "packages",
    "root"
],
```

Then, uninstall process just work. 
I do not know what will happen if this block is  put in bucket.

### Scoop and Buckets Version

```console
PS C:\Users\Felixmaker> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'scoop-cn' bucket:
090ec9609 (HEAD -> master, origin/master, origin/HEAD) Updated on 2023-06-20 01:37 +00:00

Note: the cygwin manifest file in scoop-cn bucket is the same as in main bucket!
```

### Scoop Config

```console
PS C:\Users\Felixmaker> scoop config


last_update   : 2023-06-20T18:43:33.2856863+08:00
aria2-enabled : True
aria2-split   : 5
scoop_branch  : master
scoop_repo    : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\Felixmaker> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Main/commit/24f08304004fa607d54b939199d175730bc62c95 https://github.com/ScoopInstaller/Main/commit/e7ef788c23252506d7fc89221dc9761c23d15f6f
