### ISSUE TITLE
python@3.11.4: decompress error

### ISSUE THREAD

**Issue by coderprem** [ScoopInstaller/Main#4915]
<img width="950" alt="image" src="https://github.com/ScoopInstaller/Main/assets/106749140/4c84067c-5457-491a-9afc-e24a291335a3">

**Comment by HUMORCE** [comment]
Make sure `dark` is installed correctly.

**Comment by coderprem** [comment]
ok, should I run the last command, Allow applications and third-party installers to find python by running:

![image](https://github.com/ScoopInstaller/Main/assets/106749140/3db7bafb-5dc8-4f63-a8ce-b66c5477fccd)

**Comment by HUMORCE** [comment]
it is an option

**Comment by coderprem** [comment]
ok thank you
