### ISSUE TITLE
deno@1.34.3: decompress error

### ISSUE THREAD

**Issue by Chrisdbeloved1** [ScoopInstaller/Main#4919]
Pls help look into this error I am having when trying to use scoop to install Typescript 

========
Extracting deno-x86_64-pc-windows-msvc.zip ... ERROR Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform."
Failed to extract files from C:\Users\young\scoop\apps\deno\1.34.3\deno-x86_64-pc-windows-msvc.zip.
Log file:
  ~\scoop\apps\deno\1.34.3\7zip.log

**Comment by HUMORCE** [comment]
Which archtecture of `7zip` installed?

**Comment by HUMORCE** [comment]
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information
