### ISSUE TITLE
[Request]: rustfmt

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Main#4934]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

rustfmt

### Description

A tool for formatting Rust code according to style guidelines.

### Homepage

https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

### Download Link(s)

https://github.com/rust-lang/rustfmt/releases/tag/v1.6.0

### Some Indication of Popularity/Repute

5.2K stars, this is the most used formatting tool for Rust.

**Comment by rashil2000** [comment]
> I'm not sure of this statement but I feel like other packaged rust "distributions" already include rustfmt and clippy.

Yes, they do. 

But we can still have the tool as a standalone package. Can you raise a PR for it?

**Comment by rashil2000** [comment]
> 1. The name of the directory inside the archive depends on the version of rustfmt. So from github I can get rustfmt_windows-x86_64-msvc_v1.6.0.zip which contains rustfmt_windows-x86_64-msvc_v$1.6.0 which in turn contains the rustfmt binary and I'm not sure how to cd into that directory inside the scoop json schema.

There's a field called `extract_dir` in the JSON schema, you can use that to cd inside. See https://github.com/ScoopInstaller/Main/blob/master/bucket/z3.json for example.

> 2. The rustfmt github repository only offers downloads for x86_64.

That's fine, we can include only that.
