### ISSUE TITLE
[Bug]: Windows Defender accuses `pack.exe` of being malware

### ISSUE THREAD

**Issue by otavio-silva** [ScoopInstaller/Main#4943]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

go

### Expected/Current Behaviour

Installation should occur normally and Windows Defender should not accuse any files of being malware.
Currently, the file `~\scoop\apps\go\1.20.6\go\pkg\tool\windows_amd64\pack.exe` is accused of being `Trojan:Win32/Wacatac.B!ml`.

### Steps to Reproduce

```console
scoop update go
```

### Possible Solution

Maybe it's a false positive?

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
e747ae079 (HEAD -> master) windowsdesktop-runtime: Update to version 7.0.9

'games' bucket:
c3e0e5ad (HEAD -> master, origin/master, origin/HEAD) vita3k: Update to version 3270-91d43d1

'java' bucket:
0719b8a4 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.382-4.0.202307101828

'main' bucket:
c10e4c876 (HEAD -> master, origin/master, origin/HEAD) teleport: Update to version 13.2.0

'nerd-fonts' bucket:
176a44f (HEAD -> master, origin/master, origin/HEAD) LXGWNeoXiHei: Update to version 1.102.1

'nonportable' bucket:
64554d3 (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.54

'versions' bucket:
8138167a2 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.11.0-dev.3970
```

### Scoop Config

```console
global_path last_update         scoop_repo                              scoop_branch
----------- -----------         ----------                              ------------
C:\Scoop    11/07/2023 18:35:12 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
> Installation should occur normally and Windows Defender should not accuse any files of being malware.

Basically, all download url of manifests is provided by their developers or distributors. Scoop does not scan any packages or guarantee their security, even thier are pass the virus scan or what. it is up to you to decide whether to keep or use them.

You can even distribute viruses through create a public bucket. 😒

> Maybe it's a false positive?

Yes, It's a common issue, see: https://go.dev/doc/faq#virus
