### ISSUE TITLE
dotnet-sdk and Visual Studio 2019

### ISSUE THREAD

**Issue by netxph** [ScoopInstaller/Main#495]
I'd like the dotnet-sdk maintained and installed through scoop, however, it doesn't work with Visual Studio 2019. Did you found a step to make that work?

**Comment by myty** [comment]
I believe #253 would have fixed that.  The PR was ancient and the branch all out of sync, so I created a new PR #720

**Comment by KWeaver87** [comment]
I'd like to see #720 merged as well. I use Scoop and dotnet-sdk at work (no admin install permissions) with VS Code. Without `env_add_path` set, the VS Code C# extension (OmniSharp) constantly complains about the SDK missing, and many of the debugging features do not function correctly. I manually added `env_add_path` to my local bucket copy and it fixed these issues.

**Comment by rasa** [comment]
#720 has been merged.
