### ISSUE TITLE
[Request]: jpegoptim

### ISSUE THREAD

**Issue by xd-mau5** [ScoopInstaller/Main#4952]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

jpegoptim

### Description

utility to optimize/compress JPEG files

### Homepage

https://github.com/tjko/jpegoptim

### Download Link(s)

https://github.com/tjko/jpegoptim/releases/download/v1.5.4/jpegoptim-1.5.4-x64-windows.zip

### Some Indication of Popularity/Repute

1.4k Stars on GitHub

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by BobbyWibowo** [comment]
Anybody willing to fulfill this? Maybe OP @xd-mau5 themselves?
