### ISSUE TITLE
[Request]: mediamtx

### ISSUE THREAD

**Issue by lemon-sh** [ScoopInstaller/Main#4956]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

mediamtx

### Description

RTSP / RTMP / LL-HLS / WebRTC media server and media proxy that allows to read, publish and proxy video and audio streams.

### Homepage

https://github.com/bluenviron/mediamtx

### Download Link(s)

https://github.com/bluenviron/mediamtx/releases/latest

### Some Indication of Popularity/Repute

![image](https://github.com/ScoopInstaller/Main/assets/26277478/918309b0-5a4f-42ce-bfcf-1be1fba67c4d)

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by lemon-sh** [comment]
Done (#5070)
