### ISSUE TITLE
[Request]: trzsz

### ISSUE THREAD

**Issue by lonnywong** [ScoopInstaller/Main#4961]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

trzsz

### Description

simple file transfer tools, similar to lrzsz ( rz / sz ), and compatible with tmux.

### Homepage

https://trzsz.github.io/

### Download Link(s)

https://github.com/trzsz/trzsz-go/releases/download/v1.1.5/trzsz_1.1.5_windows_x86_64.zip
https://github.com/trzsz/trzsz-go/releases/download/v1.1.5/trzsz_1.1.5_windows_aarch64.zip
https://github.com/trzsz/trzsz-go/releases/download/v1.1.5/trzsz_1.1.5_windows_i386.zip

### Some Indication of Popularity/Repute

https://github.com/trzsz/trzsz-go  594 stars and 37 forks at time of request.

Is it ok to move from https://github.com/ScoopInstaller/Extras/blob/master/bucket/trzsz.json to Main bucket?

**Comment by HUMORCE** [comment]
Could you make a PR for this?

**Comment by lonnywong** [comment]
> Could you make a PR for this?

#4963

Does it need to be removed from Extras bucket after merging?

**Comment by HUMORCE** [comment]
> Does it need to be removed from Extras bucket after merging?

Yes
