### ISSUE TITLE
[Request]: tssh

### ISSUE THREAD

**Issue by lonnywong** [ScoopInstaller/Main#4962]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

tssh

### Description

ssh client that supports trzsz, supports selecting or searching servers for login, supports remember password.

### Homepage

https://trzsz.github.io/ssh

### Download Link(s)

https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.9/tssh_0.1.9_windows_x86_64.zip
https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.9/tssh_0.1.9_windows_aarch64.zip
https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.9/tssh_0.1.9_windows_i386.zip

### Some Indication of Popularity/Repute

https://github.com/trzsz/trzsz-ssh 509 stars and 29 forks at time of request.

It’s in Extras bucket https://github.com/ScoopInstaller/Extras/blob/master/bucket/tssh.json now.

**Comment by HUMORCE** [comment]
Could you make a PR for this?
