### ISSUE TITLE
twilio-cli@5.11.0: decompress error

### ISSUE THREAD

**Issue by GenuineGenine** [ScoopInstaller/Main#4975]
Failed to extract files from C:\Users\matt\scoop\apps\twilio-cli\5.11.0\twilio-v5.11.0-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio-cli\5.11.0\7zip.log

**Comment by HUMORCE** [comment]
Solutions, choose one of them:

- Enable developer mode, learn more: `scoop checkup`
- Run terminal or shell as an Admin
- `scoop install gsudo; sudo scoop install twilio-cli`

**Comment by HUMORCE** [comment]
The offical doc of app mentions admin right is requires, so I added a note for it and closed this issue.
