### ISSUE TITLE
[Bug]: updatecli when installed as a shim does not execute

### ISSUE THREAD

**Issue by quotidian-ennui** [ScoopInstaller/Main#4992]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

updatecli

### Expected/Current Behaviour

updatecli when executed from the shims directory does not work; it has asn elevated command prompt. The binary itself when executed manually from its installation directory does.

### Steps to Reproduce

```console
XXX ~/scoop/shims
psh ❯ scoop install updatecli
Installing 'updatecli' (0.55.0) [64bit] from main bucket
Loading updatecli_Windows_x86_64.zip from cache.
Checking hash of updatecli_Windows_x86_64.zip ... ok.
Extracting updatecli_Windows_x86_64.zip ... done.
Linking ~\scoop\apps\updatecli\current => ~\scoop\apps\updatecli\0.55.0
Creating shim for 'updatecli'.
Creating shim for 'upd8cli'.
psh ❯ .\updatecli.exe
... At this point a elevated command prompt windows opens, 
... if you click yes, then updatecli runs in another window; if you click no then...
ResourceUnavailable: Program 'updatecli.exe' failed to run: An error occurred trying to start process 'C:\Users\Lewin.Chan\scoop\shims\updatecli.exe' with working directory 'C:\Users\Lewin.Chan\scoop\shims'. The operation was canceled by the user.At line:1 char:1
+ .\updatecli.exe
+ ~~~~~~~~~~~~~~~.
```

However it works when you execute it from its installation directory.

```
EELONLC ~/scoop/shims took 3s
psh ❯ cd ..\apps\updatecli\current\

EELONLC apps/updatecli/current
psh ❯ .\updatecli.exe version

VERSION

Application:    0.55.0
Golang     :    1.20.6 linux/amd64
Build Time :    2023-07-30T16:13:20Z

```

### Possible Solution

Just add it as a path.

### Scoop and Buckets Version

```console
psh ❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
1138b9d13 (HEAD -> master, origin/master, origin/HEAD) simplewall: Update to version 3.7.1

'java' bucket:
a2b272fb (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-33-ea

'jbangdev' bucket:
c41adf3 (HEAD -> main, tag: v0.110.0, origin/main, origin/HEAD) jbang v0.110.0

'main' bucket:
6e7042234 (HEAD -> master, origin/master, origin/HEAD) rust-analyzer: Update to version 2023-07-31

'nerd-fonts' bucket:
157e969 (HEAD -> master, origin/master, origin/HEAD) Maple-Mono: Update to version 6.4 and fix issues (#251)

'personal' bucket:
1c4b7aa (HEAD -> main, origin/main, origin/HEAD) updatecli: Update to version 0.55.0
```

### Scoop Config

```console
psh ❯ scoop config

alias                 :
aria2-warning-enabled : False
last_update           : 31/07/2023 09:33:25
scoop_repo            : https://github.com/ScoopInstaller/scoop
scoop_branch          : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Scoop/issues/5580

**Comment by stevehipwell** [comment]
@quotidian-ennui there is an additional alias of `upd8cli` added as a work around until #5580 is resolved. I haven't tried but I suspect that you could alias this to `updatecli` in your shell.

**Comment by HUMORCE** [comment]
@stevehipwell I copied the original manifest with that issue to the tests bucket.

**Comment by quotidian-ennui** [comment]
> @quotidian-ennui there is an additional alias of `upd8cli` added as a work around until [ScoopInstaller/Scoop#5580](https://github.com/ScoopInstaller/Scoop/issues/5580) is resolved. I haven't tried but I suspect that you could alias this to `updatecli` in your shell.

I realised why you did it steve, and I suppose we could just as well have added a note to the json saying `"notes": "if you have trouble with UAC, then use upd8cli as an alias"` instead (which is still an option, since having the shim is still preferable); but it seemed like too it would cause me too much mental friction.

Sometimes though life is too short to do things the right way (as well you know @stevehipwell 😉 ).
