### ISSUE TITLE
[Request]: deno_lint

### ISSUE THREAD

**Issue by gaeulbyul** [ScoopInstaller/Main#4993]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

deno_lint

### Description

Linter for JavaScript and TypeScript that powers Deno, but this is not Deno specific and can use for a Node.js project as well.

### Homepage

https://github.com/denoland/deno_lint

### Download Link(s)

https://github.com/denoland/deno_lint/releases/download/0.50.0/dlint-x86_64-pc-windows-msvc.zip

### Some Indication of Popularity/Repute

Currently, [deno_lint](https://github.com/denoland/deno_lint) itself has 1,465 stars and [Deno](https://github.com/denoland/deno) has 90,246 stars.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
