### ISSUE TITLE
mariadb: Service installation

### ISSUE THREAD

**Issue by isazajuancarlos** [ScoopInstaller/Main#4995]
scoop install mariadb

## install mariab service use:
mysqld.exe --install

**Comment by HUMORCE** [comment]
The manifest does not automatically install mariadb service.

**Comment by rashil2000** [comment]
The manifest shows a note during installation telling how to install the service:

https://github.com/ScoopInstaller/Main/blob/adec53467a2f7d0b540554bf70231f2802dcdc06/bucket/mariadb.json#L6-L13
