### ISSUE TITLE
erlang@22.1: hash check failed

### ISSUE THREAD

**Issue by ashtonangel7** [ScoopInstaller/Main#500]
PS C:\Users\AshtonA1> scoop update erlang
erlang: 22.0 -> 22.1
Updating one outdated app:
Updating 'erlang' (22.0 -> 22.1)
Downloading new version
Downloading http://erlang.org/download/otp_win64_22.1.exe#/dl.7z (-1 B)...

Checking hash of otp_win64_22.1.exe ... ERROR Hash check failed!
App:         main/erlang
URL:         http://erlang.org/download/otp_win64_22.1.exe#/dl.7z
First bytes: 3C 68 74 6D 6C 3E 3C 68
Expected:    46193e186a4b9ce42069b487c4907f69
Actual:      af0d2219c4a1943b9376999ce9945009

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=erlang%4022.1%3a+hash+check+failed
PS C:\Users\AshtonA1>

**Comment by linsui** [comment]
> Downloading http://erlang.org/download/otp_win64_22.1.exe#/dl.7z (-1 B)...

Your download failed, please try again.

**Comment by ashtonangel7** [comment]
@linsui thank you for the feedback, my original download timed out and every retry since gives me this response. I have updated other apps since but this one keep giving me the below error.

Downloading http://erlang.org/download/otp_win64_22.1.exe#/dl.7z (-1 B)...

Checking hash of otp_win64_22.1.exe ... ERROR Hash check failed!
App:         main/erlang
URL:         http://erlang.org/download/otp_win64_22.1.exe#/dl.7z
First bytes: 3C 68 74 6D 6C 3E 3C 68
Expected:    46193e186a4b9ce42069b487c4907f69
Actual:      af0d2219c4a1943b9376999ce9945009

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=erlang%4022.1%3a+hash+check+failed
PS C:\Users\AshtonA1> scoop update erlang
erlang: 22.0 -> 22.1
Updating one outdated app:
Updating 'erlang' (22.0 -> 22.1)
Downloading new version
Downloading http://erlang.org/download/otp_win64_22.1.exe#/dl.7z (-1 B)...

Checking hash of otp_win64_22.1.exe ... ERROR Hash check failed!
App:         main/erlang
URL:         http://erlang.org/download/otp_win64_22.1.exe#/dl.7z
First bytes: 3C 68 74 6D 6C 3E 3C 68
Expected:    46193e186a4b9ce42069b487c4907f69
Actual:      af0d2219c4a1943b9376999ce9945009

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=erlang%4022.1%3a+hash+check+failed
PS C:\Users\AshtonA1>

**Comment by linsui** [comment]
It looks like a network or firewall problem. Please test it it can be downloaded in browser.

**Comment by ashtonangel7** [comment]
Correct, thank you @linsui  for the help. I will download on another network.

![image](https://user-images.githubusercontent.com/7465941/67282429-168a9080-f4d2-11e9-82c1-91c03d78ea6e.png)
