### ISSUE TITLE
[Request]: espeak-ng

### ISSUE THREAD

**Issue by T145** [ScoopInstaller/Main#5012]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

espeak-ng

### Description

https://github.com/espeak-ng/espeak-ng#readme

### Homepage

https://github.com/espeak-ng/espeak-ng

### Download Link(s)

https://github.com/espeak-ng/espeak-ng/releases/tag/1.51

### Some Indication of Popularity/Repute

Stars: 2.2k

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
