### ISSUE TITLE
git-filter-repo@2.38.0: decompress error

### ISSUE THREAD

**Issue by Roadrunner67** [ScoopInstaller/Main#5014]
scoop install git-filter-repo
WARN  Purging previous failed installation of git-filter-repo.
ERROR 'git-filter-repo' isn't installed correctly.
Removing older version (2.38.0).
'git-filter-repo' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'git-filter-repo' (2.38.0) [64bit] from main bucket
Loading v2.38.0.zip from cache.
Checking hash of v2.38.0.zip ... ok.
Extracting v2.38.0.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\me\scoop\apps\git-filter-repo\2.38.0\v2.38.0.zip.
Log file:
  ~\scoop\apps\git-filter-repo\2.38.0\7zip.log

7zip.log:

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 197187 bytes (193 KiB)

Extracting archive: C:\Users\me\scoop\apps\git-filter-repo\2.38.0\v2.38.0.zip
--
Path = C:\Users\me\scoop\apps\git-filter-repo\2.38.0\v2.38.0.zip
Type = zip
Physical Size = 197187
Comment = cbc6535694380d3a3bf3e5c96410d4ce7e8de94f

Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\me\scoop\apps\git-filter-repo\2.38.0\git-filter-repo-2.38.0\contrib\filter-repo-demos\filter-branch-ish
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\me\scoop\apps\git-filter-repo\2.38.0\git-filter-repo-2.38.0\git_filter_repo.py

**Comment by HUMORCE** [comment]
```
> scoop checkup
WARN  Windows Developer Mode is not enabled. Operations relevant to symlinks may fail without proper rights.
  You may read more about the symlinks support here:
  https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/
```

Enable Windows Developer Mode OR `scoop install gsudo; sudo scoop install git-filter-repo`.
