### ISSUE TITLE
mingw@13.1.0-rt_v11-rev1: decompress error

### ISSUE THREAD

**Issue by yisuixinq** [ScoopInstaller/Main#5030]
Installing 'mingw' (13.1.0-rt_v11-rev1) [64bit] from main bucket
Loading x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z from cache.
Checking hash of x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z ... ok.
Extracting x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z ... ERROR Exit code was 2!
Failed to extract files from D:\Scoop\apps\mingw\13.1.0-rt_v11-rev1\x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z.
Log file:
  D:\Scoop\apps\mingw\13.1.0-rt_v11-rev1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=mingw%4013.1.0-rt_v11-rev1%3a+decompress+error

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
PS C:\Users\WDAGUtilityAccount> scoop install mingw -u
WARN  Scoop is out of date.
Installing '7zip' (23.01) [64bit] from main bucket
Loading 7z2301-x64.msi from cache
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\23.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (23.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running:
"C:\Users\WDAGUtilityAccount\scoop\apps\7zip\current\install-context.reg"
Installing 'mingw' (13.1.0-rt_v11-rev1) [64bit] from main bucket
Loading x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z from cache
Checking hash of x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z ... ok.
Extracting x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z ... done.
Linking ~\scoop\apps\mingw\current => ~\scoop\apps\mingw\13.1.0-rt_v11-rev1
Running post_install script...
'mingw' (13.1.0-rt_v11-rev1) was installed successfully!
```
