### ISSUE TITLE
[Request]: sing-box

### ISSUE THREAD

**Issue by rsp4jack** [ScoopInstaller/Main#5032]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

sing-box

### Description

The universal proxy platform

### Homepage

https://sing-box.sagernet.org/

### Download Link(s)

https://github.com/SagerNet/sing-box/releases

### Some Indication of Popularity/Repute

4.3k stars

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
