### ISSUE TITLE
elvish@0.19.2 hash switch between 2 hash strings

### ISSUE THREAD

**Issue by virasak** [ScoopInstaller/Main#5047]
According to current package spec, elvish@0.19.2 has hash=`7d13e04cb8e513e307acf889fbd2c97453764992dd7099dedac164d83750e910`.
The zip file itself has has=`28c96840fa87e654320e1fdf364589bb9a2c64146364ca10db8ecf09c00a0541` according to this command:
```
❯ sha256sum C:\Users\***\Downloads\elvish-v0.19.2.zip
28c96840fa87e654320e1fdf364589bb9a2c64146364ca10db8ecf09c00a0541  C:\Users\vdungsrikaew\Downloads\elvish-v0.19.2.zip
```
And it matches with provided hash here:
```
❯ curl -s https://dl.elv.sh/windows-amd64/elvish-v0.19.2.zip.sha256sum
28c96840fa87e654320e1fdf364589bb9a2c64146364ca10db8ecf09c00a0541  elvish-v0.19.2.zip
```

And according to [closed issues](https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+is%3Aclosed+elvish%400.19.2%3A+hash+check+failed) , this package was flipped between `7d13e04cb8e513e307acf889fbd2c97453764992dd7099dedac164d83750e910` and `28c96840fa87e654320e1fdf364589bb9a2c64146364ca10db8ecf09c00a0541` already.

https://github.com/ScoopInstaller/Main/commit/7a1e24731f23b21cb84c4787bf0679fbfc5fdb2b second switch
https://github.com/ScoopInstaller/Main/commit/b418d772f852f99ed31857029fb392e14c3fba70 first switch
https://github.com/ScoopInstaller/Main/commit/ad5e90637a3289901c89b69daf79791379978596 bump version

Don't know we can trust this package or not.

**Comment by virasak** [comment]
Maybe it related to tagging packages wrongly in `0.19.[012]` https://github.com/elves/elvish/releases.

**Comment by HUMORCE** [comment]
Fixed: https://github.com/ScoopInstaller/Main/commit/e961f3be190743a17518f464edb79416d603045d

Upstream republish under the same version.
