### ISSUE TITLE
python@3.11.5: decompress error

### ISSUE THREAD

**Issue by atanoken** [ScoopInstaller/Main#5062]
Hi,

Python install fails with following output:

PS C:\> scoop install python
Installing 'python' (3.11.5) [64bit] from main bucket
Loading python-3.11.5-amd64.exe from cache
Checking hash of python-3.11.5-amd64.exe ... ok.
Running pre_install script...
Running installer script...
ERROR Exit code was 1622!
Failed to extract files from C:\Users\XXXXX\scoop\apps\python\3.11.5\_tmp\AttachedContainer\core.msi.
Log file:
  ~\scoop\apps\python\3.11.5\_tmp\AttachedContainer\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.11.5%3a+decompress+error

**Comment by HUMORCE** [comment]
Check the error code on this page: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

1. Restart PC then retry install the manifest
2. Use alternative MSI extractor by toggle config item `scoop config use_lessmsi true|false` (default: false)

**Comment by atanoken** [comment]
Resolved by using the alternative MSI extractor. Cheers HUMORCE!

Ta,
atanoken
