### ISSUE TITLE
azure-cli@2.52.0: decompress error

### ISSUE THREAD

**Issue by shaqo88** [ScoopInstaller/Main#5074]
Log says:
=== Logging started: 06/09/2023  11:01:45 ===
Error 1304. Error writing to file: C:\Users\<MYNAME>\scoop\apps\azure-cli\2.52.0\_tmp\SourceDir\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\dla\vendored_sdks\azure_mgmt_datalake_analytics\catalog\models\data_lake_analytics_catalog_secret_create_or_update_parameters.pyc. Verify that you have access to that directory.
=== Logging stopped: 06/09/2023  11:02:16 ===

**Comment by ogerardin** [comment]
Got the same problem.
Solved temporarily by uninstalling, reinstalling 2.51.0 and pinning this version until a solution is found.

```
scoop uninstall azure-cli
scoop install azure-cli@2.51.0
scoop hold azure-cli
```

The problem seems to be with v2.52.0 specifically
The file name `data_lake_analytics_catalog_secret_create_or_update_parameters.pyc` looks suspiciously long to me...

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/4732
