### ISSUE TITLE
azure-cli@2.52.0: decompress error

### ISSUE THREAD

**Issue by gcaferra** [ScoopInstaller/Main#5081]
Unable to install Azure-cli (latest version)
=== Logging started: 9/7/2023  9:31:23 ===
Error 1304. Error writing to file: C:\Users\{user}\scoop\apps\azure-cli\2.52.0\_tmp\SourceDir\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\dla\vendored_sdks\azure_mgmt_datalake_analytics\catalog\models\data_lake_analytics_catalog_secret_create_or_update_parameters.pyc. Verify that you have access to that directory.
=== Logging stopped: 9/7/2023  9:32:03 ===

**Comment by rashil2000** [comment]
#5074
