### ISSUE TITLE
mro: Should be deprecated as MRAN shut down

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Main#5085]
The mro package should be deprecated as the Microsoft R Application Network has been shut down on 1 July 2023. Not sure what to put as the message (e.g. alternatives) so I'm opening an issue here.

See: https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161

**Comment by rashil2000** [comment]
The download link is not functional, so we can just mention that in the commit message.
