### ISSUE TITLE
[Request]: Bun

### ISSUE THREAD

**Issue by azmankudus** [ScoopInstaller/Main#5092]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Bun

### Description

About Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one

### Homepage

https://bun.sh

### Download Link(s)

https://github.com/oven-sh/bun/releases

### Some Indication of Popularity/Repute

Github Start 49.8k
Used by more than 55.6k users

**Comment by rashil2000** [comment]
They don't provide Windows builds yet

**Comment by sitiom** [comment]
> They don't provide Windows builds yet

They do now for canary:

- https://github.com/ScoopInstaller/Versions/pull/1449

**Comment by sitiom** [comment]
> They don't provide Windows builds yet

They do now for canary:

- https://github.com/ScoopInstaller/Versions/pull/1449

Also, another important news https://github.com/oven-sh/bun/issues/43#issuecomment-1791719280:

> In 11 days, Windows support for Bun will land.

**Comment by NemoStein** [comment]
They do now, fully native
https://bun.sh/blog/bun-v1.1
