### ISSUE TITLE
[Request]: GitQL

### ISSUE THREAD

**Issue by AmrDeveloper** [ScoopInstaller/Main#5095]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gitql

### Description

SQL like query language to perform queries on .git files

### Homepage

https://github.com/AmrDeveloper/GQL

### Download Link(s)

https://github.com/AmrDeveloper/GQL/releases/tag/0.6.0

### Some Indication of Popularity/Repute

More then 500 stars

**Comment by aliesbelik** [comment]
Fixed by #5096.
