### ISSUE TITLE
[Request]: mask

### ISSUE THREAD

**Issue by simonsan** [ScoopInstaller/Main#5097]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

mask

### Description

A CLI task runner defined by a simple markdown file.

### Homepage

https://github.com/jacobdeichert/mask

### Download Link(s)

https://github.com/jacobdeichert/mask/releases/download/v0.11.3/mask-v0.11.3-x86_64-pc-windows-msvc.zip

### Some Indication of Popularity/Repute

Github Stars: 884

A bit like `just`, but with a self-describing Markdown file

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by rashil2000** [comment]
Yes, it is possible, see https://github.com/ScoopInstaller/Main/blob/master/bucket/z3.json for example.
