### ISSUE TITLE
Circular dependency detected: 'dark' -> 'dark'.

### ISSUE THREAD

**Issue by DaanDeMeyer** [ScoopInstaller/Main#51]
When trying to install dark, I get the error from the title. I've tried uninstalled dark and removing all old versions from the cache but still get the error.

**Comment by DaanDeMeyer** [comment]
I'm also getting `Circular dependency detected: '7zip' -> 'dark'.` errors on my Windows CI builds as well.

**Comment by niheaven** [comment]
'develop' branch or 'master' branch?

**Comment by DaanDeMeyer** [comment]
I haven't changed anything so I think master

**Comment by h404bi** [comment]
Confirmed. @r15ch13 
https://github.com/lukesampson/scoop/blob/71f504494a682d09f8fc8d16342992bf9cbbbaa3/lib/depends.ps1#L89-L91

**Comment by niheaven** [comment]
Yes, it add `dark` for every apps deps if `dark` is not installed...

**Comment by r15ch13** [comment]
Repackaged dark as `.zip` file. Should fix the problem.

**Comment by h404bi** [comment]
Fixed in https://github.com/lukesampson/scoop/pull/3453 , please run `scoop update` and try again.

**Comment by DaanDeMeyer** [comment]
That fixed the issue. Thanks for the fast update!
