### ISSUE TITLE
azure-cli@2.52.0: decompress error

### ISSUE THREAD

**Issue by reinpeter** [ScoopInstaller/Main#5107]
Installing azure-cli fails when updating (or installing after an uninstall/clear)
NB: That folder _tmp and below has full access for the user
Previous version install no issues on exact same system.

$ scoop install azure-cli
Installing 'azure-cli' (2.52.0) [64bit] from main bucket
Loading azure-cli-2.52.0.msi from cache
Checking hash of azure-cli-2.52.0.msi ... ok.
Extracting azure-cli-2.52.0.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\reinpeter\scoop\apps\azure-cli\2.52.0\azure-cli-2.52.0.msi.
Log file:
  ~\scoop\apps\azure-cli\2.52.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=azure-cli%402.52.0%3a+decompress+error

Contents of msi.log:
=== Logging started: 14/09/2023  13:31:02 ===
Error 1304. Error writing to file: C:\Users\<<<redacted>>>\scoop\apps\azure-cli\2.52.0\_tmp\SourceDir\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\dla\vendored_sdks\azure_mgmt_datalake_analytics\catalog\models\data_lake_analytics_catalog_secret_create_or_update_parameters.pyc. Verify that you have access to that directory.
=== Logging stopped: 14/09/2023  13:32:08 ===

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+azure-cli+is%3Aclosed
