### ISSUE TITLE
azure-cli@2.53.0: decompress error

### ISSUE THREAD

**Issue by everonline** [ScoopInstaller/Main#5132]
As in version 2.52

Checking hash of azure-cli-2.53.0.msi ... ok.
Extracting azure-cli-2.53.0.msi ... ERROR Exit code was 1603!

Back to 2.51

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue+1603+is%3Aclosed
