### ISSUE TITLE
[Bug]: youtube-dl URL is unaccessible, use github URLs

### ISSUE THREAD

**Issue by nitincodery** [ScoopInstaller/Main#5140]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

youtube-dl

### Expected/Current Behaviour

It is not installing because of download url is blocked.

Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

On accessing the url: https://yt-dl.org/downloads/2021.12.17/youtube-dl.exe it says above error.

### Steps to Reproduce

```console
scoop install main/youtube-dl
```

### Possible Solution

Use github release URL: https://github.com/ytdl-org/youtube-dl/releases/download/2021.12.17/youtube-dl.exe

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
60c4afd1a (HEAD -> master, origin/master, origin/HEAD) threema@1.2.37: Fix hash (Closes #11961)

'main' bucket:
ba93055d4 (HEAD -> master, origin/master, origin/HEAD) nodejs: Update to version 20.8.0
```

### Scoop Config

```console
last_update          scoop_branch scoop_repo
-----------          ------------ ----------
29-Sep-2023 12:28:56 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
Can you make a PR for the fix?
