### ISSUE TITLE
[Request]: Kindly add microk8s 

### ISSUE THREAD

**Issue by rahulmr** [ScoopInstaller/Main#5144]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

microk8s

### Description

microk8s is easiest way to create a kubernetes cluster

### Homepage

www.microk8s.io

### Download Link(s)

https://microk8s.io/microk8s-installer.exe

### Some Indication of Popularity/Repute

It comes from Canonical (Ubuntu)
https://github.com/canonical/microk8s
7709 stars
744 forks

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by rahulmr** [comment]
Does that mean, I need to write the json myself? Never done before, need to check

**Comment by rahulmr** [comment]
Seems like proper command line installer is not available. I have raise issue [here](https://github.com/canonical/microk8s/issues/4238#issue-1930690437)

**Comment by HUMORCE** [comment]
I added it, but I can't confirm its availability.

It include a multipass installer inside, may have to be run with multipass, `scoop install multipass`
