### ISSUE TITLE
[Request]: numbat

### ISSUE THREAD

**Issue by leumasme** [ScoopInstaller/Main#5151]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

numbat

### Description

A statically typed programming language for scientific computations with first class support for physical dimensions and units

### Homepage

https://numbat.dev/

### Download Link(s)

https://github.com/sharkdp/numbat/releases

### Some Indication of Popularity/Repute

While the project itself only has 125 stars at this moment, it was only released 2 weeks ago and it is the official "follow-up project" (≈ recode+rebrand) to [insect](https://github.com/sharkdp/insect) by the same dev, which has 3.2k github stars.
I supposed whether or not this is an acceptable demonstration of reputation is up to the maintainers to decide.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!
