### ISSUE TITLE
jdupes has migrated to codeberg

### ISSUE THREAD

**Issue by g-berthiaume** [ScoopInstaller/Main#5168]
This issue is a message for the maintainer of [bucket/jdupes.json](https://github.com/ScoopInstaller/Main/blob/96ea56865edd7f38bd6e7d78ea292235f893b656/bucket/jdupes.json#L4C38-L4C38)

To my understanding, the author of `jdupes` has migrated from github to [codeberg](https://codeberg.org/jbruchon/jdupes).
Official anouncement: https://www.jdupes.com/2023/10/05/news-github-is-out-codeberg-is-in/

**Comment by rashil2000** [comment]
Hi, please make a PR to update the links!
