### ISSUE TITLE
[Request]: Add `gut`

### ISSUE THREAD

**Issue by Zliced13** [ScoopInstaller/Main#5192]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gut

### Description

A CLI frontend that makes git CLI easier to use. Written in Golang.

### Homepage

https://gut-cli.dev/

### Download Link(s)

https://github.com/julien040/gut/releases/download/0.2.10/gut_Windows_arm64.zip,
https://github.com/julien040/gut/releases/download/0.2.10/gut_Windows_i386.zip 
https://github.com/julien040/gut/releases/download/0.2.10/gut_Windows_x86_64.zip

### Some Indication of Popularity/Repute

https://www.producthunt.com/products/gut-a-user-friendly-git-cli#gut-2

https://www.reddit.com/r/golang/comments/11usyyy/gut_an_easytouse_cli_for_git_built_with_golang/

https://www.perplexity.ai/search/gitalternative-Xo4fZxzBTemptZWy.TNwaA?s=c

I wish I could write the manifest myself, but I currently busy with my secondary education course called OOP. So if anybody could please take the time to implement this into the main bucket, I would be more than grateful.

Not to be confused with, this:
https://github.com/divvun/gut

**Comment by aliesbelik** [comment]
Although it doesn't formally fit [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) (in terms of popularity) at the moment, let's maybe give it a chance here #5195.
