### ISSUE TITLE
ffmpeg@4.1.3: download via aria2 failed

### ISSUE THREAD

**Issue by Trim21** [ScoopInstaller/Main#52]
full log

says: `A socket operation was attempted to an unreachable network.`

![image](https://user-images.githubusercontent.com/13553903/57585663-ae488380-751d-11e9-8442-368cb21809c1.png)

I try download file with wget and it succeed

![image](https://user-images.githubusercontent.com/13553903/57585691-0ed7c080-751e-11e9-9acd-ada807705c0a.png)

```powershell
➜  docs git:(dev) ✗ scoop --version
Current Scoop version:
87a1e784 (HEAD -> master, origin/master, origin/HEAD) fix(decompress): Fix dark parameter order

'extras' bucket:
59fa9df0 (HEAD -> master, origin/master, origin/HEAD) spytify: Update to version 1.3

'main' bucket:
e7999978 (HEAD -> master, origin/master, origin/HEAD) elixir: Update to version 1.8.2

```

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
