### ISSUE TITLE
[Request]: Kubecolor

### ISSUE THREAD

**Issue by giggio** [ScoopInstaller/Main#5202]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Kubecolor

### Description

Colorize your kubectl output

### Homepage

https://github.com/kubecolor/kubecolor

### Download Link(s)

https://github.com/kubecolor/kubecolor/releases

### Some Indication of Popularity/Repute

This project used to live at: https://github.com/hidetatz/kubecolor
Where it has 1.4k stars.
It is now at: https://github.com/kubecolor/kubecolor/releases
Where it still has 90 stars, it has recently been moved/forked. The original was archived.

**Comment by rashil2000** [comment]
Hi, please make a PR for your request!

**Comment by aliesbelik** [comment]
PR raised in Extras (ScoopInstaller/Extras#12493) recently.
Maybe this request could be closed in favor of ScoopInstaller/Extras#12492.

**Comment by rashil2000** [comment]
Sure
