### ISSUE TITLE
[Bug]: Quarkus-cli stucks at 3.2.4 autoupdate is broken

### ISSUE THREAD

**Issue by VladDrakul1986** [ScoopInstaller/Main#5229]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

quarkus-cli

### Expected/Current Behaviour

The version is not upgraded to latest release right now 3.5.0. So the autoupgrade doesn't work fine :(

Kind regards Vlad.

### Steps to Reproduce

```console
scoop install quarkus-cli
```

### Possible Solution

change bucket/quarkus-cli.json manually and fix the autoupdate.
It seems they remove the .Final from the version name.
See latest version on their repo: 
[https://github.com/quarkusio/quarkus/releases/download/3.5.0/quarkus-cli-3.5.0.zip](https://github.com/quarkusio/quarkus/releases/download/3.5.0/quarkus-cli-3.5.0.zip)

### Scoop and Buckets Version

```console
not relevant
```

### Scoop Config

```console
not relevant
```

### PowerShell Version

```console
not relevant
```

**Comment by yostane** [comment]
Hi,

Thanks for raising this issue. I am also stuck at version 3.2.4.

I have asked a question in Quarkus GitHub to try to get an official response: https://github.com/quarkusio/quarkus/discussions/37459

I have also created an intermediary PR to at least update to 3.2.9. #5309 

BR,

**Comment by yostane** [comment]
I got the confirmation that quarkus officially removed the .Final

https://github.com/quarkusio/quarkus/discussions/37459#discussioncomment-7730969

https://quarkus.io/blog/quarkus-3-3-0-released/

**Comment by yostane** [comment]
As indicated in [quarkus-cli.json Line 14](https://github.com/ScoopInstaller/Main/blob/2684f9dd1e997dfdcd2973e72878a46323b76726/bucket/quarkus-cli.json#L14C20-L14C20) scoop looks at this file for updates: https://registry.quarkus.io/client/platforms, which seems to list only final releases (no Aplha or other qualifier) 

This PR may fix this issue: https://github.com/ScoopInstaller/Main/pull/5230/files
