### ISSUE TITLE
[Bug]: Installation of adb fails

### ISSUE THREAD

**Issue by f-cramer** [ScoopInstaller/Main#5246]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

adb

### Expected/Current Behaviour

Installation or update of adb is not possible because it references an exe that is no longer available

### Steps to Reproduce

```console
PS> scoop update adb
adb: 34.0.4 -> 34.0.5 (global)
Updating one outdated app:
Updating 'adb' (34.0.4 -> 34.0.5)
Downloading new version
Downloading https://dl.google.com/android/repository/platform-tools_r34.0.5-windows.zip (5,6 MB)...
Checking hash of platform-tools_r34.0.5-windows.zip ... ok.
Uninstalling 'adb' (34.0.4)
Removing shim 'adb.shim'.
Removing shim 'adb.exe'.
Removing shim 'dmtracedump.shim'.
Removing shim 'dmtracedump.exe'.
Removing shim 'etc1tool.shim'.
Removing shim 'etc1tool.exe'.
Removing shim 'fastboot.shim'.
Removing shim 'fastboot.exe'.
Removing shim 'hprof-conv.shim'.
Removing shim 'hprof-conv.exe'.
Unlinking C:\ProgramData\scoop\apps\adb\current
Installing 'adb' (34.0.5) [64bit] from main bucket
Loading platform-tools_r34.0.5-windows.zip from cache
Extracting platform-tools_r34.0.5-windows.zip ... done.
Linking C:\ProgramData\scoop\apps\adb\current => C:\ProgramData\scoop\apps\adb\34.0.5
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Can't shim 'platform-tools\dmtracedump.exe': File doesn't exist.
```

### Possible Solution

Remove shim for "dmtracedump.exe"

### Scoop and Buckets Version

```console
irrelevant
```

### Scoop Config

```console
irrelevant
```

### PowerShell Version

```console
irrelevant
```

**Comment by redactedscribe** [comment]
If you uninstalled adb already because of this, install the previous non-problematic version using:

```
scoop uninstall adb
scoop install adb@34.0.4
```

**Comment by EasonFP** [comment]
i have the same question!
` scoop install adb
WARN  Purging previous failed installation of adb.
ERROR 'adb' isn't installed correctly.
Removing older version (34.0.5).
'adb' was uninstalled.
Installing 'adb' (34.0.5) [64bit] from main bucket
Loading platform-tools_r34.0.5-windows.zip from cache
Checking hash of platform-tools_r34.0.5-windows.zip ... ok.
Extracting platform-tools_r34.0.5-windows.zip ... done.
Linking ~\scoop\apps\adb\current => ~\scoop\apps\adb\34.0.5
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Can't shim 'platform-tools\dmtracedump.exe': File doesn't exist.`

**Comment by StarsbySea** [comment]
I have the same problem!
```powershell
PS C:\Users\Kevin> scoop update; scoop install adb
Updating Scoop...
WARN  Uncommitted changes detected. Update aborted.
Updating 'dorado' bucket...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'nonportable' bucket...
Updating 'ocean' bucket...
Updating 'pigsflew_scoop-arbitrariae' bucket...
Updating 'sysinternals' bucket...
Updating 'versions' bucket...
Scoop was updated successfully!
WARN  Purging previous failed installation of adb.
ERROR 'adb' isn't installed correctly.
Removing older version (34.0.5).
'adb' was uninstalled.
Installing 'adb' (34.0.5) [64bit] from main bucket
Loading platform-tools_r34.0.5-windows.zip from cache
Checking hash of platform-tools_r34.0.5-windows.zip ... ok.
Extracting platform-tools_r34.0.5-windows.zip ... done.
Linking ~\scoop\apps\adb\current => ~\scoop\apps\adb\34.0.5
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Can't shim 'platform-tools\dmtracedump.exe': File doesn't exist.
```

**Comment by mrplumber** [comment]
While we wait for the fix to be merged, here is simple fix to restore previous version (34.0.4) to working condition without reinstalling it as per suggestion earlier in this thread:
```
scoop reset adb
scoop hold adb
```

**Comment by unwillinglyawesome** [comment]
The RP's been open for 5 days now. Was wondering what might take so long to merge a simple fix?

**Comment by f-cramer** [comment]
The corresponding PR is already open since this issue was created, no need to add a second one
