### ISSUE TITLE
[Bug]: helix doesn't detect custom themes stored in the persist directory, only in the default location.

### ISSUE THREAD

**Issue by andmoreduro** [ScoopInstaller/Main#5274]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

helix

### Expected/Current Behaviour

Even though helix uses the custom config, it doesn't detect custom themes in the `$HOME\scoop\persist\themes` directory, instead it only does so when the theme is in `%AppData%\helix\themes`.

### Steps to Reproduce

```console
PS> scoop install helix
```

### Possible Solution

I think this a problem with helix, because if I try to specify a config file to helix in linux (WSL 2) with the `--config` flag, the same happens: the config is used, but the theme is only used and detected when it is stored in the default location.

Even though, I think this is something we should be aware of, because the change to use the persist directory for the config file ([#4948](https://github.com/ScoopInstaller/Main/issues/4948)) probably wasn't the best idea.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'java' bucket:
00fb23c2 (HEAD -> master, origin/master, origin/HEAD) openjdk22: Update to version 22-23-ea

'main' bucket:
a52e71c22 (HEAD -> master, origin/master, origin/HEAD) symfony-cli: Update to version 5.7.3

'nerd-fonts' bucket:
bef9b8d (HEAD -> master, origin/master, origin/HEAD) Monaspace: Fix uninstaller script
```

### Scoop Config

```console
PS> scoop config

last_update            scoop_branch scoop_repo
-----------            ------------ ----------
11/14/2023 10:45:59 AM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
> helix doesn't detect custom themes stored in the persist directory, only in the default location

Why will it do so? There's no provision in helix for loading themes from any other directory. I don't think this is a problem, it's just something that the devs did not plan to do.

**Comment by andmoreduro** [comment]
Well, that is precisely the problem. When helix is installed from scoop it expects the config file to be in the persist directory, but this not by default behaviour. The default behaviour is for everything (config file, and themes) to be in the default location.

I reiterate. The problem is the fragmentation of the configuration files (I consider the themes part of the configuration) in two completely separate locations.

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Main/commit/7bfcd3f478475694cf31d5ed130215856bc0aa38
