### ISSUE TITLE
[Request]: openfga cli

### ISSUE THREAD

**Issue by polaris940** [ScoopInstaller/Main#5330]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

openfga

### Description

A cross-platform CLI to interact with an OpenFGA server

### Homepage

https://openfga.dev/

### Download Link(s)

https://github.com/openfga/cli

### Some Indication of Popularity/Repute

CLI for the OpenFGA project. Main project has 116 forks and 1.7K stars.
https://github.com/openfga/openfga

**Comment by aaguiarz** [comment]
@polaris940 thanks for doing this! 

Would you mind submitting a PR for https://github.com/openfga/cli/blob/main/README.md explaining how to install the CLI in windows? 

Thanks again in advance!
