### ISSUE TITLE
[Request]: nodejs arm64

### ISSUE THREAD

**Issue by tekumara** [ScoopInstaller/Main#5338]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

nodejs

### Description

arm64

### Homepage

https://nodejs.org/en/download/package-manager

### Download Link(s)

https://nodejs.org/dist/v20.10.0/node-v20.10.0-win-arm64.zip

### Some Indication of Popularity/Repute

x86 binaries already handled by scoop

**Comment by tech189** [comment]
This was [already added](https://github.com/ScoopInstaller/Main/pull/4690) from version 20.0.0, please run `scoop update` to get the latest manifest with arm64.
