### ISSUE TITLE
Every installaiton in scoop is failing

### ISSUE THREAD

**Issue by ajitduhoon** [ScoopInstaller/Main#5347]
Hi
Every installation in scoop is failing with the error

Extracting dark-3.11.2.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\user\scoop\apps\dark\3.11.2\dark-3.11.2.zip.
Log file:
  C:\Users\user\scoop\apps\dark\3.11.2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:

Kindly help me as I am a new bee to using scoop and I urgently need to so some installations through scoop.

If it is a very naive issue, kindly bear with me and guide

**Comment by tech189** [comment]
Hi! Please could you paste the output of the log file `C:\Users\user\scoop\apps\dark\3.11.2\7zip.log`?

You may be facing the same issue as in #5014. Please also run `scoop checkup` and paste the output.

**Comment by ajitduhoon** [comment]
Thanks a lot for getting back. I finally sorted the issue through reading around. Again thanks
