### ISSUE TITLE
nim@2.0.2: hash check failed

### ISSUE THREAD

**Issue by osfanbuff63** [ScoopInstaller/Main#5386]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

nim@2.0.2

**Comment by lfanew** [comment]
@osfanbuff63 I also had this, but noticed Windows Defender is quarantining it in the background. There were multiple parts of the install that triggered Defender to quarantine and cause the scoop install to fail, so make sure you are monitoring it.

![image](https://github.com/ScoopInstaller/Main/assets/58160325/8bb5fa89-9c42-4478-a193-8c62cadbdbea)
