### ISSUE TITLE
lessmsi@1.6.91: download via aria2 failed

### ISSUE THREAD

**Issue by 1475142232** [ScoopInstaller/Main#539]
![image](https://user-images.githubusercontent.com/25600940/68173622-890d6d00-ffb6-11e9-88ba-bd4cf6369f2c.png)

**Comment by issaclin32** [comment]
It works fine here. You can try to download it again later.

![lessmsi](https://user-images.githubusercontent.com/27724471/68174278-7dbb4100-ffb8-11e9-9a58-0ce97f6b2a25.png)
