### ISSUE TITLE
tesseract-languages@4.1.0: decompress error

### ISSUE THREAD

**Issue by tch123** [ScoopInstaller/Main#5392]
❯ scoop install tesseract-languages
Installing 'tesseract-languages' (4.1.0) [64bit] from main bucket
Loading 4.1.0.zip from cache
Checking hash of 4.1.0.zip ... ok.
Loading equ.traineddata from cache
Checking hash of equ.traineddata ... ok.
Loading snum.traineddata from cache
Checking hash of snum.traineddata ... ok.
Extracting 4.1.0.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Name\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip.
Log file:
  ~\scoop\apps\tesseract-languages\4.1.0\7zip.log

--------------
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 351046435 bytes (335 MiB)

Extracting archive: C:\Users\Name\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
--
Path = C:\Users\Name\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
Type=zip
Physical Size = 351046435
Comment = 65727574dfcd264acbb0c3e07860e4e9e9b22185

Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
ERROR: Cannot create symbolic link : The client does not have the required privileges. : C:\Users\Name\scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\configs
ERROR: Cannot create symbolic link : The client does not have the required privileges. : C:\Users\Name\scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\pdf.ttf

**Comment by HUMORCE** [comment]
```
> scoop info tesseract-languages


Name         : tesseract-languages
Description  : Fast integer versions of trained models for the Tesseract Open Source OCR Engine
Version      : 4.1.0
Bucket       : main
Website      : https://github.com/tesseract-ocr/tessdata_fast
License      : Apache-2.0
Dependencies : tesseract
Updated at   : 6/15/2023 11:22:32 AM
Updated by   : HUMORCE
Environment  : TESSDATA_PREFIX = <root>
Notes        : This packages has overwritten the 'TESSDATA_PREFIX' environment variable with "<root>".
               After updating "tesseract" please run "scoop reset tesseract-languages" to update the environment
               variable!

               - Known issue:
                 - ERROR: Cannot create symbolic link: https://github.com/ScoopInstaller/Main/issues/4874
```
