### ISSUE TITLE
[Bug]:  The gnuplot in the main bucket has not been updated to 6.0.0.

### ISSUE THREAD

**Issue by panyuz** [ScoopInstaller/Main#5403]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

gnuplot

### Expected/Current Behaviour

The gnuplot in the main library is version 5.4.6. The official website at http://www.gnuplot.info/ has already upgraded to version 6.0.0.

### Steps to Reproduce

```console
scoop status
```

### Possible Solution

update the gnuplot package to 6.0.0

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a249f5bd7 (HEAD -> master, origin/master, origin/HEAD) okular: Update to version 23.08.4-1633

'main' bucket:
27b74c744 (HEAD -> master, origin/master, origin/HEAD) rink: Update to version 0.7.0
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2024-01-07T13:26:31.8774149+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
> Current gnuplot major version is 5.4
> The most recent release was 5.4.8 (June 2023)
> 
> http://www.gnuplot.info/download.html

**Comment by liaoya** [comment]
@HUMORCE <http://www.gnuplot.info/download.html> may be out-of-date. <http://www.gnuplot.info/> announce `Gnuplot 6.0 (current stable)`

![图片](https://github.com/ScoopInstaller/Main/assets/37687/59a5c788-7296-40a0-a0df-56e4a39f8966)

**Comment by liaoya** [comment]
I will create a pull request for [gnuplot](http://www.gnuplot.info/).
