### ISSUE TITLE
[Bug]: Far Manager missing GUI shortcut

### ISSUE THREAD

**Issue by max-crow** [ScoopInstaller/Main#5406]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

far

### Expected/Current Behaviour

There is no shortcut for Far Manager

### Steps to Reproduce

```console
PS> scoop install far

open start menu
type "far"
no results
```

### Possible Solution

```
    "shortcuts": [
        [
            "Far.exe",
            "Far Manager"
        ]
    ],
```

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
2ea92b7ef (HEAD -> master, origin/master, origin/HEAD) qtemu@2.1: Fix hash (#12574)
```

### Scoop Config

```console
PS> scoop config

root_path         global_path           last_update
---------         -----------           -----------
C:\programs\Scoop C:\programs\ScoopApps 08.01.2024 18:53:55
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
It's a TUI/CLI app.

**Comment by max-crow** [comment]
Yep, it's a TUI/CLI app, but when installing with msi it creates the shortcut.

**Comment by HUMORCE** [comment]
<img width="692" alt="Snipaste_2024-01-14_02-00-38" src="https://github.com/ScoopInstaller/Main/assets/4353480/1f16a196-f84c-4d1d-8498-66dc8b4342f8">

`far` command consistent with the behavior of its shortcut. If you think it's necessary, please make a PR for review by other maintainers.
