### ISSUE TITLE
scoop-search@1.3.3: hash check failed

### ISSUE THREAD

**Issue by stinger086** [ScoopInstaller/Main#5446]
Hi,

I am receiving an error during 'scoop update scoop-search' command. The console output is as follows:

PS C:\Users\myusername> scoop update scoop-search
scoop-search: 1.3.1 -> 1.3.3
Updating one outdated app:
Updating 'scoop-search' (1.3.1 -> 1.3.3)
Downloading new version
scoop-search.exe (2.2 MB) [============================================================================================================================================================================] 100%
Checking hash of scoop-search.exe ... Get-FileHash: D:\dev\tools\Scoop\apps\scoop\current\lib\install.ps1:674
Line |
 674 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'D:\dev\tools\Scoop\cache\scoop-search#1.3.3#https_github.com_shilangyu_scoop-search_releases_download_v1.3.3_scoop-search.exe'
InvalidOperation: D:\dev\tools\Scoop\apps\scoop\current\lib\install.ps1:674
Line |
 674 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
Get-Content: D:\dev\tools\Scoop\apps\scoop\current\lib\core.ps1:1173
Line |
1173 |          return Get-Content $file -AsByteStream -TotalCount 8
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'D:\dev\tools\Scoop\cache\scoop-search#1.3.3#https_github.com_shilangyu_scoop-search_releases_download_v1.3.3_scoop-search.exe'
ERROR Hash check failed!
App:         main/scoop-search
URL:         https://github.com/shilangyu/scoop-search/releases/download/v1.3.3/scoop-search.exe
First bytes:
Expected:    d5ab7d9d164571b21c38b137e47604b8f9785758ec6ae1b99b014bef8acca4b9
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=scoop-search%401.3.3%3a+hash+check+failed

Any comments? Is it an issue or just my local problem?

**Comment by stinger086** [comment]
Thanks!
I have excluded the folder from Windows Defender scan: D:\dev\tools\Scoop and it have updated successfully!

**Comment by BinToss** [comment]
Issue resolved scoop-search [v1.4.0 - rewrite in Zig](https://github.com/shilangyu/scoop-search/releases/tag/v1.4.0), but it pending release via scoop/main

**Comment by BinToss** [comment]
Nervermind me. The `main` bucket updated its scoop-search package to v1.4.0. Run `scoop update` and `scoop update scoop-search`.
