### ISSUE TITLE
[Bug]: msys2 does not specify `env_add_path`

### ISSUE THREAD

**Issue by plutotree** [ScoopInstaller/Main#5462]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

msys2

### Expected/Current Behaviour

[msys2](https://github.com/se35710/scoop-main/blob/master/bucket/msys2.json) does not specify `"env_add_path": "usr\bin"`, which prevents the direct execution of many Linux command-line tools, such as `which`, `awk`, `dd`, `tail`, etc. 
I am wondering if there is a particular reason behind this? For example, to avoid conflicts with same named exe in cygwin or other packages. If not, I would like to submit a PR (Pull Request).

### Steps to Reproduce

```console
No relation
```

### Possible Solution

Add `"env_add_path": "usr\bin"` in `msys2.json`  manifest.

### Scoop and Buckets Version

```console
No relation
```

### Scoop Config

```console
No relation
```

### PowerShell Version

```console
No relation
```

**Comment by HUMORCE** [comment]
The manifest provides MSYS2, not its dependencies or infrastructure.

A similar issue: #5251
