### ISSUE TITLE
[Request]: radius

### ISSUE THREAD

**Issue by craigktreasure** [ScoopInstaller/Main#5474]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

radius

### Description

Radius is a cloud-native, portable application platform that makes app development easier for teams building cloud-native apps.

### Homepage

https://github.com/radius-project/radius

### Download Link(s)

https://github.com/radius-project/radius/releases

### Some Indication of Popularity/Repute

- [radapp.io](https://radapp.io/)
- GitHub stars: 1.3k
- GitHub forks: 72
- Sponsored by Microsoft (speaks to credibility rather than popularity at this point)
  - Disclosure: While I (craigktreasure) do work for Microsoft, I am not directly affiliated with the project.
- Radius has been submitted for consideration as a [Cloud Native Computing Foundation](https://www.cncf.io/) (CNCF) [Sandbox project](https://github.com/cncf/sandbox/issues/65).

**Comment by craigktreasure** [comment]
I got a bit ahead of myself and do have a [manifest prepared](https://github.com/craigktreasure/scoop-main-bucket/blob/craig/add-radius/bucket/radius.json) to submit for PR if the issue is approved.

**Comment by aliesbelik** [comment]
Please feel free to submit PR.

Several notes:
1. Use `.../rad_w_windows_amd64.exe#/rad.exe` in the `url` to rename binary inline, so you could simply use `"bin": "rad.exe"` then.
3. As for me `notes` could be avoided if provide homepage/checkver in the following form:
```
...
"homepage": "https://radapp.io",
...
"checkver": {
    "github": "https://github.com/radius-project/radius"
},
...
```

Guess you could use [this manifest](https://github.com/hoilc/scoop-lemon/blob/master/bucket/radius.json) for reference.
