### ISSUE TITLE
cygwin@2.928: hash check failed

### ISSUE THREAD

**Issue by sam-idv** [ScoopInstaller/Main#5509]
PS C:\scoop\apps\mobaxterm\sam> scoop install cygwin
WARN  Purging previous failed installation of cygwin.
ERROR 'cygwin' isn't installed correctly.
Removing older version (2.928).
'cygwin' was uninstalled.
Installing 'cygwin' (2.928) [64bit] from main bucket
setup-x86_64.exe (1.3 MB) [==========================================================================================================================================] 100%
Checking hash of setup-x86_64.exe ... ERROR Hash check failed!
App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a17217e66dd7c40fa4851a433335c1f3f003cd627116c708b2f6e66eba886ea9
Actual:      3d9e0143268f52aecaff76f81553c880ec9a353eb5a6e22bd6d34bad8251710c

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=cygwin%402.928%3a+hash+check+failed

**Comment by sam-idv** [comment]
scoop install cygwin@2.930 … OK

**Comment by tech189** [comment]
Closing because it looks like you got it working!
