### ISSUE TITLE
swift@5.9.2: decompress error

### ISSUE THREAD

**Issue by athronix** [ScoopInstaller/Main#5521]
Installing 'swift' (5.9.2) [64bit] from main bucket
Loading swift-5.9.2-RELEASE-windows10.exe from cache
Checking hash of swift-5.9.2-RELEASE-windows10.exe ... ok.
Running pre_install script...
ERROR Exit code was 1603!
Failed to extract files from C:\Users\towyq\scoop\apps\swift\5.9.2\extract_folder\AttachedContainer\a1.
Log file:
  ~\scoop\apps\swift\5.9.2\extract_folder\AttachedContainer\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=swift%405.9.2%3a+decompress+error

**Comment by tech189** [comment]
Could you post the contents of the msi.log file? It worked for me after rebooting.
