### ISSUE TITLE
[Bug]: px 0.9.0 does not start in background anymore

### ISSUE THREAD

**Issue by fschoenm** [ScoopInstaller/Main#5526]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

px

### Expected/Current Behaviour

After installing px 0.9.0, it doesn't start in the background anymore. After the system comes up, px opens in a console window that stays in the foreground.

### Steps to Reproduce

```console
Install px and configure with foreground setting 0 (default).


; Run in foreground when frozen or with pythonw.exe. 0 or 1, default: 0
;   Px will attach to the console and write to it even though the prompt is
;   available for further commands. CTRL-C in the console will exit Px
foreground = 0
```

### Possible Solution

See this related bug ticket: genotrance/px/issues/203

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
cdc720cdc (HEAD -> master, origin/master, origin/HEAD) xnview: Update to version 2.51.6

'java' bucket:
adf7e306 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.412-4.0.202402200053

'main' bucket:
2a0ee5186 (HEAD -> master, origin/master, origin/HEAD) tor: Update to version 0.4.8.10-13.0.10

'nerd-fonts' bucket:
60b9f27 (HEAD -> master, origin/master, origin/HEAD) smiley-sans-dev: Update to version 20240219.b31b81a
```

### Scoop Config

```console
gh_token              : ***
aria2-warning-enabled : False
last_update           : 20.02.2024 17:58:23
proxy                 : localhost:3128
scoop_branch          : master
scoop_repo            : https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tech189** [comment]
I could not reproduce this issue. I changed directory to `scoop\apps\px\current` and ran `.\pythonw -m px --install`. When I restarted, I confirmed from Task Manager that `px` was running in the background and no window popped up. Do you think we should add a note?

**Comment by fschoenm** [comment]
I had the previous version installed (I think 0.8.4) and then upgraded to 0.9.0. Maybe it makes a difference.
