### ISSUE TITLE
php: issue using it for development

### ISSUE THREAD

**Issue by ratatoeey** [ScoopInstaller/Main#555]
the  `"persist": [ ...` part doesn't work. So, I don't use scoop-installed php for anything. Its easier and simpler to download a zip from the site and setup things like scoop doesn't exist.

probably will elaborate later. or just ask a php developer.

will try it out for the latest php package if I have the time.
----

regards ratatoeey

**Comment by ratatoeey** [comment]
with python, using venv to create environments is a issue.

----

regards ratatoeey

**Comment by ratatoeey** [comment]
current workaround is to not use scoop at all for php. 

I download php 7 archives from the official site-> https://windows.php.net/download#php-7.3

- verify it using hashes
- extract it into the Downloads folder using 'Extract All..' option from context menu(use right-click).
- then copy this file

**Comment by ratatoeey** [comment]
I have setup `php-development.ini` for using laravel. and using sqlite3 as database. here's an ugly diff -
(can't paste it now)
```
> diff.exe '.\php-development.ini' '.\php.ini-development'

```

----

regards ratatoeey

**Comment by r15ch13** [comment]
"doesn't work" isn't an error. What exactly doesn't work?
Extensions can be enabled by adding them to a config.ini in `~\scoop\persist\php\cli\conf.d\`. You can overwrite any settings this way.


This is how my setup looks like:
![image](https://user-images.githubusercontent.com/432127/68551604-e5391c80-040e-11ea-8797-7a4605a0c124.png)

**Comment by ratatoeey** [comment]
>"doesn't work" isn't an error.

parroting is not a sign of being clever. read my posts. if you can't test it for composer. and laravel.

if your setup works, I'm curious to why it doesn't work for my setup. Which is simpler.

----

regards ratatoeey

**Comment by r15ch13** [comment]
Just updated php to 7.3.11 and composer and to 1.9.1:

`composer diagnose`:
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: <snip>
Dev Public Key Fingerprint: <snip>
OK
Checking composer version: OK
Composer version: 1.9.1
PHP version: 7.3.11
PHP binary path: D:\scoop\apps\php\current\php.exe
```

`php --ini`:
```
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         (none)
Scan for additional .ini files in: D:\scoop\apps\php\current\cli;D:\scoop\apps\php\current\cli\conf.d;
Additional .ini files parsed:      D:\scoop\apps\php\current\cli\php.ini,
D:\scoop\apps\php\current\cli\conf.d\cacert.ini,
D:\scoop\apps\php\current\cli\conf.d\extensions.ini,
D:\scoop\apps\php\current\cli\conf.d\opcache.ini,
D:\scoop\apps\php\current\cli\conf.d\sizes.ini,
D:\scoop\apps\php\current\cli\conf.d\timezone.ini,
D:\scoop\apps\php\current\cli\conf.d\xdebug.ini
```


Here is my current `php.ini` and `conf.d/`: [cli.zip](https://github.com/ScoopInstaller/Main/files/3830862/cli.zip)

Installing Laravel via composer and the Laravel installer works for me.
Does Laravel show any errors for you? I would like to understand the problem you have, but I can't figure out why it's not working for you.
Can you provide steps to reproduce your problem?

**Comment by r15ch13** [comment]
Hm, I tested a fresh scoop and php installation in a VM and I get following error from composer:

```
PHP Warning:  require(phar://C:/Users/WDAGUtilityAccount/scoop/apps/composer/1.9.1/composer.phar/bin/../src/bootstrap.php): failed to open stream: phar error: Cannot open phar archive "C:/Users/WDAGUtilityAccount/scoop/apps/composer/1.9.1/composer.phar" for reading in phar://C:/Users/WDAGUtilityAccount/scoop/apps/composer/1.9.1/composer.phar/bin/composer on line 8
PHP Fatal error:  require(): Failed opening required 'phar://C:/Users/WDAGUtilityAccount/scoop/apps/composer/1.9.1/composer.phar/bin/../src/bootstrap.php' (include_path='.;C:\php\pear') in phar://C:/Users/WDAGUtilityAccount/scoop/apps/composer/1.9.1/composer.phar/bin/composer on line 8
```

Even after loading the extensions like `mbstring`, `openssl` and so on it doesn't work. 🤔

**Comment by r15ch13** [comment]
The `extension_dir` was not enabled correctly when installing. Fixed that with https://github.com/ScoopInstaller/Main/commit/f7b880d221e2bddbb4667ca6a044dcd221a99522

**Comment by ratatoeey** [comment]
I expect the `extension_dir` fix in https://github.com/ScoopInstaller/Main/commit/f7b880d221e2bddbb4667ca6a044dcd221a99522 to fix the issue.

thanks a lot. i may or may not be able to test this.

the problem was that composer was complaining about insecure access over http as it expected https. 

you can test it by comparing what happens if you setup environment using scoop and without scoop.
and try to install `monolog/monolog`. with php 7.3.10
----

regards ratatoeey

**Comment by ratatoeey** [comment]
might need a note for this for new users. I think.

```
> composer.cmd diagnose                                                        

  [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl ex
  tension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.


diagnose
```
----

regards ratatoeey

**Comment by ratatoeey** [comment]
yep. now it works as expected.

```
> composer.cmd install                                                         Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.2): Downloading (100%)
  - Installing monolog/monolog (2.0.0): Downloading (100%)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing elasticsearch/elasticsearch (Allow sending log messages to an Elasticsearch server via official client)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongodb (Allow sending log messages to a MongoDB server (via driver))
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server (via library))
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
Writing lock file
Generating autoload files
```

no https related warnings. 

```
> composer.cmd diagnose                                                        Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: <snip>
Dev Public Key Fingerprint: <snip>
OK
Checking composer version: OK
Composer version: 1.9.1
PHP version: 7.3.11
PHP binary path: D:\scoop\apps\php\current\php.exe
```
---


----

regards ratatoeey
