### ISSUE TITLE
swift@5.10: decompress error

### ISSUE THREAD

**Issue by dbaumber** [ScoopInstaller/Main#5577]
swift: 5.9.2 -> 5.10
Updating one outdated app:
Updating 'swift' (5.9.2 -> 5.10)
Downloading new version
Loading swift-5.10-RELEASE-windows10.exe from cache
Checking hash of swift-5.10-RELEASE-windows10.exe ... ok.
Uninstalling 'swift' (5.9.2)
Installing 'swift' (5.10) [64bit] from main bucket
Loading swift-5.10-RELEASE-windows10.exe from cache
Running pre_install script...
ERROR Exit code was 1620!
Failed to extract files from C:\Users\dbaum\scoop\apps\swift\5.10\extract_folder\AttachedContainer\a0.
Log file:
  ~\scoop\apps\swift\5.10\extract_folder\AttachedContainer\msi.log

The log file was completely empty.

**Comment by HUMORCE** [comment]
#5581
