### ISSUE TITLE
azure-cli@2.58.0: decompress error

### ISSUE THREAD

**Issue by martindolezal** [ScoopInstaller/Main#5623]
scoop install main/azure-cli
Installing 'azure-cli' (2.58.0) [64bit] from main bucket
Loading azure-cli-2.58.0-x64.msi from cache
Checking hash of azure-cli-2.58.0-x64.msi ... ok.
Extracting azure-cli-2.58.0-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\martin.dolezal\scoop\apps\azure-cli\2.58.0\azure-cli-2.58.0-x64.msi.
Log file:
  ~\scoop\apps\azure-cli\2.58.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller...

Too long filename? During the extraction the folder models is being populated by a lot of .pyc file but then something fails (the error log one?) and they are deleted, so access to that folder seems to be ok, maybe the path is too long or something.

msi.log:

=== Logging started: 18.03.2024  10:26:35 ===
Error 1304. Error writing to file: C:\Users\martin.dolezal\scoop\apps\azure-cli\2.58.0\_tmp\SourceDir\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\dla\vendored_sdks\azure_mgmt_datalake_analytics\catalog\models\data_lake_analytics_catalog_secret_create_or_update_parameters.pyc. Verify that you have access to that directory.
=== Logging stopped: 18.03.2024  10:26:56 ===

**Comment by alixmacdonald10** [comment]
I had the same issue and fixed it by installing lessmsi, setting it in the scoop config and then installing azure-cli.

```
scoop install lessmsi
scoop config use_lessmsi true
scoop uninstall azure-cli
scoop install azure-cli --no-cache
```
