### ISSUE TITLE
MSYS2: Persistent on these files.

### ISSUE THREAD

**Issue by indrakaw** [ScoopInstaller/Main#563]
If possible, would you please included these files as persistent?
- mingw32.ini
- mingw64.ini
- msys2.ini

These file are launcher configuration and hasn't been modified since 2016. I don't think there will be further changes.

Normally, I symlinks them all from home dir.

**Comment by ghostArch** [comment]
**lol.** does this not work in scoop?

this change, **whenever it gets included**, will make msys2 installed via scoop a little more usable. Not implying that msys2 works currently. I still use it the regular way. No package manager hassles of any sort for me.

I would recommend everyone to not use msys2 by installing it using scoop. Its better to just get it from https://www.msys2.org/  and follow the instructions on the same page, without any customization at all. Unless you want more problems in your life.
----
**peace out**
_ghostArch_

**Comment by ghostArch** [comment]
if your files under msys2 are in `/home/raj` (msys2 style path format) 

the persistence may depend on how the paths will be handled, I'm not sure what is actually wrong.

for persistence for files in msys2's `/home` directory, see https://github.com/ScoopInstaller/Main/blob/master/bucket/php.json#L21-L27, replace `cli` with `home`. and same for `/home/raj` so no need to worry about your user's configurations for bash, zsh, etc. though
----
**peace out**
_ghostArch_
