### ISSUE TITLE
How to install old version of python3 like python 3.7.0

### ISSUE THREAD

**Issue by dakehero** [ScoopInstaller/Main#564]
I have to use python 3.7, how to choose version of apps?

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/wiki/FAQ#can-i-install-multiple-versions-of-a-specific-app-with-scoop

![image](https://user-images.githubusercontent.com/13260377/68653640-7520b880-052c-11ea-9942-5e0939623b06.png)
