### ISSUE TITLE
[Bug]: zstd v1.5.6 fails to install

### ISSUE THREAD

**Issue by Kosette** [ScoopInstaller/Main#5658]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

zstd/main

### Expected/Current Behaviour

Installation failed due to a change in the package structure.

I have checked the last three package versions and their structure is different. The structure of the packages as follows:

zstd-v1.5.6-win64.zip latest
```
__zstd-v1.5.6-win64.zip 
  |__ zstd-v1.5.6-win64.zip (a zip in zip, don't know why)
     |___ zstd-v1.5.6-win64 (folder)
         |__ zstd.exe
         |__ other contents
```
zstd-v1.5.5-win64.zip
```
__ zstd-v1.5.5-win64.zip
  |___ zstd-v1.5.5-win64 (folder)
      |__ zstd.exe
      |__ other contents
```
zstd-v1.5.4-win64.zip
```
__zstd-v1.5.4-win64.zip (no folder) 
  |__ zstd.exe
  |__ other contents
```

I don't know if there will be a next time, maybe this issue should be reported to facebook/zstd, but I'm not sure.

### Steps to Reproduce

```console
`scoop install zstd` or `scoop update zstd`
```

### Possible Solution

i'm not sure.🤔

### Scoop and Buckets Version

```console
v0.3.1
```

### Scoop Config

```console
not related
```

### PowerShell Version

```console
not related
```

**Comment by Arteiimis** [comment]
same

**Comment by YDX-2147483647** [comment]
Similar issues in previous versions:

- v1.5.1 #3115
- v1.5.2 #3221
- v1.5.5 #4630 #4631 #4632

Maybe we should fix zstd instead?
