### ISSUE TITLE
7zip@23.01: decompress error

### ISSUE THREAD

**Issue by khalomsky** [ScoopInstaller/Main#5659]
Hi.
When I click System Check, couple of things are installed, but during the NodeJs is being installed, the error occured.

message is--------------------------------------------------------------------------
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing '7zip' (23.01) [64bit] from main bucket
Loading 7z2301-x64.msi from cache.
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\yyang\scoop\apps\7zip\23.01\7z2301-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error

**Comment by khalomsky** [comment]
and the msi.log context is

=== Logging started: 2024-03-28  7:22:06 ===
Error 1401. Could not create key: Software\Microsoft\Windows\CurrentVersion\Installer\Managed\S-1-5-21-1547161642-1004336348-725345543-247094.  System error 5.  Verify that you have sufficient access to that key, or contact your support personnel.
=== Logging stopped: 2024-03-28  7:22:09 ===

**Comment by HUMORCE** [comment]
#5572
