### ISSUE TITLE
[Request]: yt-dlp-nightly

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Main#5667]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

yt-dlp-nightly

### Description

 yt-dlp nightly builds 

### Homepage

https://github.com/yt-dlp/yt-dlp

### Download Link(s)

https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.03.29.232706/yt-dlp.exe

### Some Indication of Popularity/Repute

https://github.com/yt-dlp/yt-dlp

**Comment by aliesbelik** [comment]
Nightly builds belong to [Versions](https://github.com/ScoopInstaller/Versions) bucket.
