### ISSUE TITLE
ffmpeg@7.0: download via aria2 failed

### ISSUE THREAD

**Issue by H3T-Shah** [ScoopInstaller/Main#5686]
The whole error msg:

Updating 'ffmpeg' (6.1.1 -> 7.0)
Downloading new version
Starting download with aria2 ...
Download: 04/07 20:31:35 [ERROR] CUID#12 - Download aborted. URI=https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: 04/07 20:31:35 [ERROR] CUID#8 - Download aborted. URI=https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-fDownload: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: 04/07 20:31:35 [ERROR] CUID#10 - Download aborted. URI=https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: 04/07 20:31:35 [ERROR] CUID#11 - Download aborted. URI=https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: 04/07 20:31:35 [ERROR] CUID#14 - Download aborted. URI=https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 89cc1c|ERR |   189KiB/s|D:/Program Files/Scoop/cache/ffmpeg#7.0#https_www.gyan.dev_ffmpeg_builds_packages_ffmpeg-7.0-full_build.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.0-full_build.7z
    referer=https://www.gyan.dev/ffmpeg/builds/packages/
    dir=D:\Program Files\Scoop\cache
    out=ffmpeg#7.0#https_www.gyan.dev_ffmpeg_builds_packages_ffmpeg-7.0-full_build.7z

ERROR & 'D:\Program Files\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Program Files\Scoop\cache\ffmpeg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=5184 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ffmpeg%407.0%3a+download+via+aria2+failed

It must have been the package it's trying to download is not present their...

**Comment by H3T-Shah** [comment]
it's not abt geo restrictions, it about the pacakge not being where it should be!!!!!!!!!!!!!!!!!

**Comment by niheaven** [comment]
According to error messages, it's a typical network error.

**Comment by H3T-Shah** [comment]
I clearly know that, but this has happened earlier while installing Okular,
the link was not working coz they had changed it out, here something
similar happened, their website was down for some moments and thus this
error occured.


I got to know that later after posting this issue😅
