### ISSUE TITLE
Can redis update the version?

### ISSUE THREAD

**Issue by qiaoqiao888** [ScoopInstaller/Main#571]
Can redis update the version?

**Comment by linsui** [comment]
> This project is no longer being actively maintained. If you are looking for a Windows version of Redis, you may want to check out Memurai. Please note that Microsoft is not officially endorsing this product in any way.

https://github.com/microsoftarchive/redis

**Comment by qiaoqiao888** [comment]
https://github.com/antirez/redis 
Not available?

**Comment by linsui** [comment]
Is there a binary?

**Comment by qiaoqiao888** [comment]
Not very clear~ 
Can you check it out?
https://github.com/antirez/redis

**Comment by linsui** [comment]
> Redis can be compiled and used on Linux, OSX, OpenBSD, NetBSD, FreeBSD. We support big endian and little endian architectures, and both 32 bit and 64 bit systems.

Looks like it's not available on Windows.

**Comment by qiaoqiao888** [comment]
Thank you, understand.
