### ISSUE TITLE
7zip@23.01: decompress error

### ISSUE THREAD

**Issue by samforrest730** [ScoopInstaller/Main#5722]
PS C:\Users\HP> scoop install git
WARN  Purging previous failed installation of 7zip.
ERROR '7zip' isn't installed correctly.
Removing older version (23.01).
ERROR Couldn't remove '~\scoop\apps\7zip\23.01'; it may be in use.
Installing '7zip' (23.01) [64bit] from 'main' bucket
Loading 7z2301-x64.msi from cache
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\HP\scoop\apps\7zip\23.01\7z2301-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error
PS C:\Users\HP> https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error : 无法将“https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error”项识别为 cmdlet、函
数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01% ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (https://github....ecompress+error:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by niheaven** [comment]
Try again or use `scoop config use_lessmsi true` and try again.
