### ISSUE TITLE
7zip@23.01: decompress error

### ISSUE THREAD

**Issue by coolgamee** [ScoopInstaller/Main#5725]
WARN  Purging previous failed installation of 7zip.
ERROR '7zip' isn't installed correctly.
Removing older version (23.01).
'7zip' was uninstalled.
Installing '7zip' (23.01) [64bit] from 'main' bucket
Loading 7z2301-x64.msi from cache
Checking hash of 7z2301-x64.msi ... ok.
Extracting 7z2301-x64.msi ... ERROR Exit code was 1639!
Failed to extract files from C:\Users\Francois Destroo\scoop\apps\7zip\23.01\7z2301-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4023.01%3a+decompress+error

**Comment by tpguy825** [comment]
Try using the fix in this comment: https://github.com/ScoopInstaller/Main/issues/5588#issuecomment-1991502147
