### ISSUE TITLE
cygwin@2.932: hash check failed

### ISSUE THREAD

**Issue by wilt00** [ScoopInstaller/Main#5766]
Updating 'cygwin' (2.931 -> 2.932)
Downloading new version
setup-x86_64.exe (1.3 MB) [=======================================================================================] 100%
Checking hash of setup-x86_64.exe ... ERROR Hash check failed!
App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    9aeacdcf8ff71e2d1a1f9b4685eac12c4de4bb312d44ddac2c7b226f5952bfde
Actual:      e7815d360ab098fdd1f03f10f43f363c73a632e8866e304c72573cf1e6a0dec8

**Comment by thakyZ** [comment]
Weirdly enough, I got this exact same issue, however the only difference is the actual and expected hashes are flipped.
