### ISSUE TITLE
[Bug]: charm-gum@0.14.0 needs `extract_dir`

### ISSUE THREAD

**Issue by YDX-2147483647** [ScoopInstaller/Main#5781]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

charm-gum

### Expected/Current Behaviour

charm-gum@0.14.0 cannot be installed. It used to be.

### Steps to Reproduce

```console
PS> scoop install charm-gum
…
Extracting gum_0.14.0_Windows_x86_64.zip ... done.
Linking ~\scoop\apps\charm-gum\current => ~\scoop\apps\charm-gum\0.14.0
Creating shim for 'gum'.
Line |
 783 |              $bin = (Get-Command $target).Source
     |                      ~~~~~~~~~~~~~~~~~~~
     | The term 'gum.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
Can't shim 'gum.exe': File doesn't exist.
```

### Possible Solution

#5780

### Scoop and Buckets Version

```console
N/A
```

### Scoop Config

```console
N/A
```

### PowerShell Version

```console
N/A
```

**Comment by YDX-2147483647** [comment]
Hi @aviv-julienjehannet !
This is the issue, not the PR, and the PR has been verified. Let’s just wait for maintainers.

**Comment by aviv-julienjehannet** [comment]
My bad. Sorry for that and thanks for the fix.
