### ISSUE TITLE
[Request]: imagemagick install/upgrade issues

### ISSUE THREAD

**Issue by G4nda1f** [ScoopInstaller/Main#5791]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

main/imagemagick

### Description

Attempting to install/upgrade via scoop results in error stating URL is invalid

### Homepage

https://imagemagick.org/

### Download Link(s)

https://imagemagick.org/script/download.php

### Some Indication of Popularity/Repute

Scoop site shows 1517 stars for imagemagick

**Comment by G4nda1f** [comment]
Output from my attempts to upgrade/install:

C:\Users\mark>scoop install imagemagick
Installing 'imagemagick' (7.1.1-31) [64bit] from 'main' bucket
The remote server returned an error: (404) Not Found.
URL https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-31-Q16-HDRI-x64-dll.exe is not valid

C:\Users\mark>scoop install main/imagemagick
WARN  Purging previous failed installation of imagemagick.
ERROR 'imagemagick' isn't installed correctly.
Removing older version (7.1.1-31).
'imagemagick' was uninstalled.
Installing 'imagemagick' (7.1.1-31) [64bit] from 'main' bucket
The remote server returned an error: (404) Not Found.
URL https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-31-Q16-HDRI-x64-dll.exe is not valid

C:\Users\mark>

**Comment by G4nda1f** [comment]
Was able to get it to install by forcing a version (i.e. scoop install main/imagemagick@7.1.1.-32).  So this issue is probably overkill which I guess will be resolved through the normal update process.  Just for a neophyte like I am, this can certainly be a showstopper.

**Comment by fenhl** [comment]
I am unable to work around this issue using `scoop install main/imagemagick@7.1.1-32`. Maybe this should be reopened?

**Comment by G4nda1f** [comment]
fenhl, I'm just a beginner user of scoop so I don't really know how it works so my theories here may not be completely accurate (or accurate at all).  But from my observation, this seems to be an issue that crops up for me with imagemagick particularly.  It seems like the imagemagic site itself changes their versions and this somehow doesn't immediately get communicated with scoop so scoop apparently is always playing catchup (again, I may be completely wrong, I really don't know how this works).

But here might be a better solution for you.  Go to the ImageMagick site (the scoop site does show the site URL in their imagemagick entry).  Go to the download section and check the current version.  Then try running the command specifically referring to that current version.  At this time, it's now up to 7.1.1.33 so: `scoop install main/imagemagick@7.1.1-33`
