### ISSUE TITLE
vim@8.1.2318: download via aria2 failed

### ISSUE THREAD

**Issue by CircleFaith** [ScoopInstaller/Main#582]
Download: 11/18 23:53:08 [ERROR] CUID#8 - Download aborted. URI=https://github.com/vim/vim-win32-installer/releases/download/v8.1.2318/gvim_8.1.2318_x64.zip
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is not valid in its context.
Download: [#a6af3a 0B/0B CN:0 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: a6af3a|ERR |       0B/s|C:/Users/QianWei/scoop/cache/vim#8.1.2318#https_github.com_vim_vim-win32-installer_releases_download_v8.1.2318_gvim_8.1.2318_x64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://github.com/vim/vim-win32-installer/releases/download/v8.1.2318/gvim_8.1.2318_x64.zip
    referer=https://github.com/vim/vim-win32-installer/releases/download/v8.1.2318/
    dir=C:\Users\QianWei\scoop\cache
    out=vim#8.1.2318#https_github.com_vim_vim-win32-installer_releases_download_v8.1.2318_gvim_8.1.2318_x64.zip

ERROR & 'C:\Users\QianWei\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\QianWei\scoop\cache\vim.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8780 --continue

**Comment by Ash258** [comment]
`Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred.`

![A](https://i.imgur.com/W5Kvwa2.png)
