### ISSUE TITLE
[Request]: dirx - The DIR command, extended

### ISSUE THREAD

**Issue by amreus** [ScoopInstaller/Main#5822]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [ ] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

dirx

### Description

The DIR command, extended

### Homepage

https://github.com/chrisant996/dirx/

### Download Link(s)

https://github.com/chrisant996/dirx/releases

### Some Indication of Popularity/Repute

So `dirx` isn't popular based on forks or stars.  However I do think it belongs in the `Main` repo  because its similarity by design to the builtin `dir` command that has been part of DOS and Windows forever. From its github page, `dirx` is designed "so that most command line options from the CMD dir command work the same, to make DirX mostly a drop-in replacement for dir."

If there is disagreement, I will move to the Extras repo.

**Comment by amreus** [comment]
Will re-submit at a later date.  The manifest in currently in my personal bucket: https://github.com/amreus/bucket

**Comment by chrisant996** [comment]
I'm the maintainer of [dirx](https://github.com/chrisant996/dirx), and someone recently asked me to add dirx to scoop (chrisant996/dirx#10).

I've made an app manifest with autoupdate and tested it (including testing the autoupdate).

I'll submit a pull request in a few minutes.

**Comment by chrisant996** [comment]
@z-Fng huh? Why was this closed issue from a year ago re-commented on and closed as not planned? It already happened a year ago. This smells like shenanigans or AI malfunction.

**Comment by z-Fng** [comment]
> This smells like shenanigans or AI malfunction.

Neither. I simply closed a PR that should have been closed a year ago, provided the context in a comment (https://github.com/ScoopInstaller/Main/pull/6870#issuecomment-5473643453), and changed the linked issue from 'completed' to 'not planned' to reflect its actual status.

**Comment by chrisant996** [comment]
Ohhh, ok, thanks 🤣

I thought it was already closed, because there was a history entry saying it had been closed 🤷🏻‍♂️
