### ISSUE TITLE
azure-cli@2.60.0: decompress error

### ISSUE THREAD

**Issue by aaryannnair** [ScoopInstaller/Main#5832]
Extracting azure-cli-2.60.0-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\AaryanNair\scoop\apps\azure-cli\2.60.0\azure-cli-2.60.0-x64.msi.
Log file:
  ~\scoop\apps\azure-cli\2.60.0\msi.log

**Comment by eagleeyetom** [comment]
Same happens with AWS. Reverting to 7-zip@23.0.1 fixed the issue. At least for me.
