### ISSUE TITLE
7zip@24.05: decompress error

### ISSUE THREAD

**Issue by tordenflesk** [ScoopInstaller/Main#5840]
See this issue:

https://github.com/ScoopInstaller/Scoop/issues/5975

**Comment by 0x0003** [comment]
Update from within privileged powershell session.
The error is caused because your user doesn't have write permissions in %windir%\Temp

**Comment by tordenflesk** [comment]
> Update from within privileged powershell session. The error is caused because your user doesn't have write permissions in %windir%\Temp

1. My account has always been member of the Administrators group
2. I've always had %TEMP% and %TMP% set to C:\temp. I've double-checked that I have write-permissions and tested creating files in both %temp% and %windir%\Temp
