### ISSUE TITLE
[Bug]: git (2.45.1) [32bit]: 'bin\sh.exe': File doesn't exist.

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Main#5848]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

git

### Expected/Current Behaviour

Updating 'git' (2.44.0 -> 2.45.1)
Downloading new version
Loading PortableGit-2.45.1-32-bit.7z.exe from cache
Checking hash of PortableGit-2.45.1-32-bit.7z.exe ... ok.
Uninstalling 'git' (2.44.0)
Unlinking ~\scoop\apps\git\current
Installing 'git' (2.45.1) [32bit] from 'main' bucket
Loading PortableGit-2.45.1-32-bit.7z.exe from cache
Extracting dl.7z ... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.45.1
Creating shim for 'sh'.
Get-Command: C:\Users\<user>\scoop\apps\scoop\current\lib\install.ps1:783
Line |
 783 |              $bin = (Get-Command $target).Source
     |                      ~~~~~~~~~~~~~~~~~~~
     | The term 'bin\sh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.
Can't shim 'bin\sh.exe': File doesn't exist.

### Steps to Reproduce

```console
scoop update git
```

### Possible Solution

fix manisfest

### Scoop and Buckets Version

```console
λ scoop --version
Current Scoop version:
d337bb1f (HEAD -> master, tag: v0.4.2, origin/master, origin/HEAD) chore(release): Bump to version 0.4.2 (#5964)

'main' bucket:
ee1aa02f1 (HEAD -> master, origin/master, origin/HEAD) sqlpage: Update to version 0.21.0

'extras' bucket:
9818a1045 (HEAD -> master) Merge branch 'master' of https://github.com/ScoopInstaller/Extras

'versions' bucket:
8eb0c56ec (HEAD -> master, origin/master, origin/HEAD) swift-nightly: Update to version 20240519.2

'nonportable' bucket:
3c890956 (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.160

'java' bucket:
b37d4acc (HEAD -> master, origin/master, origin/HEAD) liberica11-lite-jdk: Update to version 11.0.23-12

'scoop-aoks' bucket:
d174634 (HEAD -> master, origin/master, origin/HEAD) lakeFS-aoks: Update to version 1.24.0
```

### Scoop Config

```console
λ scoop config

alias                : @{update-all=scoop-update-all; cache-show-all=scoop-cache-show-all; cache-rm-all=scoop-cache-rm-all; cleanup-all=scoop-cleanup-all;
                       list-all=scoop-list-all; info-all=scoop-info-all; search-info=scoop-search-info; bucket-origin=scoop-bucket-origin}
aria2-enabled        : False
debug                : True
aria2                : False
last_update          : 19.05.2024 20:37:12
use_external_7zip    : True
default_architecture : arm64
scoop_branch         : master
scoop_repo           : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
λ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by AntonOks** [comment]
same applies for 'bin\bash'... as it seems, there is no more `bin` in the 32bit exe, whereas the files and directories are as expected in the `tar.bz2` artifacts :|

**Comment by HUMORCE** [comment]
Fixed upstream issue.
