### ISSUE TITLE
[Request]: android-sdk-platform-tools

### ISSUE THREAD

**Issue by Initsnow** [ScoopInstaller/Main#5880]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

sdk-platform-tools

### Description

Android SDK Platform-Tools is a component for the Android SDK. It includes tools that interface with the Android platform, primarily adb and fastboot. Although adb is required for Android app development, app developers will normally just use the copy Studio installs. This download is useful if you want to use adb directly from the command-line and don't have Studio installed. 

### Homepage

https://developer.android.com/tools/releases/platform-tools

### Download Link(s)

https://developer.android.com/tools/releases/platform-tools

### Some Indication of Popularity/Repute

Android SDK Platform-Tools

**Comment by HUMORCE** [comment]
`main/adb`, but `main/android-clt` is suggested for android related tools.
