### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by ubranch** [ScoopInstaller/Main#5918]
Signature detected: Inno Setup Setup Data (6.3.0)                                                       This is not directly supported, but i'll try to unpack it as version 5602                               ; Version detected: 6300                                                                                Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by zhangchaoza** [comment]
du #5941

**Comment by fightingcat** [comment]
> > du #5941
> 
> So? You've mentioned it in every question related to this problem, which is actually still unresolved.
> 
> 👏🎖️

I found a solution here: [by @ubranch in ](https://github.com/ScoopInstaller/Extras/issues/13444#issuecomment-2213509434_)
```
scoop uninstall innounp
scoop bucket add versions
scoop install versions/innounp-unicode
```
