### ISSUE TITLE
7zip@24.07: decompress error

### ISSUE THREAD

**Issue by CyanSyd** [ScoopInstaller/Main#5937]
scoop install twilio
WARN  Purging previous failed installation of 7zip.
ERROR '7zip' isn't installed correctly.
Removing older version (24.07).
'7zip' was uninstalled.
Installing '7zip' (24.07) [64bit] from 'main' bucket
Loading 7z2407-x64.msi from cache
Checking hash of 7z2407-x64.msi ... ok.
Extracting 7z2407-x64.msi ... ERROR Exit code was 1632!
Failed to extract files from ...\scoop\apps\7zip\24.07\7z2407-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.07\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4024.07%3a+decompress+error

**Comment by niheaven** [comment]
Run `scoop config USE_LESSMSI true` and try again.
