### ISSUE TITLE
ollama@0.1.45: decompress error

### ISSUE THREAD

**Issue by Dementore711** [ScoopInstaller/Main#5941]
`C:\Users\****>scoop update *
ollama: 0.1.42 -> 0.1.45
Updating one outdated app:
Updating 'ollama' (0.1.42 -> 0.1.45)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: a9cf6e|OK  |   6.7MiB/s|E:/Scoop/cache/ollama#0.1.45#https_github.com_ollama_ollama_releases_download_v0.1.45_OllamaSetup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of OllamaSetup.exe ... ok.
Uninstalling 'ollama' (0.1.42)
Installing 'ollama' (0.1.45) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from E:\Scoop\apps\ollama\0.1.45\OllamaSetup.exe.
Log file:
  E:\Scoop\apps\ollama\0.1.45\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.45%3a+decompress+error`

<---------------- innounp.log ---------------->

`Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
`

**Comment by zhangchaoza** [comment]
Relates to ScoopInstaller/Extras#13444
