### ISSUE TITLE
ollama@0.1.48: decompress error

### ISSUE THREAD

**Issue by rmprr** [ScoopInstaller/Main#5977]
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by KateGrim** [comment]
Same issue - 
Console:
Installing 'ollama' (0.1.48) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from D:\Programs\Scoop\apps\ollama\0.1.48\OllamaSetup.exe.
Log file:
  D:\Programs\Scoop\apps\ollama\0.1.48\innounp.log
Log:
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by KateGrim** [comment]
#5941
