### ISSUE TITLE
dvc@3.51.2: decompress error

### ISSUE THREAD

**Issue by tan-wei** [ScoopInstaller/Main#5999]
*C:\ProgramData\scoop\apps\dvc\3.51.2\innounp.log*:
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by tan-wei** [comment]
Thanks, it works. So the issue could be closed?

**Comment by tan-wei** [comment]
Seems `dvc` requires a new version of `innounp`.

**Comment by tan-wei** [comment]
> > Thanks, it works. So the issue could be closed?
> 
> this was a temporary solution

Got it. So leave it open until it is solved finally. Thanks.

**Comment by aaron-meyers** [comment]
This is a dupe though of #5994 which I opened a little earlier

**Comment by tan-wei** [comment]
OK. Since it is duplicated, so I close this one right now.
