### ISSUE TITLE
dvc@3.51.2: hash check failed

### ISSUE THREAD

**Issue by W1M0R** [ScoopInstaller/Main#6010]
Checking hash of dvc-3.51.2.exe ... ERROR Hash check failed!
App:         main/dvc
URL:         https://s3-us-east-2.amazonaws.com/dvc-public/dvc-pkgs/exe/dvc-3.51.2.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    f28b6b0198ac81de2f1aab483969a283320e0c48a1d07b5be2053f546c60a34a
Actual:      562949cf809b868c5858547a169e885e39bf08176a6bf6bb61c7ea8eba434aa0

**Comment by W1M0R** [comment]
This is a duplicate of #5993

**Comment by aaron-meyers** [comment]
Actually it seems that the package has been updated *again*, without bumping the version number. Asked in the dvc discord what's going on, seems unusual.
