### ISSUE TITLE
7zip@24.07: decompress error

### ISSUE THREAD

**Issue by Detet** [ScoopInstaller/Main#6016]
(the shell is starship if wondering) reporting issue with updating 7zip / installing it. First tried to update, then tried uninstall and reinstall, still same error.

❯ scoop install 7zip
Installing '7zip' (24.07) [64bit] from 'main' bucket
Loading 7z2407-x64.msi from cache
Checking hash of 7z2407-x64.msi ... ok.
Extracting 7z2407-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Detet\scoop\apps\7zip\24.07\7z2407-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.07\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4024.07%3a+decompress+error

~

**Comment by HUMORCE** [comment]
#5572
