### ISSUE TITLE
[Bug]: R installed by scoop is not visible to Rstudio

### ISSUE THREAD

**Issue by biocyberman** [ScoopInstaller/Main#6022]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

r

### Expected/Current Behaviour

I can't select the R version that I installed with scoop to use with Rstudio. All the version that I installed manually are visible to Rstudio.

![image](https://github.com/user-attachments/assets/c10f9d6a-d00d-4e62-9478-806256954694)

### Steps to Reproduce

```console
PS> scoop install r
# Probably also install Rstudio
PS> scoop install rstudio
# Open Rstudio, go to menu: "Tools > Global Options > General > Basic> R Sessions > Change R Version (see the screenshot)
```

### Possible Solution

Possibly something to do with registry of R in Windows that Rstudio are searching for. 

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
716b6db3 (HEAD -> master, tag: v0.5.0, origin/master, origin/HEAD) chore(release): Bump to version 0.5.0 (#6035)

'main' bucket:
16288f3d9 (HEAD -> master, origin/master, origin/HEAD) nixpacks: Update to version 1.24.6

'extras' bucket:
9e6684eb2 (HEAD -> master, origin/master, origin/HEAD) tabby: Update to version 1.0.210

'versions' bucket:
17f449574 (HEAD -> master, origin/master, origin/HEAD) swift-nightly: Update to version 20240716.0

'KnotUntied_scoop-fonts' bucket:
f2f9e18b (HEAD -> master, origin/master, origin/HEAD) juliamono: Update to version 0.056

'r-bucket' bucket:
ff176451 (HEAD -> master, origin/master, origin/HEAD) Updating hashes (Automated by Github Actions)
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_repo                              scoop_branch
-----------                       ----------                              ------------
2024-07-16T13:46:17.2262715+02:00 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.4648
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4648
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

Rstudio

**Comment by biocyberman** [comment]
Click "Browse .." and navigate to the R version installed scoop actually set R for Rstudio to that version. So, for this context, the problem is solved.

**Comment by mattsigal** [comment]
Just stumbled onto this thread after finding a similar issue (even selecting the path manually doesn't help -- RStudio always crashes). 

I did find a solution though -- you just need to make a symbolic link in PowerShell (with admin privileges): `New-Item -ItemType SymbolicLink -Path "C:\Program Files\r" -Target "C:\Users\<username>\scoop\apps\r"`

So long as RStudio sees something where it expects it to be, it is happy. The other happy outcome is it will see the "latestversion" installation of R, so theoretically should auto-update when R changes to a new version.
