### ISSUE TITLE
ollama@0.2.8: decompress error

### ISSUE THREAD

**Issue by trulliandloeb** [ScoopInstaller/Main#6045]
ERROR Exit code was 1!
Failed to extract files from D:\scoop\apps\ollama\0.2.8\OllamaSetup.exe.
Log file:
  D:\scoop\apps\ollama\0.2.8\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.2.8%3a+decompress+error

**Comment by niheaven** [comment]
`scoop install versions/innounp-unicode` and try again.
