### ISSUE TITLE
[Request]: npcap

### ISSUE THREAD

**Issue by bt4ibwem8** [ScoopInstaller/Main#6050]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

npcap

### Description

Nmap Project's Windows packet capture and transmission library

### Homepage

https://npcap.com/

### Download Link(s)

https://npcap.com/dist/npcap-1.79.exe#/npcap_setup.exe

### Some Indication of Popularity/Repute

almost 3k stars on Github

**Comment by leumasme** [comment]
See https://github.com/ScoopInstaller/Main/pull/6051#issuecomment-2247762167
Not portable, not silent and needs admin to install

**Comment by bt4ibwem8** [comment]
closed because it probably belongs to nonportable bucket
