### ISSUE TITLE
ollama@0.3.2: decompress error

### ISSUE THREAD

**Issue by eet-eet** [ScoopInstaller/Main#6065]
# error
```
WARN  Purging previous failed installation of ollama.
ERROR 'ollama' isn't installed correctly.
Removing older version (0.3.2).
'ollama' was uninstalled.
Installing 'ollama' (0.3.2) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from D:\Scoop\apps\ollama\0.3.2\OllamaSetup.exe.
Log file:
  D:\Scoop\apps\ollama\0.3.2\innounp.log
```
# innounp.log
`Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.
`

**Comment by niheaven** [comment]
`scoop install versions/innounp-unicode` and then try again.

**Comment by niceEli** [comment]
> `scoop install versions/innounp-unicode` and then try again.

is it possible to make versions/innounp-unicode a dependancy or no
