### ISSUE TITLE
ollama@0.3.3: decompress error

### ISSUE THREAD

**Issue by BLACKNOTES** [ScoopInstaller/Main#6080]
Installing 'ollama' (0.3.3) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\BlackNote\scoop\apps\ollama\0.3.3\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.3.3\innounp.log

i get this error when i try to install ollama on windows 11 23H2.

**Comment by niheaven** [comment]
`scoop install versions/innounp-unicode` and try again.
