### ISSUE TITLE
ffmpeg@7.0.2: decompress error

### ISSUE THREAD

**Issue by Ungotable** [ScoopInstaller/Main#6099]
PS C:\Users\user> scoop install fzf ffmpeg mpv
WARN  Purging previous failed installation of ffmpeg.
ERROR 'ffmpeg' isn't installed correctly.
Removing older version (7.0.2).
'ffmpeg' was uninstalled.
Installing 'ffmpeg' (7.0.2) [64bit] from 'main' bucket
Loading ffmpeg-7.0.2-full_build.7z from cache
Checking hash of ffmpeg-7.0.2-full_build.7z ... ok.
Extracting ffmpeg-7.0.2-full_build.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\user\scoop\apps\scoop\current\lib\decompress.ps1:109 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\user\scoop\apps\ffmpeg\7.0.2\ffmpeg-7.0.2-full_build.7z.
Log file:
  ~\scoop\apps\ffmpeg\7.0.2\7zip.log

**Comment by HUMORCE** [comment]
Try install or update 7zip first.
