### ISSUE TITLE
Ollama install error

### ISSUE THREAD

**Issue by csy100** [ScoopInstaller/Main#6104]
![image](https://github.com/user-attachments/assets/5a7038f4-ce8e-43c6-9c77-3df8002ffce9)

And this is the innounp.log: 
`Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.`

By the way: my computer is Windows 11, and i used the Powershell to run it.

**Comment by Yuelioi** [comment]
scoop install versions/innounp-unicode and try again.
