### ISSUE TITLE
[Bug]: nginx -p $env:NGINX_HOME command unresponsive after Scoop installation

### ISSUE THREAD

**Issue by yyj961010** [ScoopInstaller/Main#6106]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

nginx

### Expected Behavior:
After installing Nginx via Scoop, the command nginx -p $env:NGINX_HOME should initialize Nginx using the specified path as the prefix for relative paths in the configuration.
### Current Behavior:
When executing nginx -p $env:NGINX_HOME, the command appears to hang indefinitely with no response or output. The Nginx process does not start, and no error messages are displayed.

### Steps to Reproduce

```console
PowerShell 7.4.4
PS C:\Users\11795> scoop install main/nginx
Installing 'nginx' (1.27.1) [64bit] from 'main' bucket
nginx-1.27.1.zip (2.0 MB) [===================================================================================] 100%
Checking hash of nginx-1.27.1.zip ... ok.
Extracting nginx-1.27.1.zip ... done.
Linking ~\scoop\apps\nginx\current => ~\scoop\apps\nginx\1.27.1
Creating shim for 'nginx'.
Persisting conf
Persisting html
Persisting logs
Persisting temp
'nginx' (1.27.1) was installed successfully!
Notes
-----
To use the correct configuration run 'nginx -p "$env:NGINX_HOME"' or 'nginx -p "%NGINX_HOME%"'
PS C:\Users\11795> nginx -p "$env:NGINX_HOME"
```

### I also tried using nginx -p with an absolute path, but it still doesn't work.

![image](https://github.com/user-attachments/assets/14a59ad1-dfe7-497f-bb4b-41b60de21e5f)

### Scoop and Buckets Version

```console
PowerShell 7.4.4
PS C:\Users\11795> scoop --version
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
c178ef321 (HEAD -> master, origin/master, origin/HEAD) lefthook: Update to version 1.7.13

'extras' bucket:
23d30e61a (HEAD -> master, origin/master, origin/HEAD) explorerplusplus@1.4.0: Make it portable (#13664)
```

### Scoop Config

```console
PS C:\Users\11795> scoop config

last_update        scoop_repo                              scoop_branch
-----------        ----------                              ------------
2024/8/16 20:20:35 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS C:\Users\11795> $psVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by niheaven** [comment]
nginx -p $env:NGINX_HOME

Wrong `"` in the note.

**Comment by yyj961010** [comment]
> nginx -p $env:NGINX_HOME
> 
> Wrong `"` in the note.

### I tried again, but it still doesn't work

![image](https://github.com/user-attachments/assets/890d3873-de96-4656-bca2-6716862c4656)

**Comment by HUMORCE** [comment]
> When executing nginx -p $env:NGINX_HOME, the command appears to hang indefinitely with no response or output. The Nginx process does not start, 

Cannot reproduce.

> and no error messages are displayed.

This seems to be the expected behavior of the program.


```
~
❯ cd (scoop prefix nginx)
apps\nginx\current
❯ echo 'https://github.com/ScoopInstaller/Main/issues/6106' > .\html\scoop.txt
apps\nginx\current
❯ nginx -p "$env:NGINX_HOME" &

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      Job3            BackgroundJob   Running       True            localhost            nginx -p "$env:NGINX_HOM…

apps\nginx\current
✦ ❯ curl 127.0.0.1/scoop.txt
https://github.com/ScoopInstaller/Main/issues/6106
apps\nginx\current
✦ ❯ cat .\logs\access.log
127.0.0.1 - - [27/Aug/2024:08:24:53 +0800] "GET /scoop.txt HTTP/1.1" 200 52 "-" "curl/8.7.1"
apps\nginx\current
✦ ❯ stop-job 3
apps\nginx\current
❯ curl 127.0.0.1/scoop.txt
curl: (7) Failed to connect to 127.0.0.1 port 80 after 2037 ms: Couldn't connect to server
```

**Comment by yyj961010** [comment]
I want to set nginx's --prefix, otherwise I have to go to the \scoop\apps\nginx\current directory to execute it every time.
I tried running nginx -p "$env:NGINX_HOME" but it doesn't work.
When I use nginx -V to print the configuration information, I can see that --prefix is always empty.

![i1](https://github.com/user-attachments/assets/fa72fd2a-069f-4647-964e-6b3c41f6f41b)

When I'm not in the \scoop\apps\nginx\current directory, executing nginx -t or nginx -s reload commands results in an error.

![i2](https://github.com/user-attachments/assets/fb4a7efa-ed90-47fe-b1f3-8e9e2ce7ccb4)

**Comment by HUMORCE** [comment]
You should run `nginx -p "$env:NGINX_HOME" -t`, `nginx -p "$env:NGINX_HOME" -s reload`, etc.

```
~
❯ nginx -p "$env:NGINX_HOME" &

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      Job3            BackgroundJob   Running       True            localhost            nginx -p "$env:NGINX_HOM…

~
✦ ❯ nginx -p "$env:NGINX_HOME" -t
nginx: the configuration file C:\Users\humorce\scoop\apps\nginx\current/conf/nginx.conf syntax is ok
nginx: configuration file C:\Users\humorce\scoop\apps\nginx\current/conf/nginx.conf test is successful
~
✦ ❯ nginx -p "$env:NGINX_HOME" -s reload
```

> When I use nginx -V to print the configuration information, I can see that --prefix is always empty.

It's the build configure arguments of the pre-built binary, you cannot change it.
