### ISSUE TITLE
cmder-full@1.3.13: hash check failed

### ISSUE THREAD

**Issue by caowenwei** [ScoopInstaller/Main#611]
PS C:\WINDOWS\system32> scoop update *
cmder-full: 1.3.12 -> 1.3.13
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'cmder-full' (1.3.12 -> 1.3.13)
Downloading new version
Loading cmder.7z from cache.
Checking hash of cmder.7z ... ERROR Hash check failed!
App:         main/cmder-full
URL:         https://github.com/cmderdev/cmder/releases/download/1.3.13/cmder.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    11846f850dc27a7ba770e50a35879e85a6a9451ad4b14ff5120bd5593c140ff9
Actual:      c6963662dfb1b3af311a3bbe480625dea194995fd2980e1c217c41b86668f569

**Comment by Ash258** [comment]
Installed it 5 minutes ago without problem and repeatede download is same.

`scoop cache rm cmder-full; scoop uninstall cmder-full; scoop install cmder-full`

![image](https://user-images.githubusercontent.com/13260377/69523644-b5d4f480-0f64-11ea-8b0f-1ed06aa4b146.png)

**Comment by caowenwei** [comment]
Thanks. Tried it again and now it works. Downloading this in China. You know, everything is different behind the gfw.
