### ISSUE TITLE
ollama@0.3.6: decompress error

### ISSUE THREAD

**Issue by JaydonZhao** [ScoopInstaller/Main#6111]
WARN  Purging previous failed installation of ollama.
ERROR 'ollama' isn't installed correctly.
Removing older version (0.3.6).
'ollama' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'ollama' (0.3.6) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Jaydon\scoop\apps\ollama\0.3.6\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.3.6\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.3.6%3a+decompress+error

**Comment by Yuelioi** [comment]
scoop install versions/innounp-unicode and try again.
