### ISSUE TITLE
ollama@0.3.6: decompress error

### ISSUE THREAD

**Issue by zagwi** [ScoopInstaller/Main#6130]
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Duplicates #6065.

**Comment by zagwi** [comment]
scoop install versions/innounp-unicode
