### ISSUE TITLE
deno@0.25.0: hash check failed

### ISSUE THREAD

**Issue by dev-nicolaos** [ScoopInstaller/Main#614]
scoop install deno
Installing 'deno' (0.25.0) [64bit]
Downloading https://github.com/denoland/deno/releases/download/v0.25.0/deno_win_x64.zip (-1 B)...

Checking hash of deno_win_x64.zip ... ERROR Hash check failed!
App:         main/deno
URL:         https://github.com/denoland/deno/releases/download/v0.25.0/deno_win_x64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    c762b0e404e402be2df816fd8dfa01b23430a3b94ffd5c53a858e49764ac076a
Actual:      9edc15cc04b2475723f072862400eb414f2b7fdc91e4691280d1b59cb1fdadc9

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=deno%400.25.0%3a+hash+check+failed

**Comment by Ash258** [comment]
Cannot reproduce.

Based on the size of file you have some proxy/network related issue,

**Comment by dev-nicolaos** [comment]
Checked on a different/machine and network, appears to work, so it's a "doesn't work on my machine" bug.
