### ISSUE TITLE
tesseract-languages@41.0: decompress error (cannot create symbolic link, Windows 11)

### ISSUE THREAD

**Issue by niun** [ScoopInstaller/Main#6144]
When installing the package `tesseract-languages` on Windows 11 I get

> ERROR: Cannot create symbolic link : A required privilege is not held by the client

Here is my shell session (Git bash, but PowerShell is basically the same):

```
username@machine MINGW64 ~
$ scoop install tesseract-languages
WARN  Purging previous failed installation of tesseract-languages.
ERROR 'tesseract-languages' isn't installed correctly.
Removing older version (4.1.0).
'tesseract-languages' was uninstalled.
Installing 'tesseract-languages' (4.1.0) [64bit] from 'main' bucket
Loading 4.1.0.zip from cache
Checking hash of 4.1.0.zip ... ok.
Loading equ.traineddata from cache
Checking hash of equ.traineddata ... ok.
Loading snum.traineddata from cache
Checking hash of snum.traineddata ... ok.
Extracting 4.1.0.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\username\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip.
Log file:
  ~\scoop\apps\tesseract-languages\4.1.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=tesseract-languages%404.1.0%3a+decompress+error

username@machine MINGW64 ~
$ cat ~/scoop/apps/tesseract-languages/4.1.0/7zip.log

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 351046435 bytes (335 MiB)

Extracting archive: C:\Users\username\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
--
Path = C:\Users\username\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip
Type = zip
Physical Size = 351046435
Comment = 65727574dfcd264acbb0c3e07860e4e9e9b22185


Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\username\scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\configs
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\username\scoop\apps\tesseract-languages\4.1.0\tessdata_fast-4.1.0\pdf.ttf
```

**Comment by niun** [comment]
> You reported version `41.0`, but the latest available version is `4.1.0`.

this was a copy-paste error with the provided report link, sorry. All console outputs show Version 4.1.0

**Comment by lightyou** [comment]
@niun  did you solve your issue? I have the same exact problem.

**Comment by niun** [comment]
@lightyou A workaround in Windows 11 is to enable "Developer Mode" (Start > Settings > System > For Developers). You can disable the developer mode again after installing the package.

I just noticed that if you manage to successfully install the package, the install script awards you with the note:

> * Known issue:
> - ERROR: Cannot create symbolic link: https://github.com/ScoopInstaller/Main/issues/4874

It would be nice to get a link to issue #4874 when the error happens, not after you already managed to fix it...

**Comment by lightyou** [comment]
Thank you for your answer. Yes I found the ticket with these info, but not so easily as your answer seems to be the only one indexed by Google...

My point is I can't have admin permission on my work PC. So the solution is not applicable to me. I managed by extracting the zip directly in tesseract directory!
