### ISSUE TITLE
[Bug]: stlink has a newer version and is not updating/updated

### ISSUE THREAD

**Issue by Gaweringo** [ScoopInstaller/Main#6164]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

stlink

### Expected/Current Behaviour

The newest version of the program on GitHub is 1.8.0, but the scoop package is currently still on 1.7.0 because name of the zip file has changed from `stlink-1.7.0-x86_64-w64-mingw32.zip` to `stlink-1.8.0-win32.zip`.

### Steps to Reproduce

```console
PS> scoop install stlink
Installing 'stlink' (1.7.0) [64bit] from 'main' bucket
Loading stlink-1.7.0-x86_64-w64-mingw32.zip from cache
Checking hash of stlink-1.7.0-x86_64-w64-mingw32.zip ... ok.
Extracting stlink-1.7.0-x86_64-w64-mingw32.zip ... done.
Linking ~\scoop\apps\stlink\current => ~\scoop\apps\stlink\1.7.0
Adding ~\scoop\apps\stlink\current\bin to your path.
'stlink' (1.7.0) was installed successfully!
```

### Possible Solution

Change the download/update url of the stlink package

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
34274dd6d (HEAD -> master, origin/master, origin/HEAD) ruby: Update to version 3.3.5-1

'extras' bucket:
fb44b10f0 (HEAD -> master, origin/master, origin/HEAD) ytdlp-interface: Update to version 2.14.1

'versions' bucket:
f548d6565 (HEAD -> master, origin/master, origin/HEAD) vlc-nightly: Update to version 20240905

'nerd-fonts' bucket:
537ea9f4 (HEAD -> master, origin/master, origin/HEAD) LXGWNeoXiHei: Update to version 1.202

'nonportable' bucket:
cfe25f59 (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.212

'java' bucket:
12fb891d (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.432-3.0.202409030846
```

### Scoop Config

```console
PS>  scoop config

last_update         debug scoop_branch scoop_repo
-----------         ----- ------------ ----------
05/09/2024 13:37:48  True master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by taylorh140** [comment]
Version 1.8.0 doesn't seem to function. I'd rather have 1.7.0 or at least keep it in the manifest so we can download the previous version.

**Comment by Gaweringo** [comment]
The binaries for the release have been updated to solve this issue: https://github.com/stlink-org/stlink/issues/1364#issuecomment-2282736184, so if you reinstall stlink, the libusb problem should be gone.

But there is another issue with the scoop installation for 1.8.0 which should be solved by this PR: https://github.com/stlink-org/stlink/pull/1421
Which is that the `C:/Program Files (x86)/stlink/config/chips` directory does not exist and is hardcoded in stlink.
So with the current version you need to:
- create the  `C:/Program Files (x86)/stlink/config/chips` directory
- And copy the .chip files from the release .zip into that directory

So the change to the current manifest would need to include a change, that automatically copies the .chip files to the correct location, but the libusb issue should be resolved when reinstalling.

**Comment by taylorh140** [comment]
changes to C:/Program Files require admin privilege don't they?

**Comment by Gaweringo** [comment]
Yes, I think they do.
