### ISSUE TITLE
7zip@24.08: decompress error

### ISSUE THREAD

**Issue by heavyhitter69** [ScoopInstaller/Main#6166]
ERROR Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
Failed to extract files from C:\Users\sarko\scoop\apps\7zip\24.08\7z2408-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.08\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4024.08%3a+decompress+error

**Comment by jack-mil** [comment]
Could not replicate on Windows 10 with `scoop install 7zip@24.08`
Can you make sure the download completed successfully? 
Clear your scoop cache and try to install again (`scoop cache rm *`)
Supply the `msi.log` if error persists.
