### ISSUE TITLE
pnpm@9.11.0: hash check failed (malware flag)

### ISSUE THREAD

**Issue by leandro-costa** [ScoopInstaller/Main#6208]
Updating 'pnpm' (9.5.0 -> 9.11.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8a8a45|OK  |   2.6MiB/s|D:/scoop/cache/pnpm#9.11.0#8b9d50c.exe
Download: Status Legend:
Download: (OK):download completed.
Get-Content : Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado.
No D:\scoop\apps\scoop\current\lib\core.ps1:1379 caractere:16
+         return Get-Content $file -Encoding byte -TotalCount 8
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (D:\scoop\cache\pnpm#9.11.0#8b9d50c.exe:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand

Checking hash of pnpm-win-x64.exe ... Get-FileHash : O arquivo 'D:\scoop\cache\pnpm#9.11.0#8b9d50c.exe' não pode ser lido: Não foi possível concluir a operação com êxito porque o arquivo
contém um vírus ou software possivelmente indesejado.
No D:\scoop\apps\scoop\current\lib\install.ps1:634 caractere:16
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (D:\scoop\cache\pnpm#9.11.0#8b9d50c.exe:PSObject) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FileReadError,Get-FileHash

Não é possível chamar um método em uma expressão de valor nulo.
No D:\scoop\apps\scoop\current\lib\install.ps1:634 caractere:5
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado.
No D:\scoop\apps\scoop\current\lib\core.ps1:1379 caractere:16
+         return Get-Content $file -Encoding byte -TotalCount 8
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (D:\scoop\cache\pnpm#9.11.0#8b9d50c.exe:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand

ERROR Hash check failed!
App:         main/pnpm
URL:         https://github.com/pnpm/pnpm/releases/download/v9.11.0/pnpm-win-x64.exe#/pnpm.exe
First bytes:
Expected:    7a5dee642cb0111df9ea3b2b91d36a89225401cc27eddeb115e53710c18ada9d
Actual:

**Comment by glektarssza** [comment]
See pnpm/pnpm#8562
