### ISSUE TITLE
update ollama failed

### ISSUE THREAD

**Issue by ChenXu-Huang** [ScoopInstaller/Main#6216]
Installing 'ollama' (0.3.12) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Extracting OllamaSetup.exe ... done.
Linking D:\Users\ChenXu\Scoop\apps\ollama\current => D:\Users\ChenXu\Scoop\apps\ollama\0.3.12
Creating shim for 'ollama'.
Get-Command: D:\Users\ChenXu\Scoop\apps\scoop\current\lib\install.ps1:757
Line |
 757 |              $bin = (Get-Command $target).Source
     |                      ~~~~~~~~~~~~~~~~~~~
     | The term 'ollama.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Can't shim 'ollama.exe': File doesn't exist.

**Comment by HUMORCE** [comment]
Install `extras/ollama-full` instead.
