### ISSUE TITLE
heroku-cli@9.3.1: decompress error

### ISSUE THREAD

**Issue by ctoth** [ScoopInstaller/Main#6268]
Installing 'heroku-cli' (9.3.1) [64bit] from 'main' bucket
Loading heroku-v9.3.1-5cf442b-win32-x64.tar.xz from cache
Checking hash of heroku-v9.3.1-5cf442b-win32-x64.tar.xz ... ok.
Extracting heroku-v9.3.1-5cf442b-win32-x64.tar.xz ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\Q\scoop\apps\scoop\current\lib\decompress.ps1:109 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\Q\scoop\apps\heroku-cli\9.3.1\dl.xz.
Log file:
  ~\scoop\apps\heroku-cli\9.3.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=heroku-cli%409.3.1%3a+decompress+error

**Comment by HUMORCE** [comment]
```
PS C:\Users\WDAGUtilityAccount> scoop install heroku-cli
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing '7zip' (24.08) [64bit] from 'main' bucket
Loading 7z2408-x64.msi from cache
Checking hash of 7z2408-x64.msi ... ok.
Extracting 7z2408-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\24.08
Creating shim for '7z'.
Creating shim for '7zFM'.
Making C:\Users\WDAGUtilityAccount\scoop\shims\7zfm.exe a GUI binary.
Creating shim for '7zG'.
Making C:\Users\WDAGUtilityAccount\scoop\shims\7zg.exe a GUI binary.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...done.
'7zip' (24.08) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running:
"C:\Users\WDAGUtilityAccount\scoop\apps\7zip\current\install-context.reg"
Installing 'heroku-cli' (9.3.2) [64bit] from 'main' bucket
Loading heroku-v9.3.2-0bce57c-win32-x64.tar.xz from cache
Checking hash of heroku-v9.3.2-0bce57c-win32-x64.tar.xz ... ok.
Extracting heroku-v9.3.2-0bce57c-win32-x64.tar.xz ... done.
Running pre_install script...done.
Linking ~\scoop\apps\heroku-cli\current => ~\scoop\apps\heroku-cli\9.3.2
Creating shim for 'heroku'.
'heroku-cli' (9.3.2) was installed successfully!
```

Please update 7zip to latest version then retry.

**Comment by ctoth** [comment]
This worked, thanks!
