### ISSUE TITLE
[Request]: pixi

### ISSUE THREAD

**Issue by T145** [ScoopInstaller/Main#6290]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

pixi

### Description

Pixi is a cross-platform, multi-language package manager and workflow tool built on the foundation of the conda ecosystem. It provides developers with an exceptional experience similar to popular package managers like cargo or yarn, but for any language.

### Homepage

https://github.com/prefix-dev/pixi

### Download Link(s)

https://github.com/prefix-dev/pixi/releases

### Some Indication of Popularity/Repute

3k stars on GitHub

**Comment by aliesbelik** [comment]
Duplicates #5773.
