### ISSUE TITLE
rtools@4.4.6335.6327: decompress error

### ISSUE THREAD

**Issue by hanhuangv587** [ScoopInstaller/Main#6291]
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.

**Comment by Rnreck** [comment]
the same issue ,hope to be fixed

**Comment by rorric** [comment]
Replacing the version of innounp resolves this error (and similar errors). Try:

`scoop install versions/innounp-unicode`

Before installing/updating rtools.

**Comment by Rnreck** [comment]
> Replacing the version of innounp resolves this error (and similar errors). Try:
> 
> `scoop install versions/innounp-unicode`
> 
> Before installing/updating rtools.

try ,and it worked
