### ISSUE TITLE
openssl@3.4.0: decompress error

### ISSUE THREAD

**Issue by jerquiaga** [ScoopInstaller/Main#6294]
❯ scoop update *
openssl: 3.3.2 -> 3.4.0
Updating one outdated app:
Updating 'openssl' (3.3.2 -> 3.4.0)
Downloading new version
Loading Win64ARMOpenSSL-3_4_0.exe from cache
Checking hash of Win64ARMOpenSSL-3_4_0.exe ... ok.
Uninstalling 'openssl' (3.3.2)
Installing 'openssl' (3.4.0) [arm64] from 'main' bucket
Loading Win64ARMOpenSSL-3_4_0.exe from cache
Extracting Win64ARMOpenSSL-3_4_0.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\jerquiag\scoop\apps\openssl\3.4.0\Win64ARMOpenSSL-3_4_0.exe.
Log file:
  ~\scoop\apps\openssl\3.4.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=openssl%403.4.0%3a+decompress+error

**Comment by aliesbelik** [comment]
With **scoop v0.5.0+**:

```
scoop bucket add versions
scoop install versions/innounp-unicode
```

and retry update/installation.

**Comment by jerquiaga** [comment]
Thanks, that worked.
