### ISSUE TITLE
gcc@13.2.0: decompress error

### ISSUE THREAD

**Issue by AhmadRamezAli** [ScoopInstaller/Main#6298]
PS C:\Users\hp> scoop install gcc
Installing '7zip' (24.08) [64bit] from 'main' bucket
7z2408-x64.msi (1.9 MB) [=====================================================================================] 100%
Checking hash of 7z2408-x64.msi ... ok.
Extracting 7z2408-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\24.08
Creating shim for '7z'.
Creating shim for '7zFM'.
Making C:\Users\hp\scoop\shims\7zfm.exe a GUI binary.
Creating shim for '7zG'.
Making C:\Users\hp\scoop\shims\7zg.exe a GUI binary.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...done.
'7zip' (24.08) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\hp\scoop\apps\7zip\current\install-context.reg"
Installing 'gcc' (13.2.0) [64bit] from 'main' bucket
components-19.0.7z (58.6 MB) [================================================================================] 100%
Checking hash of components-19.0.7z ... ok.
Extracting components-19.0.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\hp\scoop\apps\gcc\13.2.0\components-19.0.7z.
Log file:
  ~\scoop\apps\gcc\13.2.0\7zip.log

**Comment by Daviteusz** [comment]
```
Installing 'gcc' (13.2.0) [64bit] from 'main' bucket
Starting download with aria2 ...
Download: [#305d94 0B/0B CN:1 DL:0B]
Download: [#305d94 55MiB/58MiB(94%) CN:2 DL:7.9MiB]
Download: [#305d94 57MiB/58MiB(98%) CN:1 DL:7.2MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 305d94|OK  |   6.8MiB/s|C:/Users/Mateusz/scoop/cache/gcc#13.2.0#9fc1852.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of components-19.0.7z ... ok.
Extracting components-19.0.7z ... done.
Running pre_install script...done.
Linking ~\scoop\apps\gcc\current => ~\scoop\apps\gcc\13.2.0
Adding ~\scoop\apps\gcc\current\bin to your path.
'gcc' (13.2.0) was installed successfully!
```
