### ISSUE TITLE
luajit@2.1.1725453128-1: decompress error

### ISSUE THREAD

**Issue by xudyang1** [ScoopInstaller/Main#6315]
`$ scoop install luajit`
Installing 'luajit' (2.1.1725453128-1) [64bit] from 'main' bucket
mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst (482.2 KB) [=========================================================] 100%
Checking hash of mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst ... ok.
Extracting mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst ... ERROR Exit code was 2!
Failed to extract files from C:\Users\user_name\scoop\apps\luajit\2.1.1725453128-1\mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst.
Log file:
  ~\scoop\apps\luajit\2.1.1725453128-1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=luajit%402.1.1725453128-1%3a+decompress+error

- log file:
```text

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 493749 bytes (483 KiB)

Extracting archive: C:\Users\user_name\scoop\apps\luajit\2.1.1725453128-1\mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\user_name\scoop\apps\luajit\2.1.1725453128-1\mingw-w64-x86_64-luajit-2.1.1725453128-1-any.pkg.tar.zst
Cannot open the file as archive
```

**Comment by Daviteusz** [comment]
```
scoop update 7zip
```

**Comment by xudyang1** [comment]
> ```
> scoop update 7zip
> ```

Thanks, that fixes the issue. Closed
