### ISSUE TITLE
[Bug]: Podman v5.3.0, when installed via `scoop`, produces an error when running `podman machine start`

### ISSUE THREAD

**Issue by glektarssza** [ScoopInstaller/Main#6327]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

podman

### Expected Behaviour ###

* Running `podman machine start` should produce no errors.

### Actual Behaviour ###

* Running `podman machine start` produces the following error(s):

```
API forwarding for Docker API clients is not available due to the following startup failures.
The system cannot find the path specified.
```

* Running `podman machine stop` produces the following error(s):

```
Could not stop API forwarding service (win-sshproxy.exe): open C:\Users\<username>\.local\share\containers\podman\machine\wsl\podman-machine-default\win-sshproxy.tid: The system cannot find the file specified.
```

### Steps to Reproduce

```console
1. Install Podman v5.3.0 via `scoop`.
2. Run `podman machine init` to create a default Podman machine.
3. Start the default Podman machine by running `podman machine start`.
4. Observe results of the command.
5. Stop the default Podman machine by running `podman machine stop`.
6. Observe the results of the command.
```

### Possible Solution

No known solutions or suggestions but this issue comes from a previous investigation/ticket filed with the Podman team. See containers/podman#24557.

### Scoop and Buckets Version

```console
859d1db5 chore(release): Bump to version 0.5.2 (#6080)
d3f48fe6d sqlcl: Update to version 24.3.1.311.1631
7aa89cba7 ungoogled-chromium: Update to version 130.0.6723.116-1.1
9c778239b vim-tux: Update to version 9.1.0847_20241109
4f5e5934 SarasaGothic: Update to version 1.0.23
45be4d23 temurin17-nightly-jre: Update to version 17.0.14-2.0.ea
730b366f6 vita3k: Update to version 3686-15a9e61
```

### Scoop Config

```console
last_update            scoop_repo                              scoop_branch
-----------            ----------                              ------------
2024-11-09 12:01:27 PM https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by gebinic** [comment]
I have the same problem and the error has disappeared after downgrading to podman 5.2.0 with `scoop install podman@5.2.0`.

**Comment by cpfeiffer** [comment]
podman 5.2.0 was compiled with go 1.27.7, while podman 5.3.0 was compiled with go 1.23.3, so maybe https://github.com/golang/go/issues/63703 is the cause (c.f. https://github.com/containers/podman/blob/d3e7d4e2175d858d53d9142b0125fd38fc0dd83c/pkg/machine/machine_windows.go#L254 when trying to look up win-sshproxy.exe.

**Comment by jeffrson** [comment]
@cpfeiffer nice find!
Indeed, if podman.exe is executed directly from "$env:USERPROFILE\scoop\apps\podman\5.3.0" it works.

**Comment by l0rd** [comment]
Setting the env `$env:GODEBUG="winsymlink=0"` when running Podman is sufficient to make it work as before. I have added some details [in this comment](https://github.com/containers/podman/issues/24557#issuecomment-2490996716), in particular the difference in behavior if using WSL or HyperV.
