### ISSUE TITLE
perl@5.30.1.1 : ERROR Hash check failed!

### ISSUE THREAD

**Issue by kal247** [ScoopInstaller/Main#635]
```
Checking hash of strawberry-perl-5.30.1.1-64bit-portable.zip ... ERROR Hash check failed!
App:         main/perl
URL:         http://strawberryperl.com/download/5.30.1.1/strawberry-perl-5.30.1.1-64bit-portable.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    906bd55f35b4b51c60496479bd45212a91666a7b
Actual:      63af38f7c84e7f117bb4ab1a3e0fc161939a0581
```

With Powershell, I get the same actual value :

```
PS C:\...\scoop\apps\perl\5.30.1.1> Get-FileHash strawberry-perl-5.30.1.1-64bit-portable.zip -Algorithm SHA1 | Format-List

Algorithm : SHA1
Hash      : 63AF38F7C84E7F117BB4AB1A3E0FC161939A0581
Path      : C:\Users\nnluethiju\scoop\apps\perl\5.30.1.1\strawberry-perl-5.30.1.1-64bit-portable.zip
```

But when I compute SHA-1 on the same file with two other tools (on macOS), I get the value expected by _perl.json_ :

```
$ openssl sha1 <strawberry-perl-5.30.1.1-64bit-portable.zip 
906bd55f35b4b51c60496479bd45212a91666a7b
$ shasum strawberry-perl-5.30.1.1-64bit-portable.zip 
906bd55f35b4b51c60496479bd45212a91666a7b  strawberry-perl-5.30.1.1-64bit-portable.zip
```

Does anybody knows what's going on?

**Comment by issaclin32** [comment]
I cannot reproduce the problem. (It works fine on my computer). 
Please try install it again.

**Comment by issaclin32** [comment]
Did you (1) copy the file from your Windows PC to your Mac, or did you (2) just download the file again on your Mac?

If (2) is the case, then file on your Windows PC is broken, but the file on you Mac is correct. You can try clear the cached file with `scoop cache rm perl`.

**Comment by kal247** [comment]
You were right : the PC file was broken.
No issue then.
Thanks
