### ISSUE TITLE
git-filter-repo@2.47.0: decompress error

### ISSUE THREAD

**Issue by themaryanjuguna** [ScoopInstaller/Main#6363]

**Comment by 14MBD4** [comment]
Try `sudo scoop install git-filter-repo`

**Comment by themaryanjuguna** [comment]
> Try `sudo scoop install git-filter-repo`

Thank you for your response. I was able to resolve the issue by uninstalling git-filter-repo via Scoop. I then manually located the ZIP folder, unzipped it, found the installer file nested within subfolders, and moved it to the root directory. After that, running scoop install git-filter-repo worked successfully. It seems the multiple subfolder structure was causing the issue.
