### ISSUE TITLE
python@3.8.0: decompress error

### ISSUE THREAD

**Issue by limxc** [ScoopInstaller/Main#642]
Installing 'python' (3.8.0) [64bit]
Loading python-3.8.0-amd64.exe from cache
Checking hash of python-3.8.0-amd64.exe ... ok.
Running installer script...
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\Users\xxx\scoop\apps\scoop\current\lib\decompress.ps1:281 字符: 38
+ ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\xxx\scoop\apps\python\3.8.0\python-3.8.0-amd64.exe.
Log file:
  ~\scoop\apps\python\3.8.0\dark.log

Log file @~\scoop\apps\python\3.8.0\dark.log   not found

**Comment by h404bi** [comment]
Please install dark before installing python.
`scoop install dark python`

**Comment by niheaven** [comment]
`dark` dependency is added by https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/depends.ps1#L70-L71, and installed by https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/depends.ps1#L5-L7

Maybe need check for install status of dependencies.
