### ISSUE TITLE
python@3.8.0: decompress error

### ISSUE THREAD

**Issue by 462548187** [ScoopInstaller/Main#656]
PS C:\Users\Administrator> scoop install python
Installing 'python' (3.8.0) [64bit]
Loading python-3.8.0-amd64.exe from cache
Checking hash of python-3.8.0-amd64.exe ... ok.
Running installer script...
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\Users\Administrator\scoop\apps\scoop\current\lib\decompress.ps1:281 字符: 38
+ ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\Administrator\scoop\apps\python\3.8.0\python-3.8.0-amd64.exe.
Log file:
  ~\scoop\apps\python\3.8.0\dark.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.8.0%3a+decompress+error

**Comment by niheaven** [comment]
See #642, will be fixed in https://github.com/lukesampson/scoop/pull/3784
