### ISSUE TITLE
conan@1.21.0: decompress error

### ISSUE THREAD

**Issue by mirko-ex24** [ScoopInstaller/Main#664]
C:\Users\esdwfik\tools\px>scoop install conan
Installing 'conan' (1.21.0) [64bit]
Loading conan-win-64_1_21_0.exe from cache
Checking hash of conan-win-64_1_21_0.exe ... ok.
Extracting conan-win-64_1_21_0.exe ... Invoke-ExternalCommand : Das Argument für den Parameter "FilePath" kann nicht überprüft werden. Das Argument ist NULL oder leer. Geben Sie ein Argument an, das nicht NULL oder leer ist, und führen Sie den Befehl erneut aus.
In C:\Users\esdwfik\scoop\apps\scoop\current\lib\decompress.ps1:192 Zeichen:38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\Users\esdwfik\scoop\apps\conan\1.21.0\conan-win-64_1_21_0.exe.
Log file:
  ~\scoop\apps\conan\1.21.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=conan%401.21.0%3a+decompress+error

**Comment by Ash258** [comment]
Your innounp installation is broken or missing.

`scoop install innounp; scoop uninstall conan; scoop install conan`

lukesampson/scoop#3784
