### ISSUE TITLE
azure-cli@2.0.78: hash check failed

### ISSUE THREAD

**Issue by embraces0ul** [ScoopInstaller/Main#682]
Installing 'azure-cli' (2.0.78) [64bit]
azure-cli-2.0.78.msi (49.3 MB) [============================================================================================================] 100%
Checking hash of azure-cli-2.0.78.msi ... ERROR Hash check failed!
App:         main/azure-cli
URL:         https://azurecliprod.azureedge.net/msi/azure-cli-2.0.78.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    33e757c8ebcb655cb16fc5810ce2c1059363ba1266467d64d7561185328bda76
Actual:      32732453e8194d1002a6e0aa08715e4fae22c6e224ce5a6ce11b3cd6591668fe

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=azure-cli%402.0.78%3a+hash+check+failed
PS C:\Users\sunav> ^C

**Comment by dim5** [comment]
Same here.
