### ISSUE TITLE
gpg: remove portable conf file

### ISSUE THREAD

**Issue by brunovieira97** [ScoopInstaller/Main#694]
I've been trying to set some overrides to default settings on my GPG installed via Scoop. None of the methods worked, and I discovered it was due to the existence of `gpgconf.ctl` on bin.

This file is used to set the installation to portable mode. When in such mode, GPG stores all its files - keyrings, settings, etc - inside the installation directory (in this case, `scoop/apps/gpg/current`), and doesn't accept overrides through conf files and environment variables. The only way to set an override is by always calling gpg with the `--homedir` param pointing to the new dir. 

Not creating `gpgconf.ctl` would allow settings and keyrings to be safely stored anywhere on the computer by default, using config files, environment variables, instead of keeping it all on scoop's dir. I came across the below explanation when searching the [man pages](https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html#option-_002d_002dhomedir).

> To install GnuPG as a portable application under Windows, create an empty file named gpgconf.ctl in the same directory as the tool gpgconf.exe. The root of the installation is then that directory; or, if gpgconf.exe has been installed directly below a directory named bin, its parent directory. You also need to make sure that the following directories exist and are writable: ROOT/home for the GnuPG home and ROOT/usr/local/var/cache/gnupg for internal cache files.

**So, with all that in mind, here goes my question:** would the non existence of this file, and therefore, the installation of gpg as a non-portable app interfere in any way with managing its installation/update through Scoop?

Here the `pre_install` block on the manifest that would be altered, removing the `New-Item` statement on line 2:

```
"pre_install": [
        "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\gnupg-uninstall.exe.nsis\" -Force -Recurse",
        "New-Item \"$dir\\bin\\gpgconf.ctl\" -Force | Out-Null",
        "if (!(Test-Path \"$persist_dir\\home\") -and (Test-Path \"$env:Appdata\\gnupg\")) {",
        "    Write-Host -F yellow \"Copying old '$env:Appdata\\gnupg' to '$persist_dir\\home'\"",
        "    New-Item \"$dir\\home\" -ItemType Directory -Force | Out-Null",
        "    Copy-Item \"$env:Appdata\\gnupg\\*\" \"$dir\\home\" -Recurse -Force",
        "}"
    ]
```

**Comment by brunovieira97** [comment]
Looking at the manifest's history, I see that this whole portable mode setting was implemented through PR #318 not that long ago.

Didn't find any issue/discussion explaining why this was done, though.

**Comment by linsui** [comment]
> The apps that install best with Scoop are commonly called "portable" apps: i.e. compressed program files that run stand-alone when extracted and don't have side-effects like changing the registry or putting files outside the program directory.

Scoop always try to make as less as possible side-effects to the system so portable is prefered. Do you mean you don't want to store config files in scoop directory or the portable mode break some function? We can make another non-portable manifest or you can link the home directory to some other location.

**Comment by brunovieira97** [comment]
I was trying to change the default settings, with a config file stored on what I thought was the correct "home" for GPG (~/.gnupg, if I recall correctly). It wasn't working, and I came across this portable mode situation. My original plan was just to delete the .ctl file and go on with my life, but I thought it was best to understand the whole.

Since now I shall be using GPG more often (and better too), I would like the option to just keep my keyring safe in a different folder (such as a cloud folder, for example). 

I consider a non-portable manifest the best way, not needing any manual settings for each PC I want to install GPG and run customized settings.

**Comment by brunovieira97** [comment]
@linsui since you did the changes to portable mode on the original manifest, I kindly ask you to take a look at my PR on TheRandomLabs/scoop-nonportable#100.

I've never made a Scoop manifest, and even though you added the whole pre_install block on your PR, I can't say for sure if it's explicitly related to the portable mode or if it was in favor of "clean code".

Thanks!
