### ISSUE TITLE
gcc@8.1.0.0 Application Unable to Start Correctly Error (0xc000007b)

### ISSUE THREAD

**Issue by muhlpachr** [ScoopInstaller/Main#722]
type test.c
#include <stdio.h>
int main(int argc, char*[] argv)
{
  printf("Hello world!\n");
  return 0;
}

gcc test.c

pop-up cc1.exe application error:
Application Unable to Start Correctly Error (0xc000007b)
Error is logged in System events also, no further details.

Executing cc1 without arguments from scoop/app/gcc yields same error.

**Comment by h404bi** [comment]
cant reproduce in my pc.

**Comment by muhlpachr** [comment]
What should I do to provide more leads please ?
I tested MinGW-64 installation 8.1.0 x86_64 posix seh 0, it works fine.
OS Version:                10.0.18362 N/A Build 18362
System Type:               x64-based PC

**Comment by ddavness** [comment]
Can perhaps be related to this? https://stackoverflow.com/questions/50847868/compiling-c-program-with-mingw-causes-cc1-exe-fatal-error

If your windows username contains spaces (which is somewhat common to happen), then your directory path will have spaces and might be part of your issue,

**Comment by muhlpachr** [comment]
No spaces in username, my `USERPROFILE=C:\Users\michal`
I am not getting any error in cli but error in pop-up and MSW System eventlog.

**Comment by linsui** [comment]
Please try `scoop uninstall gcc; scoop install gcc`

**Comment by muhlpachr** [comment]
Shim for gcc was not created.
`scoop\apps\gcc\current\bin\gcc test.c` generates cc1.exe - System Error popup:
The code execution cannot proceed bacause libwinpthread-1.dll was not found.

```
Installing 'gcc' (8.1.0.0) [64bit]
x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z (47,1 MB) [======================================================] 100%
Checking hash of x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z ... ok.
Extracting x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z ... done.
Linking ~\scoop\apps\gcc\current => ~\scoop\apps\gcc\8.1.0.0
Creating shim for 'make'.
WARN  Overwriting shim to mingw32-make.exe installed from make
'gcc' (8.1.0.0) was installed successfully!
Notes
-----
The 64-bit version is built with Structured Exception Handling (SEH), whereas the 32-bit version is built with DWARF.
Both 64-bit and 32-bit versions use the POSIX threading model.
```
