### ISSUE TITLE
windows-terminal@0.7.3451.0 Can not run, missing VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by muhlpachr** [ScoopInstaller/Main#723]
Can not run, missing VCRUNTIME140_1.dll

**Comment by Ash258** [comment]
`scoop install vcredist2019`

**Comment by muhlpachr** [comment]
Doesn't vcredist2019 have to be in the windows-terminal app manifest in depends ?

**Comment by Ash258** [comment]
No. I will add suggest later.

**Comment by muhlpachr** [comment]
Thank you.
It seams vcredist2019 is mandatory for windows-terminal runtime, why it should be marked as optional/complementary please ?

**Comment by muhlpachr** [comment]
Thanks.
