### ISSUE TITLE
tor@0.4.2.5: download via aria2 failed

### ISSUE THREAD

**Issue by tayrayb** [ScoopInstaller/Main#730]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dist.torproject.org/torbrowser/9.0.3/tor-win64-0.4.2.5.zip
    referer=https://dist.torproject.org/torbrowser/9.0.3/
    dir=C:\Users\Tayray\scoop\cache
    out=tor#0.4.2.5#https_dist.torproject.org_torbrowser_9.0.3_tor-win64-0.4.2.5.zip

ERROR & 'C:\Users\Tayray\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Tayray\scoop\cache\tor.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn -
-enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8964 --continue

**Comment by Ash258** [comment]
08f96585485d10358b0401e31648e4f01ab0db6b
