### ISSUE TITLE
puppet-bolt@1.45.0: a decompress error

### ISSUE THREAD

**Issue by jfastnacht** [ScoopInstaller/Main#731]
Looks like the `extract_dir` makes the installation of `puppet-bolt` (https://github.com/ScoopInstaller/Main/blob/master/bucket/puppet-bolt.json) fail:

> Installing 'puppet-bolt' (1.45.0) [64bit]
Loading puppet-bolt-1.45.0-x64.msi from cache
Checking hash of puppet-bolt-1.45.0-x64.msi ... ok.
Extracting puppet-bolt-1.45.0-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\j.fastnacht\scoop\apps\puppet-bolt\1.45.0\puppet-bolt-1.45.0-x64.msi.
Log file:
  ~\scoop\apps\puppet-bolt\1.45.0\msi.log
>
> Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=puppet-bolt%401.45.0%3a+decompress+error

When I remove `extract_dir` and adjust `bin` back to the full path it's working flawlessly. I could either remove the attribute and change back the `bin` directory or fix the problem with the file extraction, but right now I have no clue what the problem is.

The temporary folder created by scoop when installing is:
> [...]\scoop\apps\puppet-bolt\1.45.0\_tmp\SourceDir\Puppet Labs\Bolt

Right now it's configured to: `"extract_dir": "Puppet Labs\\Bolt",`

Any recommendations on how to fix it except for rolling back?

**Comment by Ash258** [comment]
What is inside `~\scoop\apps\puppet-bolt\1.45.0\msi.log`?

No issue with/without lessmsi.

![image](https://user-images.githubusercontent.com/13260377/72346616-a5283b80-36d6-11ea-9e12-657b915bda8a.png)

https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation

Most probable cause

> Windows Installer is attempting to install an app that is already installed on your PC.

**Comment by jfastnacht** [comment]
Interesting, it seems that the path is too long:

> === Logging started: 14.01.2020  13:05:05 ===
Error 1304. Error writing to file: C:\Users\j.fastnacht\scoop\apps\puppet-bolt\1.45.0\_tmp\SourceDir\Puppet Labs\Bolt\lib\ruby\gems\2.5.0\gems\puppet-6.11.0\spec\fixtures\unit\pops\loaders\loaders\dependent_modules_with_metadata\modules\user\lib\puppet\functions\user\ruby_calling_puppet_init.rb.  Verify that you have access to that directory.
=== Logging stopped: 14.01.2020  13:05:59 ===

It's 261 characters, which exceeds the MAX_LENGTH by 1 and I guess that it results in the application not being able to create the file `ruby_calling_puppet_init.rb` in the sub-directory.

**Comment by Ash258** [comment]
`scoop checkup` should get you info how to enable long path

**Comment by jfastnacht** [comment]
The problem seems to be Windows 8.1, since LongPathsEnabled is, as far as I could figure out, available since Windows 10 (v160), not Win 8.1. I'm reopening this on https://github.com/lukesampson/scoop , since it's a problem with Scoop itself, not the Main bucket.
