### ISSUE TITLE
ffmpeg-nightly@20200121-fc6fde2: hash check failed

### ISSUE THREAD

**Issue by ninja85a** [ScoopInstaller/Main#746]
ffmpeg-nightly: 20200115-0dc0837 -> 20200121-fc6fde2
Updating one outdated app:
Updating 'ffmpeg-nightly' (20200115-0dc0837 -> 20200121-fc6fde2)
Downloading new version
ffmpeg-20200121-fc6fde2-win64-static.zip (66.7 MB) [==========================================================] 100%
Checking hash of ffmpeg-20200121-fc6fde2-win64-static.zip ... ERROR Hash check failed!
App:         main/ffmpeg-nightly
URL:         https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200121-fc6fde2-win64-static.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    fceb98ed294410e7ca563d078bc85384e03132026dd6c62d0785182c746bc0b2
Actual:      f1af18082f92e3c18cb270453cde3a04e78e3d04c4abadd93a6e200ab69bc7dd

**Comment by Ash258** [comment]
Newer version available
