### ISSUE TITLE
sudo unmaintained

### ISSUE THREAD

**Issue by casz** [ScoopInstaller/Main#747]
sudo does not work with powershell core. 
See 
- https://github.com/lukesampson/psutils/pull/29
- https://github.com/ScoopInstaller/Main/blob/master/bucket/sudo.json

There is a lot of dependencies using `sudo`, seems that `psutils` was last updated 2 years ago: https://github.com/lukesampson/psutils

I see a few option

- fork `psutils` into ScoopInstaller
- accept another `psutils` fork where `sudo` at least is fixed.
  - see https://github.com/lukesampson/psutils/pull/32
- switch to `gsudo` ?

**Comment by casz** [comment]
Related to https://github.com/matthewjberger/scoop-nerd-fonts/issues/48

**Comment by rasa** [comment]
I don't use psutil's sudo, and I couldn't get `psexec -h` to work reliably, so I use:
`nircmdc.exe elevate`
when I need to elevate, which always seems to work. I haven't yet tried `gsudo`, but it certainly would fix the bill.

**Comment by rasa** [comment]
I don't use psutil's sudo, and I couldn't get [`psexec -h`](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec#using-psexec) to work reliably, so I use:
[`nircmdc elevate`](https://www.nirsoft.net/utils/nircmd.html)
when I need to elevate, which always seems to work. I haven't tried [`gsudo`](https://github.com/gerardog/gsudo) yet, but it certainly would fit the bill.

**Comment by casz** [comment]
I created #751 to hopefully fix the current situation to fix pwsh.
I also created https://github.com/matthewjberger/scoop-nerd-fonts/pull/49 to clean up the dependency on sudo it's not necessary that font's need to depend on sudo.

**Comment by casz** [comment]
fixed in https://github.com/ScoopInstaller/Main/commit/5e33474356f9c911cb6d6776cf254f43891cb0c8
