### ISSUE TITLE
[Request] Add Speedtest CLI

### ISSUE THREAD

**Issue by ntcarver0** [ScoopInstaller/Main#756]
Could Speedtest CLI by Ookla be added to the Main Bucket? It can be found at:
https://www.speedtest.net/apps/cli
Thanks.

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/tree/master/bucket/speedtest-cli.json

![image](https://user-images.githubusercontent.com/13260377/73141829-a8cda200-4088-11ea-9dad-11e82f463d9f.png)
