### ISSUE TITLE
[Request] Add tmux

### ISSUE THREAD

**Issue by flickerfly** [ScoopInstaller/Main#762]
It would be nice if tmux was supported. It is the one thing I'm looking for in bash on windows at this point.

**Comment by HUMORCE** [comment]
tmux does not support non-unix like OS

**Comment by indrakaw** [comment]
You can just have on from POSIX subsystem's package manager, like Cygwin or MSYS2.

**Comment by rasa** [comment]
WSL supports tmux, too
