### ISSUE TITLE
[Request] Handle Python user base scripts directory

### ISSUE THREAD

**Issue by bryanburke** [ScoopInstaller/Main#772]
The Scoop manifest for Python ([python.json](https://github.com/ScoopInstaller/Main/blob/3a7112ebdef3ed0ab4725926a75cf72fe143558c/bucket/python.json)) does not handle the Python [user base](https://docs.python.org/3/library/site.html#site.USER_BASE) scripts directory, so CLI scripts from packages installed in user mode (`pip install --user`) are not available on the PATH. Performing [user installations](https://pip.pypa.io/en/stable/user_guide/#user-installs) of packages is considered best practice, and many packages (such as the popular [Pipenv](https://pipenv.readthedocs.io/en/latest/install/#pragmatic-installation-of-pipenv)) recommend doing them.

Two possible solutions might be:

1. Construct the user base scripts directory and add it to PATH. The path can be constructed as follows: `Join-Path -Path (Split-Path -Path (python -m site --user-site) -Parent) -ChildPath Scripts`
1. Point the [PYTHONUSERBASE](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE) environment variable to a directory within the Python install directory and persist it.

Related issue: ScoopInstaller/Versions#196

**Comment by TheRandomLabs** [comment]
A fix for this would be nice.

**Comment by Restia666Ashdoll** [comment]
User scripts directory is actually `(Split-Path -Parent (python -m site --user-site)) + "\Scripts"`

**Comment by bryanburke** [comment]
@Restia666Ashdoll The `Join-Path` call above joins the path output by `Split-Path -Path (python -m site --user-site) -Parent` and `Scripts`. It handles the OS-specific path separator (`\` on Windows) and is safer than string concatenation to build paths.

**Comment by dwettstein** [comment]
Installing Python using Scoop is already done on user-level (without `--global` flag) , so there is no need to additionally install packages using the `--user` flag.

If you still need to install packages on user-level and have them in the `PATH`, I suggest to create a PR. Paths are added to ENV using `env_add_path`.

> env_add_path: Add this directory to the user's path (or system path if --global is used). The directory is relative to the install directory and must be inside the install directory.

https://github.com/ScoopInstaller/Main/blob/e4e85d903e6ff7adfca6d4b49a03bd50835674b9/bucket/python.json#L84

**Comment by rashil2000** [comment]
Closed by #2144
