### ISSUE TITLE
add power shell core

### ISSUE THREAD

**Issue by Cologler** [ScoopInstaller/Main#78]
`powershell-core.json` can be:

``` py
{
    "version": "6.2.0",
    "architecture": {
        "32bit": {
            "url": "https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/PowerShell-6.2.0-win-x86.zip",
            "hash": "DAE9D3D2AD332A82312D2DAFA398287670FB5CBB94128C80D422E1F3679F8EB2"
        },
        "64bit": {
            "url": "https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/PowerShell-6.2.0-win-x64.zip",
            "hash": "C02AF438D3BC8DC61815110C99189A694ED161E64C64A59B49AB01D945DFC73A"
        }
    },
    "bin": "pwsh.exe"
}
```

unknown how to auto update version from https://github.com/PowerShell/PowerShell/releases

**Comment by equinox** [comment]
Hi there, there's already a pwsh manifest which you can find [here](https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json).

**Comment by Cologler** [comment]
Oh, this is hard to search.

**Comment by ratatoeey** [comment]
powershell-core would have been a better name for letting users install it.

also, powershell 7 can't be installed by `scoop install powershell-preview`
----

regards ratatoeey
