### ISSUE TITLE
nodejs@13.7.0: decompress error

### ISSUE THREAD

**Issue by wzy2006** [ScoopInstaller/Main#784]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'nodejs' (13.7.0) [64bit]
Loading node-v13.7.0-win-x64.7z from cache.
Checking hash of node-v13.7.0-win-x64.7z ... ok.
Extracting node-v13.7.0-win-x64.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The
argument is null or empty. Provide an argument that is not null or empty, and t
hen try the command again.
At C:\Users\wzy\scoop\apps\scoop\current\lib\decompress.ps1:81 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], Param
   eterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-External
   Command

Failed to extract files from C:\Users\wzy\scoop\apps\nodejs\13.7.0\node-v13.7.0-win-x64.7z.

**Comment by Ash258** [comment]
Your 7zip installation is not correct. Do you external 7zip or have you installed it via scoop?

In the first case: `scoop config 7ZIPEXTRACT_USE_EXTERNAL $true`
Second: `scoop uninstall 7zip; scoop install 7zip`

And install node again

**Comment by wzy2006** [comment]
Thanks for your help!
And I have a good idea.
Why not print an error infomation when the users install any packages?
It can help the users to fix these question easily.
