### ISSUE TITLE
python@3.8.1: decompress error

### ISSUE THREAD

**Issue by liyiliuxingyu** [ScoopInstaller/Main#786]
Installing 'python' (3.8.1) [64bit]
Loading python-3.8.1-amd64.exe from cache
Checking hash of python-3.8.1-amd64.exe ... ok.
Running installer script...
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\ProgramData\Scoop\apps\scoop\current\lib\decompress.ps1:281 字符: 38
+ ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\ProgramData\Scoop\apps\python\3.8.1\python-3.8.1-amd64.exe.
Log file:
  C:\ProgramData\Scoop\apps\python\3.8.1\dark.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.8.1%3a+decompress+error

**Comment by linsui** [comment]
`scoop uninstall dark; scoop install dark`
