### ISSUE TITLE
python@3.8.1 path error 

### ISSUE THREAD

**Issue by wzy2006** [ScoopInstaller/Main#787]
After python@3.8.1 installed,we can use python.
But we can not use the python included tools (pip).
I would like to add (Python 's path)/scripts to path.
That can make pip work in cil easily.

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/blob/892ab189ede515d748ef3ccda6bbd56dcceb30b3/bucket/python.json#L52-L55

![image](https://user-images.githubusercontent.com/13260377/73819509-fddb8780-47ef-11ea-9fc7-2ac165c9c2fa.png)

**Comment by wzy2006** [comment]
Thanks!
Is it in the repo now?

**Comment by Ash258** [comment]
Based on the blame it is there all the time.
