### ISSUE TITLE
curl@7.68.0: decompress error

### ISSUE THREAD

**Issue by trystero11** [ScoopInstaller/Main#797]
C:\Windows\System32>scoop install curl
Installing 'curl' (7.68.0) [64bit]
Loading curl-7.68.0-win64-mingw.tar.xz from cache
Checking hash of curl-7.68.0-win64-mingw.tar.xz ... ok.
Extracting curl-7.68.0-win64-mingw.tar.xz ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null
or empty, and then try the command again.
At D:\Users\trystero\scoop\apps\scoop\current\lib\decompress.ps1:81 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from D:\Users\trystero\scoop\apps\curl\7.68.0\curl-7.68.0-win64-mingw.tar.xz.
Log file:
  ~\scoop\apps\curl\7.68.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=curl%407.68.0%3a+decompress+error

**Comment by h404bi** [comment]
#784
