### ISSUE TITLE
wyam@2.2.9: Shim wyam.exe error

### ISSUE THREAD

**Issue by aadje** [ScoopInstaller/Main#809]
The installation fails on 'Can't shim 'wyam.exe': File doesn't exist.'
Wyam version 2 was updated to be used as a dotnet global tool and includes a wyam.dll file.

https://github.com/Wyamio/Wyam/releases/tag/v2.0.0
https://wyam.io/docs/usage/obtaining

I'm not sure what the appropriate fix for this should be.  

![image](https://user-images.githubusercontent.com/1208884/74548574-6512dd80-4f4e-11ea-800f-a24276c676bb.png)

**Comment by Ash258** [comment]
Two options:

- Remove manifest
- Revert it to working version and keep it as it.
	- This will make lots of users whimpering about no new version.
