### ISSUE TITLE
7zip installed via scoop doesn't have the right click menu in file explorer

### ISSUE THREAD

**Issue by superusercode** [ScoopInstaller/Main#813]
This is my primary way of using 7zip and it's really frustrating to be unable to use this. Is it possible for me to force scoop to give it permissions to do this?

**Comment by linsui** [comment]
You can enable that in 7zip options.

**Comment by superusercode** [comment]
![image](https://user-images.githubusercontent.com/60588434/74618196-bfeb3700-50fe-11ea-9f56-fb2aa124a781.png)
"Access is denied"

**Comment by linsui** [comment]
Maybe you need to run 7zip as administrator?

**Comment by superusercode** [comment]
![image](https://user-images.githubusercontent.com/60588434/74618506-1442e680-5100-11ea-99ed-46f4a6cc4cbb.png)
then I get this error when using the context menu

**Comment by superusercode** [comment]
same issue when extracting files too

**Comment by superusercode** [comment]
after restarting it seems to work fine now

**Comment by idbrii** [comment]
To summarize solution:

1. run 7zFM as admin
2. Tools > Options > 7-Zip
3. Check "Integrate 7-zip into shell context menu"
4. OK
5. Restart computer


----

If someone felt up to it, you could implement scoops semi automation via reg files:

Adapt the scoop changes to generate a .reg file from https://github.com/ScoopInstaller/Main/pull/846/files

To figure out the .reg, I'd recommend just setting up the context menu with 7z, exporting it from regedit, and inserting the variable names.

Then users need to run that reg to add to context menu.
