### ISSUE TITLE
unxutils@2007.03.01: hash check failed

### ISSUE THREAD

**Issue by s4ik4t** [ScoopInstaller/Main#819]
PS C:\WINDOWS\system32> scoop install unxutils
Installing 'unxutils' (2007.03.01) [64bit]
UnxUtils.zip (1.4 KB) [==================================================================================================================================================================] 100%
Checking hash of UnxUtils.zip ... ERROR Hash check failed!
App:         main/unxutils
URL:         https://downloads.sourceforge.net/project/unxutils/unxutils/current/UnxUtils.zip
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    b8c694072723a417194022a2ba265750eec61e15d1725e39449df1763e224b45
Actual:      c67000f2fd70be2eeec3a657f70be2e8386546f4efde457c8507f3f3c5681fc0
SourceForge.net is known for causing hash validation fails. Please try again before opening a ticket.

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=unxutils%402007.03.01%3a+hash+check+failed

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/issues/818#issuecomment-587303606

![image](https://user-images.githubusercontent.com/13260377/74710628-611ede00-5222-11ea-811a-f946818c015d.png)

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.

**Comment by s4ik4t** [comment]
Thanks!
