### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by ghjzeus** [ScoopInstaller/Main#82]
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         main/openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      bdaaca20aff145bc1d6887f2da366862ef8d96afeabd491e27baadd6877d5224

**Comment by rasa** [comment]
The hash (d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a) in the manifest (the “expected” hash above) is correct. Please try again.
