### ISSUE TITLE
python@3.8.1: decompress error

### ISSUE THREAD

**Issue by 1019588237** [ScoopInstaller/Main#824]
Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The
argument is null or empty. Provide an argument that is not null or empty, and t
hen try the command again.
At C:\Users\Administrator\scoop\apps\scoop\current\lib\decompress.ps1:281 char:
38
+ ... Status = Invoke-ExternalCommand (Get-HelperPath -Helper Dark) $ArgLis ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], Param
   eterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-External
   Command

Failed to extract files from C:\Users\Administrator\scoop\apps\python\3.8.1\pyth
on-3.8.1-amd64.exe.
Log file:
  ~\scoop\apps\python\3.8.1\dark.log

Please try again or create a new issue by using the following link and paste you
r console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.8.1%3a+decomp
ress+error

**Comment by h404bi** [comment]
#786
