### ISSUE TITLE
helm version was downgraded from 3.10.0 to 2.16.3

### ISSUE THREAD

**Issue by vorotech** [ScoopInstaller/Main#827]
Hello @r15ch13 
I noticed the helm version was downgraded here https://github.com/ScoopInstaller/Main/commit/98ea0cce9592c47ffd18dac86f6f5ac59df6924f
Was it intentionally? Do you have plans to add `helm3` instead?
Thanks

**Comment by Ash258** [comment]
It is because developers marked latest version 2 as latest instead of verison 3

**Comment by vorotech** [comment]
Obviously, helm2 and helm3 are different now. I assume its due to automation configured to watch origin repos and released versions. Would it be possible to apply (implement) filters?

**Comment by vorotech** [comment]
Honestly, I'm not sure if my suggested PR is following the scoop concepts. 
I'm fine to do `helm install helm@3.1.0` or `helm reset helm@3.1.0`

**Comment by r15ch13** [comment]
Added helm2 to versions bucket with https://github.com/ScoopInstaller/Versions/commit/9b3f9ec3f969a0e267938c832adade3c049d6396
