### ISSUE TITLE
[Request] Add byenow

### ISSUE THREAD

**Issue by devhawk** [ScoopInstaller/Main#831]
https://iobureau.com/byenow/

**Comment by devhawk** [comment]
@Ash258 I don't know how to do the hash and autoupdate stuff for scoop. Here's a basic manifest: https://gist.github.com/devhawk/401fab47962564e8728cb9b6544f7b27/raw/byenow.json

**Comment by issaclin32** [comment]
@devhawk You are missing `description` and `hash`, which does not affect installation, but are required in official buckets.

`checkver` should be written as
```
"checkver": {
    "url": "https://iobureau.com/byenow/",
    "regex": "byenow-([\\d.]+)\\.zip"
}
```
Since we are matching the regex on the homepage(https://iobureau.com/byenow/), `url` can be omitted.

```
{
    "version": "0.2",
    "description": "Utility for folder removal",
    "homepage": "https://iobureau.com/byenow/",
    "url": "https://iobureau.com/byenow/byenow-0.2.zip",
    "hash": "4d074bb0906d810bee954b329814fdffbab29cc1178367a0055fca8e0bdbdb7c",
    "architecture": {
        "32bit": {
            "extract_dir": "32-bit"
        },
        "64bit": {
            "extract_dir": "64-bit"
        }
    },
    "bin": "byenow.exe",
    "checkver": "byenow-([\\d.]+)\\.zip",
    "autoupdate": {
        "url": "https://iobureau.com/byenow/byenow-$version.zip"
    }
}

```

**Comment by devhawk** [comment]
@issaclin32 so is that manifest ready to go? I'm happy to copy and paste it into a new PR if it is.

**Comment by issaclin32** [comment]
> @issaclin32 so is that manifest ready to go? I'm happy to copy and paste it into a new PR if it is.

Yeah. It is ready to go.
