### ISSUE TITLE
python@3.8.2: download via aria2 failed

### ISSUE THREAD

**Issue by KZcheese** [ScoopInstaller/Main#852]
PS C:\Program Files\PowerShell\6> scoop update *
python: 3.8.1 -> 3.8.2
teamviewer: 15.2.2756 -> 15.3.2682
winmerge: 2.16.4 -> 2.16.6
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating 3 outdated apps:
Updating 'python' (3.8.1 -> 3.8.2)
Downloading new version
Starting download with aria2 ...
Download: 02/28 15:20:41 [ERROR] CUID#8 - Download aborted. URI=https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
Download: [#14c71d 0B/0B CN:0 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 14c71d|ERR |       0B/s|C:/Users/kevin/scoop/cache/python#3.8.2#https_www.python.org_ftp_python_3.8.2_python-3.8.2-amd64.exe
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe
    referer=https://www.python.org/ftp/python/3.8.2/
    dir=C:\Users\kevin\scoop\cache
    out=python#3.8.2#https_www.python.org_ftp_python_3.8.2_python-3.8.2-amd64.exe

ERROR & 'C:\Users\kevin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\kevin\scoop\cache\python.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/6.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=17016 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.8.2%3a+download+via+aria2+failed
PS C:\Program Files\PowerShell\6>

![image](https://user-images.githubusercontent.com/8646140/75584649-2dbc2a80-5a3e-11ea-8dac-ae6493a87475.png)

**Comment by FDUZS** [comment]
> WARN Should it cause issues, run 'scoop config aria2-enabled false' to disable it.

After running `scoop config aria2-enabled false` it should be ok.
And, from my experience, in most time it's not that fast with aria2 enabled but often causes some problems.

**Comment by Ash258** [comment]
> Network problem has occurred. cause:A socket operation was attempted to an unreachable network.

Connection got interrupted. Everything can be downloaded without any issue.
