### ISSUE TITLE
Yarn depends on Nodejs

### ISSUE THREAD

**Issue by okonomiyaki3000** [ScoopInstaller/Main#875]
If installing `yarn` prior to installing `nodejs`, you will get an error. So `yarn.json` should contain a line like:
```
   "depends": "nodejs"
```
However, it really depends on any one of `nodej`, `nodejs-lts`, or `nodejs-chakracore`. I'm not sure if the installer json format has a way to express this kind of dependency.

**Comment by Calinou** [comment]
> However, it really depends on any one of nodej, nodejs-lts, or nodejs-chakracore. I'm not sure if the installer json format has a way to express this kind of dependency.

It should be possible to do this, but this may only be possible with `suggests`, not `depends`.

**Comment by dwettstein** [comment]
https://github.com/ScoopInstaller/Main/blob/00e369c34109e11d4028f299c5f5dfef42ad5b1b/bucket/yarn.json#L6-L13
