### ISSUE TITLE
windows-terminal: Missing shell icons

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Main#882]
Installed via Windows Store (or `Add-AppxPackage windowsterminal.msixbundle`):
![20200314001356](https://user-images.githubusercontent.com/5764917/76639273-cb5c4180-6588-11ea-8590-803a908ef116.png)

Installed via Scoop (main/windows-terminal):
![20200314001414](https://user-images.githubusercontent.com/5764917/76639325-e16a0200-6588-11ea-9a1f-9f78abf5fbd7.png)

**Comment by ifethereal** [comment]
I fixed this manually by renaming the following files in `scoop\apps\windows-terminal\current\ProfileIcons\`:

>
```
%7B0caa0dad-35be-5f56-a8ff-afceeeaa6101%7D.scale-100.png
%7B0caa0dad-35be-5f56-a8ff-afceeeaa6101%7D.scale-200.png
%7B550ce7b8-d500-50ad-8a1a-c400c3262db3%7D.scale-100.png
%7B550ce7b8-d500-50ad-8a1a-c400c3262db3%7D.scale-200.png
%7B574e775e-4f2a-5b96-ac1e-a2962a402336%7D.scale-100.png
%7B574e775e-4f2a-5b96-ac1e-a2962a402336%7D.scale-200.png
%7B61c54bbd-c2c6-5271-96e7-009a87ff44bf%7D.scale-100.png
%7B61c54bbd-c2c6-5271-96e7-009a87ff44bf%7D.scale-200.png
%7B9acb9455-ca41-5af7-950f-6bca1bc9722f%7D.scale-100.png
%7B9acb9455-ca41-5af7-950f-6bca1bc9722f%7D.scale-200.png
%7Bb453ae62-4e3d-5e58-b989-0a998ec441b8%7D.scale-100.png
%7Bb453ae62-4e3d-5e58-b989-0a998ec441b8%7D.scale-200.png
```

I replaced `%7B` with `{` and `%7D` with `}`.
