### ISSUE TITLE
nodejs@13.11.0: hash check failed

### ISSUE THREAD

**Issue by holicoweve** [ScoopInstaller/Main#891]
Updating 'nodejs' (13.10.1 -> 13.11.0)
Downloading new version
node-v13.11.0-win-x64.7z (16.1 MB) [=====================================================================================>                                                            ]  59%
Checking hash of node-v13.11.0-win-x64.7z ... ERROR Hash check failed!
App:         main/nodejs
URL:         https://nodejs.org/dist/v13.11.0/node-v13.11.0-win-x64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    a3efebb357576449561d5f58a74e7d13dda7212a0d05319281ba8961bc7c2d9f
Actual:      f623617d58148794488073540922e75ebb9aab82bfd209eab4012486bdd286bb

**Comment by Ash258** [comment]
>  59%

`scoop cache rm nodejs; scoop update nodejs -f`
