### ISSUE TITLE
nodejs@13.11.0: hash check faile

### ISSUE THREAD

**Issue by KevinTechExec** [ScoopInstaller/Main#895]
scoop install nodejs
Installing 'nodejs' (13.11.0) [64bit]
node-v13.11.0-win-x64.7z (16.1 MB) [=============================>                                            ]  40%
Checking hash of node-v13.11.0-win-x64.7z ... ERROR Hash check failed!
App:         main/nodejs
URL:         https://nodejs.org/dist/v13.11.0/node-v13.11.0-win-x64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    a3efebb357576449561d5f58a74e7d13dda7212a0d05319281ba8961bc7c2d9f
Actual:      8f7d5614916880fea7be61d68ce0b03d8a487e7d3eafb2fbe9f9d7559ecc3fc3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=nodejs%4013.11.0%3a+hash+check+failed

**Comment by Ash258** [comment]
> > ] 40%

`scoop cache rm nodejs; scoop update nodejs -f`
