### ISSUE TITLE
[Request] Add Fish Shell

### ISSUE THREAD

**Issue by foisonocean** [ScoopInstaller/Main#903]
It would be awesome if I can install [fish](https://fishshell.com/) via scoop.

**Comment by piotrek-szczygiel** [comment]
I think fish is available on Windows only through Cygwin or WSL, which is out of scope of scoop.

**Comment by Calinou** [comment]
This issue can probably be closed if the package isn't natively available on Windows.

**Comment by avarun42** [comment]
Fish is available on Windows [through the MSYS2 package repository](https://packages.msys2.org/base/fish). It would be great if this version could be added to Scoop so that the entire Cygwin environment isn't needed to be installed to get Fish.
