### ISSUE TITLE
[OmniSharp] STDIO version

### ISSUE THREAD

**Issue by Priddles** [ScoopInstaller/Main#92]
OmniSharp has refactored into two separate servers: STDIO and HTTP.

Could an `omnisharp-stdio` package or similar be created?

Thanks!

**Comment by r15ch13** [comment]
[`omnisharp`](https://github.com/ScoopInstaller/Main/commit/2219889da5f66cd1bcf57888627bf5ce4f2eb3a7) is now STDIO and added [`omnisharp-http`](https://github.com/ScoopInstaller/Main/commit/605ec43c83c0d6688592ed75d3fdd31ad6745553)

**Comment by Priddles** [comment]
That was quick! Thank you!
