### ISSUE TITLE
PowerShell Core global config file

### ISSUE THREAD

**Issue by Naomi010Sentzke** [ScoopInstaller/Main#924]
PowerShell Core's global config is stored in a 'profile.ps1' file in $PSHome (%SCOOP%\apps\pwsh\current). Its not persisted.

**Comment by Naomi010Sentzke** [comment]
I tried to create this
https://gist.github.com/Naomi010Sentzke/48d6ed4aeadb562522ed338d4ee84249
Unfortunately Scoop changes "profile.ps1" to "profile.ps1.original" and persists a folder called "profile.ps1" instead.

**Comment by BlackPowerade** [comment]
```
"if (!(Test-Path \"$persist_dir\\mednafen.cfg\")) {",
"   New-Item \"$dir\\mednafen.cfg\" | Out-Null",
"}"
```
I use this snippet all the time for applications that don't come with a file that needs to be persisted, or only creates it after being run.

**Comment by Naomi010Sentzke** [comment]
@BlackPowerade It still renames "profile.ps1" to "profile.ps1.original" and persists a folder called "profile.ps1".

**Comment by BlackPowerade** [comment]
@Naomi010Sentzke Sorry, forgot to mention it doesn't work when used in `pre-install`. Place it in `installer` or `post-install`, delete the profile.ps1 folder in your persist directory and try it again.

**Comment by Ash258** [comment]
@BlackPowerade Stop confusing users and spreading clearly incorrect information.

Doing persist checks inside post-install is completely nonsense as it leads to anything.

You can do anything to `$pesist_dir` in any of the script blocks as it is defined in whole lifecycle of the manifest installation.

`post_install` is happening after the actual persisting. Which lead into the file being created as directory and leading to same problem as you had before.

Persist checks has to be done in `pre_install` or `installer.script` as done in all of the manifests everywhere in official buckets.

![image](https://user-images.githubusercontent.com/13260377/79267027-bf6de300-7e98-11ea-91d9-d5174f69b6e0.png)

**Comment by Naomi010Sentzke** [comment]
Yeah, persisting happens before post-install. Installer script has the same issue - profile.ps1 gets renamed to profile.ps1.original and a folder called profile.ps1 gets persisted.

**Comment by BlackPowerade** [comment]
@Ash258 I see. I thought `post-install` happened right after extraction, but before persisting.
Also @Naomi010Sentzke You have to change `mednafen.cfg` to `profile.ps1`.
``` 
"if (!(Test-Path \"$persist_dir\\mednafen.cfg\")) {",
            "   New-Item \"$dir\\profile.ps1\" | Out-Null",
            "}"
```

**Comment by Naomi010Sentzke** [comment]
@BlackPowerade oops. my bad.
