### ISSUE TITLE
ImageMagick does not include .dll libraries

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Main#945]
I was trying to install ImageMagick so I could run a script making use of the python wand library but unfortunately scoop installs the portable version which doesn't include the necessary .dll libraries. It would be nice if it could add the install folder to the `MAGICK_HOME ` environment variable too.

See: http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows

**Comment by tech189** [comment]
This issue isn't solved and shouldn't be closed - for now if you want more than just using the imagemagick command line tools you have to use the proper installer rather than scoop...

**Comment by rashil2000** [comment]
Hey @tech189 can you make a PR for your proposal?

**Comment by tech189** [comment]
Sure, I'll give it a go!

**Comment by tech189** [comment]
Couldn't get it to work sadly, this is my progress so far.

I modified the original imagemagick manifest to the full installers with dlls included and added the innosetup tag to extract it, plus a new environment variable. Installation works, and `magick -version` reports that the program is working and the coders for editing files are present:
```
Version: ImageMagick 7.1.0-13 Q16-HDRI x64 2021-10-29 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2019 (192930136)
```
However, when running a test command on the included logo image (in `~\scoop\apps\imagemagick\current\images`) it states it cannot find the coders. So I manually added all the registry entries that the installer uses to locate modules:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\ImageMagick\Current]
"CoderModulesPath"="C:\\Users\\$YOUR_USERNAME_HERE\\scoop\\apps\\imagemagick\\current\\modules\\coders"
"Version"="7.1.0"
"QuantumDepth"=dword:00000010
"BinPath"="C:\\Users\\$YOUR_USERNAME_HERE\\scoop\\apps\\imagemagick\\current"
"ConfigurePath"="C:\\Users\\$YOUR_USERNAME_HERE\\scoop\\apps\\imagemagick\\current"
"LibPath"="C:\\Users\\$YOUR_USERNAME_HERE\\scoop\\apps\\imagemagick\\current"
"FilterModulesPath"="C:\\Users\\$YOUR_USERNAME_HERE\\scoop\\apps\\imagemagick\\current\\modules\\filters"
```
But the test still command fails, even though the file it is looking for is present. The file has "JPEG" in lowercase "jpeg" but renaming the file makes no difference:
```
> magick identify "logo.jpg"
identify: unable to load module 'C:\Users\$YOUR_USERNAME_HERE\scoop\apps\imagemagick\current\modules\coders\IM_MOD_RL_JPEG_.dll': The specified module could not be found.
 @ error/module.c/OpenModule/1287.
identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/572.
```

For reference here is the manifest I made:
```
{
    "version": "7.1.0-13",
    "description": "Create, edit, compose, and convert 200+ of bitmap images formats.",
    "homepage": "https://imagemagick.org/",
    "license": "ImageMagick",
    "depends": "ffmpeg",
    "architecture": {
        "64bit": {
            "url": "https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-13-Q16-HDRI-x64-dll.exe",
            "hash": "c4607f68794f9e8e5ed73b1c0a295aae8e612c4b63b163e65c5f2669068b78d0"
        },
        "32bit": {
            "url": "https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-13-Q16-HDRI-x86-dll.exe",
            "hash": "477bf261a8ad6d3034e0b6f58ce7abdeb9a2c6186c9caef34e64fe9e24eafa42"
        }
    },
    "innosetup": true,
    "bin": [
        "compare.exe",
        "composite.exe",
        "conjure.exe",
        "convert.exe",
        [
            "convert.exe",
            "imconvert"
        ],
        "dcraw.exe",
        "identify.exe",
        "IMDisplay.exe",
        "magick.exe",
        "mogrify.exe",
        "montage.exe",
        "stream.exe"
    ],
    "env_set": {
        "MAGICK_HOME": "$dir",
        "MAGICK_CODER_MODULE_PATH": "$dir\\modules\\coders"
    },
    "checkver": "The current release is ImageMagick <a.*?>([\\d.p-]+)</a>",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://www.imagemagick.org/download/binaries/ImageMagick-$matchHead$matchTail-Q16-HDRI-x64-dll.exe"
            },
            "32bit": {
                "url": "https://www.imagemagick.org/download/binaries/ImageMagick-$matchHead$matchTail-Q16-HDRI-x86-dll.exe"
            }
        },
        "hash": {
            "mode": "rdf",
            "url": "https://www.imagemagick.org/download/binaries/digest.rdf"
        }
    }
}
```

Any ideas? I looked around online and couldn't find much help. The only things I can find are people with broken installations that are magically fixed by installing vcredist 2013 but no luck here.

**Comment by rashil2000** [comment]
I'm sorry I don't really use ImageMagick, so I might not be able to help.

Are the DLL files you're looking to include, not present in the portable version? We could try adding that directory to Path.

**Comment by tech189** [comment]
No, sadly the DLL files are only included in the installers. But I tried adding the installation directory to the path with `"env_add_path": ".",` and it works now! It looks like it didn't even need the registry entries, just the `MAGICK_HOME` and `MAGICK_CODER_MODULE_PATH` environment variables. I also tested it with the Python Wand library and it also works which is great! Just doing some final tests (I've only tested `magick`, `identify`, and `IMDisplay` so far) and then I'll compose my pull request :)

**Comment by rashil2000** [comment]
Great news!

Is it really essential to set MAGICK_HOME and MAGICK_CODER_MODULE_PATH even after adding the bin directory to path?

**Comment by tech189** [comment]
Yes, if those variables aren't set then the basic commands don't work and Python Wand can't find the coder modules (the dlls).

**Comment by rashil2000** [comment]
Okay, thanks for the info

**Comment by tech189** [comment]
One issue has come up in testing. ImageMagick bundles its own ffmpeg, so when scoop adds the installation directory to the path, any ffmpeg installed by `scoop install ffmpeg` is not used. Is there any way to get around this? Could we run a pre-installation script to delete the bundled ffmpeg since imagemagick already depends on ffmpeg?

**Comment by rashil2000** [comment]
Since you're switching to the installer instead of archive, it'll already have all the dependencies. Then there's no need for `"depends": "ffmpeg"`.

But now we have a problem. Users who have installed ffmpeg via scoop (independently of ImageMagick) won't be able to use that version.

**Comment by tech189** [comment]
Exactly, so I propose that instead of having two versions of ffmpeg, both users of ffmpeg and imagemagick use the same ffmpeg binary. I think this should work fine as no-one has raised any issues with using a higher version of ffmpeg (4.4) with the current portable imagemagick than what is bundled with the full installer (4.2.3).

For redundancy, I recommend we keep the bundled ffmpeg in the directory but renamed to `ffmpeg.exe.old` and leave a note so that if someone encounters issues they can simply rename it back to `ffmpeg.exe` and continue working.

Here's my proposed solution (which I have tested), what do you think?

```
{
    "version": "7.1.0-13",
    "description": "Create, edit, compose, and convert 200+ of bitmap images formats.",
    "homepage": "https://imagemagick.org/",
    "license": "ImageMagick",
    "depends": "ffmpeg",
    "architecture": {
        "64bit": {
            "url": "https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-13-Q16-HDRI-x64-dll.exe",
            "hash": "c4607f68794f9e8e5ed73b1c0a295aae8e612c4b63b163e65c5f2669068b78d0"
        },
        "32bit": {
            "url": "https://www.imagemagick.org/download/binaries/ImageMagick-7.1.0-13-Q16-HDRI-x86-dll.exe",
            "hash": "477bf261a8ad6d3034e0b6f58ce7abdeb9a2c6186c9caef34e64fe9e24eafa42"
        }
    },
    "innosetup": true,
    "bin": [
        "compare.exe",
        "composite.exe",
        "conjure.exe",
        "convert.exe",
        [
            "convert.exe",
            "imconvert"
        ],
        "dcraw.exe",
        "identify.exe",
        "IMDisplay.exe",
        "magick.exe",
        "mogrify.exe",
        "montage.exe",
        "stream.exe"
    ],
    "env_set": {
        "MAGICK_HOME": "$dir",
        "MAGICK_CODER_MODULE_PATH": "$dir\\modules\\coders"
    },
    "env_add_path": ".",
    "post_install": [
        "Rename-Item $dir\\ffmpeg.exe $dir\\ffmpeg.exe.old"
    ],
    "notes": "The bundled ffmpeg is outdated and has been renamed to ffmpeg.exe.old - scoop will install the latest ffmpeg instead.",
    "checkver": "The current release is ImageMagick <a.*?>([\\d.p-]+)</a>",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://www.imagemagick.org/download/binaries/ImageMagick-$matchHead$matchTail-Q16-HDRI-x64-dll.exe"
            },
            "32bit": {
                "url": "https://www.imagemagick.org/download/binaries/ImageMagick-$matchHead$matchTail-Q16-HDRI-x86-dll.exe"
            }
        },
        "hash": {
            "mode": "rdf",
            "url": "https://www.imagemagick.org/download/binaries/digest.rdf"
        }
    }
}
```

If you think it's okay, I'll make a pull request!

**Comment by rashil2000** [comment]
Looks good, please go ahead!

**Comment by tech189** [comment]
Okay, I've done so here: https://github.com/ScoopInstaller/Main/pull/2885

Thanks for your help so far!
