### ISSUE TITLE
Error to install Python 3.8.2 - pep-514.reg is not valid

### ISSUE THREAD

**Issue by jeremy886** [ScoopInstaller/Main#950]
I tried to install other apps and no problem except for python.

~ $ scoop install python
Installing 'python' (3.8.2) [64bit]
install-pep-514.reg (555 B) [================================================================================] 100%
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [>                                                                              ]   0%
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 27.
URL https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/python/uninstall-pep-514.reg is not valid

**Comment by jeremy886** [comment]
Interesting. I tried again under cmd.exe and it worked.

**Comment by Ash258** [comment]
lukesampson/scoop#3891
