### ISSUE TITLE
heroku-cli@7.39.1: hash check failed

### ISSUE THREAD

**Issue by bitf16a018** [ScoopInstaller/Main#951]
C:\>scoop install heroku-cli
Installing 'heroku-cli' (7.39.1) [64bit]
heroku-win32-x64.tar.xz (14.3 MB) [==========================================================================] 100%
Checking hash of heroku-win32-x64.tar.xz ... ERROR Hash check failed!
App:         main/heroku-cli
URL:         https://cli-assets.heroku.com/heroku-win32-x64.tar.xz#/dl.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    5370c7b5e4a5e0dcae1d487bb6b3981ce5528c17b39dbc399e30d5c977685599
Actual:      e9839a5644cefb2c18c53a88a03ec29d4cecf7000afac1248e0481e2623af6bb

**Comment by Ash258** [comment]
Supressed by 04e2a74dd4c837396ce24e8b31d8d753b4e7899d
