### ISSUE TITLE
please add emacs and spacemacs

### ISSUE THREAD

**Issue by ret394** [ScoopInstaller/Main#958]

**Comment by earnestma** [comment]
Hi, Emacs is in the ["extras" bucket for scoop](https://github.com/lukesampson/scoop-extras): See https://github.com/lukesampson/scoop-extras/blob/master/bucket/emacs.json

You can add the bucket and install Emacs by using `scoop bucket add extras` and then `scoop install emacs`

After, you can `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d` for spacemacs as usual.

**Comment by ret394** [comment]
thanks.

**Comment by earnestma** [comment]
> thanks. you did not forget anything, right?

@ret394 i don't think so. 

Oh, possibly one thing is if you already have a .emacs file or .emacs.d directory, you'll want to rename that/ move it out of the way.

lmk if you run into any issues and i'll try to help out :)

**Comment by ret394** [comment]
https://git.earnestma.xyz/earnestma/earnestma

Nice!
