### ISSUE TITLE
neovim@0.3.7: hash check failed

### ISSUE THREAD

**Issue by Geezus42** [ScoopInstaller/Main#97]
> scoop update neovim
neovim: 0.3.5 -> 0.3.7
Updating one outdated app:
Updating 'neovim' (0.3.5 -> 0.3.7)
Downloading new version
nvim-win64.zip (22.5 MB) [===================================================>                                                                       ]  42%nvim
Checking hash of nvim-win64.zip ... ERROR Hash check failed!=====================================================================================] 100%
App:         main/neovim
URL:         https://github.com/neovim/neovim/releases/download/v0.3.7/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a382844cca60e110d6c7205a869d156000b093d6205df81bc1283ff19328010d
Actual:      e049e28cb9d4c0c89de33f3a1266197e6b8c3bcb28677617f7117661de702235

**Comment by Aspi1in** [comment]
me too

λ scoop install neovim
Installing 'neovim' (0.3.7) [64bit]
nvim-win64.zip (22.5 MB) [==========================================================================] 100%
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         main/neovim
URL:         https://github.com/neovim/neovim/releases/download/v0.3.7/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a382844cca60e110d6c7205a869d156000b093d6205df81bc1283ff19328010d
Actual:      e049e28cb9d4c0c89de33f3a1266197e6b8c3bcb28677617f7117661de702235

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=neovim%400.3.7%3a+hash+check+failed

**Comment by Aspi1in** [comment]
me too

λ scoop install neovim
Installing 'neovim' (0.3.7) [64bit]
nvim-win64.zip (22.5 MB) [==========================================================================] 100%
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         main/neovim
URL:         https://github.com/neovim/neovim/releases/download/v0.3.7/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a382844cca60e110d6c7205a869d156000b093d6205df81bc1283ff19328010d
Actual:      e049e28cb9d4c0c89de33f3a1266197e6b8c3bcb28677617f7117661de702235

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=neovim%400.3.7%3a+hash+check+failed
