### ISSUE TITLE
minikube@1.9.0: hash check failed

### ISSUE THREAD

**Issue by bibistroc** [ScoopInstaller/Main#975]
Minikube hash check failed:

![image](https://user-images.githubusercontent.com/3705183/78340200-5768f400-759e-11ea-9dde-5fc0948e1bfe.png)

**Comment by Ash258** [comment]
The 1.9.0 release was refreshed by authors, but I rather pushed update to 1.9.1

**Comment by bibistroc** [comment]
WOW that was fast. Thank you very much.
